### ISSUE TITLE
Segmentation fault on CentOS 7

### ISSUE THREAD

**Issue by honato11** [stoplightio/prism#1]
# CentOS 7 /usr/local/bin/prism SIGSEGV
Note: It works on macOS Sierra. 

```
$ uname -r
3.10.0-327.el7.x86_64

$ cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core)
```

# Prism segmentation fault - Debug information

```
# prism
Segmentation fault
```
``` 
$ gdb prism
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
"/usr/local/bin/prism": not in executable format: File format not recognized
(gdb)
``` 

```
# strace /usr/local/bin/prism
execve("/usr/local/bin/prism", ["/usr/local/bin/prism"], [/* 30 vars */]) = -1 EFAULT (Bad address)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_USER, si_pid=16211, si_uid=0} ---
+++ killed by SIGSEGV +++
Segmentation fault (core dumped)
```

```
$ file /usr/local/bin/prism
/usr/local/bin/prism: ERROR: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs)error reading (Invalid argument)
```

```
$ hexdump -n 16 /usr/local/bin/prism
0000000 457f 464c 0102 0001 0000 0000 0000 0000
0000010
```

**Comment by pytlesk4** [comment]
I am going to look into this for you, can you explain to me how you installed prism?  Did you use the script or did you install it manually?

Tom

**Comment by honato11** [comment]
Before you invest a lot of time, please give me another trial. The fact
that the ELF binary seems to be corrupted indicates to me that the forward
proxy is the culprit. I will circumvent the proxy tomorrow to be 100% sure
that it's not an issue created by our super amazing:) forward proxy. I will
ping you tomorrow :)

**Comment by honato11** [comment]
HI Thomas, I can't get my hands on within the next days/weeks (maybe;( but
I have good reasons to believe that the forward proxy was the culprit. Will
contact you again if I can put my hands again on this topic. Thanks

**Comment by pytlesk4** [comment]
Just wanted to check in and see if you had a chance to get your hands on this issue.

Happy Holidays!

**Comment by honato11** [comment]
Hi Thomas, the forward proxy very likely was the culprit. Can't put my
hands on it at the moment. Wishing you all the best for 2017. Happy new
year :)))
