### ISSUE TITLE
setup + teardown scenario support

### ISSUE THREAD

**Issue by marbemac** [stoplightio/prism#10]
Add "setup" and "teardown" properties to collections.

```
{
    "setup": {...scenario}, // run at start collection
    "scenarios": [], // run concurrently, after setup
    "utilities": [], // not run with collection
    "teardown": {...scenario} // run after scenarios are all completed
}
```

- add to prism
- update docs
- update json schema / model in docs

**Comment by marbemac** [comment]
an alternative here is to add the ability to mark scenarios as sync

**Comment by ChrisNLott** [comment]
With the Sync option, how does that work? Do all "sync" Scenarios run before OR after the "async" ones?

**Comment by marbemac** [comment]
I was thinking like this, assume the following scenarios:

- a [sync]
- b
- c
- d [sync]
- e [sync]
- f
- g
- h [sync]

Would be run like this:

- a
- b, c
- d
- e
- f, g
- h

Does that make sense?

**Comment by pytlesk4** [comment]
The first option is way better, and we can do setup/teardown on the scenario level as well. I think the synch option is trying to accomplish. It feels dirty that the ordering of [scenarios](https://help.stoplight.io/scenarios/input/collection-input) on a users collection all the sudden becomes super important. Tests(Scenarios) shouldn't be dependent on on previous scenarios running. 

Also, the synch option doesn't take into running a one off scenario within a collection, if I want to run scenario b in the example above, it looks like scenario A is the setup, and scenario H is the teardown. It is going to be ugly to implement and confusing to the user imho.

I do like the synch flag though, on a scenario/step level though for other things. For example you could create a scenario to send the result to slack, and in scenario H, ref it as a step and mark it as synch. You could create another one to email a report to and ect...

**Comment by pytlesk4** [comment]
Supported in [Prism v2.0.0-alpha1](https://github.com/stoplightio/prism/releases/tag/v2.0.0-alpha1)
