### ISSUE TITLE
Prism is not able to interpolate hyphenated parameters

### ISSUE THREAD

**Issue by XVincentX** [stoplightio/prism#1007]
Considering this OAS3 file:

```yaml
openapi: 3.0.0
info:
  title: httpbin
  version: '1.0'
paths:
  /get:
    get:
      responses:
        '200':
          description: OK
      parameters:
        - schema:
            type: number
          in: query
          name: q-param
          required: true
```

### Expected
Prism should be able to correctly interpolate it and propose a query parameter example in the CLI

### Result

<img width="608" alt="image" src="https://user-images.githubusercontent.com/1416224/75390301-ab046580-58ad-11ea-9625-327e04d9bc7f.png">

Prism is not crashing (which is good) and it's using the fallback behaviour of displaying the URI Template

The problem is most likely caused in the `createQueryUriTemplate` which is ignoring some part of the RFC spec (for example, hyphens are not allowed and so they should be properly encoded.

**Comment by stephenlprice** [comment]
This behavior is also affecting path parameters. If I remove the hyphen from the names of my path parameters I can can generate valid mocked responses. However if path parameter names are still hyphened Prism will present the behavior seen in these images.

![requestMakerError](https://user-images.githubusercontent.com/58522233/78914246-c7b8bf00-7a4f-11ea-9864-f8c130aaa252.png)

![consoleError](https://user-images.githubusercontent.com/58522233/78914260-cd160980-7a4f-11ea-814a-8bb0e2ad834a.png)

**Comment by XVincentX** [comment]
@stephenlprice I need to triple check but I am pretty sure that is a different issue. 

Hyphens are not a valid URI Template character, so the OpenAPI document you have is invalid. Spectral could probably emit a warning/error about it.

**Comment by stephenlprice** [comment]
@XVincentX thanks for the fast response. I just checked Spectral in Studio and CLI for this case and it did not return any related errors.
Here is the example for your reference:

```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "testAPI",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/testPath/{subscriber-id}/{destination-id}/{application-id}/{doc-id}": {
      "get": {
        "summary": "getTest",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "foo": {
                      "type": "string"
                    },
                    "bar": {
                      "type": "number"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-testPath"
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "subscriber-id",
          "in": "path",
          "required": true
        },
        {
          "schema": {
            "type": "string"
          },
          "name": "destination-id",
          "in": "path",
          "required": true
        },
        {
          "schema": {
            "type": "string"
          },
          "name": "application-id",
          "in": "path",
          "required": true
        },
        {
          "schema": {
            "type": "string"
          },
          "name": "doc-id",
          "in": "path",
          "required": true
        }
      ]
    }
  }
}
```

**Comment by XVincentX** [comment]
Update on this — unfortunately OAS2 and 3 are using a custom URI Template scheme, so that hyphen is valid. For those reasons, this is a bug in Prism we have to fix.

**Comment by XVincentX** [comment]
To whomever that's going to handle this, here are some considerations to keep in mind:

We are using [uri-template-lite](https://github.com/litejs/uri-template-lite) to expand and match our uri templates.

Such library respects the standard, which *does not* allow hyphens — that's the source of the error.

That said, we are using the library in two places:

1. When generating examples for query string values (where we are constructing an URL using the informations we have): https://github.com/stoplightio/prism/blob/8f5cacf/packages/cli/src/util/paths.ts#L35
2. When effectively working with path: https://github.com/stoplightio/prism/blob/8f5cacf/packages/http/src/validator/index.ts#L147

Here is what we can do:

1. Find another uri-template library with both expand and match capability that does support the OAS standard (I find this really unlucky but you never know.
2. Fork this library under the https://github.com/openapi-contrib organisation and make the required changes (maybe the author would be interested in accepting a PR?!)
3. We can at least fix the use case n. 1 by encoding the parameters or simply removing the hyphen. Since we're constructing the URL on our own just to provide the example. We would still need some other way to fix the use case 2 (which might be more important).

//cc @karol-maciaszek Can you check out these notes and tell me if they make sense?

**Comment by chohmann** [comment]
@vncz thank you for the review and help for this issue! What's the process for getting this actually released? Do I need to do anything?

**Comment by XVincentX** [comment]
@chohmann We do not release automatically, but whenever is necessary.

In this particular case it's going to be slightly more complicated since `master` is 4.x (which will come one day) so this PR will need to get ported to the latest 3.x. I'll take care of this and tag you wherever is necessary so you can get familiar.
