### ISSUE TITLE
Ability for dynamic mocks to be static (same response body for each request)

### ISSUE THREAD

**Issue by adam-thomas-privitar** [stoplightio/prism#1011]
**User story.**
I am using Prism in a way which perhaps might be unique -- for automated test purposes rather than filling in gaps in the API before they are developed.

Alongside Jest, I have developed a framework where we can write UI integration tests for our application, with a mocked API provided by prism. This means I can write tests as if they were end to end, without caring about writing manual mocks/fixtures for the tests. It's awesome, and I love it.

I use dynamic mode. One problem this has is that each time I request, I get random data. It would be preferable if the random data/ID's for each entity was decided on _startup_ and not on each request. That means it would be consistent between requests. That it is random causes problems for many use cases.

**Is your feature request related to a problem?**
Lets say I have an API powered list and the user moves away from the list and comes back. The data has changed, but it wouldnt have in a real situation.

**Describe the solution you'd like**
Some kind of `--static-dynamic` mode where the randomness is decided on startup. I suppose its loosely related to persistence, but with some random data bootstrapped in rather than a cold start. I dont really care about being able to modify this at runtime though with DELETE, POST, PUT etc so the use case is simpler.

**Comment by XVincentX** [comment]
@adam-thomas-privitar 

Thanks for the message.

Have you tried to use the `examples` section of the OpenAPI document? In such case you can basically pre-can the mock server with fake data and you can request them on purpose through the `__example` query string parameter.

**Comment by adam-thomas-privitar** [comment]
@XVincentX Yes, but its not quite what we want. The reason is that we _want_ to expose application flakyness via the randomness.

**Comment by adam-thomas-privitar** [comment]
@XVincentX Could this be reopened re: my reply? :)

**Comment by XVincentX** [comment]
Hey,

I'm thinking about it — thing is at this stage this feature is not planned nor in the short nor in the mid term.

I would love to help somehow in case you'd be willing to share some more details on why having a different response every time is a problem.
