### ISSUE TITLE
Invalid examples should break things

### ISSUE THREAD

**Issue by mattlock83** [stoplightio/prism#1021]
**User story.**
As a someone using examples extensively in my API spec, I should be made aware by Prism that an example is invalid to the schema, so that my spec is kept accurate.

**Is your feature request related to a problem?**
Currently if the example in an OpenAPI spec is invalid against the schema, Prism will create a mock endpoint and return the invalid response with a success code.

E.g the spec below
``` 
openapi: "3.0.0"

info:
  title: Hello World
  version: "1.0"
servers:
  - url: http://localhost:4010

paths:
  /greeting/{name}:
    post:
      summary: Generate greeting
      description: Generates a greeting message.
      responses:
        200:
          description: greeting response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Greeter"
              examples:
                asd:
                  summary: asd
                  value:
                    name: "asd"
      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          schema:
            type: string
            example: "dave"
components:
  schemas:
    Greeter:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
      required:
        - id
        - name
```
Returns a 200 OK and the response below, missing the required id field.
```
{
    "name": "asd"
}
```
The only way you can see it's wrong is with this log entry in the Prism logs
```
[VALIDATOR] ✖  error     Violation: response.body should have required property 'id'
```

**Describe the solution you'd like**
I would like Prism to either fail to start up, emitting the log error from above. Or return a 500 response instead of an invalid example

**Comment by XVincentX** [comment]
`Or return a 500 response instead of an invalid example`

This is supported, you just need to run Prism with the `--errors` flag. Check out the [documentation](https://stoplight.io/p/docs/gh/stoplightio/prism/docs/getting-started/03-cli.md?srn=gh/stoplightio/prism/docs/getting-started/03-cli.md#proxy) for more information about the response violations.

**Comment by mattlock83** [comment]
Brilliant! I'd thought that only applied when running as a proxy, but works perfectly in mock mode

**Comment by XVincentX** [comment]
Effectively the documentation was not pointing that out that clearly. Will try to revisit the wording :)
