### ISSUE TITLE
How to do 'afterScript' in new version?

### ISSUE THREAD

**Issue by finnlee87** [stoplightio/prism#1024]
**Chore summary**
How to do 'afterScript' in new version?

**Additional context**
In the older version,  it can use './prism --config /path/to/my/config.json' this param to implement 'afterScript'.

**Comment by karol-maciaszek** [comment]
@finnlee87 what is the version you are referring to?

I can't recall prism having `--config` parameter, @pytlesk4 do you?

**Comment by XVincentX** [comment]
I am pretty sure @finnlee87 is referring to Prism v2 — that is now unsupported for new features, but only bug fixes.
