### ISSUE TITLE
Prism 3 docker install issue

### ISSUE THREAD

**Issue by satheesh-subramani** [stoplightio/prism#1032]
Hi

i try to install prism 3 using docker ,following the documentation -

i tried - docker run --init -P stoplight/prism:3 mock -h 0.0.0.0 api.oas2.yml

when i " docker ps -a - i see docker container exited immediately.
MacBook-Pro-van-Eigenaar:~ eigenaar$ docker ps -a
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
ab7f201db312 stoplight/prism:3 “node dist/index.js …” 12 seconds ago Exited (0) 10 seconds ago

how to solve this

**Comment by XVincentX** [comment]
Using such command will never work because the `api.oas2.yml` file is on the host, so the docker container won't be able to use it. 

You need to mount your current directory as a volume in the container to make it work correctly:

`docker run --init -P -v $(PWD):/usr/ stoplight/prism:3 mock -h 0.0.0.0 /usr/api.oas2.yml`

**Comment by satheesh-subramani** [comment]
i am not clear.  where to i find api.oas2.yml file
i just need to try above command after placing api.oas2.yml file in my /usr/ directory? what does the $(PWD) mean

**Comment by XVincentX** [comment]
Aha ok, you might be unfamiliar with docker then — this is not a Prism issue. PWD stands for print working directory.

**Comment by satheesh-subramani** [comment]
ah okay. i will google then. you told "the api.oas2.yml file is on the host" , could you just elaborate what do you mean, and where to find this file

**Comment by XVincentX** [comment]
You need to provide it. It's the API you want to mock. You can create one with [Studio](https://stoplight.io/studio) or with whichever tool you prefer.

**Comment by satheesh-subramani** [comment]
ah i get it, i got confused by the way it is mentioned in the prism documentation, it made me to think its a file of prism. thank you
