### ISSUE TITLE
Cannot serialise complex objects as text

### ISSUE THREAD

**Issue by satheesh-subramani** [stoplightio/prism#1038]
This is my openAPI:
  '/insurance-accounting/update/{id}':
    post:
      tags:
        - Insurance accounting API
      summary: Updates business partner details for the given id
      operationId: updateBusinessPartnerUsingPOST
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
          examples:
           example_update:
             value: '100000010'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountingRequest'
            examples:
               example_update:
                 value:
                  BpId: '100000010'
                  EmailAddress: satheesh@test.com
                  PhoneNumber: ''
                  FaxNumber: ''
                  City: amstelveen
                  PostalCode: 1187 LW
                  Street: westwijkplein
                  House_no: '114'
                  Country: NL
        description: inputPayload
        required: true

when i curl request for POST, i get below error

 curl -X POST -H "Content-Type: application/json" -d '{
   "BpId" : 100000010,
   "EmailAddress" : "satheesh@test.com",
   "PhoneNumber" : "",
   "FaxNumber" : "",
   "City" : "amstelveen",
   "PostalCode" : "1187 LW",
   "Street" : "westwijkplein",
   "House_no" : "114",
   "Country" : "NL"
}' http://127.0.0.1:4010/insurance-accounting/update/100000010
{"type":"https://stoplight.io/prism/errors#NO_COMPLEX_OBJECT_TEXT","title":"Cannot serialise complex objects as text","status":500,"detail":"Cannot serialise complex objects as text

**Comment by XVincentX** [comment]
@satheesh-subramani Can you format the example document and the CURL command and explain a little bit more what's up?

It's hard to help you without a clear reproduction case.

Closing until new details provided.
