### ISSUE TITLE
Make redirection following optionnal

### ISSUE THREAD

**Issue by francois-dorval** [stoplightio/prism#104]
Hello, 
I'm trying to test an authentication api that relies on a redirection system. It replies

HTTP/1.1 302 Found
Location: https://client.example.com/example?code=SplxlOBeZQQYbYS6WxSbIA

I'd like to get the "code" but stoplight follows the redirection and I get a 200 from https://client.example.com (without the data I want) instead of the 302.

Is there a way to make redirection following optionnal in stoplight/prism?

Thanks

**Comment by pytlesk4** [comment]
If there is no settings object in your collection JSON, then past the following in at the root, otherwise add the HTTP object to settings:

```json
{
  "settings": {
    "http": {
      "redirects": 0
    }
  }
}
```

**Comment by pytlesk4** [comment]
Update prism please, going to close this issue.
