### ISSUE TITLE
Config file compatible with version 2.0.0-alpha.7

### ISSUE THREAD

**Issue by j4gh** [stoplightio/prism#106]
Hello,

I've been attempting to toy with the 2.0.0-alpha.7 build and have noticed the existing documentation doesn't appear to apply. I understand the official documentation is for version 0.6.21 since that's the current (non alpha/beta) version.

Is there a location with newer documentation for 2.x? If not, is there at least a location with a newer config file than this?
https://help.stoplight.io/prism/getting-started/custom-configuration

When trying to base a config file off of this, it appears Prism is ignoring my attempt to change the port (a well as other settings).

I apologize if this has been asked before, I wasn't able to find this particular question. Any help is greatly appreciated!

Thanks,
John

**Comment by pytlesk4** [comment]
Great question @j4gh, we are currently writing some tools to help you migrate your config file to a prism instance file. Also, we are writing documentation as fast as we can right now. Hope to have it out in the next week. The the prism run command doesn't exist anymore, and it has been replace with prism serve, which takes a prism instance file.

Also, we are adding support to generate commands for you, https://github.com/stoplightio/desktop/issues/101

Let me know if you have any questions!

**Comment by j4gh** [comment]
Ah great, thanks very much!

**Comment by hassanselim0** [comment]
Where can I find a sample prism instance file?

**Comment by pytlesk4** [comment]
@hassanselim0 https://next.stoplight.io/stoplight/prism/blob/master/todos.mocker.prism.yml

Releasing docs today too on how to set up instances, will post them shortly.

**Comment by pytlesk4** [comment]
Latest prism release makes it really easy to mock a OAS specification, going to close this now.

[2.0.0-beta.9-3](https://github.com/stoplightio/prism/releases/tag/v2.0.0-beta.9-3)
