### ISSUE TITLE
`proxy/mock` mixed behaviour

### ISSUE THREAD

**Issue by hottehead** [stoplightio/prism#1062]
**User story.**
As a backend developer I want to let consumers test against my API Mocks and at the same time record information about structural mismatches with the backend answer.

**Is your feature request related to a problem?**
It's a workflow improvement to continuously record where structural mismatches exists while the real API is being continuously build.

**Describe the solution you'd like**
I'd like to run the PRISM in `proxy` mode pointing to the real API and generating the violation hints. At the same time I'd like PRISM to answer with mock data which would have matched as if it runs in `mock` mode. It's a `proxy/mock` mixed behaviour.

**Comment by XVincentX** [comment]
Hey,

your use case looks a little bit weird to me. We do not have support for this currently in Prism and I  do not think it's coming anytime soon.

Can you clarify a little bit the specific use case?

**Comment by pytlesk4** [comment]
@XVincentX this was a feature of prism in Stoplight Classic. You could turn mocking on/off for particular operations in your API spec with [extensions](https://help.stoplight.io/prism/getting-started/swagger), you could also use a before [script](https://help.stoplight.io/prism/runtime-reference/api) to control the behavior as well.

**Comment by philsturgeon** [comment]
Sorry I’m not sure I understand the use case.

If you’re running a mock server, mismatched requests will show up in sl-violations, the same as if you ran the proxy.

The proxy is when you want to talk to a real server. The mock is for when you don’t want to talk to a real server.

Could you describe the use case where you need both?

**Comment by hottehead** [comment]
The basic idea is finding (edge) cases where responses don't match the openapi spec.

It seemed easy to do with the features in prism. But I now realize this should be better done on its own with a tool like https://dredd.org

Sorry to have bothered you two :/

**Comment by philsturgeon** [comment]
There's a bunch of options: https://apisyouwonthate.com/blog/keeping-documentation-honest

Dredd is not maintained much these days, OpenAPI v3 support only ever hit experimental, and it can be a bit of a pain to set up an effective seed anyway. If you go with it, enable the --sorted option to do all your GETs first and DELETEs at the end - that'll help a lot.

If you're concerned about keeping design and code in sync there's other ways of getting that sorted which don't involve a special test tool. More on this here: https://www.apisyouwonthate.com/blog/api-design-first-vs-code-first/

Got another article coming on that blog which drives the point home even harder but it's 24 hours from being ready. Check back tomorrow :D

**Comment by WoH** [comment]
Not sure if it's the use case @hottehead suggested, but if i have several (let's say 4) Endpoints, I'd be interested in implementing one, which I can then switch from mock to proxy (for example by using an extenstion in the spec, like `x-proxy`) while the other 3 Endpoints are still mocked.

**Comment by XVincentX** [comment]
Yeah this is something that Prism 2 was offering — we can probably enable it back sometime in the future.
