### ISSUE TITLE
Make intra-project references consistently cloud or local.

### ISSUE THREAD

**Issue by bradobro** [stoplightio/prism#107]
**What I expect**: When I task a team member with drafting an oas2 endpoint, its return models (oas2 definitions), and scenario, they'll be able to work on a branch, testing against their personal implementation of the endpoint.

**What happens instead**: 1) Contract tests seem not to recognize schema changes until they are saved to stoplight servers (*no bueno* if I'm leveraging this as a team tool and I have two devs working on two different features).

**Suggestions/Ideas**: The move to projects is brilliant, and when I pull the underlying git repo, all the files are there in one directory. I find myself wishing that the desktop version worked the same way--projects are directories, and they have the same files one would get cloning the underlying repo (either both json or both yaml--instead of yaml online and in the repo and json in local file mode).

For stoplight to be useful for team API collaboration it's got to get rock solid about references to oas2 files, from hub files, from scenario files, and from other oas2 files. There are a ton of wannabe tools out there touting team collaboration but, AFAIK, they all only handle a single person editing. Stoplight Desktop has a huge advantage, but it's got to be really, really reliable about *which* version of an *oas2* file it's using for contract tests. I argue that when the scenarios are running locally, that defaults to the referenced file in the same local directory, and when they running on stoplight.io, they default to the referenced file in the same project.

I can imagine more problems as people split monoliths up into microservices and multiple projects. I don't have a good proposal for inter-project $refs, but I think `cloud project = local directory` is powerfully consistent.

**Comment by pytlesk4** [comment]
Stale, and should be resolved in the latest, going to close this.
