### ISSUE TITLE
Run Prism programmatically

### ISSUE THREAD

**Issue by balanza** [stoplightio/prism#1070]
**User story.**
As a developer, I can start a mock server programmatically, so that I can integrate with my tests.

**Is your feature request related to a problem?**
Although Prism is thought to be run via command line, I'd find useful and interesting to have the ability of running it programmatically. I guessed I could just import needed modules in my project, but it fails at resolving expected peer-dependencies. The main problem is it seems such peer dependencies aren't specified in each package.json. This might not be a problem because everything is _orchestrated_ by the `prism-cli` package, which ships every needed dependency. However, if you pick packages independently, they fail resolving expected - but not provided - dependencies.

**Describe the solution you'd like**
I'd like to use Prism from my module just as I do via CLI. Something like the following would be perfection:

```typescript
import { createServer } from "@stoplight/prism";
const server = createServer("./mySpec.yaml", options); 
```
But it might work as well by installing each `prism-*` package separately. I think the first step would be to fix dependency declarations. Maybe each package should include all its dependencies, so they will be self-contained, and leave the package manager the burden of optimize dependencies; otherwise they could declare every needed peer dependency, so they will be clear from a user perspective.

**Additional context**
I replicated a custom example [here](https://github.com/balanza/didactic-waffle). Please note that in my example I'm using `fp-ts@1.x`, instead of `fp-ts@2.x` used by Prism. This is another caveat, as Prism cannot coexists in a stack with a different `fp-ts` version (it would with self-shipped dependencies).

Thanks!

**Comment by XVincentX** [comment]
Hey @balanza 

Most of the parts you've pointed out are inaccurate, and there were indeed different errors with the example you provided. 

I went ahead and fixed them for you here: https://github.com/balanza/didactic-waffle/pull/1

With such PR, the server correctly starts and mocks the document. Feel free to reopen the issue in case you're still struggling.
