### ISSUE TITLE
Prefer header kept for subsecuent requests

### ISSUE THREAD

**Issue by r1ckr** [stoplightio/prism#1071]
**Describe the bug**
I am following the following documentation to select what example I want when making a request:
https://stoplight.io/p/docs/gh/stoplightio/prism/docs/guides/01-mocking.md#response-examples

When I specify the `Prefer: example=<my example name>;` header it returns the requested example, but prism caches the header and all the subsequent requests without it will try to get that example.

**To Reproduce**
If I have following 2 paths:
```
/my-path
  examples:
    example1: <my example here>
    example2: <my example here>
/my-other-path
  examples:
    another-example-name: <my example here>
```

Making a call to `/my-path` with header `Prefer: example=example1;` it will return the specified example with no issues.

If I make a call to `/my-other-path` **without** the prefer header, it will return this:
```
{"type":"https://stoplight.io/prism/errors#NOT_FOUND","title":"The server cannot find the requested content","status":404,"detail":"Response for contentType: application/json and exampleKey: example1 does not exist."}
```

It's like after making a call with the Prefer header, all the subsequent calls without it, will assume that I want the `example1`.

**Expected behavior**
I am expecting that when I don't specify the `Prefer` header, it returns the first example, as it is specified in the documentation.

This used to work with version 3.2.9

**Environment:**
 - Library version: 3.3.2
 - OS: Alpine Linux v3.11, macOS

**Additional context**
I am using your docker containers and locally in my mac, both fail

**Comment by XVincentX** [comment]
Hey @r1ckr,

that is really weird, since Prism does not have any caching mechanism at all. Can you share the full document you are using so I can have a deep look into?

**Comment by Michael-Dawkins** [comment]
I have encountered the exact same problem today.
As soon as one request has the "Prefer": "example=example-1" header set, the subsequent requests to other endpoints give me an error because they do not have an "example-1".

I have tried specifying "Prefer": "dynamic=true" on the subsequent requests to try and "reset" the behaviour but it did not work.

Library: "@stoplight/prism-cli": "^3.3.2"
OS: MacOS 10.15.3

**Comment by Michael-Dawkins** [comment]
I have just tried with @stoplight/prism-cli@3.2.9 but I have the same issue.

**Comment by lehphyro** [comment]
This happens to me as well using `curl`.

**Comment by XVincentX** [comment]
@Michael-Dawkins @lehphyro Can you provide a sample document?

**Comment by lehphyro** [comment]
@XVincentX you can use the one attached to https://github.com/stoplightio/prism/issues/1073

**Comment by XVincentX** [comment]
Can you try this branch? #1074
