### ISSUE TITLE
Can't mock error response after an example is chosen

### ISSUE THREAD

**Issue by lehphyro** [stoplightio/prism#1073]
**Describe the bug**
`Prefer: code=400` doesn't work after a request with `Prefer: example=elon` is sent.
It works if no example has been chosen previously.

**To Reproduce**

1. Given the attached OpenAPI document
2. Run this CLI command: `prism mock openapi.yaml -h 0.0.0.0`
3. Execute the following requests:

`curl -H "Prefer: example=elon" http://localhost:14080/client-api/v2/test`
`curl -H "Prefer: code=400" http://localhost:14080/client-api/v2/test`

**Expected behavior**
I expect a 400 error response in the second request, I get the same response as the first request instead.

**Additional context**
Might be related to https://github.com/stoplightio/prism/issues/1071
[openapi.txt](https://github.com/stoplightio/prism/files/4416397/openapi.txt)

**Comment by XVincentX** [comment]
Can you try this branch? #1074

**Comment by lehphyro** [comment]
That fixes the issue :+1:

**Comment by lehphyro** [comment]
@XVincentX that's was quick :) Maybe you can help fix this issue in spectral that's been open for a while? https://github.com/stoplightio/spectral/issues/870

**Comment by XVincentX** [comment]
@lehphyro Tengo dos manos solo :)
