### ISSUE TITLE
Int64 validation is failing

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/prism#108]
https://next.stoplight.io/tom/prism/blob/master/todos.oas2.yml?edit=%23%2Fpaths%2F~1todos%2Fget

1513168160856

schema:

``` js
{
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64"
        }
}
```

**Comment by marbemac** [comment]
- [ ] create tests validating pass and fail for each custom jsonschema format that we've added
