### ISSUE TITLE
Expose openapi file on an endpoint

### ISSUE THREAD

**Issue by msilvestre** [stoplightio/prism#1097]
As a developer, I can expose the openapi schema file on an endpoint, so that I can use swagger-gui on it.

This way it will be very easy to construct a swagger-gui locally using prism server that is already providing the api.

The endpoint could be something like:
GET /openapi

This endpoint maybe should be configurable in case it is already a path of the spec

Thanks

**Comment by XVincentX** [comment]
Hey,

I am going to close this for now. I understand the issue but I do not think this is going to be implemented anytime soon (even if it's trivial).

As a workaround, you can use `serve` npm package to serve your file while editing it. Even better, you can use [Stoplight Studio](https://stoplight.io/studio) which will effectively allow you to have the mock server *WHILE* you're editing the OpenAPI specification file.

Un gusto,

V.
