### ISSUE TITLE
Option to specify context path in proxy mode

### ISSUE THREAD

**Issue by lehphyro** [stoplightio/prism#1100]
**User story.**
As a developer, I can specify the context path my web application is running on, so that I can proxy requests to it.

**Is your feature request related to a problem?**
Some web applications expect requests on different base paths depending on deployment configuration. For example, an API spec might specify a `GET` request to `/friends` but the application implementing it will expect requests for `GET /my-app/friends` due to deployment being done on `/my-app` context path.

**Describe the solution you'd like**
Prism could provide an option to specify a base path under which all request will be done, for example: `prism proxy openapi.yaml http://localhost:8080 --base-path /my-app --errors -p 5000`

**Additional context**
Prism should use the same base path when forwarding the requests, so a `GET http://localhost:500/my-app/friends` will be sent to `http://localhost:8080/my-app/friends`.

**Comment by XVincentX** [comment]
We've been talking a lot about this while crafting Prism 3 and we took the decision of not supporting any kind of base path, nor from the CLI, nor from the OpenAPI document itself (we even wrote it in the README).

The easiest way to workaround this is to put a small reverse proxy between your App and Prism. [caddy](https://caddyserver.com) could be a very good choice for that.
