### ISSUE TITLE
Generating Mock Data without Server

### ISSUE THREAD

**Issue by ilkerceng** [stoplightio/prism#1102]
**Chore summary**
What is the goal of this chore.
I want to create a mock data service but without http server. Currently, i have tried [swagmcok](https://github.com/subeeshcbabu/swagmock) but it goes to infinite loop in somehow. My main goal is to create a mock service layer for unit test. I need to return a response for matchin url with just Promise. It is also ok for me to just getting a mock data generated according to swagger api for given url. Is there any option on CLI to create or can i use the core package for doing this? 

**Tasks**
- [x] Need to do this.
Here an example what i need, taken from swagmock lib.
```
mockgen.responses({
        path: '/pet/findByStatus',
        operation: 'get',
        response: 200
    }).then(mock => {
        console.log(mock); // This would print:
    }).catch(error => {
        
    });
```
- [ ] And do that

**Additional context**
Add any other context about the chore here.

**Comment by XVincentX** [comment]
Hey @ilkerceng ,

I would say you can probably do that using the Client API exposed in the prims-http package. 

If you could articulate a little bit better your use case I can probably try to point you to the right direction, but from the informations you wrote, I would say [this](https://github.com/stoplightio/prism/blob/master/docs/guides/http-client.md) is where you should start.

**Comment by ilkerceng** [comment]
Hi @XVincentX 
This is exactly what i am looking for. Thanks :)
