### ISSUE TITLE
Unable to run docker image as the documentation instructions on MacOsX

### ISSUE THREAD

**Issue by sgrmgj-quotient** [stoplightio/prism#1104]
**the bug**
docker image for prism just does not start. I followed all the instructions as per the documentation.

**To Reproduce**
I am on Mac OS X Catalina and I am executing the following command 
docker run --init --rm -it -v $(pwd):/tmp -P stoplight/prism:3 mock -h 0.0.0.0 "/tmp/XXX-Service.v1.json"
[10:24:56 AM] › [CLI] …  awaiting  Starting Prism…

and it just exits and the container did not start.
But when I use the Prism CLI, it just works. There's definitely something wrong with prism3 image.

**Expected behavior**
I expected the container to behave the same as CLI .
However, when I use the prism2 image it works.

**Environment**
 - Library version:  3.0.0
 - OS: Mac OS X and Ubuntu 18

**Comment by XVincentX** [comment]
There's definitely an error in the starting process but the docker image is not showing it unfortunately. #1107 should help you to debut what's the problem.

**Comment by sgrmgj-quotient** [comment]
thank you @XVincentX - I really appreciate the guidance. I will check it out.
