### ISSUE TITLE
Control Number of Records in Collection

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/prism#1139]
**User story.**
As a CLI or HTTP user, I can do request a particular number of records be returned from the mock server, so that I can test how my frontend application looks with multiple records, odd numbers of records, and a few different values.

**Is your feature request related to a problem?**

Users need more than just a single item in a collection.

> I am +1 on having more dynamic data generated and having that controlled by configuration and/or command line switches. I use the mock server when working on our SDKs and I'm alarmingly confident at how well they work with one record returned! **-- @lornajane**

Let's let users pick, regardless of if they're using hosted mocking or CLI.

**Describe the solution you'd like**

Default behavior continues to function exactly as it does now. 

If `Prefer: records=X` appears, the first time an `items: {}` is found it will repeat the number of records in that array to match the number provided.

There may well be multiple `items: {}`, but we pick the "first", which in JSON would be closest to the root, and also in top to bottom order.

```json
{
  "links": {
    "self": "http://example.com/articles/1"
  },
  "data": [ ... ],
  "related": [ ... ],
}
```

With a schema covering this, it's the data that would be used.

This isn't going to work for everyone, but it will help a lot of people until a more comprehensive idea can be thought up. 

#20 was outstanding for a year, so let's do the quick and dirty approach now to serve those who need it sooner rather than later.

**Additional context**

A few ideas were discussed over in https://github.com/stoplightio/prism/issues/20 but this issue is to track the chosen implementation.<br><br><i>(related to <a href='https://stoplight.zendesk.com/agent/tickets/5164'>Zendesk ticket #5164</a>)<br>gz#5164</i>

**Comment by philsturgeon** [comment]
Heads up, HAL puts some of _links into an array:

```
{
    "_links": {
        "self": { "href": "/orders" },
        "curies": [{ "name": "ea", "href": "http://example.com/docs/rels/{rel}", "templated": true }],
        "next": { "href": "/orders?page=2" },
        "ea:find": {
            "href": "/orders{?id}",
            "templated": true
        },
        "ea:admin": [{
            "href": "/admins/2",
            "title": "Fred"
        }, {
            "href": "/admins/5",
            "title": "Kate"
        }]
    },
    "currentlyProcessing": 14,
    "shippedToday": 20,
    "_embedded": {
        "ea:order": [{
            "_links": {
                "self": { "href": "/orders/123" },
                "ea:basket": { "href": "/baskets/98712" },
                "ea:customer": { "href": "/customers/7809" }
            },
            "total": 30.00,
            "currency": "USD",
            "status": "shipped"
        }, {
            "_links": {
                "self": { "href": "/orders/124" },
                "ea:basket": { "href": "/baskets/97213" },
                "ea:customer": { "href": "/customers/12369" }
            },
            "total": 20.00,
            "currency": "USD",
            "status": "processing"
        }]
    }
}
```

With just HAL being effected so far I'd say lets carry on with this approach.

Solutions can be made to add support for HAL records or more custom work later.

**Comment by axicorp-scottedwards** [comment]
This will be useful to us to allow us to test an array with 0 items, 1 item (current) and 2+ items which greatly increases our testing coverage.

Adding 'Prefer: records=X ' works for us and at the moment we aren't using HAL so I can't provide too much feedback on requirements here but can see it getting quite complex so I would imagine the best approach is to add the ability to control the count first and then add HAL support in a later release.

**Comment by philsturgeon** [comment]
Ok, the switch is sorted, but for the actual implementation do we think "Look for the first+top array in the schema and assume that's where the records live" is comprehensive enough to proceed?

**Comment by axicorp-scottedwards** [comment]
If you are asking how to handle models that have multiple arrays then I would say that the number governs them all, if there are three arrays in the model then you would generate x number of items (where x is the number specified in the switch) within each array.

**Comment by philsturgeon** [comment]
I was wondering how we could find _the_ array which is supposed to be considered the array of records. As I mentioned, it could be

```
[ { ... } ]
```

or 

```
{
  "data": [ { ... } ]
}
```

or 

```
{
  "links": [ { ... } ],
  "data" [ { ... } ]
}
```

Clearly from these examples it gets pretty tricky to say "make _any_ array suddenly have 100 things." because 100 links is probably not what you're looking for.

Also there's more complex examples like [JSON Schema supporting tuples](https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation).

```
{
  "type": "array",
  "items": [
    {
      "type": "number"
    },
    {
      "type": "string"
    },
    {
      "type": "string",
      "enum": ["Street", "Avenue", "Boulevard"]
    },
    {
      "type": "string",
      "enum": ["NW", "NE", "SW", "SE"]
    }
  ]
}
```

We'd want `[1600, "Pennsylvania", "Avenue", "NW"]` not 100 random strings.

So, we simply cannot do _every_ array in the response, but we can try and pick one. 

I mentioned first/top which would pick "links" over "data" in that one example, but we could easily put this in documentation to say "it's going to pick the first/top array" so you can switch the order of "links, data" to "data, links" and you're all set.

How's that sound folks? @XVincentX @axicorp-scottedwards?

**Comment by axicorp-scottedwards** [comment]
I would do it for arrays of objects only, this is the usecase that works for me and given you already have logic for generation of these objects creating a sensible list of randomised data would work e.g. for your second example i would have defined an address object and then defined the array as an array of addresses, and would then expect that the system would generate 100 random address using your existing generation logic (respects enums, regex formating and faker).

**Comment by riteshganatraanz** [comment]
Hi @philsturgeon @XVincentX  @axicorp-scottedwards 
do we have any ETA on this one? we need the ability to specify/limit the maxEntries for random responses since some of our mocks give 10s of MBs of response and way too much time.

**Comment by philsturgeon** [comment]
@axicorp-scottedwards the difficult tightrope we have to walk with prism is not creating any functionality that imposes “the right way” to design an API. We lean on the HTTP Standard for a reasonable default when something is unclear, but we’re not going to pick and choose how people should form their JSON requests or responses, even if one approach seems superior to us. So, trying to keep supporting the examples JSON Schema provide in their documentation working would be an important thing for us.

So far we have:

1. first+top array
2. all arrays of objects 
3. Look for a default envelope like “data” and let users configure it

Do we have any other options for consideration?

**Comment by axicorp-scottedwards** [comment]
Could you have a header that allows the specification of a JSON path plus the number to allow the request to define and have it as a delimited list or some form of an array to support doing this for multiple arrays?

For example, you could define each of your examples as follows:
.:10
`[ { ... } ]`

data:10
`{
  "data": [ { ... } ]
}`

links:2,data:10
`{
  "links": [ { ... } ],
  "data" [ { ... } ]
}`

Another option could be to define an x- tag in the spec that specifies the upper and low bounds for the generation and it would pick a random number between this for each call? For example lower=1 and upper=10 then it would randomly return between 1 to 10 records in the array, or you could set it to lower=5 and upper=5 and you would always get 5.

**Comment by philsturgeon** [comment]
> Another option could be to define an x- tag in the spec that specifies the upper and low bounds for the generation and it would pick a random number between this for each call? For example lower=1 and upper=10 then it would randomly return between 1 to 10 records in the array, or you could set it to lower=5 and upper=5 and you would always get 5.

This is being done in #1889. If setting this globally in the API description works for you then you're all set.

**Comment by ryotrellim** [comment]
Closing this ticket as resolved.

We've added x-json-schema-faker support in https://github.com/stoplightio/prism/pull/1899 which allows you to specify min-items and max-items.

For more information, see https://meta.stoplight.io/docs/prism/ZG9jOjk1-http-mocking#dynamic-response-generation.
