### ISSUE TITLE
Read-Only and Write-Only doesn't respect the scope.

### ISSUE THREAD

**Issue by nicolastakashi** [stoplightio/prism#1142]
**Describe the bug**
The required properties in schema don't respect the scope if we take a look at the OpenAPI Specification [documentation](https://swagger.io/docs/specification/data-models/data-types/) there is the following explanation:

> **Read-Only and Write-Only Properties**
If a readOnly or writeOnly property is included in the required list, required affects just the relevant scope – responses only or requests only. That is, read-only required properties apply to responses only, and write-only required properties – to requests only.

Seems to me that Prism doesn't apply this approach as you guys can see below.

**To Reproduce**

1. Given this OpenAPI document 

```yaml
openapi: 3.0.0
info:
  title: API
  description: API.
  version: v1
  contact:
    email: email@email.com
    name: Contato
tags:
  - name: items
servers:
  - url: 'http://127.0.0.1:4010'
    description: Prism
paths:
  /items:
    post:
      operationId: create-item
      summary: summary
      description: description
      tags:
        - items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - id
              properties:
                id:
                  description: Item unique identifier
                  type: string
                  format: uuid
                  readOnly: true
                name:
                  description: Project name
                  type: string
                  example: Item One
      responses:
        '201':
          description: Created
          headers:
            Location:
              description: '/items/{id}'
              schema:
                type: string

```

2. Run this CLI command 
```bash
prism mock api.yaml -d
```
3. See error
After sending a `POST` request, the request has a 400 status code, informing that `id` is required.
**Expected behavior**
Return a `201` status code, because `id` is required but is `readOnly` so must be required just on the response scope.

**Screenshots**

1 - Swagger Request

![image](https://user-images.githubusercontent.com/8205546/80712415-e14aa500-8ae9-11ea-8260-36ba0b205342.png)

2 - Swagger Response 

![image](https://user-images.githubusercontent.com/8205546/80712576-0dfebc80-8aea-11ea-896b-5a674bbead32.png)

3 - Console Output

![image](https://user-images.githubusercontent.com/8205546/80712643-28389a80-8aea-11ea-9f44-58dd675ff669.png)

**Environment (remove any that are not applicable):**
- Library version: 3.3.3
- OS: Ubuntu 18.04
- Browser: All browsers

**Additional context**
I did some tests using the same spec file sending the rest to a [Mock Bin](http://mockbin.org/) and everything looks good.

**Comment by XVincentX** [comment]
That is correct, we are effectively ignoring these fields at the moment. We need to look into this.

**Comment by XVincentX** [comment]
Underlying dependency issue: https://github.com/json-schema-faker/json-schema-faker/issues/289

**Comment by philsturgeon** [comment]
Also what was linked to is not specification documentation, just some tutorials some folks wrote about OpenAPI. https://swagger.io/docs/specification/data-models/data-types/

Here's what the specification says on the topic: 

<img width="879" alt="image" src="https://user-images.githubusercontent.com/67381/92891571-53c47d80-f418-11ea-92e0-21d79629e9fb.png">

_**Source:** http://spec.openapis.org/oas/v3.0.3.html#fixed-fields-19_

Interestingly this has been removed in OAS3.1 as part of the move towards full JSON Schema 2019-09 support, where applications get to chose what they do with annotations like this, instead of there being any specific behavior defined in OpenAPI v3.1 itself.

This means that... well we _could_ start getting opinionated about things and doing similar functionality to what you're asking for, and what OpenAPI v3.0 says, but it involves stripping any readOnly properties out of the request, or writeOnly out of the response, which is harder than it sounds when you consider allOf and other forms of subscheme. It also requires AJV to support annotation collection and it's not there yet... 

So, punt on this for now. I won't be expecting JSON Schema Faker to do it, but when AJV is up to 2019-09 and we support OAS3.1, we can probably sort this out.

**Comment by XVincentX** [comment]
Roger @philsturgeon

**Comment by philsturgeon** [comment]
We've started doing this in Docs now, it's in production. 

![image](https://user-images.githubusercontent.com/67381/103406261-66df9280-4b5a-11eb-930d-44220d0b4245.png)

@XVincentX could you talk to @marcelltoth about how they've done it, and see if the same logic can be used (copy and paste or abstracted) to solve things here? I'm guessing its done in http-spec but I don't look at code much anymore. 

If not, if we can shrink the JSON Schema to remove anything not relevant before its passed to json-schema-faker, then this should work fine even without the support of the upstream library.

**Comment by marcelltoth** [comment]
It's a JSV feature so it won't be us but @stoplightio/void-crew (we simply pass the fact to JSV whether it's a request or a response). 

> If not, if we can shrink the JSON Schema to remove anything not relevant before its passed to json-schema-faker, then this should work fine even without the support of the upstream library.

In theory this could work. I might contribute if I'll have the time at the end of sprint. 

If I'm not mistaken we would "just" need to replace [this `cloneDeep`](https://github.com/stoplightio/prism/blob/master/packages/http/src/mocker/generator/JSONSchema.ts#L23) with a function that strips anything with `writeOnly: true` before returning, right?

**Comment by philsturgeon** [comment]
We've got a PR up now, @nicolastakashi think you could take a look and see if it solves your use-case?

**Comment by marcelltoth** [comment]
I tested with the example from this issue so I really hope it does 😄

**Comment by nicolastakashi** [comment]
Sorry for the delay!
I will try to test it today :D

**Comment by nicolastakashi** [comment]
Looks great to me guys, thank you so much

**Comment by philsturgeon** [comment]
Thank you for getting this done @radzserg! That was a tough one. 🙌🏻
