### ISSUE TITLE
Unknown path command using a local scenarios file

### ISSUE THREAD

**Issue by wvzuilen** [stoplightio/prism#115]
I'm trying to run prism on a windows server using a local scenarios file:

`prism conduct scenarios.json --path "scenarios/scenario1"`

Prism responds with:
`Error: unknown flag: --path`

The 'path' command is suggested in de Next UI in the 'Trigger this scenario / Run from terminal'
 block.

**Comment by pytlesk4** [comment]
can you run `prism version`, and if it is < 2.x.x, please run `prism update 2.0.0-beta.9-1` and try again.

**Comment by wvzuilen** [comment]
Duh. I was on a < 1.0 version. Sorry, user error I guess.
