### ISSUE TITLE
Prism not handling date-time where example contains time-offset

### ISSUE THREAD

**Issue by mpretty-cyro** [stoplightio/prism#1153]
**Describe the bug**
When a response has a variable with the `date-time` format and it provides an example with a `time-offset` value (eg. `2020-01-01T11:52:12+1000` which is valid according to the [RFC3339](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14) specification with OpenAPI 3 follows). **Note:** This does work if you just provide a `Z` for the time-offset to indicate GMT (eg. `2020-01-01T11:52:12Z`).

**To Reproduce**

1. Given this OpenAPI document
```
openapi: 3.0.0
info:
  title: httpbin
  version: '1.0'
paths:
  /get:
    get:
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                required:
                  - value
                properties:
                  value:
                    type: string
                    format: date-time
                    example: 2020-01-01T11:52:12+1000
```

2. Run this CLI command 
```
prism mock api.yaml
```
3. See error
After sending a Get request you receive the following error - `Request terminated with error: https://stoplight.io/prism/errors#VIOLATIONS: Request/Response not valid`

**Expected behavior**
A valid response with the example date-time should be returned

**Environment (remove any that are not applicable):**
 - Library version: 3.3.4
 - OS: OS X 10.15.2

**Comment by XVincentX** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1416224/81368595-c235af80-90b5-11ea-9abc-e1eef6a5c7d4.png">

I can't reproduce this one — can you verify and reopen if necessary?

**Comment by mpretty-cyro** [comment]
@XVincentX Sorry for wasting your time - looks like this is working in a fresh project just not in our full project (must be some weird project configuration or due so something odd we've done in our documentation)

**Comment by mpretty-cyro** [comment]
Ok managed to debug it - looks like it's the regex in AJV `/^(\d\d):(\d\d):(\d\d)(\.\d+)?(z|[+-]\d\d:\d\d)?$/i` - the time_offset part is expecting a colon which we were missing; I have no idea why it's working without the colon on a fresh project though 😂
