### ISSUE TITLE
Support colocated json files in externalValue property for response bodies in static mock mode

### ISSUE THREAD

**Issue by Perni1984** [stoplightio/prism#1155]
In general I am not 100% sure if this is a feature request or a bug report, but I guess this could be a matter of perspective.

**User story.**
As a prism user, I can use the `externalValue` property in my openapi specification, so that I can provide request and response examples through external json files.

**Is your feature request related to a problem?**
We have several example request and response bodies in json files colocated to our openapi specification that we provide to the specification through the `externalValue` property. When running prism in static mode I would expect that these externalValue examples are also considered for the response bodies that are delivered in the static mock mode.

When we have the following openapi specification `api_specification_minimal.yaml`:
```yaml
openapi: 3.0.0
info:
  title: Book Store API
  version: 1.0.0
servers:
  - url: 'https://example-book-store.com'
    description: Test Environment
paths:
  /backend/book:
    get:
      operationId: getBooksCollection
      summary: Returns a list with all books in the system
      responses:
        '200':
          description: A list of all books
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfBooks'
              examples:
                default:
                  externalValue: 'examples/backend/books/getBooksCollectionResponse.json'
                empty:
                  externalValue: 'examples/backend/books/getBooksCollectionResponseEmpty.json'
components:
  schemas:
    IdReadOnly:
      type: string
      pattern: '[a-fA-F0-9]{24}'
      readOnly: true
      example: 5ea736d41142bb6d740f2dd2
    ArrayOfBooks:
      type: array
      items:
        $ref: '#/components/schemas/Book'
    Book:
      required:
        - title
      properties:
        id:
          $ref: '#/components/schemas/IdReadOnly'
        title:
          type: string
        author:
          type: string
        price:
          type: number
      type: object
```

whereas colocated to the `api_specification_minimal.yaml` we have:

`examples/books/getBooksCollectionResponse.json`:
```json
[
    {
        "id": "5ea7d0df998cba41316d9ab2",
        "title": "Hamlet",
        "author": "William Shakespeare",
        "price": 123
    }
]
```
`examples/books/getBooksCollectionResponseEmpty.json`:
```json
[]
```

When I now run `prism mock api_specification_minimal.yaml` :
![image](https://user-images.githubusercontent.com/9039956/81140724-be494680-8f6a-11ea-8774-3bbb7a44f9b4.png)

and call GET `http://localhost:4010/backend/book` from e.g. Postman, I am getting a `200` response, but there is no content in the response:
![image](https://user-images.githubusercontent.com/9039956/81140767-e2a52300-8f6a-11ea-8dae-b5ed9ceb6cad.png)

![image](https://user-images.githubusercontent.com/9039956/81140784-f3ee2f80-8f6a-11ea-8624-8f2050cdf8e5.png)

Whereas dynamic mode works perfectly - `prism mock api_specification_minimal.yaml -d`:
![image](https://user-images.githubusercontent.com/9039956/81140864-2e57cc80-8f6b-11ea-8c8c-91b0d9e8cccc.png)
![image](https://user-images.githubusercontent.com/9039956/81140894-3ca5e880-8f6b-11ea-9276-cf64ee9fed25.png)

**Describe the solution you'd like**
When running prism in the static mock mode with an openapi specification that provides example response bodies through the `externalValue` property I would expect that those examples are delivered through the mock server

**Comment by XVincentX** [comment]
Hey,

we deliberately skipped this so far, but apparently it might be the time to implement this.

As a temporary workaround, I think you can use the $ref even when OpenAPI does not allow that, since our resolver will resolve the references anyway, no matter where they're put.

I'll keep on eye on this and see if we can do something about it. My main concern would be the size of the external file and find a secure way to load its content without making damages.

**Comment by lehphyro** [comment]
I think I have the same need, I'm getting the following error when I try to use an external PDF file as example:
```
{
    "type": "https://stoplight.io/prism/errors#UNKNOWN",
    "title": "Cannot find serializer for application/pdf",
    "status": 500,
    "detail": ""
}
```

The OpenAPI spec looks as follows:
```
responses:
        '200':
          description: Some description
          content:
            application/pdf:
              examples:
                example1:
                  externalValue: https://some.address.com/my.pdf
```

`$ref` doesn't work too.

**Comment by XVincentX** [comment]
Got it. I can't really give an ETA for this, but it seems like people want this so we will try to figure out something.

**Comment by gap777** [comment]
@XVincentX We really need this to manage the library of examples we're using. Can you implement this feature, suggest a work-around, or point us in the right direction? FWIW, we're not even seeing the behavior that @Perni1984 described, wherein  the external local examples could be leveraged albeit with dynamic tuned on.

**Comment by XVincentX** [comment]
@gap777 We have put some issues on our backlog and we _hope_ to be able to work on these soon.

In meantime, unfortunately, I cannot think of any other workaround if not using JSON references.

**Comment by gap777** [comment]
@XVincentX I did end up getting things working via `$ref`... which is great. Can I link a json file via $ref into a yaml file?

**Comment by XVincentX** [comment]
That should work also @gap777

**Comment by gap777** [comment]
@XVincentX We're using `$ref` for linking in JSON files, but we also need to return binary files.... and for that, we're getting the `Cannot find serializer` errors. 

Any work-arounds to enable this?

**Comment by XVincentX** [comment]
Hey @gap777 

I do not work for Stoplight anymore; @philsturgeon or @karol-maciaszek are the right people to ask about this.

**Comment by gap777** [comment]
@philsturgeon or @karol-maciaszek - can you support us in the short-term returning binary data from a local file?

**Comment by philsturgeon** [comment]
Hey @gap777. Proper externalValue support with support for common reasonable mime types like PDF, CSV, HTTP, images, etc would be a lovely feature. 

If anyone has some bandwidth to take it on I’ll be happy to give tips where I have context, but it’s not something on the roadmap at the moment.

**Comment by gap777** [comment]
@philsturgeon Can you describe the solution you'd recommend, so I can evaluate whether it's something I can contribute?

**Comment by philsturgeon** [comment]
@chohmann could somebody give a few pointers as to how this one might be implemented? Just point them in the right direction even if its not full on sudo code. :D

**Comment by lukasz-kuzynski-11sigma** [comment]
That's a great idea.

Few details we need to take into account when implementation that:
1) when resolving URI of `externalValue` we should limit the path for resolution to prevent security issues like reading `../../../etc/hosts` etc.
2) Consider converting all `externalValue` to `stream.Readable` to prevent huge memory usage and long initial server startup time

**Comment by EdVinyard** [comment]
@gap777 we're going to close this issue since the original request, for external JSON, was satisfied.  If you are still interested in references to files containing other content, please feel free to open a new issue.

**Comment by juan-belmonte** [comment]
I'm sorry to write just after being closed, but I couldn't make it work. May I ask you how did you manage to use `$ref` to link a JSON file and have Prism returning it? I am still receiving a 200 status code and an empty response.

Trying with both the Docker image `stoplight/prism:4.8.0` and the NPM package `@stoplight/prism-cli@4.8.0`, I played with local references to file system and URLs. My findings:

* When I specify an invalid path to a file, Prism logs the error at startup.
* When I specify an invalid URL or shutdown the server or whatever action that prevents the URL from getting the file, Prism logs the error when initializing.
* When I reference a correct example in the `Prefer` HTTP header, Prism returns a 200 status code and an empty response.

So, invalid configurations are rejected by Prism at startup, but correct configurations end up with an empty response.

Here are some examples I tried:
```yaml
responses:
  "200":
    description: A successful response.
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/SuccessfulResponse'
        examples:
          "some/path-like/name":
            $ref: http://localhost:8000/some/path/example.json
          "some/path-like/name2":
            $ref: some/path/example.json
          simplerName:
            $ref: some/path/example.json
          workingExample:
            $ref: '#/components/examples/someExample'
```

As you can see, I try to use path-like example names, but also tried with simpler names just in case that was related to the issue.

**Comment by juan-belmonte** [comment]
Thank you very much @EdVinyard ! That was really fast and time-saving!
You're right: I was so close, but I didn't find the missing line for hours.
