### ISSUE TITLE
Docs issues with the example: https://github.com/stoplightio/prism/blob/master/docs/guides/http-client.md.

### ISSUE THREAD

**Issue by kalpesh6641** [stoplightio/prism#1156]
**Chore summary**
What is the goal of this chore.

* Hi we are trying to use prism for some service mocking. We were following the above readme doc https://github.com/stoplightio/prism/blob/master/docs/guides/http-client.md.

 
**Tasks**

- [ ] Need to do this

   Can you point us out to the correct working example for the the above prism-http.

 

**Additional context**

We are not planning of using the cli but wanted to create a wrapper since we want to customize some response error for our service.

**Comment by XVincentX** [comment]
Hey,

If you want to use the Prism Http library directly, keep in mind you're going to have to create an HTTP Server to host the library on your own. You can take some inspiration from the http-server package.

As for point us in the correct direction, the documentation looks accurate to me. If you're referring to something not working or you're looking for something in particular, please elaborate.

I'm closing this, but feel free to continue the conversation when you'll have more details.
