### ISSUE TITLE
Faker locale

### ISSUE THREAD

**Issue by aibar** [stoplightio/prism#1160]
How to set locale for faker extension?

**Comment by XVincentX** [comment]
Unfortunately it's not possible at this moment. We might want to make this configurable, but we are going to need to find a reasonable way to do that.

**Comment by xvilo** [comment]
I would also like to see such an ability.

**Comment by philsturgeon** [comment]
We've got an issue talking about this over here: https://github.com/stoplightio/prism/issues/1647
