### ISSUE TITLE
Prism version 2.0.18 API key environment variable not working when conduct(windows exe)

### ISSUE THREAD

**Issue by Gregoryyp** [stoplightio/prism#1169]
Hello,

When I run my specification by using my api key as an environment variable it does not work. Hard coding this value in each step does work.
Could this be because my api key contains illegal characters (example “/” and “=”). The api key variable is used in the header “X-api-key”.
Example:
{
    "scenarioVersion": "1.1",
    "scenarios": {
        "h4_ky": {
            "name": "New Scenario",
            "steps": [
                {
                    "type": "http",
                    "name": "Retrieve list configurations",
                    "input": {
                        "method": "get",
                        "url": "http://{$$.env.host}/lists",
                        "headers": {
                            "X-ApiKey": "{$$.env.apiKey}"
                        }
                    },
                    "after": {
                        "assertions": [
                            {
                                "target": "output.status",
                                "op": "eq",
                                "expected": 200
                            }
                        ]
                    }
                }
            ]
        }
    },
    "settings": {
        "testing": {
            "oas2": [
                "./test-spec.yml"
            ]
        }
    }
}

And I run the command prism conduct "‪C:\Users\tests.yaml" --path "scenarios/h4_ky" --env "host=test.com " --env "apiKey=stringwith/and=”. When I run this command I get a 401 (in Stoplight Next I do not get this error). When I fill in the value for each step (hardcoded) it does work in Prism.

**Comment by pytlesk4** [comment]
@Gregoryyp thanks for the issue, one workaround you could do is set a Before Scenario that has one step, and it's just a script that sets the environment variables. You will only be able to run the whole collection because that is the only time the before scenarios are run. Here is an example:

```json
{
  "scenarioVersion": "1.1",
  "scenarios": {
    "h4_ky": {
      "name": "New Scenario",
      "steps": [
        {
          "type": "http",
          "name": "Retrieve list configurations",
          "input": {
            "method": "get",
            "url": "http://{$$.env.host}/lists",
            "headers": {
              "X-ApiKey": "{$$.env.apiKey}"
            }
          },
          "after": {
            "assertions": [
              {
                "target": "output.status",
                "op": "eq",
                "expected": 200
              }
            ]
          }
        }
      ]
    }
  },
  "settings": {
    "testing": {
      "oas2": [
        "./test-spec.yml"
      ]
    }
  },
  "before": {
    "setenv": {
      "name": "Set Environment",
      "steps": [
        {
          "type": "script",
          "name": "Set Environment",
          "input": {
            "script": "switch($$.env.get('env')) {\n  case 'dev': {\n    $$.env.set('apiKey', 'stringwith/and=');\n    break;\n  }\n    \n  case 'prod': {\n    $$.env.set('apiKey', 'stringwith/and=prod');\n  }\n}"
          }
        }
      ]
    }
  }
}
```

Then you can do this:

`prism conduct "‪C:\Users\tests.yaml" --env "host=test.com"`

Depending on how many scenarios you have in a collection, you could turn that before scenarios into a utility one and do something like the following:

```json
{
  "scenarioVersion": "1.1",
  "scenarios": {
    "h4_ky": {
      "name": "New Scenario",
      "steps": [
        {
          "type": "ref",
          "input": {
            "name": "setenv - utilities",
            "$ref": "#/utilities/setenv"
          },
          "name": "Set Environment"
        },
        {
          "type": "http",
          "name": "Retrieve list configurations",
          "input": {
            "method": "get",
            "url": "http://{$$.env.host}/lists",
            "headers": {
              "X-ApiKey": "{$$.env.apiKey}"
            }
          },
          "after": {
            "assertions": [
              {
                "target": "output.status",
                "op": "eq",
                "expected": 200
              }
            ]
          }
        }
      ]
    }
  },
  "settings": {
    "testing": {
      "oas2": [
        "./test-spec.yml"
      ]
    }
  },
  "utilities": {
    "setenv": {
      "name": "Set Environment",
      "steps": [
        {
          "type": "script",
          "name": "Set Environment",
          "input": {
            "script": "if ($$.env.get('contenxt') === 'cli') {\n  switch($$.env.get('env')) {\n    case 'dev': {\n      $$.env.set('apiKey', 'stringwith/and=');\n      break;\n    }\n\n    case 'prod': {\n      $$.env.set('apiKey', 'stringwith/and=prod');\n    }\n  }\n}"
          }
        }
      ]
    }
  }
}
```

With the above scenario you can run one-off scenarios from the command line, just set the environment variable value `context` to `cli`. Example:

prism conduct "‪C:\Users\tests.yaml" --path "scenarios/h4_ky" --env "host=test.com " --env "context=cli"`

Hopefully, this can hold you over, for the time being. Let me know if you have any questions.
