### ISSUE TITLE
Single threaded?

### ISSUE THREAD

**Issue by bootstraponline** [stoplightio/prism#123]
I'm seeing the same performance from prism when using synchronous requests vs 100 requests in parallel. Is prism using a single thread to process incoming connections?

> $ prism version
Prism version is 0.6.21
>
> $ prism run --mock --list --spec [testing_v1_swagger_2.json](https://github.com/TestArmada/flank/blob/ba41e29030ab0ed8dd1b3d40f4716742d5351ad8/cloud_testing/apis/testing_v1_swagger_2.json)

```kotlin
// sync - 100 => 24s (sync)
repeat(shardCount) {
  println("$it")
  matrixIds.add(async { testMatrixCreate.execute() }.await().testMatrixId)
}
```

```kotlin
// async - 100 => 25s (async)
repeat(shardCount) {
  println("$it")
  jobs += async { testMatrixCreate.execute() }
}
jobs.forEach { matrixIds.add(it.await().testMatrixId) }
```

**Comment by bootstraponline** [comment]
I tried the v2 beta and see `Please set up prism instance.` and all the requests fail.

> prism serve testing_v1_swagger_2.json
> Prism version is 2.0.0-beta.9

**Comment by pytlesk4** [comment]
Should be a little faster now, but in general prism isn't the most performant. Try `prism mock --spec testing_v1_swagger.json` with the latest 2.x.x release.
