### ISSUE TITLE
Language localisation

### ISSUE THREAD

**Issue by john-yick** [stoplightio/prism#1233]
**User story.**
As a user, I can do set the language (en, de, zh etc), so that I can use the faker.js ability to set localisation and change the faked strings.

**Is your feature request related to a problem?**
Whilst basic faked data is great for English, we come across an issue for non-english based languages

**Describe the solution you'd like**
Add some tag at the top of the yaml file something like 'x-locale' and pass it onto faker.js
```
faker.setLocale("de");
```

**Comment by XVincentX** [comment]
Duplicate of #1160
