### ISSUE TITLE
Postman inference fails

### ISSUE THREAD

**Issue by aarroyoc** [stoplightio/prism#1246]
> For support questions, please use the [Stoplight Community Forum](https://community.stoplight.io). This repository's issues are reserved for feature requests and bug reports. If you are unsure if you are experiencing a bug, the [Community Forum](https://community.stoplight.io) is a great place to start.
>
> **Please delete this section, any any sections below that you don't use, before creating the issue.**

**Describe the bug**
I have an API of which I only have the Postman files. I generated examples for almost all endpoints, however, there's a problem with an endpoint which accepts multiple bodies.

**To Reproduce**

I have the following two sample POST requests in Postman:
```
{
  "to": "342334535335",
  "type": "text",
  "recipient_type": "individual",
  "text": {
    "body": "Welcome"
  }
}
```
```
{
	"to": "344455434",
	"type": "image",
	"recipient_type": "individual",
	"image": {
		"caption": "Quo Vadis",
		"id": "2bd2826a-c9ed-431d-beb6-f0eed5c24382"
	}
}
```
They go to the same endpoint: POST /v1/messages. With the first one, I succesfully get the mock result, but with the second I get the following error:
```
{"type":"https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY","title":"Invalid request body payload","status":422,"detail":"Your request is not valid and no HTTP validation response was found in the spec, so Prism is generating this error for you.","validation":[{"location":["body"],"severity":"Error","code":"required","message":"should have required property 'text'"}]}
```

Is there any way to remove the constraint of text being a required property?

**Expected behavior**
Both should return a mocked response

**Comment by XVincentX** [comment]
Hola @aarroyoc,

por lo que veo en el poco que pegaste, Prism se esta lamentando de la falta del campo `text` en tu solicitud web.

Me facilitaría mucho darte una respuesta precisa si pudieses compartir el documento Postman que estas usando.

Un saludo

P.S: Vivo en Austin pero viví en Madrid por largo tiempo y de hecho voy a regresar este Julio por vacaciones :)

**Comment by aarroyoc** [comment]
Jeje, menuda sorpresa! La colección de Postman que estoy intentanto mockear es esta: https://github.com/fbsamples/WhatsApp-Business-API-Postman-Collection
