### ISSUE TITLE
Proxy doesn't strip content-encoding header but doesn't encode response body either

### ISSUE THREAD

**Issue by sandinmyjoints** [stoplightio/prism#1272]
## Describe the bug

(see title)

## To Reproduce

1. Given this OpenAPI document 
any
2. Run this CLI command '....'
```
$ prism proxy api.yml http://127.0.0.1:10000
# proxying our api server on port 10000

$ curl -v 'http://127.0.0.1:4010/route'
```

3. See error
Upstream compresses body. Response from proxy includes `content-encoding: gzip` header, but body is uncompressed. If you visit this route in a browser, it will show an error page complaining about a content encoding error. 

## Expected behavior
Either proxy respects content-encoding header (so would return compressed body) (preferred), or proxy removes content-encoding header.

## Additional context
Cool project!

**Screenshots**

**Environment (remove any that are not applicable):**
 - Library version: 3.3.5
 - OS: macOS
 - Browser: Firefox

**Comment by XVincentX** [comment]
Closed by #1309 and #1319
