### ISSUE TITLE
Output test results in standard formats (e.g: xUnit)

### ISSUE THREAD

**Issue by russmilburn** [stoplightio/prism#128]
Prism output report for bamboo integration. prism results to be reported in JUnit

**Comment by nclarkau** [comment]
I'll second this (please!!). While any common test reporter format would be good, most CI/CD servers support JUnit parsers so it would be a good choice.

This would allow us to fully integrate Prism into our (Bamboo based) CD pipeline.

**Comment by marbemac** [comment]
@ntiss would junit be helpful for you all?

@pytlesk4 can you spend a little bit of time to scope this out so that we can at least understand the time involved?

**Comment by pytlesk4** [comment]
@marbemac I will take a look at JUnit this week.

@ntiss totally agree with being able to chose the format!

**Comment by philsturgeon** [comment]
Prism v3.x is taking a different approach with contract validation (#429), so we're not going to have anything to xUnit. More testing-related tooling will be back in the future, but Prism was trying to do a few too many things, and now we're focusing its scope.
