### ISSUE TITLE
Potential bug: doesn't understand nullable in combination with allOf

### ISSUE THREAD

**Issue by skrivanos** [stoplightio/prism#1294]
## Describe the bug

Prism doesn't understand nullable in combination with allOf. I.e. this pattern:

```
        pet:
          nullable: true
          allOf:
            - $ref: '#/components/schemas/Pet’
```

This pattern is discussed here:

https://github.com/OAI/OpenAPI-Specification/issues/1368

## To Reproduce

1. Given this OpenAPI document https://pastebin.com/QQEeaSFc
2. Run this CLI command 
```
curl -X POST -H "Content-Type: application/json" -d '{"pet": null}' http://127.0.0.1:4010/pet
```
3. See error

```
[12:21:52 PM] ›     [VALIDATOR] ⚠  warning   Request did not pass the validation rules
[12:21:52 PM] ›     [NEGOTIATOR] ⬤  debug     Unable to find a 422 response definition
[12:21:52 PM] ›     [NEGOTIATOR] ✔  success   Found response 400. I'll try with it.
[12:21:52 PM] ›     [NEGOTIATOR] ⬤  debug     Unable to find a content with an example defined for the response 400
[12:21:52 PM] ›     [NEGOTIATOR] ✔  success   Responding with the requested status code 400
[12:21:52 PM] ›     [VALIDATOR] ✖  error     Violation: request.body.pet should be object
```
## Expected behavior

Return a 201 response

## Additional context
Spec discussion, where this pattern is mentioned:
https://github.com/OAI/OpenAPI-Specification/issues/1368

I should also mention that it's supported by other tools such as Redoc

**Edit:**

After reading a bit more I think Prism actually handles it correctly, at least if these are supposed to be believed:

https://github.com/OAI/OpenAPI-Specification/issues/1368#issuecomment-580103688
https://github.com/OAI/OpenAPI-Specification/blob/master/proposals/003_Clarify-Nullable.md

Like I mentioned, other tools seem to interpret the spec differently, so I guess it's up to the Prism team to decide whether or not the pattern should be supported.

**Comment by XVincentX** [comment]
Hey,

I'm sorry it took long to respond. Effectively, the clarification specification is in line with the way Prism behaves:

> nullable: true is only meaningful in combination with a type assertion specified in the same Schema Object.

The schema you provided as example does not have a type constraint, so there is no modification to be applied (thus the nullable gets ignored).

We want to be as close as possible with the spec — I'm not planning to change this at the moment.

If you have any other concerns, feel free to reopen the issue or file a new one.
