### ISSUE TITLE
Can't use allOf to "extend" object schema: "schemas with different types can't be merged"

### ISSUE THREAD

**Issue by skrivanos** [stoplightio/prism#1295]
## Describe the bug

Prism doesn't seem to allow use an object schema in combination with allOf:

```
        pet:
          type: object
          nullable: false
          allOf:
            - $ref: '#/components/schemas/Pet’
```

## To Reproduce

1. Given this OpenAPI document https://pastebin.com/KY62st8N
2. Run this CLI command 
```
curl -X POST -H "Content-Type: application/json" -d '{"pet": {}}' http://127.0.0.1:4010/pet
```
3. See error

```
[2:19:21 PM] › [HTTP SERVER] post /pet ℹ  info      Request received
[2:19:21 PM] ›     [NEGOTIATOR] ℹ  info      Request contains an accept header: */*
[2:19:21 PM] ›     [VALIDATOR] ✔  success   The request passed the validation rules. Looking for the best response
[2:19:21 PM] ›     [NEGOTIATOR] ✔  success   Found a compatible content for */*
[2:19:21 PM] › [HTTP SERVER] post /pet ✖  error     Request terminated with error: Error: allOf: schemas with different types can't be merged
```
## Expected behavior

Return a 201 response

## Additional context

I discovered this when trying to find a spec-compliant workaround for #1294.

https://github.com/OAI/OpenAPI-Specification/issues/1368#issuecomment-580290441 
https://github.com/OAI/OpenAPI-Specification/blob/master/proposals/003_Clarify-Nullable.md#can-allof-be-used-to-define-a-non-nullable-subtype-of-a-nullable-base-schema

**Comment by XVincentX** [comment]
Note to self: even though the schema is marked as non nullable, we're still marking the schema as nullable. This is likely a bug in openapi-schema-to-json-schema package.

<img width="252" alt="image" src="https://user-images.githubusercontent.com/1416224/90512642-bcdd0c00-e15e-11ea-9b90-12b90c0e35e4.png">

**Comment by XVincentX** [comment]
We're now responding with a 201 in Prism 4.0.0

<img width="822" alt="image" src="https://user-images.githubusercontent.com/1416224/91447808-60be6a00-e879-11ea-9e84-13f204c481ca.png">
