### ISSUE TITLE
integrate benchmarking into CI / release process

### ISSUE THREAD

**Issue by marbemac** [stoplightio/prism#13]
After internal testing overhaul, but before open sourcing:

**Methods**
- Synthetic benchmarks with go
- Realworld benchmarks with aws + some load testing product (blitz, loader?)

**Examples**
- Kong: https://getkong.org/about/benchmark/
- Tyk: https://tyk.io/tyk-api-gateway-benchmarks/

**Comment by hutchic** [comment]
what was the outcome :) ?
