### ISSUE TITLE
Testing Prism proxy feature with https request fails with SSL self signed certificate issue

### ISSUE THREAD

**Issue by sathya20075** [stoplightio/prism#1305]
Testing prism proxy feature with https request fails with SSL self signed certificate issue
Steps :
1. Making a request to Products API  hosted in localhost 5000 port to know the status of the product whether it is 'Available' or 'Sold'
2. Prism is acting as proxy here.  'prism proxy products_oas3.yml https://localhost:5000/v1'
3. GET        http://127.0.0.1:4010/products/findByStatus?status=Available&status=Sold
    Request routed to https://localhost:5000/v1/products/findByStatus
4. But getting the below 'Self Signed Certificate' error.

**Description**:
[9:29:10 PM] » [HTTP SERVER] get /products/findByStatus i  info  Request received
[9:29:10 PM] »     [PROXY] i  info   Forwarding "get" request to https://localhost:5000/v1/products/findByStatus?status=Closed...
[9:29:10 PM] » [HTTP SERVER] get /products/findByStatus ×  error     Request terminated with error: FetchError: request to https://localhost:5000/v1/products/findByStatus?status=Closed failed, reason: self signed certificate

**Comment by XVincentX** [comment]
@sathya20075 Did you try to run Prism with `NODE_TLS_REJECT_UNAUTHORIZED` env variable set?

**Comment by sathya20075** [comment]
Thanks for your reply. Kindly let me know whether this environment variable holds a boolean value
> `NODE_TLS_REJECT_UNAUTHORIZED`

**Comment by XVincentX** [comment]
You can find all the required informations on the [Node JS Docs page](https://nodejs.org/api/cli.html#cli_node_tls_reject_unauthorized_value).

Feel free to reopen if you get the same issue again.

**Comment by sathya20075** [comment]
Works! Thanks a lot!! Appreciate the help here.

**Comment by pradeep-shanmugham** [comment]
How do you set the NODE_TLS_REJECT_UNAUTHORIZED value to 0 ?
I don't see a way to do so in the CLI for prism
