### ISSUE TITLE
Prism Validator doesnt validates array response from API

### ISSUE THREAD

**Issue by sathya20075** [stoplightio/prism#1306]
## Summary

Prism validator component should validate array response from API.
1. Make request to http://127.0.0.1:4010/products, which inturn redirects request to actual products server
    https://localhost:5000/v1/products
2. The API returns array api response
[
    {
        "description": "New Product01",
        "id": 1,
        "name": "Product_01",
        "price": 1354,
        "qty": 13,
        "status": "Available"
    },
    {
        "description": "New Product02",
        "id": 2,
        "name": "Product_02",
        "price": 154,
        "qty": 12,
        "status": "Available"
    },
    {
        "description": "New Product03",
        "id": 3,
        "name": "Product_03",
        "price": 134,
        "qty": 13,
        "status": "Available"
    },
    {
        "description": "New Product04",
        "id": 4,
        "name": "Product_04",
        "price": 144,
        "qty": 14,
        "status": "Sold"
    },
    {
        "description": "New Product05",
        "id": 5,
        "name": "Product_05",
        "price": 154,
        "qty": 15,
        "status": "Sold"
    },
    {
        "description": "New Product06",
        "id": 6,
        "name": "Product_06",
        "price": 164,
        "qty": 16,
        "status": "Sold"
    },
    {
        "description": "New Product07",
        "id": 7,
        "name": "Product_07",
        "price": 174,
        "qty": 17,
        "status": "Closed"
    },
    {
        "description": "New Product08",
        "id": 8,
        "name": "Product_08",
        "price": 174,
        "qty": 18,
        "status": "Closed"
    },
    {
        "description": "New Product09",
        "id": 9,
        "name": "Product_09",
        "price": 194,
        "qty": 19,
        "status": "Available"
    },
    {
        "description": "New Product10",
        "id": 10,
        "name": "Product_10",
        "price": 104,
        "qty": 10,
        "status": "Available"
    }
]

3. But Prism validator validates as object not as array
[12:07:00 AM] » [HTTP SERVER] get /products i  info      Request received
[12:07:00 AM] »     [PROXY] i  info      Forwarding "get" request to https://localhost:5000/v1/products...
[12:07:00 AM] »     [VALIDATOR] ×  error     Violation: response.body should be array
[12:07:00 AM] »     [VALIDATOR] ×  error     Violation: response.body should be array
[12:07:00 AM] »     [VALIDATOR] ×  error     Violation: response.body should be array
[12:07:00 AM] »     [VALIDATOR] ×  error     Violation: response.body should be array
[12:07:00 AM] »     [VALIDATOR] ×  error     Violation: response.body should be array
[12:07:00 AM] »     [VALIDATOR] ×  error     Violation: response.body should be array
[12:07:00 AM] »     [VALIDATOR] ×  error     Violation: response.body should be array
[12:07:00 AM] »     [VALIDATOR] ×  error     Violation: response.body should be array
[12:07:00 AM] »     [VALIDATOR] ×  error     Violation: response.body should be array
[12:07:00 AM] »     [VALIDATOR] ×  error     Violation: response.body should be array

    

## Tasks

- [ ] Need to do this
- [ ] And do that

## Additional context

Add any other context about the chore here.

**Comment by XVincentX** [comment]
@sathya20075 Hey,

thanks for the bug report. It's kind of hard for me to reproduce the following use case you provided. To help you out I'd need at least the offending OpenAPI document; if you could also set up a test http server I could use to proxy the request, that would also speed up the fixing of the (eventual) bug as well.

Thanks!

**Comment by sathya20075** [comment]
Thanks Vincent.
Please find the open api document

openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Products API'
  description: 'An API that allows user to obtain products details'
  termsOfService: ''
  contact:
     name: 'test'
     url:  'products.com'
     email: 'products@productshome.com'
  license: 
     name: 'test license'
     url:  'test.com'

servers:
   - url: https://localhost:5000/v1
     description: TestServer
     
   - url: https://devserver:5000/v1
     description: devServer
     
tags:
- name: product
  description: Everything about your Products
  externalDocs:
    description: Find out more
    url: http://test.products.io
     
paths:

   "/products":
      post:
         tags:
         - product
         summary: Creates a new product in the database
         description: ''
         operationId: addProduct
         requestBody:
           content:
             application/json:
               schema:
                 $ref: "#/components/schemas/Product"
             application/xml:
               schema: 
                 $ref: "#/components/schemas/Product"
           description: adding a new product to database
           required: true
         responses:
           200:
             description: successful operation             
           400:
             description: Invalid Product
             
      get:
          tags:
          - product
          summary: Get all products information
          description: 'Get all products information from the store'
          operationId: getProducts
          responses:
             200:
               description: successfull pull of products info
               content: 
                 application/json:
                   schema:
                     type: array
                     items: 
                        $ref: '#/components/schemas/Products'
                       
                 application/xml:
                    schema:
                      type: array
                      items:
                        $ref: '#/components/schemas/Products'
             
      put:
         tags:
         - Product
         summary: Update an existing product
         description: ''
         operationId: updateProduct         
         requestBody:
           required: true 
           content:
             application/json:
                schema:
                  type: object
                  items:
                    $ref: '#/components/schemas/Product'
             application/xml:
                schema:
                  type: object
                  items:
                    $ref: '#/components/schemas/Product'
         responses:
           '400':
             description: Invalid ID supplied
           '404':
             description: Product not found
           '405':
             description: Validation exception
         #security:
         #- products_auth:
         # - write:products
         # - read:product
         
      delete:
         tags:
         - product
         summary: Deletes a product
         description: ''
         operationId: deleteProduct
         parameters:         
         - name: productId
           in: path
           description: Product id to delete
           required: true
           schema:
             type: integer
             format: int32
         responses:
           '400':
             description: Invalid ID supplied
           '404':
             description: Product not found
         security:
           - products_auth:
             - access:products              
           
   "/products/findByStatus":
    get:
      tags:
      - product
      summary: Finds Products by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findProductsByStatus
      parameters:
      - name: status
        in: query
        description: Status values that need to be considered for filter
        required: true
        explode: true
        schema:
          type: array
          items:
            type: string
            enum:
            - Available
            - Closed
            - Sold
            default: Available
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Products"
        '400':
          description: Invalid status value
      security:
      - products_auth:
        - access:products
                
   "/products/no_auth/{productId}":
    get:
      tags:
      - product
      summary: Find product by ID
      description: Returns a single product
      operationId: getProductByIdNoAuth
      parameters:
      - name: productId
        in: path
        description: ID of product to return
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
              examples:
                Product:
                  summary: An example of a Product
                  value:
                    id: 20
                    description: 'example product'
                    price: 354.40
                    qty: 30  
                    status: 'Available'
                    
        '400':
          description: Invalid ID supplied
        '404':
          description: Product not found
        '500':
          description: Internal Server Error
        '418':
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        default:
          description: default response
          content:
            application/json:
              schema:
                required:
                - code
                - message
                properties:
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string    
           
   "/products/{productId}":
    get:
      tags:
      - product
      summary: Find product by ID
      description: Returns a single product
      operationId: getProductById
      parameters:
      - name: productId
        in: path
        description: ID of product to return
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
              examples:
                Product:
                  summary: An example of a Product
                  value:
                    id: 20
                    description: 'example product'
                    price: 354.40
                    qty: 30  
                    status: 'Available'
                    
        '400':
          description: Invalid ID supplied
        '404':
          description: Product not found
        '500':
          description: Internal Server Error
        '418':
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        default:
          description: default response
          content:
            application/json:
              schema:
                required:
                - code
                - message
                properties:
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string
      security:
        - products_auth:
          - access:products                       
      #security:
      #- api_key: []
         
components:
   securitySchemes:
    products_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: http://localhost:5000/oauth/authorize
          tokenUrl: http://localhost:5000/oauth/token
          scopes:            
            access:products: access your products
   schemas:   
      Products:
         description: Model of an array of products info
         type: array
         items:
            $ref: '#/components/schemas/Product'
      
      Product:
         type: object
         properties:            
            name:
               type: string
            description:
               type: string
            price:
               type: number
               format: float
            quantity:
               type: integer
               format: int32
            status:
               type: string

**Comment by XVincentX** [comment]
@sathya20075 Can you format the document accordingly using back ticks? It's very hard to use it in a real example.

**Comment by sathya20075** [comment]
openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Products API'
  description: 'An API that allows user to obtain products details'
  termsOfService: ''
  contact:
     name: 'test'
     url:  'products.com'
     email: 'products@productshome.com'
  license: 
     name: 'test license'
     url:  'test.com'

servers:
   - url: https://localhost:5000/v1
     description: TestServer
     
   - url: https://devserver:5000/v1
     description: devServer
     
tags:
- name: product
  description: Everything about your Products
  externalDocs:
    description: Find out more
    url: http://test.products.io
     
paths:

   "/products":
      post:
         tags:
         - product
         summary: Creates a new product in the database
         description: ''
         operationId: addProduct
         requestBody:
           content:
             application/json:
               schema:
                 $ref: "#/components/schemas/Product"
             application/xml:
               schema: 
                 $ref: "#/components/schemas/Product"
           description: adding a new product to database
           required: true
         responses:
           200:
             description: successful operation             
           400:
             description: Invalid Product
             
      get:
          tags:
          - product
          summary: Get all products information
          description: 'Get all products information from the store'
          operationId: getProducts
          responses:
             200:
               description: successfull pull of products info
               content: 
                 application/json:
                   schema:
                     type: array
                     items: 
                        $ref: '#/components/schemas/Products'
                       
                 application/xml:
                    schema:
                      type: array
                      items:
                        $ref: '#/components/schemas/Products'
             
      put:
         tags:
         - Product
         summary: Update an existing product
         description: ''
         operationId: updateProduct         
         requestBody:
           required: true 
           content:
             application/json:
                schema:
                  type: object
                  items:
                    $ref: '#/components/schemas/Product'
             application/xml:
                schema:
                  type: object
                  items:
                    $ref: '#/components/schemas/Product'
         responses:
           '400':
             description: Invalid ID supplied
           '404':
             description: Product not found
           '405':
             description: Validation exception
         #security:
         #- products_auth:
         # - write:products
         # - read:product
         
      delete:
         tags:
         - product
         summary: Deletes a product
         description: ''
         operationId: deleteProduct
         parameters:         
         - name: productId
           in: path
           description: Product id to delete
           required: true
           schema:
             type: integer
             format: int32
         responses:
           '400':
             description: Invalid ID supplied
           '404':
             description: Product not found
         security:
           - products_auth:
             - access:products              
           
   "/products/findByStatus":
    get:
      tags:
      - product
      summary: Finds Products by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findProductsByStatus
      parameters:
      - name: status
        in: query
        description: Status values that need to be considered for filter
        required: true
        explode: true
        schema:
          type: array
          items:
            type: string
            enum:
            - Available
            - Closed
            - Sold
            default: Available
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Products"
        '400':
          description: Invalid status value
      security:
      - products_auth:
        - access:products
                
   "/products/no_auth/{productId}":
    get:
      tags:
      - product
      summary: Find product by ID
      description: Returns a single product
      operationId: getProductByIdNoAuth
      parameters:
      - name: productId
        in: path
        description: ID of product to return
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
              examples:
                Product:
                  summary: An example of a Product
                  value:
                    id: 20
                    description: 'example product'
                    price: 354.40
                    qty: 30  
                    status: 'Available'
                    
        '400':
          description: Invalid ID supplied
        '404':
          description: Product not found
        '500':
          description: Internal Server Error
        '418':
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        default:
          description: default response
          content:
            application/json:
              schema:
                required:
                - code
                - message
                properties:
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string    
           
   "/products/{productId}":
    get:
      tags:
      - product
      summary: Find product by ID
      description: Returns a single product
      operationId: getProductById
      parameters:
      - name: productId
        in: path
        description: ID of product to return
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
              examples:
                Product:
                  summary: An example of a Product
                  value:
                    id: 20
                    description: 'example product'
                    price: 354.40
                    qty: 30  
                    status: 'Available'
                    
        '400':
          description: Invalid ID supplied
        '404':
          description: Product not found
        '500':
          description: Internal Server Error
        '418':
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        default:
          description: default response
          content:
            application/json:
              schema:
                required:
                - code
                - message
                properties:
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string
      security:
        - products_auth:
          - access:products                       
      #security:
      #- api_key: []
         
components:
   securitySchemes:
    products_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: http://localhost:5000/oauth/authorize
          tokenUrl: http://localhost:5000/oauth/token
          scopes:            
            access:products: access your products
   schemas:   
      Products:
         description: Model of an array of products info
         type: array
         items:
            $ref: '#/components/schemas/Product'
      
      Product:
         type: object
         properties:            
            name:
               type: string
            description:
               type: string
            price:
               type: number
               format: float
            quantity:
               type: integer
               format: int32
            status:
               type: string

**Comment by sathya20075** [comment]
[products_oas3.zip](https://github.com/stoplightio/prism/files/4967459/products_oas3.zip)
Attached the OpenApi document here. Let me update you on test http server.

**Comment by sathya20075** [comment]
Hi Vincent.. Any updates on this?

**Comment by XVincentX** [comment]
We haven’t been able to check this out yet. Will post an update whenever I get a chance to work on this.

**Comment by XVincentX** [comment]
@sathya20075 You did not get back to me with a testing server. In any case I took a look at your document and I am quite sure you have a problem here:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/1416224/89213621-a6af4780-d5c5-11ea-9a93-2db5ff82bb4c.png">


You're saying that the response is an array of `Products`; `Products` is on its own an array of `Product` — that means the generated response is an array of an array. I guess what you wanted to do is rather return `Products` or an array of `Product`.

That is likely the source of the error. I'm closing this, feel free to open in case I was wrong.

**Comment by sathya20075** [comment]
Hi Vincent..
Thanks for pointing out that. My bad. Works as expected after making the change as instructed by you.
