### ISSUE TITLE
Proxy: Allow to listen to URLs

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [stoplightio/prism#1307]
## User story.

As a backend developer, I can start a proxy, which listens to an URL, so that I can transparently proxy requests to servers, which have a base-path (`/v1`) specified in their URL.

## Is your feature request related to a problem?
OAS3 allows [specifying server URLs including a base-path](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#server-object) (e.g. `/v1`). It also described [here](https://swagger.io/docs/specification/api-host-and-base-path/). Right now it is not possible to start a proxy, which listens to a base-path.

When sending a request to the proxy with `/v1` in the path the following error is thrown:

```json
{
    "type": "https://stoplight.io/prism/errors#NO_PATH_MATCHED_ERROR",
    "title": "Route not resolved, no path matched",
    "status": 404,
    "detail": "The route /v1/users hasn't been found in the specification file"
}
```

In order to avoid the error `/v1` has to be removed from the request URL.

## Describe the solution you'd like

Instead of "only" specifying `host` and `port` like in:
```sh
prism proxy ./reference/users.v1.yaml http://localhost:8081/v1 -h localhost -p 8080
```

I would like to specify a "listen-to-url" like
```sh
prism proxy ./reference/users.v1.yaml http://localhost:8081/v1 --url http://localhost:8080/v1
```
so that server can be easier replaced by the proxy in this case.

### Workaround
Yes, it is possible to move the /v1 base-path from the server URL to the definition of the API paths, but I want to avoid this.

**Comment by XVincentX** [comment]
Hey @ThomasKoppensteiner 

We are not handling this case on purpose; you can find our reasons on the [FAQ page](https://github.com/stoplightio/prism#faqs). 

I understand that it might be annoying for you; on the other hand you can use a reverse proxy to handle this with almost 0 hassle. We also provide a quick guide for that on our [docs page](https://github.com/stoplightio/prism/blob/master/docs/guides/multiple-documents.md).

Feel free to comment or reopen in case there are more details missing.

**Comment by ThomasKoppensteiner** [comment]
Hey @XVincentX,

thank you for your reply. I'll have a look into the reverse proxy setup you mentioned.
In the end, it boils down how URLs are built in Postman collections, specs etc.
