### ISSUE TITLE
Stoplight App 3.6.0 crash on Win7 64bits

### ISSUE THREAD

**Issue by samuel-colin** [stoplightio/prism#133]
Since the 3.6.0, Stoplight App crashes. I have black screen. I use a proxy with authentication.
When I try to launch app with a cmd I have this repetitive error : 

![17813544 16](https://user-images.githubusercontent.com/16137612/36315952-41c7bb32-1339-11e8-93a8-a4425d1063ca.png)

**Comment by marbemac** [comment]
Hi @samuel-colin - could you try navigating to the preferences screen via the menu in the top windows menu, and just double check that the basic auth settings carried through the update?

**Comment by samuel-colin** [comment]
Hi,
It's impossible to navigate to the preferences screen. This screen doesn't open.

**Comment by marbemac** [comment]
Ok we're looking into it now, will have something for you shortly.

**Comment by marbemac** [comment]
It is odd that you are not even seeing the app window open. We've made some updates that seem promising in our tests, could you try it out and let us know if it helps?

Download: https://ufile.io/jf17h

Note that you may still need to set your proxy user/pass setting again. Step 1 is getting the app window to open (even if blank content on screen), step two is navigating to preferences via the OS menu in top left, and saving the appropriate network settings.

Thanks for your patience!

**Comment by marbemac** [comment]
Fixed in https://github.com/stoplightio/desktop/releases/tag/v3.6.1 - please let us know if otherwise!
