### ISSUE TITLE
Docker windows: invoke process using a file in a shared volume

### ISSUE THREAD

**Issue by TheEYL** [stoplightio/prism#1341]
I have this command that works perfectly on linux but fails on windows.   

    docker run --init --publish=4010:4010  -it -v $(pwd)/src/main/resources:/tmp -P stoplight/prism:3 mock -d -h 0.0.0.0 "/tmp/swagger.yaml"

On linux the prism process understands that the file I'm looking for is in /tmp but somehow on windows it does not see and returns the following error using the bash console as adminstrator:

    [10:23:51 AM] › [CLI] ✖  fatal     ENOENT: no such file or directory, open 'C:/Users/leo/Temp/swagger.yaml'

when using the poser-shell command as adminstrator it returns the following error:

 

        docker run --init --publish=4010:4010 --rm -it -v C:\Users\leo\IdeaProjects\java-demo-rest\src\main\resources:/tmp -P stoplight/prism:3 mock -d -h 0.0.0.0 "/tmp/swagger.yaml"                                
    [10:42:10 AM] › [CLI] …  awaiting  Starting Prism…
        [10:42:11 AM] › [CLI] ✖  fatal     ENOENT: no such file or directory, open '/tmp/swagger.yaml'

**Environment :**
 - Library version: [ 3.0.0]
 - OS: [Windows 10]

**Comment by XVincentX** [comment]
Hey,

this does not really seem to be a Prism specific error — but rather the file is being mounted somewhere else; can you ssh in the container and check out if the file is effectively there?

**Comment by XVincentX** [comment]
I'm closing this since it's not Prism related, but feel free to reopen in case you can provide more details.
