### ISSUE TITLE
Prism is not sending query parameters

### ISSUE THREAD

**Issue by russmilburn** [stoplightio/prism#135]
in the web app when you press the ? the interface will  product a form for query params, when using prism from the command line they parameters are not sent in the url. in the code view the json looks like this

`"query": 
{
              "source": "{$.ctx.source}",
              "destinations": "{$.ctx.destinations}",
              "bitrate": "{$.ctx.bitrate}",
              "duration": "{$.ctx.duration}",
              "performance": "{$.ctx.performance}",
              "management": "{$.ctx.management}"
}` 

the url request is this 

`GET http://myserver.com:8081/gmn/pricing/v1/prices/itinerant`

not 

`GET http://myserver.com:8081/gmn/pricing/v1/prices/itinerant?source=EDG1&destinations=COR2&bitrate=25&duration=260&performance=Premium&management=Responsive`

**Comment by pytlesk4** [comment]
@russmilburn pushing out a prism binary tonight, and this is fixed. I can send along a new build if this is a blocker for you?

**Comment by russmilburn** [comment]
yes please thank you

**Comment by pytlesk4** [comment]
Released an update!
