### ISSUE TITLE
Prism used programmatically

### ISSUE THREAD

**Issue by morten-nielsen** [stoplightio/prism#1353]
## Summary

Is using prism programmatically a usecase that is actively supported? 
We have seen bits and pieces of nodejs based approaches, but not something that works.

We would like to use prism to be deliver first versions of new API initiatives (alpha), based on a spec with embedded examples, hosted on nodejs.

Is this something we can do with Prism?

**Comment by XVincentX** [comment]
We do provide a JavaScript API you can use, and it's documented in https://github.com/stoplightio/prism/blob/master/docs/guides/http-client.md

You can also use the super low level interface if you prefer, but it is not documented and you're going to have to dig the source code to find it.
