### ISSUE TITLE
Support for yaml merge keys

### ISSUE THREAD

**Issue by ioggstream** [stoplightio/prism#1360]
## Describe the bug

Prism does not support yaml merge keys

## To Reproduce

1. Given this OpenAPI document https://raw.githubusercontent.com/teamdigitale/api-starter-kit-python/master/openapi/simple.yaml.src
2. Run this CLI command 

```
prism mock simple.yaml.src &
curl http://localhost/datetime/v1/status
```

3. See error

```
{"type":"TypeError",
"title":"Header name must be a valid HTTP token [\"<<\"]",
"status":500,"detail":""
}

[3:38:53 PM] › [HTTP SERVER] 

get /status ✖  error     
Request terminated with error: TypeError [ERR_INVALID_HTTP_TOKEN]:
 Header name must be a valid HTTP token ["<<"]

```

## Expected behavior

A 200 Ok status message 

## Additional context

it seems prism does not process yaml merge keys `<<: ` correctly

**Environment (remove any that are not applicable):**
 - Library version: 3.3.7
 - OS: docker stoplight/prism  image, checksum                 658fc3154a85      size     120MB

**Comment by XVincentX** [comment]
Note to self: This is something we should support; we can do that by parsing the file manually, resolve the references and then feed Prism Http.

**Comment by ioggstream** [comment]
@XVincentX I was guessing why don't you use a yaml parser that resolves automatically refs and merge-keys...

**Comment by XVincentX** [comment]
To keep it short, I do not trust any yaml parser out on the market. Some of them have proven to be insecure and invalid.

**Comment by philsturgeon** [comment]
@XVincentX and on top of that, some are also slow. 😆 

@P0lip we do a pretty good job handling merge keys in stoplight/yaml and Spectral right? Do you have any tips for sorting this out in Prism?

**Comment by P0lip** [comment]
Yeah, I added support for [merge keys](https://github.com/stoplightio/yaml/blob/master/src/types.ts#L8) to `@stoplight/yaml`, and Spectral indeed handles them well. It's disabled by default, however, so Prism would need to enable it.

**Comment by XVincentX** [comment]
Yes I was aware of that (I had a private conversation with @P0lip about it). I can schedule this and other changes for Prism in the next sprint.

**Comment by XVincentX** [comment]
Merge keys are supported in Prism 4.
