### ISSUE TITLE
Can we deactivate schema validation?

### ISSUE THREAD

**Issue by dantexid** [stoplightio/prism#1369]
Hello, 

First of all thank you for the project, it's really something innovative!

We are interested in generating mocks without validating schema... notably for the request and for the response as well in the case of postman? 
Is this possible without rebuilding prism, or by using the docker file?

**Comment by XVincentX** [comment]
Can you elaborate a little bit on your use case? Seems pretty weird to me that you want to send invalid data to a mock server…

**Comment by dantexid** [comment]
With postman examples, I think the schema generation is just over ambitious (or maybe I missed something in terms of the OpenAPI contract). In terms of response validation it's asking for fields that are not part of the example responses. 
Basically the validator requires all response objects to have a code and a name:
"[VALIDATOR] ?  error     Violation: response.body.result[106].should have required property 'code'"
"[VALIDATOR] ?  error     Violation: response.body.result[106].should have required property 'name'"

With the mock systems, i think it would be useful to have the request validation as "warning" only, in the cases where the existing service does not yet comply with its own schema ... for various reasons, but the tests using these mocks should still functionally pass.

Perhaps I'm grasping at straws here and maybe something like newman is more appropriate for my use case.

**Comment by XVincentX** [comment]
Any chance you can post an example document I can take a look at?

**Comment by dantexid** [comment]
Sorry for the late reply,

I finally figured out what happened and managed to generate an example. Basically, the problem is twofold:

1) Prism is sending back the errors in the response header and the example I was using was so big and with so many errors, that it overflows the maximum header size of postman (and probably the limits of application servers as well). From a user perspective I would like to be able to deactivate the validation errors in headers (for requests as well for that matter), since not all APIs start out with valid OpenAPI specifications.
2) I might be wrong but I don't not see why the following  postman collection should generate an error from an OpenAPI p.o.v..  
[example.postman_collection.json.txt](https://github.com/stoplightio/prism/files/5143848/example.postman_collection.json.txt)

Any suggestions?

**Comment by XVincentX** [comment]
1. Why do you to disable that? Can't you just ignore the header and start checking it out when it's necessary? Thing is — the validation proxy's job is to…validate; if not, then the primary reason to exist is gone.

> since not all APIs start out with valid OpenAPI specifications.

I'd love to know more about this use case; I'd argue it's simply the fact that the API is not following the specification — which is that the validation proxy should do; underlying the discrepancies.
 
2. It depends on the request you sent to Prism; without that I cannot tell you anything about it.

This looks like a question/discussion tag, so I'm closing this but we can keep the conversation going here.

**Comment by dantexid** [comment]
Hi Vincent,

> Why do you to disable that? Can't you just ignore the header and start checking it out when it's necessary? Thing is — the validation proxy's job is to…validate; if not, then the primary reason to exist is gone.

I agree, but I am arguing here is that I am not using Prism as a validation proxy but as a **mock server** . Moreover, the problem is that I cannot just drop the header because the response is refused by the API client because of its size. Postman for example does not allow to drop the response headers as far as I know. 
Also, I would not drop the response header when running tests against the mock server as this would require modifying production code for the purpose of tests.

**Comment by XVincentX** [comment]
> I agree, but what I am arguing here is that I am not using Prism as a validation proxy but as a mock server

Ah ok, I was confused this clarified.

If you are using Prism as a mock server, it means that the response example and the response schema do not match; so either Prism has a bug in the generation of the response schema for Postman Collection (which I guess it's what you're arguing) or something else that I am missing.

I guess there are two things here we need to do:

1. Verify the Schema generation for the Postman Collection file you provided
2. Verify Prism is returning a `sl-violation` header that complies with the HTTP Spec limits

Does that sound good to you?

**Comment by dantexid** [comment]
Yep that sounds good to me. 

Thanks a lot and best,
Dante

**Comment by XVincentX** [comment]
All right. I have created https://github.com/stoplightio/http-spec/issues/116 for us to investigate at some point.

Keep in mind that:

1. Postman Collection is not exactly our top priority at the moment
2. We are aware of different limitations in our Schema generator
3. We are not planning to let the user disable the validation in any case

1.

**Comment by dantexid** [comment]
👍  , thanks for the info and for the quick replies ;)
