### ISSUE TITLE
Query Params: support JSV-Format (JSON without quotes) for complex objects

### ISSUE THREAD

**Issue by ujlbu4** [stoplightio/prism#1370]
## User story.

As a user, I want validate complex query params in [JSV-Format](https://github.com/ServiceStack/ServiceStack/wiki/Serialization-deserialization#passing-complex-objects-in-the-query-string) (json without quotes).

example query-format (params is not url-encoded for readability):
```
GET /requests?sortDefinition={column:"data.creationDateTime",isDescending:true}&filters={startLocations:{date:{from:1598821200000,to:1598907599999}}}&limit=30
```

## Is your feature request related to a problem?

We use ServiceStack as our backend framework, which is use jsv-format for complex query params by default. 
Prism launched in proxy-mode doesn't handle such objects:
```
[6:10:45 PM] › [CLI] ▶  start     Prism is listening on http://127.0.0.1:4011
[6:10:58 PM] › [HTTP SERVER] get /requests ℹ  info      Request received
[6:10:58 PM] ›     [PROXY] ℹ  info      Forwarding "get" request to http://localhost:1337/requests?offset=12345&limit=12345&sortDefinition=%7BbySize%3Atrue%2Ccolumn%3A%22generated-string-value%22%2CisDescending%3Atrue%7D&returnTotals=true...
[6:10:59 PM] ›     [VALIDATOR] ✖  error     Violation: request.query.sortdefinition should be object
```
decoded uri looks as follow:
```
offset=12345&limit=12345&sortDefinition={bySize:true,column:"generated-string-value",isDescending:true}&returnTotals=true
```

openapi definition:
```yaml
openapi: 3.0.1
paths:
  /requests:    
    get:
      description: some desc
      operationId: GetRequests_Get
      parameters:
        - $ref: '#/components/parameters/sortDefinitionParam'
      responses:
        '200':
          content:
            application/json:
              schema:
                description: response success
                properties:
                  someValue:
                    description: some desc
                    type: string
                title: my title
                type: object
components:
  parameters: 
    sortDefinitionParam:
      name: sortDefinition
      in: query
      description: Sorting
      schema:
        $ref: '#/components/schemas/SortDefinitionMold'
  schemas:
    SortDefinitionMold:
      description: Desc sorting
      properties:
        bySize:
          description: desc 
          nullable: false
          type: boolean
        column:
          description: desc 
          type: string
        isDescending:
          description: desc 
          nullable: false
          type: boolean
      title: SortDefinitionMold
      type: object
```

## Describe the solution you'd like

The official JSV library for JavaScript is available [here].(https://github.com/ServiceStack/ServiceStack/blob/v5.4.1/lib/js/JSV.js) 
Probably it's possible to append new type of Deserializer [here](https://github.com/stoplightio/prism/blob/master/packages/http/src/validator/deserializers/index.ts#L15) to handle this format.

## Additional context

Prism launches in proxy mode
```sh
$ prism proxy --port 4011 specs/openapi.yaml http://localhost:1337
```

**Comment by XVincentX** [comment]
Hey @ujlbu4 ,

thanks for writing us; our intention and top priority is to support OpenAPI2/3 and Postman Collection; this format you're mentioning is not listed in the official specification — therefore, even though it might probably be easy to add its support I really do not think this is going to happen.

If that's a breaking change for you, I'd suggest to fork the project and add this small line that might fulfil your use case. I'm gonna have to close this, but feel free to reopen in case I've missed something.

P.S: I am wondering what is the rationale behind such format 🤔
