### ISSUE TITLE
Prism responds with "Not Acceptable" when returning empty response

### ISSUE THREAD

**Issue by GramozKrasniqi** [stoplightio/prism#1388]
## Describe the bug

When we request a PUT verb on Prism with the content-type: application/json if the returned type has an empty response Prism responds with :

```
Error: Not Acceptable
Response body
Download
{
  "type": "https://stoplight.io/prism/errors#NOT_ACCEPTABLE",
  "title": "The server cannot produce a representation for your accept header",
  "status": 406,
  "detail": "Unable to find content for application/json"
}
```

## To Reproduce

**API Spec Definition:**
```
openapi: 3.0.0
paths:
  /todos:
    put:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        200:
          description: Get Todo Items
```

**Request:**

`curl http://localhost:4010/todos -H "accept: application/json"`

**Response:**
```
NOT_ACCEPTABLE
Message: The server cannot produce a representation for your accept header Returned Status Code: 406 Explanation: This error occurs when the current request has asked the response in a format that the current document is not able to produce.
```

## Expected behavior

200 OK with emtpy body

## Additional context
Prism 3.3.7 on Docker Desktop

**Comment by XVincentX** [comment]
@GramozKrasniqi Hmm, that is not exactly correct I think.

If the curl request says that `application/json` is what you want to produce but your API Definition is not able to define it — then 406 is what you should get back.

Keep in mind that an empty response is not a valid JSON. What is the specific use case??

**Comment by GramozKrasniqi** [comment]
@XVincentX thank you for your reply.
Now that i have time to analyze it i totally agree with your comment.
Actually there is no valid use case to ask for an application/json content-type and expect an empty response as a valid JSON.
