### ISSUE TITLE
503 Service Unavailable - Remote network

### ISSUE THREAD

**Issue by Wolar** [stoplightio/prism#14]
Everything works on localhost just fine, we have deployed Prism on our server and when we access it from local network everything works just fine as well. But when I try to access it (same request) from outside network, the Prism will get (and print into console) the request, but does not send any response. Only later it will send 503 (see attached screenshot). Our network seems to be configured properly, do you have any idea where could be the problem?

--debug flag does not print anything into the console

![screen shot 2017-04-13 at 15 09 09](https://cloud.githubusercontent.com/assets/6131648/25014546/7b54020c-2078-11e7-9803-c200748cc121.png)

**Comment by pytlesk4** [comment]
What is the command you are using to start Prism?

**Comment by Wolar** [comment]
prism run --debug --mock --list --spec swagger.yaml

But I think I also tried other flags

**Comment by pytlesk4** [comment]
Would you be able to jump on a quick google hangout and share your screen with me? Just shoot me an email tom@stoplight.io.

**Comment by Wolar** [comment]
Yes but unfortunatelly not today, you need the screen of the server that is running the prism right? Right now I don't have any remote access into this server from outside network and I'm not in work (CET timezone).

**Comment by pytlesk4** [comment]
Sounds good, and it would be nice to have access to it. Can we do it on Monday, we are based in Austin, TX and the time zone is CST so you are 6 hours ahead.

Also, have you tried running prism on a different port? Try to change the port to the port you expose on your remote server. Just replace remote port below.

prism run -d -m -l -p remoteport -s swagger.yaml

**Comment by Psykyck** [comment]
Was there ever any resolution to this issue? We are seeing the same thing where prism registers the request on the server, but returns a 503 - Service Unavailable.

**Comment by BrandonBlair** [comment]
Same. I can hit the endpoint I'm running locally just fine, but once I try to hit it through prism proxy with the exact same headers, it does not pass it through to the endpoint, and returns 503.

**Comment by ramesius** [comment]
Running into this issue as well. I think we have narrowed it down to host headers. Anything making a request using `localhost` works fine, but when aliasing/proxying `localhost` or linking in docker, the requests are never fulfilled and a HTTP 503 is returned. We do however still see these in the prism logs:
`Endpoint found (getQuote, /prospects/quotes/{id}, GET, /prospects/quotes/{id})`
Indicating that to an extent prism is "working"

Here is the command we are using to start prism:
`prism run -p=4011 --mock --list --spec ./app/config/prospect.yaml`

**Comment by mieszkomalawski** [comment]
Same here. Using docker to run prism: 

> docker-compose -f docker-compose.yml run -d --rm prism run --mock --list --spec /app/swagger.json

results in 503, while logs show:

> [VM] Endpoint found (5aa43d7c992d0e0001d6b80f, /catalog/products, GET, /catalog/products)

**Comment by Chexpir** [comment]
Same here. working when mapping the same port (4010) 
`docker run -p 4010:4010 9f1d3b5c0cd1`

but failing when mapping like
`docker run -p 9034:4010 9f1d3b5c0cd1`

The underlying call in the Docker container is always the same
prism run --mock --list --spec=config.json

**Comment by mdmollah** [comment]
Was there ever any solution to this issue?

**Comment by mdmollah** [comment]
its working for me. now i can access from outside network and getting response. I did one change to spec file. i did replace value of host with host IP of running prism. after that its working fine for me.

**Comment by philsturgeon** [comment]
@pytlesk4 was this something that got fixed, or does this IP change help? If it’s fixed we can close this issue.

**Comment by pytlesk4** [comment]
@philsturgeon We can close this, this is for v1 prism as well.
