### ISSUE TITLE
client not returning specified example even when "Prefer" header specified

### ISSUE THREAD

**Issue by hpl002** [stoplightio/prism#1409]
## Describe the bug
Title says it all: client not returning specified example even when prefer header specified.
followed the docs at <https://meta.stoplight.io/docs/prism/docs/guides/01-mocking.md#response-examples>

## To Reproduce
I have created a small demo project to highlight this. This is available at <https://github.com/hpl002/prismdebug>

>install packages and run 'test' script

## Expected behavior

expected the specified example to get returned but instead get the first example, which is the default behavior.
 
 

**Environment:**
    "@stoplight/prism-cli": "^4.0.1",
    "@stoplight/prism-http": "^4.0.1"

**Comment by hpl002** [comment]
Here is the .js file.

```JS
//To run: yarn; yarn test

const fs = require("fs");
const {
  createClientFromOperations,
} = require("@stoplight/prism-http/dist/client");
const {
  getHttpOperationsFromSpec,
} = require("@stoplight/prism-cli/dist/operations");

const initiateSandbox = async () => {
  const operations = await getHttpOperationsFromSpec("bundle.json");
  /* write operations to file for easy debugging */
  fs.writeFileSync("operations.json", JSON.stringify(operations));
  const client = createClientFromOperations(operations, {
    mock: true,
    validateRequest: false,
    validateResponse: false,
  });
  return client;
};

initiateSandbox().then((client) => {
  client
    .request("/accounts", {
      method: "get",
      headers: {
        Prefer: "example=scenario-3",
      },
    })
    .then((response) => console.log(response.data));
});

//Docs: https://meta.stoplight.io/docs/prism/docs/guides/01-mocking.md#response-examples
//should have returned the scenario 3 example. This example was declared in bundle.json and also carried over to the operations obj
```

**Comment by XVincentX** [comment]
Hey @hpl002,

this is indeed on purpose. The Http Server is the piece of code doing the actual extraction of the data from the header and it's a commodity for the Prism Http package.

If you want to do the same thing from the Http package directly, you need to feed the [explicit option](https://github.com/stoplightio/prism/blob/2c7e3ef/packages/http/src/types.ts#L14)

Essentially, you need to modify your example to be:

```js
client
  .request("/accounts", { method: "get" }, { mock: { exampleKey: "scenario-3", dynamic: false } })
  .then(response => console.log(response.data));
```

I'll open a PR to clarify the documentation — in meantime, let me know if this works and feel free to reopen in case it does not.
