### ISSUE TITLE
Cannot select a section when editing hub

### ISSUE THREAD

**Issue by nclarkau** [stoplightio/prism#141]
Cannot select a section or use the delete (trash) button. Clicking on a section immediately triggers drag mode even though there is no mouse movement and the button is not held.

![image](https://user-images.githubusercontent.com/29241826/37182233-7850a10e-2384-11e8-8a71-f123b62ee0b8.png)

**Comment by pytlesk4** [comment]
Thanks for the report, I am going to move this over to stoplightio/desktop.

**Comment by pytlesk4** [comment]
https://github.com/stoplightio/desktop/issues/164

Going to close this.
