### ISSUE TITLE
Add support for some wildcard that returns all examples specified on a path.

### ISSUE THREAD

**Issue by hpl002** [stoplightio/prism#1411]
### Add support for some wildcard that returns all examples specified on a path. 

Currently we are defaulting to first element in example array if nothing else is specified. 

Would be nice to get back all examples by passing some wildcard. Then, based on the returned examples i can choose what example i want to get and pass this in the header. 

Would perhaps make it easier to get a glimpse of all examples without having to reference the config directly.

Admittedly, this does contradict the purpose of the config. By returning an array of examples i suspect we would create a conflict with response validation as the returned examples would not follow the declared response schema as it would expect a single element, but then get a collection..

Perhaps this a silly feature as the config should be be the main reference anyway.. 

I would be happy to investigate this if this seems reasonable.

Thanks!

**Comment by philsturgeon** [comment]
This seems rather similar to #1139 which we've almost figured out an approach for. If you'd like to work on that one, plenty of Prism users would really appreciate it!

**Comment by hpl002** [comment]
> This seems rather similar to #1139 which we've almost figured out an approach for. If you'd like to work on that one, plenty of Prism users would really appreciate it!

Great! i will look into it and follow up on that thread! 

Thanks!
