### ISSUE TITLE
Tried to force a dynamic response for: application/json but schema is not defined

### ISSUE THREAD

**Issue by mochadwi** [stoplightio/prism#1432]
## User story.

As a Frontend engineer, I can do define an `examples` only without defining `schemas`, so that I can get response from HTTP request as well.

## Is your feature request related to a problem?

When defining the YAML format, I only add the actual 
```
responses:
        '200':
          content:
            application/json:
              examples:
                response:
                  value:
                     approval_type: manual
                     created_at: '2020-09-14T05:48:24.966971+00:00'
      # .... and so on
```

But when trying to execute the HTTP request below response returned instead.
```
{
    "type": "https://stoplight.io/prism/errors#UNKNOWN",
    "title": "Tried to force a dynamic response for: application/json but schema is not defined.",
    "status": 500,
    "detail": ""
}
```

I'm assumed that this is because I didn't define a `schema` like this
<img width="1084" alt="Screen Shot 2020-09-21 at 10 04 58 AM" src="https://user-images.githubusercontent.com/7057959/93730294-364e9b00-fbf2-11ea-8e16-6e6fc16e5fd5.png">

## Describe the solution you'd like

Is it possible for prism to generate response for `application/json` based on the `examples` only to reduce step defining `schema` for our teams (frontend)

**Comment by XVincentX** [comment]
Hey,

I am not exactly sure what you're trying to achieve; what does it mean for you to return a dynamic example — if there's no schema (and thus examples cannot be generated?)

Do you mean randomly returning the defined examples?

**Comment by mochadwi** [comment]
Does the `Prism` is necessary to define `schema` so the request can be executed correctly? 

We're defining our Mock API previously using `apiary.io`, then using api-spec-converter library to convert from `api_blueprint` to `openapi_3`.


The result is YAML generated the `examples` without `schemas` block, but compiles correctly in `editor.swagger.io`. 

Afterward we're trying to create simple API Description using YAML, with `schema` block, defining the object and its properties, the Prism able to return correct response. 


Otherwise, without `schema` block the Prism return the above 500 error instead

**Comment by philsturgeon** [comment]
Dynamic mode requests a schema to work, as it generated the dynamic example from a schema. 

https://meta.stoplight.io/docs/prism/docs/guides/01-mocking.md

You can use static mode which is default for Prism CLI, or can be picked with the Prefer header for Prism running in other modes (hosted, try it now, etc).

**Comment by XVincentX** [comment]
Exactly — @mochadwi just run Prism without the dynamic flag and then either select your example using the Prefer header or let it return the first one for you.

Feel free to reopen or comment if you need further clarifications.

**Comment by mochadwi** [comment]
@XVincentX @philsturgeon does the static mode, applied for all endpoint defined, or we can we specified which endpoint dynamic/static?

**Comment by mochadwi** [comment]
does the `Prefer: static` for that specific endpoint we hit, means will generate a response from `examples`?

**Comment by mochadwi** [comment]
UPDATES:

Results for `Prefer: dynamic=true` (why this issue opened in the first time):
<img width="871" alt="Screen Shot 2020-09-23 at 10 50 29 AM" src="https://user-images.githubusercontent.com/7057959/93964928-01298080-fd8b-11ea-86f7-199f07ccfc12.png">

Result for `Prefer: dynamic=false` (solving our issue, thus this issue closed):
<img width="1205" alt="Screen Shot 2020-09-23 at 10 48 48 AM" src="https://user-images.githubusercontent.com/7057959/93964918-fd95f980-fd8a-11ea-8762-fc2a6b59790b.png">

Both of the above response is runs by `-d` argument when running Prism locally. Thus I assume, when configured in our Mock Server, this also fixed our issue

Thanks @XVincentX & @philsturgeon for your answer
