### ISSUE TITLE
documentation: security validation

### ISSUE THREAD

**Issue by hpl002** [stoplightio/prism#1457]
Would be nois with some documentation and examples on how to implement security validation in the http client, and also expected behavior.. 

This is seemingly glossed over in the docs: https://github.com/stoplightio/prism/blob/master/docs/guides/http-client.md

Would it be possible to elaborate a bit more?

**Comment by XVincentX** [comment]
@hpl002 Can you elaborate a bit more? I do not really understand what you're trying to achieve.

**Comment by hpl002** [comment]
This was a poorly formatted issue, apologies for that.

What would be more useful would be a breakdown of the Client config interface. 

https://github.com/stoplightio/prism/blob/4e993aa8f0128c87152936572ef08f3b658b0e5d/packages/http/src/client.ts#L20

What is was trying to reference was the *checkSecurity* attribute in the default object. 

{
  mock: false,
  validateRequest: true,
  validateResponse: true,
  **checkSecurity**: false,
  errors: true,
  upstream: new URL('https://api.example.com'),
}

**Comment by XVincentX** [comment]
Unfortunately, I still do not understand what you're talking about.
