### ISSUE TITLE
Is it possible to generate mocks as static files?

### ISSUE THREAD

**Issue by CarltonHowell** [stoplightio/prism#1458]
We have a use case where we want to generate the mock responses as static json or js files so we can import the mocks into Jest for testing. Is this something that is supported? 🙏

**Comment by XVincentX** [comment]
Hey @CarltonHowell 

I am not too sure I understand your use case, can you elaborate a bit more? What kind of testing are you trying to get?

You have not provided a lot of details but it appears to me that you're looking for contract testing or something similar?

Keep also in mind that you can also use Prism programmatically and extract the mocked payload from the generated response and do whatever you need.

**Comment by CarltonHowell** [comment]
Thanks @XVincentX 

I'm using https://github.com/mswjs/msw to mock my REST endpoints and was hoping I could generate some mock json from an openapi file which I would then import into my JEST test and use with `msw`.

Prism is great as it generates the json that I need however it exposes it on a local server which I need to poll in order to get the json. Is there a way to instead of running Prism as a local server, have it run through all the endpoints and save the generated JSON response into `.json` files?

**Comment by XVincentX** [comment]
@CarltonHowell Ok understood!

Unfortunately we do not offer such capability out of the box, it's kind of far from the aims of Prism; however you can manually do that using the Prism Http Client (see the documentation to get an idea of what that would look like), but it's not going to be that easy.

Check that out, and maybe write back in case you need some more clarification.
