### ISSUE TITLE
Use default example if preferred example is not found

### ISSUE THREAD

**Issue by nbryan** [stoplightio/prism#1468]
## User story.

As a mock API consumer, I can get a default response when requesting an non-existent example, so that I can programmatically request examples without having to hard-code the full set of possible responses.

## Is your feature request related to a problem?

I'm mocking a vendor API since it's hard to work with locally:
1. It requires developers to be on a VPN.
2. It requires manual credential configuration on developers' machines.
3. It exposes sensitive data, even in the vendor's lower environments, so it's better not to give individual developers credentials unless necessary.

There are hundreds of thousands of records exposed by the API, but I only want to mock a dozen or so interesting examples. When our application requests an example record which doesn't exist, the mock server should respond with the default example rather than a 404 error.

## Describe the solution you'd like

Either default behavior or a configurable option to use the default example when the preferred example doesn't exist.

## Additional context

My application just uses a simple convention to map requests to examples. For example, a `GET /some_resource/123` would map to example `123` in my mock server. I can't guarantee that other developers or QAs will always choose pre-existing examples, and adding hundreds of examples doesn't seem fun.

**Comment by XVincentX** [comment]
@philsturgeon ?

**Comment by philsturgeon** [comment]
Is this maybe another vote for #962?

**Comment by philsturgeon** [comment]
At the moment the logic of returning an error when the chosen example doesnt exist is intended, so that people can know the request they're making isn't doing what they think it is. Based on the use case I think #962 would be the more appropriate solution so I'll close this one out. Thanks everyone!

**Comment by nbryan** [comment]
This isn't like #962 as there's no state kept between requests. The feature request is simply for to respond with the default example when the specified example isn't found rather than respond with an error. Since this is a change in behavior it could be a configurable option rather than the default behavior.

**Comment by philsturgeon** [comment]
Hey @nbryan, I understand that was the feature you requested, I was trying to understand the motivations and the use case behind that feature request. Creating lots of examples may be a bit rubbish, and is often confusing for different teams who need different example data, but if you have persistence you can make a seed script which will set prism up with all the examples you need.

If you can think of another feature which takes care of your use case without altering what we consider to be intentional functionality, that'll be helpful too.

**Comment by nbryan** [comment]
Having persistence wouldn't allow for my use case where I specifically want to use a default example if the specified one doesn't exist.

Persistence itself may allow for a nicer way to organize dozens of examples, but it seems to go against the idea that mocks are driven by the OpenAPI spec itself. Though it might still be nice to have, because I agree, organizing lots of examples by some opaque identifier isn't obvious, and doesn't really help document the API being mocked.

**Comment by philsturgeon** [comment]
Sorry for the confusion, I am looking at what you're writing and see a feature request and a use case, they're different things.

Feature Request: "I specifically want to use a default example if the specified one doesn't exist."

Use Case:  "I can't guarantee that other developers or QAs will always choose pre-existing examples, and adding hundreds of examples doesn't seem fun."

Adding hundreds of examples _to the OpenAPI description_ certainly does not seem like fun, and confuses the very definition of the API with examples that various teams might want. The examples that various teams might want may not always be the same, so letting them set their own seeds through #962 is one feature request that might solve the base use case even if its not the feature you're asking for here.

Another feature request that solves that use case is "example pairs", where `GET /foo/123` returns `examples./foo/123.value` but that's only going to help with URL matching and is a bit rubbish when it comes to POST responding differently for different values. Maybe it's ok to start down this path of convention knowing that it doesn't lead very far, but I'd rather see if there is another approach we can take, with #435 or something similar.

Both these features are on the cards, but for now we want to let users know if they have requested an invalid example so they can request an example that actually does exist.

**Comment by nbryan** [comment]
>Trying to squish business logic into an OpenAPI description through conventions and overuse of examples is not ideal IMO.

I agree that overuse of examples is not ideal, which is why I'm trying to limit it to just interesting cases. There is no business logic contained within my examples though.

>Both these features are on the cards, but for now we want to let users know if they have requested an invalid example so they can request an example that actually does exist.

Right, which is why I'd suggest this be a configurable option and disabled by default. It would be a breaking change otherwise.

Without going into too much detail, the real problem is that in many cases other teams don't care what my API returns, just so long as it works, so they don't always use specific examples. They're developing/testing some other aspect of the system. Perhaps the real solution is for us to pare down and fully-define the set of test data. Anyway, thanks for your consideration and feedback.

**Comment by philsturgeon** [comment]
Thank you for your feedback too! It would be another mock mode like static or dynamic if it happened, so no worries there.
