### ISSUE TITLE
Custom base path

### ISSUE THREAD

**Issue by scotchneat** [stoplightio/prism#1478]
## User story.

As an API tester, I need to be able to set a custom base path (e.g /v2/), so that I can run prism in an existing environment (tests expect a certain base path).

## Is your feature request related to a problem?

This isn't a problem as it can be worked around (add another proxy layer with something like nginx) but it would be nice to have built into the tool.

## Describe the solution you'd like

I'd like to be able to pass a custom base path to prism via command line argument when launching a mock or proxy server.
Prism will then prefix the path for all requests with the given base path. 

This should not affect validation.

## Additional context

We've defined the OpenAPI spec with the `/v2` in the server path instead of the path definitions. This gives us a cleaner spec. However, when running the proxy, it expects requests to go directly to the defined resources, which don't have the `/v2` base path. 
In existing environments, tests and integrations expect the endpoint to be defined with `/v2` in the base path so requests don't match the definition and aren't proxied to the origin service.

**Comment by XVincentX** [comment]
@scotchneat — we have deliberately chosen not to implement such feature. You can find the rationale in our [FAQ](https://github.com/stoplightio/prism#faqs)
