### ISSUE TITLE
Install.sh is installing Latest version of the tool, which is 2.0.0-alpha.3

### ISSUE THREAD

**Issue by echovue** [stoplightio/prism#15]
Just an FYI: The new version looks like it has some cool features, but the documentation on stoplight.io is still referencing the previous version.  I was able to work around this by modifying the local version of the install script, but I'm using the previous version.  Would be nice to have documentation on the new version as well.

**Comment by pytlesk4** [comment]
Good catch, we won't install it automatically anymore. We are going to be releasing documentation soon, just need to get a couple more things done. We will also be open sourcing the new version of prism as well.

**Comment by echovue** [comment]
Thanks!  Excited to see the open source offering.
