### ISSUE TITLE
prism-http does not work with webpack 5 out of the box

### ISSUE THREAD

**Issue by mpodlasin** [stoplightio/prism#1502]
## Describe the bug

Webpack 5 no longer provides node polyfills for browsers out of the box. 

Because of that, the following code:

```js
import * as PrismClient from '@stoplight/prism-http/dist/client';
console.log(PrismClient);
```
doesn't compile with out of the box settings of webpack 5

## Expected behavior

In documentation for `prism-http` there should be a description how to run it with webpack 5.

I already prepared a configuration that works.

This configuration compiles and allows to execute import of the library in the browser without any errors.

However *I didn't do any extensive regression tests* to make sure that the code actually works. So this should be double checked before including the config in the documentation.

```js
// webpack.config.js
const webpack = require('webpack');

module.exports = {
  // usual config content
  resolve: {
    fallback: {
      "path": require.resolve("path-browserify"),
      "vm": require.resolve("vm-browserify"),
      "https": require.resolve("https-browserify"), // needed by json-schema-ref-parser
      "http": require.resolve("http-browserify"), // needed by json-schema-ref-parser
      "stream": require.resolve("stream-browserify"),
    }
  },
  plugins: [
    new webpack.DefinePlugin({
        'process.env.NODE_DEBUG': JSON.stringify(false), // needed by json-schema-ref-parser
        'process.platform': JSON.stringify(null), // needed by json-schema-ref-parser
    })
  ],
};
```

**Comment by XVincentX** [comment]
1. This configuration file is probably too much for Prism. Looking at these modules I think the only one we _might_ use is `path`, all the others would not required

2. I do not want to play this game. We'll start with Webpack, then Parcel, then another one, and we got an entire section of module bundling that *I* will have to maintain. I'm more inclined to be like "figure it out"

> However I didn't do any extensive regression tests to make sure that the code actually works

That's enough for me to hold on merging this for sure

**Comment by mpodlasin** [comment]
>This configuration file is probably too much for Prism. Looking at these modules I think the only one we might use is path, all the others would not required

In that case it would be awesome to have an indication which modules are actually required. :)

Even better would be if they disappeared from the code altogether, if they aren't necessary - and I obviously only mean here part of the code that is supposed to be browser-compatible - I don't know if you intend supporting prism in the browser and it what capacity.
