### ISSUE TITLE
Allow absence of success reponses

### ISSUE THREAD

**Issue by michele-carignani** [stoplightio/prism#1520]
## User story.

As a tester of an API (client or server), I may need to validate that a certain endpoint always returns an error code, so that I can make sure the endpoint is never used. I would then need the mock to respond with an error code.

## Is your feature request related to a problem?

This is a relevant use case for standardized APIs, where the designers want to prevent that the implementer of the API introduces a custom usage of endpoint within API.

## Describe the solution you'd like

Instead of returning the server error (as documented in [link](https://meta.stoplight.io/docs/prism/docs/guides/errors.md#no_success_response_defined)), the mock would return the 4xx or 5xx as documented in the contract (e.g. OpenAPI).

## Additional context

An example of API endpoints always returning error codes is available at [link](https://forge.etsi.org/swagger/editor?url=https://forge.etsi.org/jenkins/job/NFV%20-%20Network%20Functions%20Virtualisation/job/sol005-master/23/artifact/build/SOL005-NSLifecycleManagement-API.yaml/*view*/).

**Comment by XVincentX** [comment]
@philsturgeon Thoughts?

**Comment by philsturgeon** [comment]
would standardisation behaviour like this belong in spectral instead? 

Prism is about creating a mock of what you’ve designed.

Spectral is about shaping what you’ve designed to be more standard.

Lots of functionality _could_ go in either but whether it _should_ or not is a very different matter.

**Comment by XVincentX** [comment]
On one way the common sense would suggest me to say "Hey, Prism mocks what you've designed"; so if the user designed something that does not make any sense — let they have it them way. Spectral can fill the hole if necessary.

I do not even recall why it was mandated that Prism would require a successful response; that was not a decision I took and it was already in place when I took over the project.

**Comment by philsturgeon** [comment]
@XVincentX good point, I don't know the history of this or the motivations either. If something only has a 3xx that's fine too. Instead of expanding to all 3xx let's just not make demands about how people design their APIs, as that's for Spectral to do.

Kill it 🔥
