### ISSUE TITLE
Deprecation HTTP Header

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/prism#1563]
## User story.

As a API client developer, I can interact with Prism Mock or Proxy, and find out when an endpoint I interact with is deprecated. 

## Is your feature request related to a problem?

Now that Studio and Docs mark HTTP Operations as deprecated, we need to help surface that to developers in any way possible. 

## Describe the solution you'd like

When an API client application is interacting with Prism, they should see a [Deprecation HTTP header](https://tools.ietf.org/id/draft-dalal-deprecation-header-01.html) for any Mock endpoint which has `deprecated: true`.

The Deprecation HTTP Header should look like this:

```
Deprecation: true
```

Seeing as OpenAPI does not offer any other information, like a date or replacement information, we cannot do anything more than this, but this is enough to let developers know that something is up (if they're looking for it, but that is a whole other story).

For the proxy, if the server has set its own `Deprecation` header then we should respect it, only add this header if there is not one defined in the message already.

**Comment by lukasz-kuzynski-11sigma** [comment]
Released in version https://github.com/stoplightio/prism/releases/tag/v4.4.0 :)
