### ISSUE TITLE
Example by $ref returned as the content of the "value" key of a wrapper json object

### ISSUE THREAD

**Issue by MarinKacaj** [stoplightio/prism#1590]
## To Reproduce

1. Given this OpenAPI document named my-spec.yaml
`
openapi: 3.0.3
info:
  title: My API
  version: 2.0.0
  description: Some description
paths:
  /my/path:
    get:
      responses:
        '200':
          content:
            application/json:
              example:
                $ref: '#/components/examples/MyResponse'
              schema:
                $ref: '#/components/schemas/MyResponse'
components:
  schemas:
    MyResponse:
      type: array
      items:
        $ref: '#/components/schemas/MyItem'
    MyItem:
      type: object
      properties:
        id:
          description: Reference to the id
          type: number
        name:
          description: The name
          type: number
  examples:
    MyResponse:
      value:
        - id: 1
          name: John
        - id: 2
          name: Jack
`
2. Run this CLI command `prism mock -h 0.0.0.0 -p 4010 my-spec.yaml`
3. This error log is printed: ` [VALIDATOR] ✖  error     Violation: response.body should be array`. Wrong response, wrapped in {"value": [example content]}. 

## Expected behavior

Expected response:
`[{"id":1,"name":"John"},{"id":2,"name":"Jack"}]`
Actual response:
`{"value":[{"id":1,"name":"John"},{"id":2,"name":"Jack"}]}`

An example in an OpenAPI yaml file is referred to by a $ref. The example's content, under #/components/examples/MyResponse/value, is returned as {"value": <example content>} from prism. Defining an example under components is allowed, as shown [here](https://swagger.io/docs/specification/adding-examples/), in the "Reusing Examples" paragraph.

## Additional context
Using 4.1.2, installed through `npm install -g @stoplight/prism-cli`

**Screenshots**

**Environment (remove any that are not applicable):**
 - Library version: 4.1.2
 - OS: MacOS Catalina 10.15.7
 - Browser: Chrome 87
 - Platform: Desktop

**Comment by chohmann** [comment]
Here's the formatted spec that was provided for reproduction of the issue:
```
openapi: 3.0.3
info:
  title: My API
  version: 2.0.0
  description: Some description
paths:
  /my/path:
    get:
      responses:
        '200':
          content:
            application/json:
              example:
                $ref: '#/components/examples/MyResponse'
          schema:
            $ref: '#/components/schemas/MyResponse'
components:
  schemas:
    MyResponse:
      type: array
      items:
        $ref: '#/components/schemas/MyItem'
    MyItem:
      type: object
      properties:
        id:
          description: Reference to the id
          type: number
        name:
          description: The name
          type: number
  examples:
    MyResponse:
      value:
        - id: 1
          name: John
        - id: 2
          name: Jack
```

**Comment by XVincentX** [comment]
Hey @MarinKacaj,

we have just concluded an investigation on this matter; Prism is behaving correctly in this case.

According to the [media object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#media-type-object) specification, the example is typed as `any` and its content gets dumped in the response.

When Prism is loading your document, the OpenAPI Specific References get resolved according to the specification rules; all the other references (which is your case) simply gets resolved and its content dumped in the relative section.

Essentially, this means that the final example is:

```yaml
content:
  application/json:
    example:
      value:
        - id: 1
            name: John
        - id: 2
            name: Jack
```

Which is the response you're getting. On the other hand, the example resolution is different for the `examples` keyword; so this document behaves in the way you're expecting:

```yaml
openapi: 3.0.3
info:
  title: My API
  version: 2.0.0
  description: Some description
paths:
  /my/path:
    get:
      responses:
        '200':
          content:
            application/json:
              examples:
                - $ref: '#/components/examples/MyResponse'
          schema:
            $ref: '#/components/schemas/MyResponse'
components:
  schemas:
    MyResponse:
      type: array
      items:
        $ref: '#/components/schemas/MyItem'
    MyItem:
      type: object
      properties:
        id:
          description: Reference to the id
          type: number
        name:
          description: The name
          type: number
  examples:
    MyResponse:
      value:
        - id: 1
          name: John
        - id: 2
          name: Jack
```

Cheers!
