### ISSUE TITLE
Reconsider implementing basepath (v2) or server (v3)

### ISSUE THREAD

**Issue by boeboe** [stoplightio/prism#1591]
Basepath and server are both essential elements in the V2 and V3 specification. Not supporting it because "it is confusing to some others" does not make sense. It is very little implementation work to implement this and you can still keep the default behavior to ignore it, if you wish (although I do not understand why a client implementation would need to make an exception w.r.t basepath just because a mock server is not implementing it correctly). The only way to support a real mock server now (and having the right full URL paths is essential for that), is to front prism with a reverse proxy to do URL remapping.

I am going to need to look for alternatives, as the goal of a mock server is to stay as close to the specifications as possible, not to make exceptions and chose to ignore essential elements. Clients, like SwaggerUI and others, all are implemented taking the basepath or server correctly into account.

https://microcks.io looks very promising.

**Comment by XVincentX** [comment]
I’m closing this. We can continue the conversation in the other issue already opened which I’m going to convert to a discussion.

**Comment by arnaubennassar** [comment]
Totally agree with @boeboe we have added versioning on the path of our API and prism stopped working because of that. I hope this gets implemented as described in the spec, until then I'll have to look for alternatives.

**Comment by jonnyhork** [comment]
@XVincentX I completely agree with @boeboe , not honoring  the servers `servers` property in OpenAPI 3 basically renders Prism useless for my team. It makes no sense to me how a mock server that does not accurately mock the server is supposed to be helpful. Is there any updates on supporting base paths?

**Comment by jonnyhork** [comment]
ok thank you!

**Comment by komachi** [comment]
As a simple hack to support `basePath` I just map over operations list to rewrite to needed path.

```js
import { createServer } from '@stoplight/prism-http-server';
import { getHttpOperationsFromSpec } from '@stoplight/prism-cli/dist/operations';
import { createLogger } from '@stoplight/prism-core';

const specUrl = 'https://raw.githubusercontent.com/sendgrid/sendgrid-oai/eb7a825bf06dfec7da2622735c5334c0d35da9fa/oai_stoplight.json';
const operations = await getHttpOperationsFromSpec(specUrl);
const patchedOperations = operations.map(operation => ({
  ...operation,
  path: `/v3${operation.path}`
}));
const server = createServer(patchedOperations, {
  cors: true,
  config: {
    checkSecurity: true,
    validateRequest: true,
    validateResponse: true,
    mock: { dynamic: true },
    errors: false
  },
  components: {
    logger: createLogger('TestLogger')
  }
});
await server.listen(1337, '127.0.0.1');
 ```

This finally works, and this also will allow https://github.com/sendgrid/sendgrid-oai to upgrade to new version, as they use old version specifically to handle this case (took me a while to figure out why it works in their case and not working in mine).
