### ISSUE TITLE
Contract testing 204 no content oddities.

### ISSUE THREAD

**Issue by marbemac** [stoplightio/prism#16]
Version: 2.0.0-alpha.3
Context: Conductor

Needs verification.

Scenario step sends HTTP request, with response status 204 (no content) after a DELETE operation. 

The body shown in the UI is “undefined” whereas my API writes nothing at all on output. Therefore, the contract testing always fails.

Found a workaround in declaring an output model as “string” and “optional” but it’s not true.

**Comment by pytlesk4** [comment]
Releated to #24
