### ISSUE TITLE
Cannot serve 204 response with client specified Accept header

### ISSUE THREAD

**Issue by lehphyro** [stoplightio/prism#1618]
## Describe the bug

Given an API spec like the following:
```
  /test:
    delete:
      operationId: testDelete
      responses:
        '204':
          description: Item has been deleted successfully
```

If a client sends a `DELETE` request *without* an `Accept` header, prism returns a 204 response successfully.
But if the client defines `Accept: application/json` in the request then prism returns a 406 response with the message: `The server cannot produce a representation for your accept header`.

## Expected behavior

I expect that prism returns a 204 response in both cases as there is no content to be returned.

**Comment by XVincentX** [comment]
Hey @lehphyro,

@philsturgeon, any thoughts? I am confident we already discussed this in the past.

As far as I am concerned, the spec claims that, if the `Accept` is missing, `Accept: */*`; should be assumed, which we treat as "Anything is good". Including an empty payload.

In your case, you're asking for a very specific media type (application/json) that the document does not instruct us how to create. To me, the behaviour looks correct.

**Comment by lehphyro** [comment]
@XVincentX `Accept` indicates what the client is able to understand, not what the server should return: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept

In this case, the client understands JSON, so iff there is a response body, it should be JSON. An empty response is acceptable and is in fact what the server will return in successful cases, error cases may have JSON bodies.

**Comment by XVincentX** [comment]
Hmm, you might have a valid point. I will check out the spec one again; in case you're right, we'll try to accommodate the use case.

**Comment by philsturgeon** [comment]
Yeah this makes sense. "The 204 status code means that the request was received and understood, but that there is no need to send any data back." so if we don't need to send back any data, we don't need to go looking for any data, so we don't need to complain that we couldn't find the type of data they were asking for. 

Thanks for the great feedback @lehphyro!

**Comment by lehphyro** [comment]
@XVincentX @chohmann We just got bitten by this issue again, are you guys planning to fix it any time soon?

**Comment by chohmann** [comment]
We don't have this fix slated for any sprints in the near term. Our team is currently working on releasing a new feature for Stoplight's platform. It is in our backlog and will be prioritized when we have capacity to do so.

In the meantime, we do accept PRs! So if you need it sooner than we can get to it, feel free to open up a PR!
