### ISSUE TITLE
[Bug] 422 Response Not Being Used For Validation Response

### ISSUE THREAD

**Issue by loganknecht** [stoplightio/prism#1657]
## Describe the bug

Hello! I could really use some help and guidance!

I have an `Open API` spec that is valid when I used `Spectral`

I can successfully run it with `Prism`

I have unit tests that validate an endpoint, so I am using `Prism` like so
`prism proxy --errors example.yaml http://localhost:8080`

When I send an invalid request it keeps giving me this error
```bash
{
  type: 'https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY',
  title: 'Invalid request',
  status: 422,
  detail: 'Your request is not valid and no HTTP validation response was found in the spec, so Prism is generating this error for you.',
  validation: [
    {
      location: [Array],
      severity: 'Error',
      code: 'required',
      message: "should have required property 'firstname'"
    },
    {
      location: [Array],
      severity: 'Error',
      code: 'required',
      message: "should have required property 'lastname'"
    },
    {
      location: [Array],
      severity: 'Error',
      code: 'required',
      message: "should have required property 'email'"
    },
    {
      location: [Array],
      severity: 'Error',
      code: 'required',
      message: "should have required property 'password'"
    }
  ]
}
```
Which is wild because this DOES exist.

It keeps stating `Your request is not valid and no HTTP validation response was found in the spec, so Prism is generating this error for you` which is not true at all because I have a `422` response declared for the endpoint that's being hit!

I have tried setting a `400` response. I've tried setting different data for the response. And nothing is working.

What am I doing wrong?

## To Reproduce

Use this file
```yaml
---
openapi: '3.0.2'

servers:
    - url: http://localhost:8080
      description: Local deployment from your computer

paths:
    /api/users/register:
        post:
            summary: 'Register New User'
            description: 'Register a new user'
            operationId: 'registerNewUser'
            tags: ['Users']
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: 'object'
                            properties:
                                firstname:
                                    type: 'string'
                                    minLength: 2
                                    maxLength: 100
                                    example: 'John'
                                lastname:
                                    type: 'string'
                                    minLength: 2
                                    maxLength: 100
                                    example: 'Roberts'
                                email:
                                    type: 'string'
                                    minLength: 4
                                    maxLength: 100
                                    example: 'john@example.com'
                                password:
                                    type: 'string'
                                    minLength: 8
                                    maxLength: 50
                                    example: 'abc123456'
                            required:
                                - firstname
                                - lastname
                                - email
                                - password
            responses:
                '201':
                    description: Successful registration of a new user
                '422':
                    description: Failed to register new user
                    content:
                        application/json:
                            schema:
                                type: 'object'
                                properties:
                                    message:
                                        type: 'string'
                                        example: 'firstname is required'
```

Run `prism proxy --errors example.yaml http://localhost:8080`

Run this curl command to confirm it works
```bash
curl --location --request POST 'localhost:4010/api/users/register' \
--header 'Content-Type: application/json' \
--data-raw '{
	"firstname": "First",
	"lastname": "Last",
	"email": "example@example.com",
	"password": "This_is_4_str0ng_password!"
}'
```

If you want pretty printing you can add `json_pp`
```bash
curl --location --request POST 'localhost:4010/api/users/register' \
--header 'Content-Type: application/json' \
--data-raw '{
	"firstname": "First",
	"lastname": "Last",
	"email": "example@example.com",
	"password": "This_is_4_str0ng_password!"
}'
```

Run this command to confirm it fails
```bash
curl --location --request POST 'localhost:4010/api/users/register' \
--header 'Content-Type: application/json' \
--data-raw '{}'
```
Same, but with pretty printing
```bash
curl --location --request POST 'localhost:4010/api/users/register' \
--header 'Content-Type: application/json' \
--data-raw '{}' | json_pp
```
And the final output is this
```bash
~/Repositories/example   feature/api_spec_and_test_reconciliation ±  ⬡ v12.17.0  curl --location --request POST 'localhost:4010/api/users/register' \
--header 'Content-Type: application/json' \
--data-raw '{}' | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   702  100   700  100     2   113k    333 --:--:-- --:--:-- --:--:--  114k
{
   "detail" : "Your request is not valid and no HTTP validation response was found in the spec, so Prism is generating this error for you.",
   "title" : "Invalid request",
   "type" : "https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY",
   "status" : 422,
   "validation" : [
      {
         "severity" : "Error",
         "location" : [
            "body"
         ],
         "message" : "should have required property 'firstname'",
         "code" : "required"
      },
      {
         "message" : "should have required property 'lastname'",
         "location" : [
            "body"
         ],
         "severity" : "Error",
         "code" : "required"
      },
      {
         "code" : "required",
         "severity" : "Error",
         "location" : [
            "body"
         ],
         "message" : "should have required property 'email'"
      },
      {
         "message" : "should have required property 'password'",
         "location" : [
            "body"
         ],
         "severity" : "Error",
         "code" : "required"
      }
   ]
}
```

## Expected behavior

I expect the responses I created for `422` to be used so that I don't have to worry about `Prism` returning different payloads than what my server does.

## Questions

How do I get `Prism` to not return a generated `422` override?

Because it keeps generating that validation response I can't integrate it with my tests, because the tests expect a `message` property to be there.

I've read through the documentation here:
- https://meta.stoplight.io/docs/prism/docs/guides/errors.md#unprocessable_entity
- https://meta.stoplight.io/docs/prism/docs/guides/02-request-validation.md#request-validation

And none of it provides an explicit example on how to make it so that `Prism` does not return an auto-generated response.

## Additional context

 - Prism: 4.1.2
 - OS: MacOS

**Comment by loganknecht** [comment]
Hello! Is there anyone who can provide guidance on how to get `422` errors in the request body to return a response that isn't auto-generated?

**Comment by loganknecht** [comment]
Hello!

Are there any examples to demonstrate how to send a non-generated response for a `422` error with the `requestBody`

**Comment by loganknecht** [comment]
Hello!

Is there any documentation on the `prism proxy --errors` command and how to get it to return the server response instead of a generated response for an invalid `requestBody`?

**Comment by loganknecht** [comment]
Hello!

Is there any guidance on how to use the api server's `422` error `response` when using the `prism proxy --errors` command?

**Comment by loganknecht** [comment]
Hello! 👋 

My org is very excited about Prism and would love to know if there are any ways to seek support regarding this issue we're encountering!

**Comment by chohmann** [comment]
@loganknecht thank you for reaching out about this issue and for providing detailed reproduction steps! Prism should be able to respond with the 422 response you have defined in your spec. Here's some [docs](https://meta.stoplight.io/docs/prism/docs/guides/02-request-validation.md#parameter-validation) with more information regarding Prism's handling of invalid requests. We will investigate to see why this is not happening for your specification.

**Comment by loganknecht** [comment]
Hi @chohmann!

Thank you so much for taking the time to respond!

I've read the lovely documentation page you've provided and that's why I was under the impression my `422` response should be used.

Specifically this part
```
Look for a response with status code 422 on the operation you were trying to execute

If there's not a 422 defined, it will look for a response with status code 400 on the operation you were trying to execute

In case there's neither a 422 nor a 400 defined, Prism will create a 422 response code for you indicating all the validation errors it found along the way. Such response will have a payload conforming the application/problem+json specification.
```

But alas, nothing happens when I run with `prism proxy ...`

I'm more than happy to help try and resolve the problem with a merge request if you can point me to the offending area in the codebase.

Until then I am eagerly awaiting your insight and response!

**Comment by chohmann** [comment]
Hi @loganknecht,

I was taking a closer look at this and realized you're using prism in `proxy` mode, and not in `mock` mode. When in `proxy` mode a request that does not match the schema will either be forwarded to the existing api server, or prism will blow up the request based on the use of the `--errors` flag. It will not return a response defined in the spec in `proxy` mode. More information on `proxy` mode can be found [here](https://meta.stoplight.io/docs/prism/docs/guides/03-validation-proxy.md).

The error message is absolutely misleading when read in the context of `proxy` mode. The error object is shared across both `mock` and `proxy` modes, but is worded primarily for the `mock` context. We could look into making this error message more clear when used in the `proxy` context, but probably won't be able to do so in the short term.

If you run prism in `mock` mode, the example defined for the `422` response will be returned if an invalid request is sent to prism:
![image](https://user-images.githubusercontent.com/33431856/106980396-bc90f700-6725-11eb-8be8-8727b8fdd3e7.png)

I hope that answers your questions!

**Comment by loganknecht** [comment]
Heyo @chohmann

Thank you so much again for taking the time to discuss this.

I've read the documentation a few more times, and it sounds like I misinterpreted the `prism proxy --errors ...` functionality. Thank you for the clarification.

# `Prism Proxy` Requests

If it's possible, when using `proxy` mode it would be absolutely fantastic if there was a way to allow invalid requests through, instead of generating an error.

The use case I'm trying to solve is that we have a `server` that is deployed, and we want to see if our `spec` matches the `server`. Additionally we want it to fail loudly as ideally it would be integrated into our CI/CD. Lastly, I want to run `prism proxy --error ...` with my tests to see where the `spec` is wrong, but I don't want my tests broken or to be rewritten entirely.

For example, my tests are intended to fail when the `request body` is incorrect. So they're already looking for a `422` code with the error message. And all I'm looking for from `prism` is to confirm that the `invalid request` is getting at least one of the expected `responses` back. And that all of these pieces are expected in the `spec`. It just needs to let the `request` through and validate the `response`, and tell me if the `response` doesn't match the `spec` and fails.

In this situation I KNOW that the request is incorrect. So I don't need `prism` to tell me the `request` is incorrect. I need it to tell me the `response` is incorrect as that's what the test is validating.

In its current form what I get is a test that fails because the intentionally `invalid input` causes `prism` to return a `generated error` for validating the request instead of using the `server error` that is expected and erroring out when the `response` is invalid.

The result of all of this, is I can't use `prism proxy --errors ...` mode as an integrated CLI tool for CI/CD because it won't integrate with the existing tests that are intentionally sending bad requests, and instead generates failure responses in the place of my server.

# Prism Mock Requests

I have been trying the `mock` functionality and I'm not having much luck in smoothly integrating it into the existing tests.

## Unable to Select `example` using `Prefer`

I have been able to successfully use the `Prefer code=<NUMBER>`, however I have not been able to successfully use the `example` portion. Like so, `Prefer example=<STRING>`.

So if I have something like this

```yaml
---
description: Invalid request bodies
content:
    application/json:
        schema: { $ref: "../../resources/common/error_message.yaml" }
        examples:
            projectDoesNotExist:
                value:
                    message: "failed to update project information with invalid parameter {id}"
            projectNameIsEmpty:
                value:
                    message: '"name" is not allowed to be empty'
```

If I do something like this in my code

```javascript
// ...
it("It should fail to update project with a payload that has a name with an empty string", (done) => {
    chai.request(server)
        .patch(`/api/projects/${id}`)
        .set("Prefer", "example=projectNameIsEmpty") // Required for Prism integration
        .send({
            name: "",
            description: "editing project name"
        })
        .end((err, res) => {
            if (err) done(err);
            assert.equal(res.status, 422);
            assert.equal(res.body.message, '"name" is not allowed to be empty');
            done();
        });
});
// ...
```

It will actually use the `projectDoesNotExist` instead of the `projectNameIsEmpty` example. It seems as though it's just picking from the top of the list. It doesn't matter how many other examples I have.

## Unable to Combine `Prefer` `code` and `example`

The documentation states

> Remember: you can combine code, example and dynamic parameters. By default, when the code parameter is not given, Prism will always try to fetch an example using the exampleKey from the 200 HTTP responses only. You'll need to use the code parameter alongside the example one for any specific example using a different HTTP status code than 200

However it does not show an example of what they look like together.

Should it be something like one of these?

-   `Prefer code=422;example=userDoesNotExist`
-   `Prefer code=422&example=userDoesNotExist`
-   Or do I set the `prefer` header twicer

## Unable to Disable Validation On a Request or Response Using Headers

If you look at the documentation here
https://meta.stoplight.io/docs/prism/docs/guides/http-client.md#create-client-from-file

There are properties called

-   `validateRequest`
-   `validateResponse`

Because of those properties I had assumed that I would be able to add `headers` to the request and be able to toggle the `request` and `response` of a request so that essentially I could `disable prism mock` for the test I'm running

**The goal I'm trying to solve here is disabling validation for a request because Prism isn't working with the test**

I tried setting the headers to `validateRequest=false` and it didn't change anything.

Is there a way to disable validation for a request using the header in order to integrate `prism mock` with existing tests without using the `prism client`?

**Comment by chohmann** [comment]
@loganknecht I'm going to try to answer all of your questions.

>If it's possible, when using proxy mode it would be absolutely fantastic if there was a way to allow invalid requests through, instead of generating an error.

This is possible, just leave off the `--errors` flag and the request will be forwarded to the actual server. Prism will also still validate the request matches the spec and log out any validation errors.

Here's how I verified this use case:
1. rather than building an api server to proxy requests to, I spun up a mock server using your OAS Spec 
  ```
prism mock /Users/chelseapace/stoplight/prism/examples/sample-openAPI.yaml -h localhost -p 4090
```
so now I have my "actual" server running at http://localhost:4090

2. spin up prism in proxy mode and proxy requests to our "actual" server created in step 1. Leave off the `--errors` flag to make sure the requests get forwarded to our actual server
```
prism proxy /Users/chelseapace/stoplight/prism/examples/sample-openAPI.yaml http://localhost:4090
```
our prism proxy now accepts request at http://localhost:4010 and forwards them to http://localhost:4090

3. Make a request to the prism proxy and see it get forwarded to our actual server at http://localhost:4090.
```
curl --location --request POST 'localhost:4010/api/users/register' \
--header 'Content-Type: application/json' \
--data-raw '{}'
{"message":"firstname is required"}%
```

The response we get is the one returned by our actual server:
![image](https://user-images.githubusercontent.com/33431856/107265093-78de0c00-6a09-11eb-8df7-2ae0717a51bf.png)

And looking at the logs of the prism proxy, you can see it logged out validation errors the request had:
![image](https://user-images.githubusercontent.com/33431856/107265186-96ab7100-6a09-11eb-96ad-6902e7cc8b42.png)

Based on the use case you described, I don't think Prism will add any value. You want to hit the actual server, receive the actual response, and then validate the string like `expect(response).toBe('message defined in spec')`. You can do that without prism proxy, you'll just have to keep the test code up to date with what response to expect.

**Comment by loganknecht** [comment]
Hello @chohmann!

I really wish there was a higher bandwith form of communication we could use 😂 
I think we may be getting our wires crossed together and I would love the opportunity to understand the thought process as well as contrast it with the goals I'm trying to achieve.

# RE: `--errors` Flag

I want to use `prism` in my CI/CD in order to call out drift between my `spec` and `implementation`. I **need** this on a spiritual level, and on an organizational level 😂 

With the `--errors` flag the CI/CD will fail because `Prism` will return an error code when the `spec` does not match the `request` or `response` payload. **I want this feature**

My understanding is that if I drop the `--errors` flag that will not cause an error to be generated and instead will just be receiving the exact `response` from my server back, which is fine. But not what I'm looking for.

What I want is `prism` to allow opting out of the `request` validation in order to allow the opportunity for the `response` to be validated against the `spec` BEFORE I receive the response back and run my validations on it.

In this situation there would be a `response` error generated just like the `request error`.

What I would like it look like is this

1. Test `Request` -> `Prism` -> `Server`
    - No request validation 
1. Server `Response` -> `Prism` -> `Test`
    - Response validation is performed
1. `Prism` screams about a `response` and `spec` mismatch
    - I fix mismatch, and run it again
    - Now response is valid
1. Test `Request` -> `Prism` -> `Server`
    - No request validation 
1. Server `Response` -> `Prism` -> `Test`
    - `Response` validation is performed, but no errors were found, so original server response is returned

In this situation I can rely on `Prism` to fail when the spec doesn't match and succeed when it does. And then, I get an addition layer of validation that's easy to layer on top of existing tests without having to rewrite anything, because it will check

1. Specification validity
AND when the spec is valid, the correct response will get through so now I also get
2. My tests to validate the response as well

# Reiterating Desired Feature

I would love love love it if `Prism` generated errors when the `response` payload does not match the `response` in the `specification`.

In order to get to this step, I NEED `Prism` to allow the ability to skip `request validation` otherwise it generates a response saying the `request is invalid`, which is intended.

I see in your `Prism Client` documents here, that this type of logic is already supported
https://meta.stoplight.io/docs/prism/docs/guides/http-client.md#override-the-configuration-object-on-the-request-level

HOWEVER, I do not want to code this in the `Prism Client` because I already have tests set up and configured.
What I do want though, is the ability to pepper in something like a header to skip `requestValidation`

I want to have `Prism` as an intermediate layer that I spin up and run requests/responses through in my CI/CD

Ideally, just like the `Prefer` header you all have provided, it would be radical if you had something like

- `RequestValidation: False`
- `ResponseValidation: False` 

For example - See line 4
```javascript
// ...
it("It should fail to update project with a payload that has a name with an empty string", (done) => {
    chai.request(server)
        .patch(`/api/projects/${id}`)
        .set("RequestValidation", "false") // Required for Prism integration
        .send({
            name: "",
            description: "editing project name"
        })
        .end((err, res) => {
            if (err) done(err);
            assert.equal(res.status, 422);
            assert.equal(res.body.message, '"name" is not allowed to be empty');
            done();
        });
});
```

Which would then let me simply change my tests to add headers in order to skip the steps.

In this way, I can integrate `Prism` on top of my tests for free AND I don't have to write any of my tests over again. I just add `headers` to indicate the validation I want `Prism` to scream about.

By dropping the `--errors` flag I am missing the best part about `Prism` which is the screaming about a `spec` mismatch. That is why I am so excited about the tool - `Contract validation`.

# `Prefer` Header Usage

@chohmann Can you please clarify the issues I was having with the `Prefer` keyword and `example` as well as combining the usage of `code` and `example`

Or, would it be better to open a separate ticket for that issue?

**Comment by loganknecht** [comment]
Hi @chohmann!

Just following up! Can you clarify if my requests are unreasonable? Are they also currently possible?

Can you also clarify how to use `code` and `example` when using the `mock` functionality of `prism`? If not, I'll make a follow-up ticket :)

**Comment by philsturgeon** [comment]
@loganknecht hey, you can ignore Prism HTTP Client, that was an experimental API which was never finalized, and is being axed soon.

Can I ask _why_ you want to be able to slip validating requests to only validate responses? If you want to use contract testing to make sure there's no drift between spec and implementation, why exactly would you only want to validate half of the contract?

**Comment by loganknecht** [comment]
@philsturgeon Absolutely!

# Short Version

- I have `tests` that are intentionally sending a bad `request` because they want to validate the `response` that is returned.
- I need `Prism` to tell me if my `responses` for a bad `request` don't match the `specification`
    - I already know the `request` is bad, because that's the point of the test
- If I send a bad `request` when I use `--errors` `Prism` will fail loudly and send the `generated response` back instead of the server response.
    - I want the loud failure because it's for CI/CD
    - I want to be able to skip the `request` validation, just to see if it will fail loudly for the `response`
- Because I can't send a bad `request` to get a `response`, in order to have `Prism` validate the `response` and in turn have my test validate the `response`, I cannot integrate this easily into my CI/CD as a tool to validate contracts of a service using existing tests.

# Long Version

**[Cue Don LaFontaine Voice](https://www.youtube.com/watch?v=PjWKE-IJ4R8)** 

〜In a world〜 Where you are an engineer who's being asked the big question.
> How do we know that our `implementation` matches our `specification`

We already have quite a few `system tests` that run. These are tests that are configured to target a `server` and make queries to validate it is all correct. The idea is that the tests hit the server, and then check the payload received.

The problem is that the `System Tests` DO NOT validate against the `specification`. We are just checking that garbage in === garbage out. Which is what creates `specification drift`

One solution is that I could hand write several tests and check them directly in the code asking if the `response` etc matches the specification. I have a code base of over 90 different tests to validate the endpoints of our API. To re-write that is a lot, so it's not something I'm hyped about doing because I have to hook up the pieces to either check the contract directly in the test. Or I have to write 90 new tests.

But all that's ok I found `Prism`. Which is AMAZING.

The `prism proxy --errors ...` feature provides a fantastic ability to serve as a `cli` middle ware for validating contracts and failing loudly when they don't match!

So rather than having to worry about rewriting, or creating new tests. I should be able to run `prism` and then have my `system tests` target the proxy.
- If the contract is valid, then each test can continue to perform
- If the contract isn't valid, then `Prism` generates an error and it fails loudly, which causes the test to fail

And it's fantastic! It's super easy to run the proxy, and then re-run tests using the proxy, and the tests are able to validate without out issues, but if the contract is wrong it fails loudly and we're able to fix it!

## The Issue
We have tests built out to intentionally send bad requests. And this is because we want to make sure the `server` is sending the correct `response` and performing the correct operations in the case of a failure.

Something like this
```javascript
        it('It should fail to create a new project with a name that is empty', (done) => {
            chai.request(server)
                .post('/api/projects')
                .send({
                    name: '', // project name is empty
                    description: 'this is a test project',
                })
                .end((err, res) => {
                    if (err) done(err);
                    assert.equal(res.body.hasOwnProperty("message"), true);
                    assert.equal(res.status, 422);
                    done();
                });
        });
```

In this case, we still want `prism proxy --errors ...` to fail loudly, but we want it to fail loudly when our `response` is incorrect! Not when our `request` is incorrect.

What you all did with the `Prefer` header is brilliant. Because in this case, what I need is something to tell the server that might be testing against that I KNOW the `request` is bad.
So my suggestion/request is that you simply add a `SkipRequestValidation` and/or `SkipResponseValidation` headers. If I was able to skip the `request` validation, I would be able to make sure that the `response` validation is executed. And in my tests all I have to do is add a header.

```javascript
        it('It should fail to create a new project with a name that is empty', (done) => {
            chai.request(server)
                .post('/api/projects')
                .set('SkipRequestValidation', true) // <--- HERE
                .send({
                    name: '', // project name is empty
                    description: 'this is a test project',
                })
                .end((err, res) => {
                    if (err) done(err);
                    assert.equal(res.body.hasOwnProperty("message"), true);
                    assert.equal(res.status, 422);
                    done();
                });
        });
```

And then! I can drop `Prism` cli across my organization for FREE, by simply tweaking testing headers, and creating a new CI/CD step that runs the same tests, but just against a `prism proxy --errors ...` instance.

This is HUGE and would accomplish such a big piece of testing for our organization!

We would be able to craft tests that target `api specification contracts` and `implementation` contracts using the SAME tests.

**Comment by loganknecht** [comment]
Hey @chohmann and @philsturgeon!

I've updated the above post in response to @philsturgeon a couple of times. So make sure to give it another look if you haven't!

Looking forward to your response!

**Comment by philsturgeon** [comment]
@loganknecht I see what you're trying to do but this isn't what the proxy is for. There are lots and lots and lots of assertion libraries out there you can use to confirm the response from a HTTP request matches a certain JSON Schema / OpenAPI Schema, and there's no reason to try and use Prism to do that.

See this article for some pointers: https://apisyouwonthate.com/blog/writing-documentation-via-contract-testing

The use cases we aim to support are general traffic passing through. If you want it to blow up, you can use --errors, if you dont, you can inspect the `sl-violations` headers to see what is reported there. That should cover anyone's use cases but the sample you've shown me suggests wrong tool for the job. :)

**Comment by loganknecht** [comment]
Hey @philsturgeon

That's really unfortunate to hear.

Your documentation explicitly states
> The proxy feature will help you identify discrepancies between the OpenAPI document (supposedly the source of truth) and any other server you designate as the target. 

It even goes further to state
> In this use case, the OpenAPI documents would be provided by the API team, distributed to the API consumers, and the proxy server would be pointing to the dev environment. We'd also want to enable --errors so Prism will blow up your request if a mismatch is noticed.

However there is clearly a shortcoming here where I cannot validate the discrepancies between the responses in the case of a `422` of a live server when using the `--errors` flag.

If `prism` is intended to `help you identify discrepancies between the OpenAPI document (supposedly the source of truth) and any other server`

Then it is falling short in 50% of the process in the case of `422` errors.

- I cannot identify discrepancies in my `responses` in the case of a `422` error of the server using the `--errors` flag because `prism` blocks on that
- I can ONLY blow up in the case of the mismatched request which misses the second half of the `end-to-end` life cycle listed as another use case.

I see that you've closed this ticket. But, in truth I would really prefer to leave this open or create a new ticket that is a `feature request` where `prism` allows the ability to skip `request validation` in order to support `response validation` on the service it's proxying. Or at least provides a way to guarantee as your documentation says `help you identify discrepancies between the OpenAPI document` for the case of `responses`

**Comment by philsturgeon** [comment]
You do not need the error to be in the response to see if there’s a problem. You can look at the `sl-violations` header.

Alternatively you can use tools that are designed to work as chai assertions.

**Comment by loganknecht** [comment]
@philsturgeon I think there is a misunderstanding 😄 

Thank you for the links you provided, but they are not relevant.

My goal is **not** to perform `chai` assertions.
The reason I have provided `chai` assertions was to help demonstrate that `prism` is so close to the finish line in being able to slot into `end-to-end` tests and be a tool for automation.

My goal is to place `prism proxy --errors` in front of my service for [end-to-end contract testing use cases](https://meta.stoplight.io/docs/prism/docs/guides/03-validation-proxy.md#end-to-end-contract-testing) and be able to know that there is a mismatch between the spec and the service. However that execution is handled doesn't matter. It could be `postman` it could be `chai` it could be `go assertions`. The goal is to have `prism proxy --errors ...` break loudly in the case of `422` errors response that does not match the spec.

The issue is that, at the moment, `prism proxy` does not really do `end-to-end contract testing`,  in this case for `422` responses using the `--errors` flag because `prism` won't allow the request to pass through in the case of an invalid request. Yes, I can do `sl-violations` but that doesn't break and scream loudly. I am not looking to interrogate the headers to determine if the request failed.

This makes it impossible to rely on `prism` in the case of validating all responses `end-to-end`.

Please consider this a `feature request` to figure out a way to support breaking loudly using the `errors` flag so that users of `prism` can know when their responses are mismatched against the specification.

**Comment by philsturgeon** [comment]
Use `--errors` if you want it to scream loudly. Do not use errors and inspect `sl-violations` if you do not want it to scream loudly.

Either way, users will know if their responses are mismatched against the specification.

This thread has become far too long to be considered anything other than a wontfix response to a bug that's not a bug. This is intentional functionality.

Thank you for understanding.

**Comment by dabernathy89** [comment]
I happened on the thread because I could not figure out how to do what I assumed was a pretty straightforward feature. I have E2E tests running, and currently I am manually asserting request/response data against our OpenAPI document.

I had hoped I could simplify my tests by just slapping Prism's proxy in between my test code and the test server. However, I'm unable to test _invalid_ requests because there is no way to configure the `validate-request` option via a request header. It seems a little strange that this is configurable at the CLI level but can't be overridden on a per-request basis.

**Comment by gechu** [comment]
I have a similar need as @dabernathy89 described, and yes, it would be optimal to have the option to deactivate request validation in Prism per request.

A workaround, assuming your 400 response is always the same, could be to simply bypass prism, and perform the response validation in the client like @philsturgeon mentioned.

A test in Postman could look like this:

```
let actualResponse = pm.response.json();

const expectedResponse = JSON.parse(`
{
  "type": "about:blank",
  "title": "Bad Request",
  "status": 400
}
`);

pm.test("Validate response body", function ()
{
    pm.expect(expectedResponse).to.deep.equal(actualResponse); 
});
```
