### ISSUE TITLE
allow prism to work with other schemas other than openapi

### ISSUE THREAD

**Issue by dagda1** [stoplightio/prism#1667]
## User story.

As a user
I can work with other schemas other than openapi

## Is your feature request related to a problem?

I think prism looks really, really cool and the code is very well written but it will only work with openapi.

I am using both open API and graphql.  It would be excellent if it worked for both using providers or something.

## Describe the solution you'd like

Prism provides an open API provider and a graphql provider.

**Comment by philsturgeon** [comment]
We support Postmsan Collections but slapping GraphQL into Prism isn't an easy job. 

This is not a feature the team is likely to pick up any time in 2021, but if anyone is interested in working on it I'd be very happy to discuss it with you.
