### ISSUE TITLE
CORS Error - stoplight response header contains multiple origin values

### ISSUE THREAD

**Issue by Gaetanbrl** [stoplightio/prism#1725]
## Describe the bug

I use a free web mock service : `https://jdev.stoplight.io`

From a **localhost project only** and since few days (don't now when exactly), stoplight mock service insert 2 values in the header origin : 

`Access to XMLHttpRequest at 'https://jdev.stoplight.io/mocks/jdev/tabou_api_swagger/4964747/etapes-pa-mock' from origin 'http://localhost:8081' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost:8081 always', but only one is allowed.`

Indeed, response header content 2 access-control-allow-origin (not permited by CORS):
`access-control-allow-origin: http://localhost:8081 always`

Here the response and request Headers :
![image](https://user-images.githubusercontent.com/16317988/110438045-51389d00-80b6-11eb-846b-195d8974b0d2.png)

When i try in production (with real domain and not localhost:8081) response headers content only one origin.

The request is created by axios lib inside react project. The react project is serv by webpack dev server in localhost port.

2 weeks ago, this works fine with localhost env. Yesterday, i come back work (after pause) and no response works... the code was not change.

Howerver, i dunno if this repo is the correct place for this issue... but this seems to be link with something like stoplight enhancement ? Maybe not... 

How could we fix that  ?

Thanks.

## To Reproduce

1. Start a local project
2. Runlib  query
3. Get response error

## Expected behavior

I expect stoplight.io mock request works with localhost origin.

## Additional context

**Environment (remove any that are not applicable):**
 - Browser: FF 86,  Chrome 88.0.4324
 - Platform: web

**Comment by Gaetanbrl** [comment]
> Howerver, i dunno if this repo is the correct place for this issue... but this seems to be link with something like stoplight enhancement ? Maybe not...

In addition, i just tested with another online mock service and it works fine. Stoplight error seems to be a correct idea...

**Comment by marbemac** [comment]
Hi @Gaetanbrl - I just tried it out and can't reproduce - are you still seeing the issue?

`curl -k -I -X GET -H "Origin: http://localhost:8081" https://jdev.stoplight.io/mocks/jdev/tabou_api_swagger/4964747/etapes-pa-mock`

<img width="1262" alt="Screen Shot 2021-04-14 at 9 14 51 PM" src="https://user-images.githubusercontent.com/847542/114804158-76c85e80-9d66-11eb-8a17-ac2558b484a2.png">
