### ISSUE TITLE
more control over faker datatypes and generated mocks

### ISSUE THREAD

**Issue by Nilegfx** [stoplightio/prism#1781]
## User story.

As a developer, I can pass faker function arguments, so that I can further customize my mocks.

## Is your feature request related to a problem?

No. Actually, I would like to thank the team behind prism and ask for feature that gives developers more control over the generated mocks

## Describe the solution you'd like

for now, I read the docs and went through the code quickly, I couldn't find a way to customize the faker datatypes, for example, paragraph with 5 sentences or firstName and gender as female.. etc

## Additional context

I would suggest having something along the lines of `x-faker: name.firstName female`

**Comment by chohmann** [comment]
@Nilegfx Thanks for your input! We actually have another issue describing this same feature request:

https://github.com/stoplightio/prism/issues/1647

We'll use that one to track this feature request, and I'll close this one.

Feel free to add any additional info or ideas to that ticket.
