### ISSUE TITLE
As a developer, I would like to check that requests only include fields which are in the specification

### ISSUE THREAD

**Issue by BenHewins** [stoplightio/prism#1787]
## User story

As a developer, I can currently use Prism to validate that requests I make in my tests are not missing fields which are required by the specification. I would like to be able to check that they also do not include fields which are not in the spec (via a config option).

## Is your feature request related to a problem?

* If you have an optional field, it is easy to mistype it when writing tests. Prism will not pick up that the additional field is not in the spec.

* It is easy to add a new field to an api, and update all the tests, without updating the spec. Prism will not currently alert you to the requests in tests not matching the spec, but it could do.

## Describe the solution you'd like

An optional flag (possibly at the request level) which causes Prism to generate validation errors if any fields are present in a request (or response?) that are not present in the spec.

## Additional context

This would not be useful for everyone, but when you are adding a spec to a project which didn't previously have one, or working on a project which is becoming more important and needs a better defined specification, it would be a lifesaver.

**Comment by philsturgeon** [comment]
Are you using additionalProperties: false?

**Comment by BenHewins** [comment]
You're right, that does it. Thank you!
