### ISSUE TITLE
Fallback to default response when example response is not found

### ISSUE THREAD

**Issue by jackbsv** [stoplightio/prism#1790]
## User story.

*api.v1.yaml*

```yaml
openapi: "3.0.0"
info:
  title: Example API
  version: 2.0.0
paths:
/endpoint:
    get:
      summary: 'some endpoint'
      operationId: login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  token:
                    type: string
                    minLength: 3
              examples:
                example-1:
                  value:
                    token: "example-1"
```
*EXAMPLE NOT FOUND*
1. `prism mock ./api.v1.yaml -d`
2. `GET /example?__example=example-2`
3. `{ token: "xyz" }`

*EXAMPLE FOUND*
1. `prism mock ./api.v1.yaml -d`
2. `GET /example?__example=example-1`
3. `{ token: "example-1" }`

## Is your feature request related to a problem?

No

## Describe the solution you'd like

When passing the `example=<example_name>` in either the `header` or as a `query` parameter, if the example is not found, it should fall back to the default response of either `static` or `dynamic` unless specified in a config option.

## Additional context

None

**Comment by philsturgeon** [comment]
This has been requested once or twice, but I am not sure what the benefit is. If somebody asks for something, they should get it. Hiding the mistake does not seem like a benefit, it just seems like it will confuse people who typo.
