### ISSUE TITLE
Allow request body bigger than 1MB

### ISSUE THREAD

**Issue by lehphyro** [stoplightio/prism#1814]
## User story.

As a developer, I can send requests bigger than 1MB, so that I can post images in base64 format to a REST endpoint.

## Is your feature request related to a problem?

It's impossible to use prism with big requests.
Also, prism doesn't log the request it rejected with a 413 response, so it's failing silently which makes it difficult to debug.

## Describe the solution you'd like

An option to configure max request size.

## Additional context

Other HTTP servers like nginx support configuration of max request size, prism should support it too.

**Comment by philsturgeon** [comment]
What are the big requests you are sending? The user story is not a pointless request, it's trying to understand the context of whats going on, which helps us figure out prioritization.

**Comment by gap777** [comment]
Why the hardcoded limit? Why the lack of explanatory error messages when prism mock server fails in this way? Doesn't sound like an enhancement to me... this seems like an outright bug, and unfortunately, it just bit us. 

How soon can we get this fixed?
Any work-arounds in the meantime?

**Comment by philsturgeon** [comment]
@gap777 Prism does not hardcode a limit, there is a default limit set in micri - the JS framework being used. The default is 1mb: https://github.com/turist-cloud/micri#api

The benefit of this being an FOSS package is that this could easily be contributed if its something you need quickly. Check it out:

https://github.com/stoplightio/prism/blob/0e43d0b2603f126e70cc9b109c1f8a1d183f9dc9/packages/http-server/src/server.ts#L40-L55

If you could send a PR that bumped that to 10mb for now, or whatever default you'd be happy with, then we can merge that and tag a patch release. If you'd like to get real adventurous you can figure out how to get CLI values passed through, so we could have `--upload-limit=10`.

Or, you can wait until we have time free from working on other things (that other people consider equally important), to get your thing done. 

Check out CONTRIBUTING.md for tips on how to send PRs and run the test suite.

**Comment by chohmann** [comment]
This has been included in Prism 4.2.6 release!
