### ISSUE TITLE
raise error when there is a property names 'pattern'

### ISSUE THREAD

**Issue by grunmin** [stoplightio/prism#182]
when there is a property names 'pattern', prism raise an error: `prism response body helper mock error Error: Expected a regexp or string in /`

example: swagger.json
```
...
"responses": {
  "200": {
    "schema": {
      "type": "object",
      "properties": {
        "pattern": {
          "type": "string"
        }
      }
    }
  }
}
```

**Comment by tbarn** [comment]
Hey @grunmin! We are looking more into this one.

**Comment by tbarn** [comment]
Workaround for this is to set a static example. It is caused by this error in JSON schema faker: https://github.com/json-schema-faker/json-schema-faker/issues/465

Although it doesn't look like they've created a release in a while, so we will need to figure out how we want to bring it in.

**Comment by pytlesk4** [comment]
@grunmin just released an update, issue is now resolved.
