### ISSUE TITLE
Prism cannot mock date format

### ISSUE THREAD

**Issue by Fohlen** [stoplightio/prism#183]
When mocking the following

```
responses:
    schema:
         created_date: 
             type: "string"
             format: "date"
```

will return `undefined` in mocked responses. Some `new Date()` would be a good response, for instance.

**Comment by tbarn** [comment]
Hey @Fohlen! Can you send over a specification where this is happening with? We hadn't seen this issue before, so we wanted to see it with what you are using.

**Comment by MeesterDev** [comment]
Had the same issue, date-time seems to be working fine. Made an additional test case as small as possible:

```
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Isolated test case"
schemes:
  - "https"
paths:
  /thing:
    get:
      responses:
        200:
          description: "Thing data"
          schema:
            $ref: "#/definitions/Thing"
definitions:
  Thing:
    required:
      - "date"
      - "dateTime"
    properties:
      date:
        type: "string"
        format: "date"
      dateTime:
        type: "string"
        format: "date-time"
```

**Comment by tbarn** [comment]
@MeesterDev what version of Prism are you using right now?

**Comment by MeesterDev** [comment]
I'm using version is 2.0.17, the most recent version of prism_windows_amd64.exe available from https://github.com/stoplightio/prism/releases.

**Comment by gschafra** [comment]
I'm experiencing exactly the same Problem when using the docker-container (https://hub.docker.com/r/stoplight/prism) which is currently on v2.0.16.

**Comment by tbarn** [comment]
Hey everyone, just wanted to let you know that we will be working on this bug in the next engineering sprint. We aren't ignoring y'all!

**Comment by tbarn** [comment]
We've got a fix for this and working on releasing a new version soon!

**Comment by pytlesk4** [comment]
Binary has been released, updating hosted prism now.
