### ISSUE TITLE
origin xx has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains the invalid value 'string'.

### ISSUE THREAD

**Issue by fabricemanhart** [stoplightio/prism#1839]
## Describe the bug

CORS not working

## To Reproduce

If I test my Vue app against prism Mock, I get following error

origin 'http://localhost:8080' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains the invalid value 'string'.

If I check in Chrome I can see that Prism returns for all CORS headers the value 'string' (see picture)

## Expected behavior

That there are the correct values, so that the request can be processed.

**Screenshots**

![image](https://user-images.githubusercontent.com/2248414/120102933-961c1f00-c14d-11eb-9b56-ba1f17c98bc5.png)

Preflight: 
![image](https://user-images.githubusercontent.com/2248414/120102903-7127ac00-c14d-11eb-9612-ed61df327048.png)

Thanks Fabrice

**Comment by chohmann** [comment]
@EdVinyard can you try to reproduce this so we can get more info?

**Comment by EdVinyard** [comment]
@fabricemanhart , I suspect that you have included `Access-Control-*` headers in your specification.  If so, removing those headers from your spec will allow Prism to include CORS-compatible headers in the response, which it will do unless you specify them.

For example, when I save the following spec as `issue1839.oas`...

```yaml
openapi: 3.1.0
paths:
  /:
    get:
      responses:
        '200':
          description: OK
          headers:
            # DO NOT SPECIFY Access-Control-* HEADERS MANUALLY
            # PRISM WILL ADD THEM AUTOMATICALLY.
            # Access-Control-Allow-Origin: 
            #   schema:
            #     type: string
          content:
            "*/*":
```

...and run Prism with `prism-cli mock issue1839.oas`, you can see in the following `curl` output that appropriate `Access-Control-*` headers are included automatically by Prism.

```sh
% curl -v localhost:4010/

...
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: *
< Access-Control-Allow-Credentials: true
< Access-Control-Expose-Headers: *
...
```

If I uncomment the `Access-Control-Allow-Origin` header in the spec though, the output matches your screenshot:

```sh
% curl -v localhost:4010/

...
< Access-Control-Allow-Origin: string
...
```

If you _must_ specify them explicitly, you'll need to include an example containing the desired header value.  For example, to match the automatically generated CORS headers, I could use:

```yaml
            Access-Control-Allow-Origin: 
              schema:
                type: string
                example: "*"
```

Please let us know if that works.
