### ISSUE TITLE
Include selected state for Tabs to the Admin Workspace page

### ISSUE THREAD

**Issue by noor-ahmad** [stoplightio/prism#1846]
Missing selected state for tabs
Component Reference: https://mosaic.vercel.app/docs/navigation/tabs

![image.png](https://images.zenhubusercontent.com/60abb0b7364d5be2dc789f9b/fbe43f2e-bce0-47ef-a0e3-d74de8f0ac3f)

**Comment by chohmann** [comment]
Closing as this was created in the Prism repository not the platform-internal repository. Created https://github.com/stoplightio/platform-internal/issues/6812 to replace it.
