### ISSUE TITLE
Stoplight Prism- unable to stop Running on the devops pipeline using cli

### ISSUE THREAD

**Issue by vijayanand-m** [stoplightio/prism#1850]
### Discussed in https://github.com/stoplightio/prism/discussions/1847

<div type='discussions-op-text'>

<sup>Originally posted by **vijayanand-m** June 21, 2021</sup>
I am working on running Prism using cli on the Devops pipeline for unit testing.

Problem:
Using Cli I am able to start the mock server and once it is started the control never comes out of the step, I understand that is because of the autoreloading feature in Prism. It keeps on looking at the open api document for any changes. 
Because of this the CI pipeline never finishes the prism step and keep on running. As a result I have to manually kill the job in pipeline.

Is there anyway in Cli to start the mock and stop the mock server using the commands.
Eg:
prism mock .... start
prism mock ..... stop  </div>

**Comment by rtritean** [comment]
Same. Also, is there a way to run it in the background? We might want to run additional steps while Prism is running, but it's currently blocking the pipeline.

**Comment by philsturgeon** [comment]
Interesting enhancement idea.

@ryotrellim what do you think?

**Comment by EdVinyard** [comment]
@vijayanand-m , the functionality you've described is valuable when Prism is used as part of your automation, but because there are other tools that can be used to daemon-ize Prism, we don't feel adding that to Prism itself is the right answer.

Although there are many tools that accomplish something similar and may better suit your particular needs, here's an example using [PM2](https://github.com/Unitech/pm2).

```sh
% npm install pm2 -G
...
✨  Done in 8.47s.


% npx pm2 start "prism-cli mock issue1850.oas" --name "issue1850"
[PM2] Starting /bin/bash in fork_mode (1 instance)
[PM2] Done.
┌─────┬──────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name         │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ issue1850    │ default     │ N/A     │ fork    │ 3775     │ 0s     │ 0    │ online    │ 0%       │ 880.0kb  │ evinyard │ disabled │
└─────┴──────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘


% curl localhost:4010/ -s
{"color":"red"}


% npx pm2 stop issue1850
[PM2] Applying action stopProcessId on app [issue1850](ids: [ 0 ])
[PM2] [issue1850](0) ✓
┌─────┬──────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name         │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ issue1850    │ default     │ N/A     │ fork    │ 0        │ 0      │ 0    │ stopped   │ 0%       │ 0b       │ evinyard │ disabled │
└─────┴──────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
```

**Comment by bernardgut** [comment]
Data point for anyone landing here: the always-on spec watcher can do worse than keep the process alive in CI — it can silently pin a full CPU core.

`prism mock` watches the document with chokidar using a relative path and no `error` handler. If the spec's directory tree (including the process working directory) is deleted while the server is still running — e.g. a mock left running in a CI workspace or git worktree that later gets cleaned up — chokidar's re-add logic degenerates into a zero-delay retry loop: ~100% CPU, ~35k fs ops/sec, completely silent. We hit this in the wild with `prism mock <spec> ` under `CHOKIDAR_USEPOLLING=1`: the orphaned process burned a core for 22+ hours with an empty log.

Upstream report with a minimal repro (reproduces on chokidar v3.6.0 / v4.0.3 / v5.0.0, Node 24 and 26): paulmillr/chokidar#1474

Mitigations from that investigation, until chokidar fixes it:
- serve the spec from a URL (`prism mock http://…`) — the watcher is only set up for local file specs
- or pass an **absolute** spec path and avoid deleting the CWD out from under a running prism (the spin requires a relative path)
- don't set `CHOKIDAR_USEPOLLING` on native filesystems (it's only needed for bind mounts / network fs)

A `--no-watch` flag would remove this whole failure class for CI/automation use.
