### ISSUE TITLE
Update Avatar Size on the Project's Tab

### ISSUE THREAD

**Issue by noor-ahmad** [stoplightio/prism#1852]
- Update the avatars on the project's tab to be 20x20. 
- Currently, they are oval shaped and different sizes 

Reference: [Figma File - Projects Tab](https://www.figma.com/file/PzxLMVm3NmDuKX1y3UR4x9/Workspace?node-id=2760%3A1902)

**Screenshot from Meta:** 
![image.png](https://images.zenhubusercontent.com/60abb0b7364d5be2dc789f9b/88247841-8666-4f33-9d97-ea870afb54e2)

**Comment by ryotrellim** [comment]
Issue moved to [stoplightio/platform-internal #6872](https://github.com/stoplightio/platform-internal/issues/6872) via [**ZenHub**](https://www.zenhub.com/)

**Comment by raleigh04** [comment]
not a thing.
