### ISSUE TITLE
[prism-cli] getHttpOperationsFromSpec performance regression

### ISSUE THREAD

**Issue by nulltoken** [stoplightio/prism#1860]
## Describe the bug

Following https://github.com/APIDevTools/json-schema-ref-parser/issues/211 by the amazing @P0lip everything was neat and nice running Prism 4.1.2.

We recently tried to bump to 4.3.1 but discovered a similar performance regression while running `getHttpOperationsFromSpec()`

## To Reproduce

A complete standalone repro case is available at https://github.com/nulltoken/prism_repro

Running `yarn repro` against 
 - https://github.com/nulltoken/prism_repro/commit/e5c7c23d80944d34918c6616946a6da609101935 (prism 4.1.2 + json-schema-ref-parser bugfix) shows the following output

```
$ yarn repro
yarn run v1.22.5
$ yarn node -r ts-node/register --unhandled-rejections=strict ./src/repro.ts
Running prism v4.1.2
Converting to Prism format: 330.432ms
Number of processed (basic) endpoints 600
Done in 4.71s.
```

 - https://github.com/nulltoken/prism_repro/commit/6ef765bbf3ba22238e11b1c0b0e5073fe3e4d4d6 (prism 4.3.1) shows the following output

```
$ yarn repro
yarn run v1.22.5
$ yarn node -r ts-node/register --unhandled-rejections=strict ./src/repro.ts
Running prism v4.3.1
Converting to Prism format: 27.135s
Number of processed (basic) endpoints 600
Done in 31.13s.
```

## Expected behavior

Jumping from 330ms to 27s when processing the same file looks a bit much, doesn't it? :wink:

Getting back to 330ms would be great.
And maybe adding a unit test to protect this method from suffering from new potential performance related regressions in the future ?

/cc @chohmann

**Comment by chohmann** [comment]
@nulltoken we probably won't be able to get to this for a few sprints as we're trying to finish up another release. However, if you need this sooner, we welcome PRs!

**Comment by nulltoken** [comment]
>However, if you need this sooner, we welcome PRs!

@chohmann Sadly, I'm not sure I've got the magic dust that @P0lip sprinkles around when he flaps his wings 😜 

>we probably won't be able to get to this for a few sprints as we're trying to finish up another release.

Fine by me, provided you keep this one on your radar. Deal?
