### ISSUE TITLE
Old npm version shows strange error

### ISSUE THREAD

**Issue by rklec** [stoplightio/prism#1866]
## To Reproduce

```
$ npm install -g @stoplight/prism-cli
$ npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
C:\Program Files\nodejs\prism -> C:\Program Files\nodejs\node_modules\@stoplight\prism-cli\dist\index.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\@stoplight\prism-cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @stoplight/prism-cli@4.3.1
added 249 packages from 276 contributors in 11.395s
$ prism mock https://petstore.swagger.io/v2/swagger.json


#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 000000FC285AD1A0
```

## Expected behavior

Some useful error.
IMHO even as I was cleraly doing something wrong, it could be more helpful to point me to what I'm doing wrong. 🙃 

## Additional context

Actually the problem was that I did not properly use nvm for windows`. `nvm on` fixed it for me.
Before it was using NodeJS v6, which showed this error.

So use NodeJS v12 and it works.

**Screenshots**
N/A

**Environment (remove any that are not applicable):**
 - Library version: 4.3.1 as it seems
 - OS: Windows 10, tested with cmd and powershell
 - Browser: N/A
 - Platform: desktop

**Comment by philsturgeon** [comment]
Newer versions of Node bundle newer versions of NPM, and they've made things a little more strict in v7. 

You aren't doing anything wrong, we just need to get the module upgraded to support NPM v7.

**Comment by rklec** [comment]
But I wa susing NodeJS v6... 🤔

**Comment by philsturgeon** [comment]
Ah sorry I completely misread that error and mistook it for another error I saw recently.

NodeJS v6 is unsupported, please upgrade to v12 or higher and Prism will be able to help. nvm (or my personal favourite [asdf](https://github.com/asdf-vm/asdf)) should be able to help run multiple versions locally if that's the trouble.
