### ISSUE TITLE
[prism-cli] Question about encoding

### ISSUE THREAD

**Issue by nulltoken** [stoplightio/prism#1882]
Not a bug. A question.

:wave: I'm hitting a `matchPath` issue and started to work on a PR. However, before going further, I'd need to get a better understanding about the use case behind @rainum 's work on #1873:

The harness test that's been added as part of the PR leverages a spec as follows:

```yaml
openapi: 3.0.2
paths:
  /test path > with | unsafe % characters:
    get:
      responses:
        200:
          content:
            description: ok
            application/json:
              example: "ok"
```

Is that a real world use case or a quickly drafted one for the sake of end to end testing?
Was the encoding/decoded change in the code related to fixing concrete path segments issues or path parameters issues?

My underlying question is how should paths be expressed in the OpenAPI spec. I haven't found any definitive answer regarding this. There's https://github.com/OAI/OpenAPI-Specification/issues/2119 which deals with the same subject, but there are only questions, no guidance, nor opinions..

And if indeed paths should be expressed as RFC 3986, shouldn't the chars `>`, `|` and `%` in this harness spec path be rather expressed as percent encoded values?

@philsturgeon Any idea?

**Comment by philsturgeon** [comment]
This sort of test just makes sure that Prism doesn't vomit when faced with nonsense input.

I helped get some more specific wording into the allowed values for URI parameters: 

> The value for these path parameters MUST NOT contain any unescaped "generic syntax" characters described by RFC3986: forward slashes (/), question marks (?), or hashes (#).

I don't think OpenAPI has a particular stance on putting reserved characters into the path. Maybe just don't? 

Could be an interesting issue to raise over here? https://github.com/OAI/OpenAPI-Specification/
