### ISSUE TITLE
Enable the ability to return dynamic responses without requiring an extra header for each call (i.e -H "Prefer: dynamic=true")

### ISSUE THREAD

**Issue by hammidf** [stoplightio/prism#1887]
## User story.

As a QA automation engineer, I want to call the mock server from my React/UI app without modifying my existing headers, so that I can generate dynamic responses with each call.

## Is your feature request related to a problem?

We're considering using Prism to mock some 3rd party services in our UI-based E2E tests. To be clear, our primary focus is on testing our front-end and backend, but some of our internal logic automatically calls these external services and requires unique data in certain fields in the JSON response. 
We would very much like to eliminate our reliance on these outside services in order to increase the speed and reliability of our tests. We hope Prism will enable us to create mock servers that stand in for these external calls.

## Describe the solution you'd like

I realize you can already generate dynamic responses by specifying the -H "Prefer: dynamic=true" in each call (after starting in dynamic mode of course). But since our calls originate from a UI action, we don't have the ability to add this header without modifying the code for testing - which we would rather not do. 

What I'd like is:
1) Start the mock server in dynamic mode 
2) Automatically have all calls return dynamic data in the specified fields WITHOUT the need for the above header

## Additional context

Alternatively, I'd also consider some other options on how to accomplish this. 

Thanks!

**Comment by XVincentX** [comment]
@hammidf You can indeed start Prism in dynamic mode using the `-d` flag

https://github.com/stoplightio/prism/blob/master/packages/cli/src/commands/mock.ts#L17

**Comment by hammidf** [comment]
@XVincentX Thanks for the response. I want to highlight the second part of my feature request here, which is I'd like to return those dynamic responses without adding the header `-H "Prefer: dynamic=true"` to each API call.

**Comment by philsturgeon** [comment]
@hammidf if you start the server in dynamic mode you should not need to add the header. It's one or the other, not both.

**Comment by philsturgeon** [comment]
if prism is not returning dynamic errors in dynamic mode let us know as that would be a bug. :)
