### ISSUE TITLE
Respect `Prefer` header with validation proxy when server returns 501

### ISSUE THREAD

**Issue by hieucd04** [stoplightio/prism#1895]
## Summary

I was able to use `Prefer` header to control returned mock response when using `mock-server` (`Prefer: example=example-key`). Then I switched to `validation-proxy` , hard-coded my upstream sever to return 501 for all requests and send a request to the `validation-proxy` with `Prefer` header as I did with `mock-server`. Surprisingly, it didn't work. I always returned the first example.

Is this how the `validation-proxy` is supposed to work?

## Additional context

Prism: 4.4.0 (get via docker)

**Comment by ryotrellim** [comment]
Hey @hieucd04 - Sorry this one got lost.

Your use case makes sense and our documentation does give the impression that [unimplemented ops will be mocked](https://meta.stoplight.io/docs/prism/ZG9jOjk3-validation-proxy#unimplemented-operations-will-be-mocked), so it stands to reason that the `Prefer` header would be used do determine the correct way to mock.

We'll take a look at prioritizing this.

**Comment by chohmann** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Team-Tacocat-5eb9bc4a1fddfe30b94f78b1/issues/stoplightio/prism/1895?planning-poker) with Zenhub @EdVinyard @daniel-white @brendarearden @matthewmurphy
