### ISSUE TITLE
Integer query param with "[" in it throws "invalid type" error

### ISSUE THREAD

**Issue by DaveWM** [stoplightio/prism#19]
I'm currently using prism to mock an api endpoint where one of the query parameters is called `page[limit]`, with a type of `integer`. The mock api works fine if I omit this query param, but when I make a request with the query string `?page%5Blimit%5D=100`, it throws this error:
```
{
  "errors": [
    {
      "context": "request.url.queryString",
      "description": "Invalid type. Expected: [array,integer], given: string",
      "field": "page[limit]",
      "location": "page[limit]",
      "type": "invalid_type"
    }
  ]
}
```
This error isn't thrown if I change the name of the param to `limit`, or if I change the type to `string`.

Am I doing something wrong here, or is this a bug?

**Comment by marbemac** [comment]
Hi @DaveWM this would be a bug. What Prism should be doing is trying to parse url params as int, boolean, etc, before applying the validation. Prism v2, which @pytlesk4 is working on, should fix this issue - we're aiming to have it released towards the end of July.

**Comment by DaveWM** [comment]
@marbemac great, thanks for the info :). Should I close this issue, or leave it open until Prism v2 is released?

**Comment by pytlesk4** [comment]
@DaveWM Leave it open please.

**Comment by pytlesk4** [comment]
duplicate #43
