### ISSUE TITLE
> # Schema Inaccuracy

### ISSUE THREAD

**Issue by thepowerzero** [stoplightio/prism#1906]
> # Schema Inaccuracy
> 
> `PUT /repos/{owner}/{repo}/issues/{issue_number}/labels`
> 
> ```json
> {
>   "summary": "Set labels for an issue",
>   "description": "Removes any previous labels and sets the new labels for an issue.",
>   "tags": [
>     "issues"
>   ],
>   "operationId": "issues/set-labels",
>   "externalDocs": {
>     "description": "API method documentation",
>     "url": "https://docs.github.com/rest/reference/issues#set-labels-for-an-issue"
>   },
>   "parameters": [
>     {
>       "$ref": "#/components/parameters/owner"
>     },
>     {
>       "$ref": "#/components/parameters/repo"
>     },
>     {
>       "$ref": "#/components/parameters/issue_number"
>     }
>   ],
>   "requestBody": {
>     "content": {
>       "application/json": {
>         "schema": {
>           "anyOf": [
>             {
>               "type": "object",
>               "properties": {
>                 "labels": {
>                   "type": "array",
>                   "description": "The names of the labels to add to the issue. You can pass an empty array to remove all labels. **Note:** Alternatively, you can pass a single label as a `string` or an `array` of labels directly, but GitHub recommends passing an object with the `labels` key.",
>                   "items": {
>                     "type": "string"
>                   }
>                 }
>               }
>             },
>             {
>               "type": "array",
>               "items": {
>                 "type": "string"
>               }
>             },
>             {
>               "type": "object",
>               "properties": {
>                 "labels": {
>                   "type": "array",
>                   "items": {
>                     "type": "object",
>                     "properties": {
>                       "name": {
>                         "type": "string"
>                       }
>                     },
>                     "required": [
>                       "name"
>                     ]
>                   }
>                 }
>               }
>             },
>             {
>               "type": "array",
>               "items": {
>                 "type": "object",
>                 "properties": {
>                   "name": {
>                     "type": "string"
>                   }
>                 },
>                 "required": [
>                   "name"
>                 ]
>               }
>             },
>             {
>               "type": "string"
>             }
>           ]
>         },
>         "example": {
>           "labels": [
>             "bug",
>             "enhancement"
>           ]
>         }
>       }
>     }
>   },
>   "responses": {
>     "200": {
>       "description": "Response",
>       "content": {
>         "application/json": {
>           "schema": {
>             "type": "array",
>             "items": {
>               "$ref": "#/components/schemas/label"
>             }
>           },
>           "examples": {
>             "default": {
>               "$ref": "#/components/examples/label-items"
>             }
>           }
>         }
>       }
>     },
>     "410": {
>       "$ref": "#/components/responses/gone"
>     },
>     "422": {
>       "$ref": "#/components/responses/validation_failed"
>     }
>   },
>   "x-github": {
>     "githubCloudOnly": false,
>     "enabledForGitHubApps": true,
>     "previews": [
> 
>     ],
>     "category": "issues",
>     "subcategory": "labels"
>   }
> }
> ```
> 
> ## Expected
> 
> Same as `POST /repos/{owner}/{repo}/issues/{issue_number}/labels`, which as oneOf
> 
> ## Reproduction Steps
> 
> n/a

_Originally posted by @thepowerzero in https://github.com/github/rest-api-description/issues/273#issuecomment-934352959_

**Comment by thepowerzero** [comment]
Good and nice

**Comment by ryotrellim** [comment]
Hi @thepowerzero, I'm closing this issue since it doesn't look like this impacts Prism at all. Let me know if this is in error.
