### ISSUE TITLE
Dynamically generated enum values limited to 100 characters

### ISSUE THREAD

**Issue by enekonieto** [stoplightio/prism#1914]
## Describe the bug

Dynamically generated enum values are truncated to 100 characters length.

## To Reproduce

1. Given this OpenAPI document:

        uri:
          type: string
          description: URI to the data set
          format: uri
          enum:
            [
              https://this_is_a_terrible_long_URL_so_loooooooooooooooooooooooooooooooooooooooooong_that_prism_truncates_it.html,
            ]

2. Run this CLI command `prism -- mock -d api/openapi.yaml`
3. Prism generated JSON has uri member value truncated to 100 characters

## Expected behavior

Value not to be truncated.

## Additional context
I have met this limit more than once, specially working with URIs.

**Comment by philsturgeon** [comment]
Welcome! First bug report here or first bug report ever? Either way, happy to have you here, thank you!

Hopefully somebody will be able to take a look and squeak this into a sprint, but if you fancy going for a pull request we're planting 400 trees for every successful pull request!
