### ISSUE TITLE
Add custom implementation of operation

### ISSUE THREAD

**Issue by maxlapshin** [stoplightio/prism#1937]
## Summary

Want to add some VERY primitive dynamic behaviour of API  (show download progress).

Are there any ways to get into prism response generation mechanism and put there some hooks?

**Comment by chohmann** [comment]
@maxlapshin we don't feel that this functionality fits the spirit of what Prism should be. Relates to #1838.

**Comment by maxlapshin** [comment]
No problems, I just cannot use prism and I do not use it, because it is practically not useable =)

I took openapi sampler and it helped me to write server that can simulate real server.
