### ISSUE TITLE
Prism 4.6 Returning "Bad Request" when Content-Type header is set

### ISSUE THREAD

**Issue by xero-timothy** [stoplightio/prism#1939]
## Describe the bug

After upgrading Prism from 4.5 to 4.6, requests that specify a content-type header return with the following error message: `[6:24:06 AM] ›     [VALIDATOR] ✖  error     Violation: request Supported content types: `

## To Reproduce

1. Given this OpenAPI document (see attached)
[swagger.txt](https://github.com/stoplightio/prism/files/7502490/swagger.txt)

2. Run Prism
3. Make a request with `Content-Type: application/json`
4. The request will return a 400

## Expected behavior

The request should return a 200

## Additional context
We're running this on Docker with the public images. Rolling back to 4.5 works as expected (and thank you for such a nice product!)

**Screenshots**

**Environment (remove any that are not applicable):**
 - Library version: 4.6
 - OS: Mac OS (although Prism is running in the Docker images provided by Stoplight
 - Browser: Curl
 - Platform: 

gz#8029<br><br><i>(related to <a href='https://stoplight.zendesk.com/agent/tickets/8029'>Zendesk ticket #8029</a>)</i>

**Comment by joel-wright** [comment]
I have been hitting the same issue, but after a bit of investigation I think the issue is caused by a dependency. When using the downloadable CLI built assets from https://github.com/stoplightio/prism/releases I see the behaviour described above with `4.6.0` & `4.6.1`, but not any previous versions.

If I install using `yarn` I also see the above issue with `4.5.0` and `4.4.3` (I stopped trying to find the bottom at that point).

Hopefully this little bit of output will be helpful:

```
[20:46:05] › [HTTP SERVER] get /resource/1234 ℹ  info      Request received
[20:46:05] ›     [NEGOTIATOR] ℹ  info      Request contains an accept header: application/json
[20:46:05] ›     [VALIDATOR] ⚠  warning   Request did not pass the validation rules
[20:46:05] ›     [NEGOTIATOR] ⬤  debug     Unable to find a 415 response definition
[20:46:05] ›     [NEGOTIATOR] ⬤  debug     Unable to find a 422 response definition
[20:46:05] ›     [NEGOTIATOR] ⬤  debug     Unable to find a 422,400 response definition
[20:46:05] ›     [NEGOTIATOR] ⬤  debug     Unable to find a 'default' response definition
[20:46:05] › [HTTP SERVER] get /resource/1234 ✖  error
```

## Additional context

**Environment (remove any that are not applicable):**
 - Library version: 4.4.3, 4.5.0, 4.6.0, 4.6.1
 - OS: Linux (Ubuntu 20.04)

**Comment by endigo9740** [comment]
Just wanted to chime in that I've been hitting the same issue. I was running version `4.5.0` mostly without issue. Updated to `4.6.1` and with no other changes start receiving 415 errors for "unsupported/invalid content type". I figured it was a breaking change so I rolled back to version `4.5.0` and the errors have persisted.

To me this aligns with a breaking dependency update. The same "newer" dependency is installed regardless of Prism's version, and this version provides this error status.

FYI we were running this within an Angular client if that matters. May be something not playing nice with the HTTP module.

Open to any suggested fixes or workarounds if possible. Thanks!

**Comment by to-ph** [comment]
Same here with this issue. Me and my colleague have tried POST, PUT, PATCH on an endpoint and getting a 415 error response. We've tried specifying the content-type and also omitting the content-type in out openapi.json. Same error on both tries.

Also looking for any workarounds if anyone happens to discover one, thanks!

**Comment by to-ph** [comment]
Update:
Weirdly, sending "null" works 🤔

**Comment by chohmann** [comment]
Plan to fix:
- if there is no body, do not look at the content-type header and do not try to parse the empty body

NOTE: XML seems to work this way so ensure others match

**Comment by daniel-white** [comment]
this was introduced as a feature request: https://github.com/stoplightio/prism/issues/1813

**Comment by reinholdfuereder** [comment]
Should doc change of #1981 be reverted again due to this (nice) fix?
