### ISSUE TITLE
Return request body as response

### ISSUE THREAD

**Issue by hsnsalhi** [stoplightio/prism#1940]
Hello,
Is there a way to return the same request body as a response (echo API) ?
I want to retreive the body object and return it in the body response.
Thank you for your help

**Comment by chohmann** [comment]
@hsnsalhi can you explain your use case for this further?

**Comment by hsnsalhi** [comment]
Hello and sorry for my late reply.

In my use case, I need to create a mock service that responds with the same request body.
For example, if the request is a POST with body:
`{
    "name": "a name",
    "age": 123
}`

So, the mock service must respond with the same body. (I know I can generate a response with the same schema but I need the response to be exactly the same as the request)

Hope I was clear enough this time :)
