### ISSUE TITLE
Faker repo wiped, change dependency to fork

### ISSUE THREAD

**Issue by shajz** [stoplightio/prism#1968]
## Summary

Hello, recently, the owner of `faker` has wiped the repository. See https://github.com/Marak/faker.js. Fortunately, he published a v6.6.6 on npm, which means `prism` is (for now) is not affected by this as the `http` package targets `^5.5.3`.

It would be a good idea to change the dependency in the `http` package to a fork like this one https://github.com/faker-js/faker / https://www.npmjs.com/package/@faker-js/faker.

Some discussion regarding the future of faker is happening in this issue : https://github.com/withshepherd/faker.js/issues/1

## Tasks

- [ ] Move dependency from `faker` to a fork

----

EDIT: Updated fork link to https://github.com/faker-js/faker

**Comment by shajz** [comment]
Updated fork link to https://github.com/faker-js/faker

**Comment by chohmann** [comment]
This PR from @jasonbarry achieves exactly this: https://github.com/stoplightio/prism/pull/2021

We just need to get that over the finish line.

**Comment by chohmann** [comment]
This is included in Prism 4.9.3.
