### ISSUE TITLE
select group row and open details panel

### ISSUE THREAD

**Issue by EdVinyard** [stoplightio/prism#1979]
As a workspace member who can create projects,
Given I am viewing the new, combined project & group table,
...

1.  click an existing group row

    ...
    When I click on an existing group row,
    Then the group row is selected,
      and the right sidebar/panel is opened,
      and the selected group's details are displayed in the right sidebar/panel.

2. create a new group

    ...
    When I finish creating a new group,
    Then the new group row is selected,
        and the right sidebar/panel is opened,
        and the new group's details are displayed in the right sidebar/panel.

**Comment by chohmann** [comment]
@EdVinyard I think this was created in Prism repo by mistake. Going to close it.
