### ISSUE TITLE
May I use  your test harness?

### ISSUE THREAD

**Issue by ahx** [stoplightio/prism#2004]
## Summary

Hi. As someone building tooling OpenAPI tooling (like https://github.com/ahx/openapi_first/), I would benefit from using an extensive and language agnostic test suite like your [test harness](https://github.com/stoplightio/prism/tree/master/test-harness/specs). In practice, I was thinking about using the code in a git submodule, similar to how people are using https://github.com/json-schema-org/JSON-Schema-Test-Suite. I am not so much interested in the mocking, but would like to use the test cases about content-negotiation and request/response validation.
What do you think? Are you okay with that?

**Comment by chohmann** [comment]
In the spirit of open source projects, as long as you are in compliance with our licensing, go for it! Feel free to contribute to this project in other ways as well!

**Comment by ahx** [comment]
Thank you @chohmann
