### ISSUE TITLE
Query Parameters do not validate correctly when special characters used - [ ]

### ISSUE THREAD

**Issue by NoahDaveySwyftx** [stoplightio/prism#2017]
## Describe the bug

We have been trying to use `prism` the last week. However our org has a standard for our `REST` endpoints, such that when we use query parameters, they generally look like the following format `filter[userId]`. When trying to run a test against a mocked out api, we seem to be running into issues where the query parameter validation is not working as expected. I.e even when we pass in seemingly correct query parameters, it does not think we have the parameters required by the spec

I believe this is an issue with url encoding specifically, as if we change the query parameter to `userId` on its own, it works fine

## To Reproduce

For example if i make a `GET` request to `http://127.0.0.1:4010/api/v1/resource?filter[userId]=0613a91d-c1ae-4c14-afb9-33b86ceffa19` I would expect this to be a valid request as set out in my oas schema.  

<details> 
<summary> OpenAPI Spec </summary>

```json
{
	"components": {
		"examples": {},
		"headers": {},
		"parameters": {},
		"requestBodies": {},
		"responses": {},
		"schemas": {
			"StatusDto": {
				"enum": [
					"Processing",
					"Failed",
					"Complete"
				],
				"type": "string"
			},
			"ResourceDto": {
				"properties": {
					"status": {
						"$ref": "#/components/schemas/StatusDto",
						"description": "The status of the resource"
					},
					"amount": {
						"type": "string",
						"description": "The amount",
						"example": 0.0002314
					}
				},
				"required": [
					"status",
					"amount"
				],
				"type": "object",
				"additionalProperties": false
			},
			"ApiBodyDtoArray": {
				"properties": {
					"data": {
						"items": {
							"$ref": "#/components/schemas/ResourceDto"
						},
						"type": "array"
					}
				},
				"required": [
					"data"
				],
				"type": "object",
				"additionalProperties": false
			},
			"UUID": {
				"type": "string",
				"description": "RFC 4122 UUID",
				"pattern": "^\\b[0-9a-f]{8}\\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\\b[0-9a-f]{12}\\b$"
			}
		},
		"securitySchemes": {}
	},
	"info": {
		"title": "api",
		"version": "0.0.0",
		"contact": {}
	},
	"openapi": "3.0.0",
	"paths": {
		"/api/v1/resource": {
			"get": {
				"operationId": "GetResource",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ApiBodyDtoArray"
								}
							}
						}
					}
				},
				"security": [],
				"parameters": [
					{
						"in": "query",
						"name": "filter[userId]",
						"required": true,
						"schema": {
							"$ref": "#/components/schemas/UUID"
						}
					}
				]
			}
		}
	},
	"servers": [
		{
			"url": "/"
		}
	]
}
```
</details>

Run any of the following
- `http://127.0.0.1:4010/api/v1/resource?filter[userId]=0613a91d-c1ae-4c14-afb9-33b86ceffa19`
- `http://127.0.0.1:4010/api/v1/resource?filter[userid]=0613a91d-c1ae-4c14-afb9-33b86ceffa19`
- `http://127.0.0.1:4010/api/v1/resource?filter%5buserId%5d=0613a91d-c1ae-4c14-afb9-33b86ceffa19`
- `http://127.0.0.1:4010/api/v1/resource?filter%5BuserId%5D=0613a91d-c1ae-4c14-afb9-33b86ceffa19`

This should give you the error 
``` json
{
    "type": "https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY",
    "title": "Invalid request",
    "status": 422,
    "detail": "Your request is not valid and no HTTP validation response was found in the spec, so Prism is generating this error for you.",
    "validation": [
        {
            "location": [
                "query"
            ],
            "severity": "Error",
            "code": "required",
            "message": "must have required property 'filter%5buserid%5d'"
        }
    ]
}
```

## Expected behavior

Expect response to be as it would be if we did not have the special characters in the url (i.e. `[ ]`)

```json
{
    "data": [
        {
            "status": "Processing",
            "amount": 0.0002314
        }
    ]
}
```

## Additional context

Attempted with docker image and with cli directly

**Environment (remove any that are not applicable):**
 - Library version: `4.8.0`
 - OS: macOS

**Comment by treyturner** [comment]
Hi again @NoahDaveySwyftx ! I'm going to presume this is resolved, but if that's incorrect or you have further questions, feel free to reopen or comment. Thanks!
