### ISSUE TITLE
Use node 14 as base engine version

### ISSUE THREAD

**Issue by jasonbarry** [stoplightio/prism#2022]
Node 12's [end-of-life](https://nodejs.org/en/about/releases/) is approaching on 2022-04-30. We should upgrade to the next LTS version which is node 14. 

## Context
Keeping this repo up-to-date with supported node releases. 

## Current Behavior
The repo doesn't build in CI if any dependencies specify an engine of >= 14. 

## Expected Behavior
Things should work the exact same, but will require node >= 14 to run.

**Comment by chohmann** [comment]
closed because we merged the PR upgrading to node 16.
