### ISSUE TITLE
Provide support for 500 responses as a range (5XX)

### ISSUE THREAD

**Issue by caitlinnew** [stoplightio/prism#2024]
Instead of specifying a “500” specifically, user wants to specify a “5XX” as a range for the series:
https://swagger.io/docs/specification/describing-responses/

When using the stoplight mocking functionality (dynamic or static), mocking returns the following attached image response (requested a mock of a 500 and it return a 404. You can see it thought that 5XX was actually just “5”).

## Current Behavior
5XX responses return a 404 error in mocking
![image](https://user-images.githubusercontent.com/92755071/160489820-9e70a2e5-eecc-4b6c-8562-b5fd649a2494.png)

## Expected Behavior
5XX response ranges are supported

gz#8916<br><br><i>(related to <a href='https://stoplight.zendesk.com/agent/tickets/8916'>Zendesk ticket #8916</a>)</i>

**Comment by chohmann** [comment]
Update logic for picking a response to:
- Look for exact match on code
- then look for range match (4xx or 5xx, etc.)
- then look for default
- otherwise fail like we are today that we could not find response in spec
