### ISSUE TITLE
Question: Store data operations

### ISSUE THREAD

**Issue by thim81** [stoplightio/prism#2026]
## User Story Description

As a mock API user,
I want to be able to use modification operations (POST/PUT/PATCH/DELETE) to be stored
so I can use the API based on the OpenAPI with real usage and potential CRUD flows.

(a bit like the [json-server](https://github.com/typicode/json-server) npm but then as part of Prism)
This user story is more a question, if it was discussed as valuable feature and feasible?

## Acceptance Criteria

- [ ] Store a new entity via POST (temporary)
- [ ] Get the created entity via GET
- [ ] Update the created entity (PUT/PATCH)
- [ ] Remove the created entity

## Sprint Ready Checklist

- [ ] Acceptance criteria defined
- [ ] Team understands acceptance criteria
- [ ] Team has defined solution / steps to satisfy acceptance criteria
- [ ] Acceptance criteria is verifiable / testable
- [ ] External / 3rd Party dependencies identified

**Comment by chohmann** [comment]
@thim81 this functionality is not built into Prism today, and we don't think it belongs in Prism. However, you could easily use Prism as a proxy in front of json-server to achieve what we think you are looking to do. Prism as a proxy would provide the contract testing you probably want, and json-server would provide the CRUD operations and store state like you're asking for. Does that seem like it would meet your needs?

**Comment by thim81** [comment]
@chohmann Thanks for providing me a very clear and useful explanation.

I'm going to give your suggestion a try, and if it works, I'll report back here for anybody else really liking the Prism and want to use it create realistic API mocking services.

**Comment by chohmann** [comment]
@thim81 I'm going to close this issue. Feel free to add your comments to this ticket even after it's closed!
