### ISSUE TITLE
The property type validation failed as always return type with null

### ISSUE THREAD

**Issue by GabbyChang** [stoplightio/prism#203]
I just use stoplight Application to run test scenario. For the contract testing, I have defined the response body should be one array with object in it. But it always failed with error:

```
output.body [validate.contract] [schema object not shown for now]
(root): Invalid type. Expected: null, given: array
```

The document is not valid. see errors

The scheme I defined at yaml file at Modeling part is like below:

```
"responses": {
          "200": {
            "description": "Get feedback successfully",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Feedback"
              }
            }
          }
}
```

Definition is like below:

```
  "definitions": {
    "Feedback": {
      "type": "object",
      "description": "Model of Feedback",
      "properties": {
        "text": {
          "type": "string",
          "example": "test"
        },
        "id": {
          "type": "integer",
          "example": 1
        },
        "timestamp": {
          "type": "string",
          "format": "date-time",
          "example": "2019-03-25T03:20:42.492Z"
        }
      },
      "required": [
        "text"
      ]
    }
  }
```
I am working on Windows system, the stoplight application I install is stoplight-next-setup-4.8.1.exe

**Comment by philsturgeon** [comment]
Hey @GabbyChang, I edited your post a little for formatting (three backticks give you code fences!). 

I think this might be the incorrect place to post for help with Platform issues in general, as this is for Prism specifically. 

For now I can try and help though, maybe you could post me the entire YAML file and the JSON instance (the data it is trying to validate)? If you dont want to post it pubicly, you can fire it over to phil@stoplight.io for now. 

_Future people please do not just send things directly at me this is just for @GabbyChang right now._

**Comment by pytlesk4** [comment]
@philsturgeon did you get an email? Prism v2 runs scenarios, so this is the correct place to post this issue :).

**Comment by philsturgeon** [comment]
@pytlesk4 I did not!
