### ISSUE TITLE
Error: Schema size exceeded

### ISSUE THREAD

**Issue by hainessss** [stoplightio/prism#2033]
Hello,

I am getting `Error: Schema size exceeded` 

And I can't figure out why.

repro script here
```
const { getHttpOperationsFromSpec } = require('@stoplight/prism-cli/dist/operations');
const { createClientFromOperations } = require('@stoplight/prism-http/dist/client');

(async function main () {
  let operations = await getHttpOperationsFromSpec('src/mocks/swagger.json');

  operations = operations.filter(operation => operation.path === '/api/candidate-role')

  console.log('operations', operations)
  const client = createClientFromOperations(operations, {
    mock: true,
  });

  client.get('/api/candidate-role').then(console.log);
})();
```

swagger schema here:
https://prod.betterleap-api.com/api-docs-0001-json

Thanks

**Comment by chohmann** [comment]
@EdVinyard can you try to reproduce?

**Comment by EdVinyard** [comment]
I've reproduced this issue.  We're bumping into a limit hard-coded into `json-schema-sampler` that limits the number of "nodes" in the response to 1000: https://github.com/stoplightio/json-schema-sampler/blob/master/src/traverse.js#L20

Switching Prism into dynamic mock mode gives me a different error, so I suggest we need to:
1. (at least) return a much more descriptive error, and
2. (probably) identify exactly what it is about this schema that breaks `json-schema-sampler`'s mocking.

**Comment by hernanpis-inditex** [comment]
Hello,

I am working on generating mocks for openapi specifications for which sometimes have a very large response schema and I also get the error:

```
{
  "type": "https://stoplight.io/prism/errors#UNKNOWN",
  "title": "Schema size exceeded",
  "status": 500,
  "detail": ""
}
```

Are there any open working lines in order to modify by configuration these default values that are currently hardcoded?
https://github.com/stoplightio/json-schema-sampler/blob/066d49b574246ae3ea5aa821a14e3a3f31836962/src/json-schema-sampler.js#L6

I urgently need a solution to this problem and will probably work on a fork as long as the configuration of these values is not enabled.

Thanks!

**Comment by ryotrellim** [comment]
Todo:
- Improve error messaging
- Create CLI parameter for expanding the node limit

**Comment by ryotrellim** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Team-Tacocat-5eb9bc4a1fddfe30b94f78b1/issues/stoplightio/prism/2033?planning-poker) with Zenhub @chohmann @EdVinyard @daniel-white @brendarearden

**Comment by leonovi** [comment]
Caught the same behavior

**Comment by daniel-white** [comment]
json schema sample is now doing

```
Schema size exceeded: over ${options.startingTicks} properties. For more info, visit https://docs.stoplight.io/docs/platform/zumkfdc16oypw-json-schema-editor#generate-examples
```

@ryotrellim is this a message we want for prism as well?

**Comment by daniel-white** [comment]
@hainessss @leonovi @hernanpis-inditex 

can you please provide us with a spec document that has this problem? thanks!

**Comment by tyler71** [comment]
This triggers it for me

https://docs.medusajs.com/api/store -> [spec](https://docs.medusajs.com/redocusaurus/plugin-redoc-0.yaml)

docker-compose.yml
```
services:
  mock_store:
    # https://docs.medusajs.com/api/store
    image: stoplight/prism:4
    command: >
      mock -p 4010 --host 0.0.0.0
      https://docs.medusajs.com/redocusaurus/plugin-redoc-0.yaml
```

```
/store/carts/1
{
	"type": "https://stoplight.io/prism/errors#UNKNOWN",
	"title": "Schema size exceeded",
	"status": 500,
	"detail": ""
}
```

**Comment by daniel-white** [comment]
saving spec for future
[plugin-redoc-0.yaml.txt](https://github.com/stoplightio/prism/files/12095968/plugin-redoc-0.yaml.txt)

**Comment by leonovi** [comment]
Unfortunately, i won't be able to provide a schema ☹️. But perhaps i will be able to make a scheme manually, with the same level of nesting and the count of nodes, if there is time.

**Comment by EdVinyard** [comment]
Attempt to fix Prism build problem due to Stoplight's fork of HTTPbin used during the build: https://github.com/stoplightio/httpbin/pull/4
