### ISSUE TITLE
No errors thrown by prism even though the api response is not matching with api specification

### ISSUE THREAD

**Issue by venkat2286** [stoplightio/prism#2034]
As part of enhancement, lets assume that developer adds a new field  to the API  response(implementation) but don’t update the specification. I am expectign to see error so as to enforce developers to update the specification to be in sync with implementation.
## Context

discrepency between specification and impementation

## Current Behavior

Not throwing any error message instead gettign the successful response.

## Expected Behavior

I am expecting to see error as there is descrepency between specificationad response.
## Steps to Reproduce

1.
2.
3.
4.

## Environment

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your environment/workspace/project:

**Comment by chohmann** [comment]
@venkat2286 could you provide a spec to reproduce this with? Could you also double check that you have the `additionalProperties` property in your spec set to false? If that is set to true (it defaults to true) then it is valid to have additional properties in the response.

**Comment by chohmann** [comment]
@venkat2286 I'm going to close this issue as we haven't received steps to reproduce this. Feel free to re-open with more info!
