### ISSUE TITLE
Pattern matching seems to strip away backslash?

### ISSUE THREAD

**Issue by sashafklein** [stoplightio/prism#2073]
Prism seems to take away a backslash from string regex patterns, causing it to find improper "violations". That or I'm doing something wrong :)

I have the following field:

```json
"ein": {
  "pattern": "/^\\d{9}$/",
  "type": "string",
  "example": "123456789"
},
```

When the Prism API returns that example "123456789", it does so with the following error:

```
 [VALIDATOR] ✖  error     Violation: response.body.org.entity.ein must match pattern "/^\d{9}$/"
```

It seems to me that the error is likely that the pattern being used by prism isn't the exact one in my spec, because Prism's pattern shown in the above error is missing the double backslash. 

The pattern in my spec:            `"/^\\d{9}$/"`
The pattern in the Prism error: `"/^\d{9}$/"`

If not that, I'm not sure what the error is, since the API is returning that exact example string (`"123456789"`), which should match the pattern provided.

## Context

This isn't urgent, since I can just ignore the error.

## Current Behavior

Described above.

## Expected Behavior

The pattern validates correctly. For what it's worth, I'm generating my pattern from JS, by first generating a regex `/^\d{9}$/` and then calling `toString()` on it. Before I call `toString()` on the regex, in the library which generates the eventual JSON specification, I validate that the example matches the regex myself:

```ts
  if (!(example || "").match(pattern)) {
    throw new Error(`Pattern/Example mismatch. Pattern: "${pattern}". Example: "${example}".`);
  }
```

So it does seem to be on Prism's end. That or I'm misunderstanding how this should be configured.

## Steps to Reproduce

I suspect you could use the above example ein field and configure the Prism OpenAPI spec to return the example value, and it would cause the same error. 

## Environment

`"@stoplight/prism-cli": "^4.9.3",`

OpenAPI v3. Mac laptop. Node 16.14.0

**Comment by chohmann** [comment]
@sashafklein looking at the [docs](https://spec.openapis.org/oas/v3.1.0#paths-object) for regex in json-schema say you don't need to include the leading and trailing slashes.

Could you try updating your spec to have the following:
```
"ein": {
  "pattern": "^\\d{9}$",
  "type": "string",
  "example": "123456789"
},
```

Let us know if that works for you!

**Comment by sashafklein** [comment]
Sorry just saw your comment, but that was it. Thank you!
