### ISSUE TITLE
Add User-Agent when fetching remote OpenAPI document

### ISSUE THREAD

**Issue by jakowenko** [stoplightio/prism#2092]
## Context

We have a hosted version of our spec file that is handled by AWS API Gateway and AWS WAF. The default behavior for the web application firewall is to block any requests that do not contain a user agent.

## Current Behavior

AWS WAF blocks the prism request because no user agent header is present.

## Expected Behavior

A user agent header is passed when fetching the remote OpenAPI document.

**Comment by treyturner** [comment]
This was implemented; thanks for your feature request @jakowenko !
