### ISSUE TITLE
Cookie Runtime Helpers

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/prism#21]
Add back cookie helper api, similar to the previous version of prism.

Input: https://help.stoplight.io/prism/runtime-reference/api#requestcookieall-namestring-valuestring-pathstring-domainstring-expirestime-securebool-httponlybool

Output: https://help.stoplight.io/prism/runtime-reference/api#responsecookieall-namestring-valuestring-pathstring-domainstring-expirestime-securebool-httponlybool

**Comment by pytlesk4** [comment]
needed-by #44

**Comment by pytlesk4** [comment]
done, need to document them

**Comment by marbemac** [comment]
TODO: hook up cookie helpers to global response / response (for use in prism server)
