### ISSUE TITLE
truncate sl-violations when it would be too long

### ISSUE THREAD

**Issue by EdVinyard** [stoplightio/prism#2129]
## Context

In proxy mode when there are many contract violations, the `sl-violations` response header may exceed size limitations and cause failures in proxies and clients.

See https://github.com/stoplightio/prism/pull/2126 for context.

## Expected Behavior

The `sl-violations` response header never exceeds a length that will cause errors in proxies and clients.

## Solution

The `sl-violations` header is automatically truncated at a length less than common server limits ([8KB](https://stackoverflow.com/a/686243/150)).  Start at https://github.com/24i/prism/blob/master/packages/http-server/src/server.ts#L104

**Comment by ryotrellim** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Team-Tacocat-5eb9bc4a1fddfe30b94f78b1/issues/stoplightio/prism/2129?planning-poker) with Zenhub @chohmann @EdVinyard @daniel-white @brendarearden
