### ISSUE TITLE
Mocky.io "503 Service Unavailable"

### ISSUE THREAD

**Issue by OvaisFareed** [stoplightio/prism#2131]
Hi Everyone!

I'm using **nz-upload** of **Ng-Zorro** which POST an API on every file upload to "https://www.mocky.io/v2/5cc8019d300000980a055e76" using its **nzAction** attribute which produced "503 Service Unavailable" error, almost every time.

I also tried by removing **nzAction** attribute but nz-upload won't work without it.

Any guesses?

**Comment by chohmann** [comment]
We're not quite sure how this pertains to Prism. We're going to close this for now. Feel free to open this back up with further explanation about how Prism is involved.

**Comment by alienvikas** [comment]
I found working mocky url. It worked for me

https://run.mocky.io/v3/530e60ce-f689-4ea8-9f22-57fefa8ec1eb
