### ISSUE TITLE
Behaviors and state

### ISSUE THREAD

**Issue by alexec** [stoplightio/prism#2139]
## Context

I want complex test fakes for APIs. I want write to affect reads, and I want to define the behavior of the API simulation. I’ve prototyped this in Golang and its very similar to Prism, except:

The CLI takes an additional file named `operations.js`. This file contained functions that have the the following signature:

```js
(req, ctx) -> resp
```

The function is stateless. It is supplied the HTTP request and context and returns a HTTP response. I.e. it is a Lambda.

The context gives it access to state. 

```js
function listPets(req,ctx) {
  var pets = ctx.db.list("pets/*")
   return {statusCode: 200, body: {pets: pets}}
}
```

**Comment by chohmann** [comment]
Hi @alexec! Thank you for reaching out about this enhancement idea. We encourage using the prefer header to return specific examples from your spec and having the logic on which one to choose be in your test code. We believe that the approach you outlined is outside the scope of the spirit of Prism. You can look at #586 for a more in depth discussion on the topic.
