### ISSUE TITLE
Please update uri-template-lite to 22.9.0

### ISSUE THREAD

**Issue by therve** [stoplightio/prism#2155]
url-template-lite 22.1.0 and below is flagged by a CVE. It's unlikely to affect prism but it should be easy enough to update to the latest version to shut up security scanners. Thanks!

**Comment by daniel-white** [comment]
hey @therve - what version are you running - our packagejson and lock file indicates we are on 22.9.0

https://github.com/stoplightio/prism/blob/2c998634ac3306301b87393a8e07537df7fec91a/packages/cli/package.json#L27

https://github.com/stoplightio/prism/blob/2c998634ac3306301b87393a8e07537df7fec91a/yarn.lock#L8922

**Comment by chohmann** [comment]
We're going to close this issue as we do have that version in our latest version of Prism.

**Comment by therve** [comment]
Sorry for the noise, I probably looked in the wrong place.
