### ISSUE TITLE
How to simulate a 500 if the open api doesn't define it

### ISSUE THREAD

**Issue by epifab** [stoplightio/prism#2165]
I have an open api document lacking some errors - I know for instance that the endpoint can return a 500 but that's not in the document.
How do I get prism to simulate such a scenario? I've tried with the `Prefer: code=500` header, but that doesn't work as prism rightfully respond with the an error: `Requested status code 500 is not defined in the document.`

**Comment by chohmann** [comment]
Hi @epifab, Prism needs to the know the shape of the response to be able to mock it out. Therefore, the response code needs to be defined in the spec to tell us what shape to mock out. Here's documentation on how Prism decides which response to mock out.

https://docs.stoplight.io/docs/prism/branches/master/83dbbd75532cf-http-mocking#the-decision-engine
