### ISSUE TITLE
Security Schema Logic is incorrect

### ISSUE THREAD

**Issue by saasha05** [stoplightio/prism#2166]
Currently, for security schema there is an OR choice between API key and Bearer token when sending requests. There should be an ability to have both

## Context
This results in 403s in sending API calls since security schema information is not provided

## Current Behavior

There is only one of two requests that can be made
```
curl --request GET \
  --url https://some-endpoint \
  --header 'Content-Type: application/json' \
  --header 'x-api-key: xxx'
```
OR
```
curl --request GET \
  --url https://some-endpoint \
  --header 'Authorization: Bearer xxx' \
  --header 'Content-Type: application/json'
```

## Expected Behavior

API request should be able to look like
```
curl --request GET \
  --url https://some-endpoint \
  --header 'Authorization: Bearer xxx' \
  --header 'Content-Type: application/json'
  --header 'x-api-key: xxx'
```

## Possible Workaround/Solution

No

## Steps to Reproduce

1. created OpenAPI Spec that contains the following:
```
security:
  - X-Api-Key: []
    Authorization: []
```
2. Rendering of page has dropdown menu on right side to choose ONLY ONE between the above two options

![Screen Shot 2022-11-01 at 3 02 03 PM](https://user-images.githubusercontent.com/14097410/199350356-84a16544-d705-4130-a8a2-a480f3e4275f.png)

## Environment

Used as part of an internal tool so cannot provide details

**Comment by daniel-white** [comment]
WIP:

I tried in studio web creating this

```
  securitySchemes:
    x-api-key:
      name: API Key
      type: apiKey
      in: header
      description: ''
    authorization:
      type: http
      scheme: bearer
```


OAS 3.1 first states that the security mechanisms are alternative, not an aggregate:
> The list of values includes alternative security requirement objects that can be used. Only one of the security requirement objects need to be satisfied to authorize a request. 

See https://spec.openapis.org/oas/latest.html#fixed-fields-7

However later it says multiple should be supported, however it is not documented what this should look like:

> Security Requirement Objects that contain multiple schemes require that all schemes MUST be satisfied for a request to be authorized. This enables support for scenarios where multiple query parameters or HTTP headers are required to convey security information.

See https://spec.openapis.org/oas/latest.html#security-requirement-object

**Comment by chohmann** [comment]
@saasha05 this is a known enhancement we'd like to make in our Try It component for Stoplight web. You can follow [this insight](https://roadmap.stoplight.io/c/174-try-it-auth-multiple-auth) to see when it gets prioritized and implemented. In the meantime, as @daniel-white tested and verified, Prism handles passing multiple auth mechanisms already. This means, that although our Try It component currently doesn't allow you to select multiple auth mechanisms to auto generate a curl request, you can still manually add the second auth mechanism to the curl request and that will be successful. 

Thank you for reaching out about this!
