### ISSUE TITLE
Unable to define variable array sizes

### ISSUE THREAD

**Issue by ryotrellim** [stoplightio/prism#2168]
## Context
Incorrect behavior when defining array minItems and maxItems, ~and also inconsistent across hosted mocks on Stoplight and Prism CLI.~

OAS: [fakerTest.json.zip](https://github.com/stoplightio/prism/files/9922714/fakerTest.json.zip)

The faker array lengths are defined like so:
```
  "x-json-schema-faker": {
    "minItems": 1,
    "maxItems": 3
  },
```

~## Steps to Reproduce Hosted Prism Issue~
~1. Go to the endpoint here: https://troy-test.stoplight.io/docs/fakertest/b9a454ade4d00-your-get-endpoint~
~2. Send an API Request to the mock server using Dynamically Generated Content. Note that the array will always have 20 items.~

~Result: Hosted Prism always returns 20 array items.~
~Expectation: Response should vary between 1 and 3 array items.~

## Steps to Reproduce Prism CLI Issue

Given: `prism mock fakerTest.json`
Then:
```
curl --request GET \
  --url http://127.0.0.1:4010/fetch1/ \
  --header 'Content-Type: application/json' \
  --header 'Prefer: code=200, dynamic=true'
```

Result: Prism CLI always returns 3 items.
Expectation: Response should vary between 1 and 3 array items.

**Comment by ryotrellim** [comment]
Note that this playground has the correct behavior: https://json-schema-faker.js.org/ (after configuring min/maxItems in Options)

**Comment by chohmann** [comment]
@ryotrellim the behavior is inconsistent between hosted prism and prism cli because we haven't gotten to this ticket to actually pass the faker options to hosted prism:

https://github.com/stoplightio/prism/issues/1954

**Comment by brendarearden** [comment]
During my testing of x-faker options, I did notice that some of  jsf.options via the schema were working and some weren't through the cli - I went ahead and included that investigation as part of this ticket https://github.com/stoplightio/prism/issues/2175

**Comment by daniel-white** [comment]
we are setting `optionalsProbability` to `1`. this is causing jsf to fill in the "optional" slots of an array, effectively making them `maxItems`. for example

```
// using these options
minItems: 1
maxItems: 5

// causes an array like this
[item, <optional>, <optional>, <optional>, <optional>]

// for each of the optional slots jsf determines whether it should be filled based on optionalsProbability
// since its 1, it will happen 100% of the time, creating
[item, item, item, item, item]
```
