### ISSUE TITLE
Run different services in different ports?

### ISSUE THREAD

**Issue by ShahOdin** [stoplightio/prism#2172]
I would like to run different services running in different ports. Currently I have:

```dockerfile
#syntax=docker/dockerfile:1.4
FROM stoplight/prism:4
COPY --from=src out/open-api.json open-api.json
CMD ["mock", "-h", "'0.0.0.0'", "-d", "-p 8081", "open-api.json"]
```

I want to make `8081` parametric so I can have different instances of this image with different open-api files in different ports. 

the `stoplight/prism:4` doesnt have shell so I can't use the shell notation of the CMD part which would incidentally offer me env-var interpolation.

I'm not an expert in docker so thought I'd ask around. Is there no way of doing this? Should say I have seen this: https://meta.stoplight.io/docs/prism/4bf78efbf9dd2-serving-multiple-open-api-documents but I'd like to consider other options.

**Comment by daniel-white** [comment]
@ShahOdin how are you running docker? are you exposing and binding the ports? is there a reason that you want this to run in docker as port 8081 over our default of 4010?

**Comment by chohmann** [comment]
@ShahOdin since we haven't received any more clarifying details about your issue, we are going to close this issue. Feel free to reopen with additional details if you have them!
