### ISSUE TITLE
Investigate jsf.options

### ISSUE THREAD

**Issue by brendarearden** [stoplightio/prism#2175]
## Context
We are currently setting jsf.options https://github.com/stoplightio/prism/blob/65445ef9365d7f1214ccb14324db6e629cb817d5/packages/http/src/mocker/generator/JSONSchema.ts#L19 as part of our Json Schema Faker configuration. This is resulting in unexpected behavior in Prism. 

For example, the maxLength of strings is set to 100 characters. If you are mocking a long lorem.paragraph, it will only return 100 characters of that paragrah and appear as though its only mocking a lorem.sentence. 

You can also set jsf.options through the schema using `x-json-schema-faker`
```
openapi: 3.1.0
x-json-schema-faker:
  maxItems: 4
```
If its an [availabe jsf.option](https://github.com/json-schema-faker/json-schema-faker/tree/v0.5.0-rcv.40/docs#available-options) you should be able to set it here. 

## Current Behavior
The default JSP options are modifying the behavior of JSF
Not all JSF options set via the schema are modifying the behavior as expected 

## Possible Solution(s)
- Double check that all of the options we are setting by default still make sense to use - specifically: 
```
  failOnInvalidTypes: false,
  failOnInvalidFormat: false,
  alwaysFakeOptionals: true,
```
- determine why not all jsf options are working as expected.

**Comment by daniel-white** [comment]
doc notes: 
* https://github.com/json-schema-faker/json-schema-faker/tree/develop/docs
* ~if changing `x-json-schema-faker` options in your spec - restart prism (global state at play) deleting a property doesn't work~
* if you want to use `minItems`, `maxItems` set `optionalsProbability`
