### ISSUE TITLE
[Validation Proxy] – Documentation of all Validation possibilities?

### ISSUE THREAD

**Issue by m-graf** [stoplightio/prism#2176]
Hey everyone,

I'm looking for documentation (either inline or reference) for all of the possible validations that the validation Proxy provides. I'm aware of [this document](https://github.com/stoplightio/prism/blob/fb388d3cf76f164272a4e44c4ff23471da4c85dd/docs/guides/06-errors.md#validation-errors) but it feels like it falls short. I'm happy to put together a better document if someone can point me toward a jumping off point (code or otherwise)

Thank you!

**Comment by daniel-white** [comment]
hey @m-graf - is there something specific that is falling thru? we'd be happy to take a look if we knew where to start! thanks.

**Comment by m-graf** [comment]
> hey @m-graf - is there something specific that is falling thru? we'd be happy to take a look if we knew where to start! thanks.

Hey thanks for the reply, I ended up doing some more digging into the RFC... I've got plenty to work with! Thanks :)
