### ISSUE TITLE
Date pattern mismatch error on response validation 

### ISSUE THREAD

**Issue by lovetemple** [stoplightio/prism#2193]
open api spec >> 
  "expiryDate": {
            "type": "string",
            "pattern": "DD MMMM YYYY",
            "description": "Fixed Rate Expiry in DD MMMM YYYY format",
            "example": "31 December 2020"
          }
On response validation prism complaints on mismatch despite the payload having the right format.
Ex:    "severity": "Error",
            "code": "pattern",
            "message": "must match pattern \"DD MMMM YYYY\""
        }

Actual response : 31 December 2020 and above error is thrown
is there any option to set locale ?

**Comment by chohmann** [comment]
@lovetemple json schema says that [pattern is a regex](https://json-schema.org/draft/2020-12/json-schema-validation.html#name-pattern), so you can either make pattern be a regex or format your date as a json schema date using the formats outlined in [this doc](https://json-schema.org/understanding-json-schema/reference/string.html#dates-and-times).
