### ISSUE TITLE
Configureable Request Timeout

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/prism#22]
Right now the default request timeout is 30 seconds, and there is no way for the user to control.

**Comment by lukoyanov** [comment]
+1 for this feature

**Comment by madcent** [comment]
+1

**Comment by MissingHandle** [comment]
+1

**Comment by pytlesk4** [comment]
- needed-by #71 

Def think we need this for data driven scenarios.

**Comment by pytlesk4** [comment]
- When timeout happens, send back the current results as well, with a log on the collection result that a timeout has happened.

**Comment by pytlesk4** [comment]
released in 2.0.0-beta.7
