### ISSUE TITLE
Response body Json parser fails with reason: Unexpected end of JSON input"

### ISSUE THREAD

**Issue by sub10xsen** [stoplightio/prism#2202]
```
RESPONSE BODY: 

{
    "code": {
        "encryptedValue": "N9+Ekw0ck96uNRGhKYZe5VwRPkUe73Db+zGwxTf8Od+ShdHwAkZdpgEhf40GylYBuFc7Irx4rc9LcbHQIrNxZignVO0SiFlyNM6jU2REWhtb/q8WiSvNEfvzcyCkXyWvJr/E7JOqZAmFLyTtkGAdYne4cYNE8Sim6vWWnxAQKqsRjI8Vc",
        "encryptionAlgorithm": "TEST_123_456"
    }
}
```

We are using prism proxy for validating our api specs and above response body is causing issues.
```
{
    "type": "FetchError",
    "title": "invalid json response body at https://ENDPOINT reason: Unexpected end of JSON input",
    "status": 500,
    "detail": ""
}
```

Checked using json parser and above is a valid json.

Could someone help around resolving this please. 
Thank You.

**Comment by chohmann** [comment]
@sub10xsen could you give us some more information about the issues you're experiencing?

1. The openAPI spec you're using (or at least the operation at play here)
2. wireshark output from your service response to prism

**Comment by sub10xsen** [comment]
Prism validates below  response body from our endpoint

RESPONSE BODY: 

{
    "code": {
        "encryptedValue": "N9+Ekw0ck96uNRGhKYZe5VwRPkUe73Db+zGwxTf8Od+ShdHwAkZdpgEhf40GylYBuFc7Irx4rc9LcbHQIrNxZignVO0SiFlyNM6jU2REWhtb/q8WiSvNEfvzcyCkXyWvJr/E7JOqZAmFLyTtkGAdYne4cYNE8Sim6vWWnxAQKqsRjI8Vc",
        "encryptionAlgorithm": "TEST_123_456"
    }
}


 **and gives out below error** 

{
    "type": "FetchError",
    "title": "invalid json response body at https://ENDPOINT reason: Unexpected end of JSON input",
    "status": 500,
    "detail": ""
}

I have not tried Wireshark to get the response... if you could guide me around what you are expecting can try and update here.

**Comment by daniel-white** [comment]
hey @sub10xsen - it would be great if you could figure out whether your full response is actually making it into prism before the JSON is attempting to be parsed. Prism only can work with what its given from your networking stack.

Wireshark is a bit more raw but provides a lot of details into your network traffic. You might be also able to use another HTTP proxy tool like Fiddler (all dependent on your environment). A capture of the full request-response from either of these tools might be enlightening more than your pasted response body.

**Comment by chohmann** [comment]
Hi @sub10xsen, we're going to close this as we haven't received enough information. Please reopen if you have any more information surrounding the issue you're experiencing.
