### ISSUE TITLE
Usage of query params when creating a mock server from Postman Examples

### ISSUE THREAD

**Issue by LaiaPR** [stoplightio/prism#2232]
## Context
I am trying to create a mock server from Postman Examples and found that I cannot get different responses based on different query params that the API is using.

Example: an API endpoint to check purchases for a user: GET /purchases

There is an endpoint that provides with the list of purchases for a specific user. There are 2 query params you can use to specify the user:
- user_id : the user ID 
- user_code : another way to specify the user

For 200 OK status code, it returns a json body response with some purchases info.

## Current Behavior
When requesting the API endpoint with different query params or different values for a query param, I get the same exact response.

GET /purchases?user_id=123 -> 200 OK and the info for the very first example described in Postman

GET /purchases?user_id=456 -> same response as above

GET /purchases?user_code=aaa-000-qwerty -> same response as above

GET /purchases?user_code=zzz-111-asdfg -> same response as above

## Expected Behavior
Get different responses depending on the query params used when calling the API.

GET /purchases?user_id=123 -> 200 OK and just 1 purchase

GET /purchases?user_id=456 -> 200 OK and 5 purchases

GET /purchases?user_code=aaa-000-qwerty -> 200 OK and 0 purchases

GET /purchases?user_code=zzz-111-asdfg -> 200 OK and 3 purchases

## Question

Is this a bug, am I doing it wrong or it is not implemented? A link to the documentation or a code example would help, thanks! :D

**Comment by chohmann** [comment]
Hi @LaiaPR!

There are several ways you can get different responses from Prism:
- using [dynamic generation mode](https://meta.stoplight.io/docs/prism/83dbbd75532cf-http-mocking#static-or-dynamic-generation) instead of the default static mode
- using the [prefer header](https://meta.stoplight.io/docs/prism/83dbbd75532cf-http-mocking#response-examples) to pick which example you want returned

Let us know if you have any further questions!

**Comment by LaiaPR** [comment]
Hi @chohmann ,

already tried using the Prefer Header but I was not getting the expected response. So my question is specificly for Mocking with Postman Collections (using Postman Examples), is this supported? May it be a bug?
Checking the documentation and doing some tests, it seemed to me that this is only supported when Mocking using OpenAPI specification 😞

**Comment by chohmann** [comment]
@LaiaPR could you provide the information above?

**Comment by chohmann** [comment]
@LaiaPR we're going to close this issue as we don't have enough information. Feel free to re-open if you can provide the requested information!
