### ISSUE TITLE
Receiving violation: ____ must match pattern: error from validator when running prism

### ISSUE THREAD

**Issue by williamj20** [stoplightio/prism#2243]
I'm currently running prism with an openapi spec using the command prism mock test.yaml. Then I'm testing an api response using Postman. I have a parameter defined as:

type: string
pattern: '^[0-9]{32}$'
which should be in the response body of one of my GET requests. However, when I run the GET request on postman, I receive an error like so:

error Violation: response.body.string must match pattern '^[0-9]{32}$'

This seems to be because the generated response is the generic 'string' and not one that matches the format. I thought Prism was supposed to generate this response based on this pattern? Am I misunderstanding/doing something wrong?

**Comment by williamj20** [comment]
Sure,

I am running `prism mock api.yaml` 

api.yaml:
```
openapi: 3.0.0
paths:
  /api/v1/test:
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                    key:
                      type: string
                      pattern: '^[0-9a-f]{5}$'
```
Response:
`{ "key": "string" }`

Expected Response: a string that matches the specified pattern i.e.  d31fg
`{ "key": "d31fg" }`

Also, the terminal reports the following error:
`[VALIDATOR] error Violation: response.body.key must match pattern "^[0-9a-f]{5}$`

**Comment by ryotrellim** [comment]
I'm having trouble reproducing @williamj20. 

![troy_Troys-MacBook-Pro___and_prism_mock_prismTest_yaml_and_Receiving_violation_______must_match_pattern__error_from_validator_when_running_prism_·_Issue__2243_·_stoplightio_prism](https://user-images.githubusercontent.com/182591/225992390-8f7afbb3-1b68-4693-b472-618179da6b5b.png)

If you're getting back `{"key":"string"}`, then you might not be sending the Prefer header. 

How are you making the request? Are you using the latest version of prism (4.11.1)?

**Comment by williamj20** [comment]
Indeed I am not sending the prefer header with `dynamic=true`. I see that the request works when I specify `dynamic=true`. Is it intended for it to not work when `dynamic=false`? (i.e., what I was doing originally)
