### ISSUE TITLE
HTTP Basic Auth not working in in 4.11.0

### ISSUE THREAD

**Issue by MerlinMason** [stoplightio/prism#2270]
Hi there, thanks for a great tool! We have discovered the following problem that we believe may be a bug.

Our API documentation is behind http basic auth and we use 
```
prism mock https://username:password@domain.com/api-docs/raw 
```
to launch our mock server. 
This has been working for some time, but when upgrading from `4.10.0` to `4.11.0` this no longer works and we get the following error:

```
ResolverError: Error downloading https://username:password@domain.com/api-docs/raw
Request cannot be constructed from a URL that includes credentials: https://username:password@domain.com/api-docs/raw
```

I cannot see anything in the changelog to suggest this change is intentional.

Thanks!

## Context

This gives us the choice of not upgrading to `4.11.0` (which we would like to do) or making our API documentation public (which we would not like to do).

## Current Behavior

Error mentioned above

## Expected Behavior

Should spin up a mock server as in `4.10.0`

## Possible Workaround/Solution

Don't upgrade or remove authentication.

## Steps to Reproduce

1. Have an API definition behind http basic auth
2. Use Prism `4.11.0`
3. Attempt to start mock server with `prism mock https://username:password@domain.com/api-docs/raw`

## Environment

- Version used: 4.11.0
- Environment name and version (e.g. Chrome 39, node.js 5.4): Node 18.14.2
- Operating System and version (desktop or mobile): MacOS 13.3.1

**Comment by daniel-white** [comment]
hey @MerlinMason 4.14 which landed should resolve the problem. let us know if it doesn't! thanks!
