### ISSUE TITLE
Do not reply with content from examples if they don't match the specified types

### ISSUE THREAD

**Issue by ilanashapiro** [stoplightio/prism#2271]
Prism replies with content from the "examples" property in OpenAPI even if the examples don't match types specified in the schema.

## Context
Consider the following OpenAPI spec:
```
openapi: 3.0.2
paths:
  /pets:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                '$ref': '#/schemas/Pet'
              examples:
                cat:
                  summary: An example of a cat
                  value:
                    id: "string_id"
                    name: 123
                    photoUrls: [[]]
                    status: 135

schemas:
  Pet:
      type: object
      required:
      - name
      - photoUrls
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          xml:
            name: photoUrl
            wrapped: true
          items:
            type: string
        status:
          type: string
          description: pet status in the store
          enum:
          - available
          - pending
          - sold
```

Notice how the values given in the "cat" example do not match the types in the schema. id should be an integer but is the string "string_id", name should be a string but is the integer 123, photoUrls should be an array of strings but instead is an array of arrays [[]], and status is the string "available1" but not one of the allowed enums for status ("available", "pending", "sold").

## Current Behavior
Currently, if we mock the above spec and call curl -i http://localhost:4010/pets, we get the following result:

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/28958079/234963500-9e55a372-6308-4897-b063-1b533f939c42.png">

The example is successfully returned even though the types of its values do not match the schema. These errors are detected as sl-violations, but the example is still returned. The logger also picks up the errors as seen below:

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/28958079/234962995-994ab53d-3ac5-4085-aaeb-721744acac11.png">

## Expected Behavior
We want to introduce a command-line flag or equivalent to tell Prism not to reply with content from the examples if the types don't match the schema. Instead, Prism should return an error, potentially a 406 Not Acceptable error.

## Possible Workaround/Solution
I am working introducing a command-line flag for this issue that supports the expected behavior described above. I am posting the issue here in case anyone has any input as to how they want this to look.

## Steps to Reproduce
Let the OpenAPI spec pasted above be in a file called example.yaml.
1. Call ```prism mock example.yaml```
2. Call ```curl -i http://localhost:4010/pets``` and notice how the example is returned even though it has invalid content for the specified types in the schema

**Comment by ilanashapiro** [comment]
@rattrayalex

**Comment by rattrayalex** [comment]
Thanks for filing this, @ilanashapiro ! It looks like you closed this as completed, but I don't see a linked PR – was that intentional?

**Comment by ilanashapiro** [comment]
@rattrayalex Yes -- I am following up via email! Thanks!

**Comment by ilanashapiro** [comment]
RE: Closing this issue

After poking around the code for a bit to figure out how to introduce the command line flag, I discovered that if you include the existing --errors flag in the cURL command, an error will be thrown if the example doesn't match the schema type.
For instance, if you take the spec that I used for the GitHub issue: https://github.com/stoplightio/prism/issues/2271, and put it in a file called example.yaml, you can mock it with Prism using ```prism mock example.yaml --errors```. Then if you call ```curl -i http://localhost:4010/pets```, it returns the following error
![image](https://user-images.githubusercontent.com/28958079/236592245-7d8df85a-41c6-4fe2-baf9-b199ef27f55f.png)
rather than returning the invalid example. If you leave out the --errors flag and solely call ```prism mock example.yaml```, the invalid example is returned as in the GitHub issue I created. I believe this behavior is implemented here: https://github.com/stoplightio/prism/blob/53d60521cafaa877e7495909aa7bb62aceb1b638/packages/http-server/src/server.ts#:~:text=if%20(opts.config,)%3B

**Comment by RobertCraigie** [comment]
@ilanashapiro ah the behaviour we'd like is for Prism to ignore the provided `example` if it is invalid and instead generate  a valid example itself - do you think that would be possible?
