### ISSUE TITLE
Invalid response object is generated for cyclical schemas

### ISSUE THREAD

**Issue by RobertCraigie** [stoplightio/prism#2291]
## Context

Given this OpenAPI spec which contains a circular schema definition:

```yml
openapi: 3.0.2
paths:
  /pet:
    get:
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/return'
components:
  schemas:
    return:
      type: object
      properties:
        child:
          $ref: '#/components/schemas/return'
          nullable: true
      required:
        - child
```

## Current Behavior

Prism responds with

```json
{
  "child": {
    "$ref": null
  }
}
```

## Expected Behavior

It should instead respond with

```json
{
  "child": null
}
```

## Possible Workaround/Solution

Explicitly setting an `example` for the `child` property to `null`

## Steps to Reproduce

1. Start a mock server for the given spec
2. Run `curl -sXGET http://127.0.0.1:4010/pet`

## Environment

- Version used: `4.14.1`
- Environment name and version (e.g. Chrome 39, node.js 5.4):  nodejs v19.6.1
- Operating System and version (desktop or mobile): MacOS M1
- Link to your environment/workspace/project:

**Comment by chohmann** [comment]
@RobertCraigie the spec you provided is invalid. `$ref` cannot have any other sibling properties. When you remove the invalid `nullable: true` from the spec you provided, Prism correctly mocks the response.

To represent the child property either being the `return` schema or null, you would need to use a `oneOf`.
