### ISSUE TITLE
Disable authentication on mock server

### ISSUE THREAD

**Issue by yosuke-nakamura** [stoplightio/prism#2313]
Disable authentication on moc server

401 response returned when using moc server.

Application uses OAuth2 Proxy and does not keep authentication information on the client.

## Technical Problem Statement

Is it possible to disable authentication on the moc server?
If possible, please let me know how.

## Possible Solution(s)

If I could disable authentication on the moc server, that would solve the problem.

## Timebox Limit

I prefer within 3 days.

This is my first post. Please contact me if anything is unclear.

## Spike Ready Checklist

- [ ] I have acknowledged that the work done in this spike is ephemeral and any PRs created from it will not be merged.
- [ ] I have scheduled a meeting with relevant engineering stakeholders to go over what has been learned from this spike.
- [ ] I have started drafting documentation to describe the results of this spike (including any potential tech debt we might take on).
  - [ ] Either in the form of an [ADR](../../docs/adrs/README.md),
  - [ ] Or in some other structured document, which I will link here.

**Comment by chohmann** [comment]
>Is it possible to disable authentication on the moc server?

Prism's mock mode does not actually perform authentication. It validates that you've sent authentication data in accordance to the OAS spec you provided to Prism. For example, if your OAS spec says an endpoint uses Bearer tokens, Prism will validate that a bearer token was provided in the request, but not actually use the provided token to perform authentication of any kind. So there is nothing to turn off.

We don't quite understand the problem you are having.

Could you provide some clarification to the following questions:
1. What does your OAuth2 Proxy do?
2. How does your OAS spec differ from what the OAuth2 Proxy expects or produces?
3. Can you provide a description of your overall setup between your OAuth2 Proxy and Prism? Basically some sort of diagram of what you've setup.

**Comment by yosuke-nakamura** [comment]
> What does your OAuth2 Proxy do?

Sorry for the lack of words. You can use the following OSS to protect your app.
https://oauth2-proxy.github.io/oauth2-proxy/
browser → oauth2pxoy → react front-end
                      → backend app
This is used to protect react front-end and backend app.


> How does your OAS spec differ from what the OAuth2 Proxy expects or produces?

I don't have enough knowledge to understand OAS, but here is what I understand.
The OAuth2 Proxy converts the request to JWT using cookies and sends it to the backend app, so there is no need for the frontend to send any particular information.
Therefore, there is no programmatic behavior to put anything in the header.
However, Prism now programmatically returns a 401 error when Security is set.


> Can you provide a description of your overall setup between your OAuth2 Proxy and Prism? Basically some sort of diagram of what you've setup.

The answer is similar to the above question, but as you can see in the image, there is a difference between the actual deployment environment and the development environment, so the Prism side will return a 401 error.
[Production environment](https://drive.google.com/open?id=1IPBA3nfxz0T-5_3ITVuFDtz7ijIebth7&usp=drive_fs)
[Development environment](https://drive.google.com/open?id=1IfDEfPCdDi-KsSsyRdzBqKpd6jZ1l9wD&usp=drive_fs)
Is that an answer?

**Comment by chohmann** [comment]
@yosuke-nakamura thank you for providing further details on your request.

Ultimately, the OAS spec used to run Prism with needs to have a security scheme defined that matches what's produced from your OAuth2 proxy.

Another option is to move Prism to a point in your system where the authentication mechanism in the request sent to Prism will match the one defined in the OAS spec.

Prism needs to adhere to what is defined in the OAS spec, and being able to alter that behavior goes against the spirit of the tool.
