### ISSUE TITLE
Upgrade to Latest Version of Lerna + Jest (to upgrade Semver)

### ISSUE THREAD

**Issue by chohmann** [stoplightio/prism#2319]
Upgrade to latest version of Lerna + Jest.

https://github.com/stoplightio/prism/security/dependabot/57

**Comment by brendarearden** [comment]
Our jest dependencies rely on Babel which is still using an unpatched version of semver - but according to them, https://github.com/babel/babel/issues/15720#issuecomment-1606789221 we can ignore the security in regards to Babel
