### ISSUE TITLE
Realization of pattern bifurcation

### ISSUE THREAD

**Issue by yosuke-nakamura** [stoplightio/prism#2330]
## Technical Problem Statement

I would like to use this for frontend UI and function binding tests. However, although we can write an Example to return the expected value, we cannot branch the pattern, so we cannot do an exhaustive test.
Are there any parameters or ideas to make this possible?

## Spike Ready Checklist

- [ ] I have acknowledged that the work done in this spike is ephemeral and any PRs created from it will not be merged.
- [ ] I have scheduled a meeting with relevant engineering stakeholders to go over what has been learned from this spike.
- [ ] I have started drafting documentation to describe the results of this spike (including any potential tech debt we might take on).
  - [ ] Either in the form of an [ADR](../../docs/adrs/README.md),
  - [ ] Or in some other structured document, which I will link here.

**Comment by chohmann** [comment]
@yosuke-nakamura we not sure we entirely understand what you're asking for.

However, do either of these discussions help?
1. https://github.com/stoplightio/prism/issues/1838
2. https://github.com/stoplightio/prism/issues/2250

If neither of these help answer your questions, can you provide the following information to help clarify your question:
1. an example spec to illustrate your question
2. what prism commands are you running?
3. what is a sample request you're making?
4. what response is Prism giving you?
5. what response do you want prism to give you?

**Comment by chohmann** [comment]
@yosuke-nakamura since we haven't gotten a response from you, we will close this issue.
