### ISSUE TITLE
Array minItems not respected on anyOf

### ISSUE THREAD

**Issue by rubensa** [stoplightio/prism#2343]
When you specify a `requestBody` with `anyOf` two properties where each one is an `array` with a `minItems`, despite one of them is present but not valid with the specified `minItems`, if the other one is valid, no errors are reported.

## Context

I want to require the following json request:
```json
{
  "property1": [1, 2],
  "property2": [3, 4]
}
```
where there must exist `property1` or `property2` (or both) and if any of those properties exists, they should have at least one item.

## Current Behavior

Currently, if one property is present but is an empty array, no error is reported if the other property is present and is not an empty array.

## Expected Behavior

There should be an error telling that se empty array should have at least one element.

## Possible Workaround/Solution

None found yet.

## Steps to Reproduce

1. Given the following schema definition:
```yaml
openapi: 3.0.0
info:
  title: Test API
  version: "1.0.0"
  description: Test API
  contact:
    name: Test
servers:
  - description: local
    url: http://localhost:4010
tags:
  - name: test
    description: Test
paths:
  "/anyof/array/minitems":
    post:
      operationId: testAnyOf
      description: Test array minItems
      tags:
        - test
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              anyOf:
                - properties:
                    property1:
                      type: array
                      minItems: 1
                      items:
                        type: integer
                        format: int64
                  required: [property1]
                - properties:
                    property2:
                      type: array
                      minItems: 1
                      items:
                        type: integer
                        format: int64
                  required: [property2]
      responses:
        "200":
          description: OK
```
2. The following call:
```bash
curl --location 'http://localhost:4010/anyof/array/minitems' \
--request POST \
--header 'Content-Type: application/json' \
--data '{
 "property1": []
}'
```
3. Gives the right error answer:
```json
{
  "type": "https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY",
  "title": "Invalid request",
  "status": 422,
  "detail": "Your request is not valid and no HTTP validation response was found in the spec, so Prism is generating this error for you.",
  "validation": [
    {
      "location": [
        "body",
        "property1"
      ],
      "severity": "Error",
      "code": "minItems",
      "message": "Request body property property1 must NOT have fewer than 1 items"
    },
    {
      "location": [
        "body"
      ],
      "severity": "Error",
      "code": "required",
      "message": "Request body must have required property 'property2'"
    },
    {
      "location": [
        "body"
      ],
      "severity": "Error",
      "code": "anyOf",
      "message": "Request body must match a schema in anyOf"
    }
  ]
}
```
4. But given the following request:
```bash
curl --location 'http://localhost:4010/anyof/array/minitems' \
--request POST \
--header 'Content-Type: application/json' \
--data '{
  "property1": [],
  "property2": [1, 2]
}'
```
5. An HTTP 200 OK is returned
6. Where it should have returned:
```json
{
  "type": "https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY",
  "title": "Invalid request",
  "status": 422,
  "detail": "Your request is not valid and no HTTP validation response was found in the spec, so Prism is generating this error for you.",
  "validation": [
    {
      "location": [
        "body",
        "property1"
      ],
      "severity": "Error",
      "code": "minItems",
      "message": "Request body property property1 must NOT have fewer than 1 items"
    }
  ]
}
```

## Environment

- Version used: 4.10.3 and 5.2.0
- Environment name and version (e.g. Chrome 39, node.js 5.4): Docker 23.0.5
- Operating System and version (desktop or mobile): Ubuntu 22:04
- Link to your environment/workspace/project: local-test-setup

**Comment by chohmann** [comment]
@rubensa The current behavior you outlined is the correct behavior and there is no issue with it.

This request body:
```
{
  "property1": [],
  "property2": [1, 2]
}
```
matches the second child of the anyOf because it is lacking `additionalProperties: false`. Because that schema allows for additional properties to be present, the `property1` is considered an additionalProperty, even though it matches the first anyOf child's schema. You'd get the same behavior if the request body contained something random, that doesn't match the first anyOf child:
```
{
  "somethingRandom": 1,
  "property2": [1, 2]
}
```

You can check this in any online json schema validator, (e.g. https://www.jsonschemavalidator.net/).
