### ISSUE TITLE
`validateOuput()` produces false positives when OAS schema uses internal $ref

### ISSUE THREAD

**Issue by mtjandra** [stoplightio/prism#2364]
## Context
[validateOutput()](https://github.com/stoplightio/prism/blob/master/packages/http/src/validator/index.ts#L187) is not producing expected error when response doesn't match OAS schema that includes an internal `$ref`

```yaml
openapi: 3.0.0
info:
  description: service description
  version: '0.1'
  title: service title
tags:
- name: tag1
  description: tag1 description
paths:
  "/test":
    get:
      tags:
      - tag1
      summary: ''
      description: ''
      operationId: testCreateOne
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TestCreateOneResponse"
components:
  schemas:
    TestCreateOneResponse:
      type: object
      description: ''
      properties:
        output:
          "$ref": "#/components/schemas/OutputType"
      required:
      - output
    OutputType:
      type: string
      description: ''
```

## Current Behavior
Error not produced when response does not match OAS schema that includes an internal `$ref`. See https://github.com/stoplightio/prism/pull/2363 for more details.

```json
{
  "_tag":"Right",
  "right":{
    "statusCode":200,
    "headers":{
      "x-powered-by":"Express",
      "content-type":"application/json; charset=utf-8",
      "content-length":"2",
      "etag":"W/\"2-vyGp6PvFo4RvsFtPoIWeCReyIC8\""
    },
    "body":{
      
    }
  }
}
```

## Expected Behavior
Error should be produced when response does not match OAS schema that includes an internal `$ref`. See https://github.com/stoplightio/prism/pull/2363 for more details.

```json
{
  "_tag":"Left",
  "left":[
    {
      "path":[
        "body"
      ],
      "code":"required",
      "message":"Request body must have required property 'output'",
      "severity":0
    }
  ]
}
```

## Possible Workaround/Solution
See https://github.com/stoplightio/prism/pull/2363

## Steps to Reproduce
See [test case](https://github.com/stoplightio/prism/pull/2363/files#diff-e036cce93f7cc75d0f472ace6b9c7acff80069e343bff2b440300d3749996029R191)

Using example schema
```json
{
  "schema":{
    "type":"object",
    "properties":{
      "output":{
        "$ref":"#/__bundled__/OutputType"
      }
    },
    "required":[
      "output"
    ]
  }
}
```

With empty body
```json
{ "body": {} }
```

[validateOutput()](https://github.com/stoplightio/prism/blob/master/packages/http/src/validator/index.ts#L187) did not produce any errors. Expected error about required property `output`

## Environment

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your environment/workspace/project:

**Comment by chohmann** [comment]
This was released in version 5.3.1.
