### ISSUE TITLE
Prism request 500s on a null schema property

### ISSUE THREAD

**Issue by RobertCraigie** [stoplightio/prism#2375]
## Current Behavior

Making a request to an endpoint with a `null` property schema causes Prism to return this error
```
get /foo ✖  error     Request terminated with error: TypeError: Cannot read properties of null (reading '$ref')
```

## Expected Behavior

Prism should treat the schema the same as if it was set to an empty object.

## Possible Workaround/Solution

Using `null` where a schema is expected is not valid, so just replacing it with `{}` fixes the error.

## Steps to Reproduce

OpenAPI:
```yml
paths:
  /foo:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  any_prop: null
                required:
                  - any_prop
```

1. Run mock server against the provided schema
2.  Make a get request to `/foo`

## Environment

- Version used: 5.2.0
- Environment name and version (e.g. Chrome 39, node.js 5.4): node.js 18
- Operating System and version (desktop or mobile): MacOS
- Link to your environment/workspace/project: N/A

**Comment by EdVinyard** [comment]
Are you trying to express that `any_prop` is always of type `null`, has a default value of `null`, is an empty object, or something else?

We completely agree that the error message should be more helpful, and perhaps even should occur at start-up rather than during validation or generation.  Our understanding is that Schema Objects _must_ be objects ([reference](https://spec.openapis.org/oas/v3.0.1.html#schema-object)) and not null, so at this point we're not inclined to make `null` a synonym for `{}` in that context.

**Comment by chohmann** [comment]
Closing ticket as we have not received any more details, and the spec being used with Prism is invalid.

**Comment by RobertCraigie** [comment]
Ah sorry that wasn't clear, I wasn't intending for there to be any special meaning in this case but instead just that the spec was invalid which causes a bad error message.

Our use case is dealing with third-party OpenAPI specs and it doesn't matter to us whether or not they are invalid in some way like this, which is why I suggested the `{}` synonym. We use Prism for validating requests and for testing that certain response deserialising logic works as expected, for which Prism does an amazing job.

Is this a use case that Prism can support? (totally understandable if not!)

---

Sorry I didn't include this context in the original description but just in case it helps:

The original case in which I ran into this was when dealing with an OpenAPI spec that accidentally omitted a value for a property
```yml
properties:
  any_prop:
```

Which translates to `null` when parsed.

**Comment by chohmann** [comment]
@RobertCraigie Thank you for providing more information! There's not much that Prism can do with an invalid spec. Even replacing `null` with `{}` still does not make the spec valid, so mocking this operation would still not work. We do offer an open source linting tool called [Spectral](https://github.com/stoplightio/spectral) that will point out errors with specifications that you can use to find out if the third party spec is invalid.
