### ISSUE TITLE
Support for default JSON deserialization of arrays of objects in form data request bodies in OpenAPI 3

### ISSUE THREAD

**Issue by ilanashapiro** [stoplightio/prism#2380]
## User Story Description

As a developer, I want to be able to pass in arrays of objects in multipart/form-data and application/x-www-form-urlencoded request bodies, not just arrays of primitives.

## Acceptance Criteria

Arrays in form data request bodies, with delimiters specified by the encoding style, can now include JSON objects. For instance, `curl -v -F "arrays={'foo':'value', 'data':'a'}, {'foo':'value1', 'data':'a'}, {'foo':'value2', 'data':'a'}"` when 'arrays' has the Form encoding style with explode set to false, will get serialized appropriately as the array [{'foo':'value', 'data':'a'}, {'foo':'value1', 'data':'a'}, {'foo':'value2', 'data':'a'}]. This is based on the default serialization standard for arrays of objects in OpenAPI 3: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.1.md#styleValues. As far as I understand, arrays of objects are not supported in OpenAPI 2. 

Currently, `curl -v -F "arrays={'foo':'value', 'data':'a'}, {'foo':'value1', 'data':'a'}, {'foo':'value2', 'data':'a'}` will result in a type error as 'arrays' will have the string literal value of the JSON array.

## Sprint Ready Checklist

- [ ] Acceptance criteria defined
- [ ] Team understands acceptance criteria
- [ ] Team has defined solution / steps to satisfy acceptance criteria
- [ ] Acceptance criteria is verifiable / testable
- [ ] External / 3rd Party dependencies identified

**Comment by daniel-white** [comment]
we appreciate the issue and pr @ilanashapiro! however, we do not see that there is a standard way to construct such a request body schema. The `style` prop describes `query`, `path`, `header` and `cookie` parameters objects. do you see something in oas 3.x where that would apply to a request body schema? otherwise we will close the issue and pr.

**Comment by ilanashapiro** [comment]
@daniel-white I see how the `style` prop in this particular table only describes `query`, `path`, `header`, and `cookie` parameter objects. I realized I should have made the link more specific, as this same document also has a description of how the request body schema should be serialized for form data: https://tinyurl.com/dnca4knd. 
Specifically, "the following default Content-Types are defined for multipart... If the property is complex, or an array of complex values, the default Content-Type is application/json". 
Then, in the example below, it specifies that the "default Content-Type for arrays is based on the `inner` type (object shown, so `application/json` in this example)". 

Subsequently, the following table (https://tinyurl.com/5n8wemsx) goes on to discuss how one can apply single encoding definitions to a single schema property in the request body. For the `style` attribute, the following description is given: "Describes how a specific property value will be serialized depending on its type... The behavior follows the same values as query parameters, including default values." 

According to this standard, one can specify how the parameter in the request body should be serialized using the `content-type` prop in the `encoding` object. However, my PR only introduces support for the default serialization strategy (arrays of objects as JSON), although I could certainly work on introducing custom `content-type` serialization in a future PR.

**Comment by ilanashapiro** [comment]
@daniel-white just wanted to check in if it's ok to move ahead with the issue and PR? Thanks!

**Comment by ilanashapiro** [comment]
@rattrayalex @RobertCraigie

**Comment by daniel-white** [comment]
@ilanashapiro our team took a look at your PR - we need to get it into a sprint to review more in depth. thanks for your patience.
