### ISSUE TITLE
Command-line flag to dynamically generate default valid examples in place of invalid static examples 

### ISSUE THREAD

**Issue by ilanashapiro** [stoplightio/prism#2384]
## User Story Description
As a developer, I want to have a command line flag that allows me to mock a schema where, if the static example to be returned in the response body is invalid (i.e. the example results in validation errors), a valid example is dynamically generated instead. 

Currently, Prism's behavior is to log validation errors without returning errors if the --errors flag is omitted. In this case, the request "flows to the actual API and returns what it returns." Valid examples can be dynamically generated by including the --dynamic flag, which will ignore all provided static examples and skip the validation process (the --dynamic flag overrides the --errors flag). However, there is currently no option to use the static example only if it is valid, and to otherwise log the validation errors and dynamically generate a valid example in place of the invalid one. I seek a command line flag that allows this behavior.

## Acceptance Criteria

Given a schema like the following that has an invalid example (note the type mismatch of the example values with the schema):
```
openapi: 3.0.2
paths:
  /pets:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                '$ref': '#/schemas/Pet'
              examples:
                cat:
                  summary: An example of a cat
                  value:
                    id: 123
                    name: "cat"
                    photoUrls: ["url"]
                    status: 123

schemas:
  Pet:
    type: object
    required:
    - name
    - photoUrls
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: doggie
      photoUrls:
        type: array
        xml:
          name: photoUrl
          wrapped: true
        items:
          type: string
      status:
        type: string
        description: pet status in the store
        enum:
        - available
        - pending
        - sold
```

Mocking it would return the following:

```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: *
sl-violations: [{"location":["response","body","status"],"severity":"Error","code":"type","message":"Response body property status must be string"},{"location":["response","body","status"],"severity":"Error","code":"enum","message":"Response body property status must be equal to one of the allowed values: available, pending, sold"}]
Content-type: application/json
Content-Length: 194
Date: Wed, 13 Sep 2023 00:21:25 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"id":-3805631612888092700,"name":"incididunt","photoUrls":["enim","nostrud dolor adipisicing ea in","qui in Duis aliquip in","aliqua elit commodo sed esse","ea cillum enim"],"status":"pending"}%   
```

Note how a dynamically generated valid example has replaced the invalid one that would have otherwise been returned.

## Sprint Ready Checklist

- [ ] Acceptance criteria defined
- [ ] Team understands acceptance criteria
- [ ] Team has defined solution / steps to satisfy acceptance criteria
- [ ] Acceptance criteria is verifiable / testable
- [ ] External / 3rd Party dependencies identified

**Comment by chohmann** [comment]
Closing as won't do. See comment [here](https://github.com/stoplightio/prism/pull/2383#issuecomment-1721551155).
