### ISSUE TITLE
fillproperties / additionalProperties are no longer generated when using dynamic parameter and there is a required property set

### ISSUE THREAD

**Issue by mimkorn** [stoplightio/prism#2386]
## Context
I can either generate non-fake static responses with additional properties generated or fake, but additional properties will not be generated.

## Bug conditions
- Run prism with -d parameter and 
- have additionalProperties of some type that you expect to be generated
- on that same response object have at least one required property
(example OAS below)

## Current Behavior
Not using -d flag will still generate property1 and property2 as additionalProperties. 
```json
{
    "total": 0,
    "offset": 0,
    "limit": 0,
    "results": [
         ....
    ],
    "property1": "string",
    "property2": "string"
}
```
But when I use -d flag the additional properties are not filled anymore if there is some set of required properties. (yes, fill-properties is set to true)
```json
{
    "total": 65704358,
    "limit": 69864003,
    "offset": 44045927,
    "results": [
        ....
    ]
}
no filled properties
```

## Expected Behavior
I would expect the additional properties to be generated as per documentation here https://docs.stoplight.io/docs/prism/9528b5a8272c0-dynamic-response-generation-with-faker#fill-or-additional-properties

## Steps to Reproduce
Simple OpenAPI spec file:

```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: Simple User API
paths:
  /users/{userId}:
    get:
      parameters:
      - name: userId
        in: path
        required: true
        description: The ID of the user to retrieve.
        schema:
          type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
          example: "John Doe"
      additionalProperties:
        type: string
      required:  #if you remove this line and the one below, additionalProperties start to be generated 
        - name
```

## Environment

- Version used: 5.3.1
- Environment name and version (e.g. Chrome 39, node.js 5.4): node 20
- Operating System and version (desktop or mobile): M1 Pro Ventura

**Comment by chohmann** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Team-Tacocat-5eb9bc4a1fddfe30b94f78b1/issues/stoplightio/prism/2386?planning-poker) with Zenhub @EdVinyard @brendarearden @daniel-white @matthewmurphy

**Comment by EdVinyard** [comment]
This may be due to json-schema-faker behavior, or our configuration of it.  Using this JSON Schema

```json
{
  "type": "object",
  "properties": {
    "name": { "type": "string" }
  },
  "required": [ "name" ]
}
```

...the `requiredOnly` option seems to have no effect, but with `alwaysFakeOptionals` enabled, additional properties _are_ generated.  (I was playing with this on https://json-schema-faker.js.org/.)
