### ISSUE TITLE
arrays never have less than maxItems in dynamic responses

### ISSUE THREAD

**Issue by laduke** [stoplightio/prism#2406]
I'm seeing a similar issue to #1549. 

Using the same test.yaml, it always returns arrays with the size of `maxItems` (never less)

```
npm ls json-schema-faker
└─┬ @stoplight/prism-cli@5.4.0
  ├─┬ @stoplight/prism-http@5.4.0
  │ └── json-schema-faker@0.5.3 deduped
  └── json-schema-faker@0.5.3
```

`prism mock -d ./test.yaml` `curl -sL -H "prefer: dynamic=true" localhost:4010/stuff | jq .`

I just started using prism, so I might be doing something wrong. 

I did convert the yaml to json-schema with 
`npx openapi2schema -i test.yaml -p   ` 
and then pasted it into https://json-schema-faker.js.org/

and that does seem to work like I expect. The array length is randomly between minItems and maxItems.

**Comment by laduke** [comment]
wait, why am i getting old faker deps?
```
yarn list --pattern "faker"                            
yarn list v1.22.19
├─ @faker-js/faker@6.3.1
├─ json-schema-faker@0.5.3
└─ postman-collection@4.2.1
   └─ @faker-js/faker@5.5.3
```

My only dependency in package.json is

`    "@stoplight/prism-cli": "^5.4.0"`

**Comment by chohmann** [comment]
Hi @laduke! Sounds like you need to configure the `optionalsProbability` setting for json-schema-faker. You also need to ensure that the `fixedProbabilities` is set to false. Here's some [documentation](https://meta.stoplight.io/docs/prism/9528b5a8272c0-dynamic-response-generation-with-faker#configure-json-schema-faker) on how to do this.

**Comment by laduke** [comment]
Hello!

This always return 20 stuffs

```
openapi: 3.0.0

x-json-schema-faker:
  optionalsProbability: 0.5
  fixedProbabilities: false

info:
  title: Orange v1.0
  version: "1.0"
  description: Orange you glad I didn't say banana! Hah!
  contact:
    name: Stoplight
    url: stoplight.io
    email: support@stoplight.io
servers:
  - url: "http://localhost:3001"
    description: Development
paths:
  /stuff:
    get:
      summary: Retrieve API stuff
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                maxItems: 16
                minItems: 0
                items:
                  type: string
                  minLength: 1
                  maxLength: 20
              examples: {}
      description: |-
        Stuff
      parameters: []
      operationId: stuff
    parameters: []
components:
  schemas: {}
```
```
curl -s localhost:4010/stuff | jq length 
```

I might have the wrong expectations.

**Comment by chohmann** [comment]
You also need to set `alwaysFakeOptionals` = `false`.

From the [json schema faker docs](https://github.com/json-schema-faker/json-schema-faker/tree/master/docs#available-options):

>alwaysFakeOptionals — When enabled, it will set optionalsProbability: 1.0 and  fixedProbabilities: true (default: false)

And from our Prism docs, we default that to true, so you need to override it.

You can always play around with json schema faker settings and their behavior [here](https://json-schema-faker.js.org/).

**Comment by laduke** [comment]
Thanks! that does it.
