### ISSUE TITLE
Update http-spec dependency

### ISSUE THREAD

**Issue by rattrayalex** [stoplightio/prism#2418]
## Context
Would fix https://github.com/stoplightio/prism/issues/1992 since https://github.com/stoplightio/http-spec/pull/253 has merged

## Current Behavior

Same problem reported in https://github.com/stoplightio/prism/issues/1992 and https://github.com/stoplightio/http-spec/pull/253

## Possible Workaround/Solution

Suggestions welcome!

I was previously working around this with `example: 0`, but that doesn't work if you use `--ignoreExamples`.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your environment/workspace/project:

**Comment by rattrayalex** [comment]
:tada: thank you Chelsea!

**Comment by chohmann** [comment]
This was released in version 5.5.1.
