### ISSUE TITLE
Same URLs with differently typed path variables does not route correctly

### ISSUE THREAD

**Issue by DerpgonCz** [stoplightio/prism#2448]
When using multiple routes with the same "template", but their path parameter types differ (especially `string` vs `integer`), the router does not resolve them correctly.

## Context
I am no longer able to maintain 100% test coverage.

## Current Behavior
Using multiple URLs with the same amount of path parameters, but different parameter types, results in wrong routing.

## Expected Behavior
Same URLs with different parameter types result in 

## Possible Workaround/Solution
It is possible to fix this by editing the API. However, adding prefixes here and there really makes things confusing, and is not backwards-compatible.

I noticed that, in https://github.com/stoplightio/prism/blob/master/packages/http/src/router/matchBaseUrl.ts#L39, it always replaces parameters with `.*?` regexp (or an enum regexp if it is an enum). Would it be possible to add this check for numbers aswell? By detecting if the schema is a number, it could be looking for `\d+`.

## Steps to Reproduce
Example schema:
```
{
  "openapi": "3.0.0",
  "info": {
    "description": "",
    "title": "",
    "version": ""
  },
  "servers": [
    {
      "url": "http://localhost:8081/"
    }
  ],
  "paths": {
    "/api/v1/admin/audits/{entity_slug}": {
      "get": {
        "parameters": [
          {
            "example": "test-scenario",
            "in": "path",
            "name": "entity_slug",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "audits": [
                        {
                          "action": "update"
                        }
                      ]
                    }
                  }
                }
              }
            },
            "description": "",
            "headers": {}
          }
        },
        "tags": [],
        "description": ""
      }
    },
    "/api/v1/admin/audits/{id}": {
      "get": {
        "parameters": [
          {
            "example": "123",
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "action": "update"
                    }
                  }
                }
              }
            },
            "description": "OK",
            "headers": {}
          }
        },
        "tags": [],
        "description": ""
      }
    }
  },
  "tags": []
}

```

**Comment by chohmann** [comment]
@DerpgonCz OpenaAPI does not support this and calls it out in the spec [here](https://spec.openapis.org/oas/v3.0.0#patterned-fields). 

>Templated paths with the same hierarchy but different templated names MUST NOT exist as they are identical. In case of ambiguous matching, it’s up to the tooling to decide which one to use.

**Comment by DerpgonCz** [comment]
Hello, thanks for taking the time to answer that, I was not aware and OAS Editor did not complain, either.
