### ISSUE TITLE
Prism Proxy Request Violation for Valid oneOf Schemas

### ISSUE THREAD

**Issue by travisgosselin** [stoplightio/prism#2469]
Prism Proxy seems to be aware of and support `oneOf` usage in OpenAPI specL
https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

However, when in use Prism Proxy always returns a violation.

## Context
With a valid request coming in for one of the provided schemas, violations are reported in testing always, which is a false positive.

## Current Behavior
With the following demonstrative OpenAPI spec:

```
---
openapi: "3.0.1"
info:
  title: demo api
  description: demo api
  version: 1.0.0
paths:
  /example:
    post:
      description: an example with oneOf and prims proxy
      requestBody:
        content:
          application/json:
              schema:
                oneOf:
                  - type: "object"
                    properties:
                        blue:
                          type: string
                  - type: "object"
                    properties:
                        red:
                          type: integer
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                    blue:
                      type: string

```

A request as follows:
```
curl -X POST -H "Content-Type :application/json" -d "{\"blue\": \"hello\"}" http://localhost:4010/example
```
Result sin the following error:
```
Violation: request.body Request body must match exactly one schema in oneOf
```

## Expected Behavior
A request with the body `{\"blue\": \"hello\"}`  OR   `{\"red\": 1}` I would expect no violation reported.

## Environment
Prism Proxy Version: 5.5.4
Node Version: 20.8.1
OS: Windows 11 / Desktop

Your help in identifying if this is a bug, or if my expected behavior is not accurate would be much appreciated.

**Comment by brendarearden** [comment]
The violation you are receiving is correct because `"{\"blue\": \"hello\"}"` matches both of the oneOf options because `additionalProperties` defaults to true so blue is seen as an additional property to `red`. OneOfs can only match one and only one of the combiner options. If you match multiple of the options, it is considered not valid. You can try this out for yourself at https://www.jsonschemavalidator.net/

To resolve the violation, you can do either of the following

Make a property required:
```
      oneOf:
        - type: "object"
          properties:
              blue:
                type: string
        - type: "object"
          properties:
              red:
                type: integer
          required: ['red']

```
Make additionalProperties false
```
        oneOf:
          - type: "object"
            properties:
                blue:
                  type: string
          - type: "object"
            additionalProperties: false
            properties:
                red:
                  type: integer
```

**Comment by travisgosselin** [comment]
@brendarearden thanks so much for your timely response. I wondered if I was missing something completely and that answers it!!! Tested it out just to verify and it works perfectly!
