### ISSUE TITLE
Prism Proxy is not working as expected for binary content types image/jpeg and application/pdf

### ISSUE THREAD

**Issue by Nagasures** [stoplightio/prism#2475]
Response code receiving as 500 when prism proxy is running where as same request is working when sent to actual live end point URL. Issue is occurring when request sent to prism proxy URL 

## Context
unable to implement prism for my team of 10 members

## Current Behavior
Prism proxy forwards the request to base server but we receive response with code 500. Same request sends to actual base/live URL instead of proxy URL sends me 200 code. 

## Expected Behavior
Prism proxy should work as live server

## Steps to Reproduce
```yaml
paths
    /anything
       post:
           requestBody:
               content:
                 image/jpeg
                    schema:
                       type: string
                       format : binary
                  application/pdf
                    schema:
                       type: string
                       format : binary
```
2.  File is being uploaded as binary ( not form-data) 
3. uploading content types image/jpeg , application/pdf
4.

## Environment
Latest version of prism : 5.5.4 

Files being uploaded from windows 10 into Linux docker container

**Comment by Nagasures** [comment]
When request message is received at Proxy URL ... as a next step Proxy is forwarding the request to Live URL. However format of the file is being modified by Proxy causing the 500 response code.

**Comment by brendarearden** [comment]
https://docs.stoplight.io/docs/prism/1593d1470e4df-concepts#content-negotiation this content type is not currently supported in prism. We are tracking this enhancement / feature here: https://github.com/stoplightio/prism/issues/2349 and will close yours as duplicate.

**Comment by Nagasures** [comment]
Thank you for support
