### ISSUE TITLE
Receiving "Invalid reference token: __bundled__" in CI

### ISSUE THREAD

**Issue by yjp20** [stoplightio/prism#2566]
## Context

We've been seemingly spurious errors in CI with `Invalid reference token: __bundled__`. This is happening here: 

https://github.com/openai/openai-python/actions/runs/10010129012/job/27670617482

## Current Behavior

```
[4:35:54 PM] › [HTTP SERVER] post /threads/string/messages ✖  error     Request terminated with error: Error: Invalid reference token: __bundled__
```

## Expected Behavior

I wouldn't expect the prism server to have a fatal error here

## Steps to Reproduce

```bash
npm exec  --package=@stoplight/prism-cli@~5.8 -- \
      prism mock https://storage.googleapis.com/stainless-sdk-openapi-specs/openai-518ca6c60061d3e8bc0971facf40d752f2aea62e3522cc168ad29a1f29cab3dd.yml
```

```bash
curl -L localhost:4010/threads/string/messages -X POST \
            -H 'Authorization: Bearer xxx' \
            -H 'Content-Type: application/json' \
            --data '{"content":"hello","role":"user"}'
```

Strangely this does not happen after cloning the repo, then running the cli through `(cd packages/cli && yarn cli mock https://storage.googleapis.com/stainless-sdk-openapi-specs/openai-518ca6c60061d3e8bc0971facf40d752f2aea62e3522cc168ad29a1f29cab3dd.yml)`

## Environment

- Versions: 5.8.3, 5.8.2, 5.7.0
- OS: MacOS 13.4 (but also in CI)

**Comment by yjp20** [comment]
Removing yarn.lock and running `(cd packages/cli && yarn cli mock https://storage.googleapis.com/stainless-sdk-openapi-specs/openai-518ca6c60061d3e8bc0971facf40d752f2aea62e3522cc168ad29a1f29cab3dd.yml)` seems to reproduce the issue actually, so it may just be a package version bump.

**Comment by yjp20** [comment]
After some bisecting it seems like upgrading from
```
@stoplight/http-spec@7.0.3
to
@stoplight/http-spec@7.1.0
```

causes a breakage, which breaks on the consumer end of the library.

**Comment by RobertCraigie** [comment]
Note that short of forking to pin the `@stoplight/json` dependency we aren't aware of any workarounds

**Comment by mnaumanali94** [comment]
Should be fixed by: https://github.com/stoplightio/json/pull/141

**Comment by dgellow** [comment]
@mnaumanali94 We are seeing this issue again.

https://github.com/openai/openai-go/actions/runs/10322573838/job/28578086104?pr=7

**Comment by RobertCraigie** [comment]
@mnaumanali94 this time I think it's because prism-http

**Comment by RobertCraigie** [comment]
yup it looks like pinning these deps fixes it https://github.com/stainless-api/prism/commit/335f8a829e65a9777beed654dc57f1598be55e86
