### ISSUE TITLE
Error:  "Expected: object, given: string" for query request

### ISSUE THREAD

**Issue by JacksonRudd** [stoplightio/prism#261]
Prism is working fine for `http://localhost:4010/api/ReviewTask`

but when I add query parameters such as:

**URL**:` http://localhost:4010/api/ReviewTask?assignedToId=5
`
I get the following

**Response**:

`
 {"errors":[{"requestQuery":{"error":["(root): Invalid type. Expected: object, given: string"],"message":"The document is not valid. see errors","type":["invalid_type"]}}],"info":"400 response not defined in specification for GET /api/ReviewTask operation. Response generated from request contract validation errors, instead of OAS specification."}`

my swagger doc for this endpoint looks like the following: 
```

"/api/ReviewTask": {
        "get": {
          "tags": [
            "ReviewTask"
          ],
          "operationId": "ReviewTask_Get",
          "parameters": [
            {
              "type": "string",
              "name": "assignedToId",
              "in": "query",
              "x-nullable": true
            },
            {
              "type": "string",
              "name": "state",
              "in": "query",
              "x-schema": {
                "$ref": "#/definitions/WorkflowTaskStates"
              },
              "x-nullable": true,
              "enum": [
                "Assigned",
                "Unassigned",
                "Completed",
                "Cancelled"
              ]
            },
            {
              "type": "string",
              "name": "taskType",
              "in": "query",
              "x-schema": {
                "$ref": "#/definitions/WorkflowTaskTypes"
              },
              "x-nullable": true,
              "enum": [
                "GROCERY",
                "DOG"
              ]
            }
          ],
```

To start prism I ran: 
`./prism mock --spec ./swaggerOutput.json --debug
`
Lastly, I keep seeing this issue in the debugger: 
`DEBUG: martian: connection closed prematurely: EOF
`
I have many different permutations of the query strings but all get the same error. 

What I am doing wrong? Thanks

**Comment by pytlesk4** [comment]
@JacksonRudd thank you for reporting this, releasing a fix right now.

**Comment by JacksonRudd** [comment]
Awesome. This works perfectly now :) Thank you!
