### ISSUE TITLE
Prism sends empty responses after about 15 api calls

### ISSUE THREAD

**Issue by JacksonRudd** [stoplightio/prism#264]
In postman, if I hit my prism endpoint I get a valid response. 

If I hit the end point about 15 more times I continue to get a 200 from prism but I get an empty response which is **not** a valid response. I am using the windows binary and running the following: 

`./prism mock --spec swagger-output.json --debug
`
This issue seems to happen to all of my endpoints on my prism instance. I am waiting for a request to successfully come back before I make the next request. Once prism starts failing, it fails for all future request regardless of the endpoint or the timing of the request. 

The debugger prints the following regardless of if the request is working or not: 

```
INFO: martian: received request: http://localhost:4010/api/Report/TasksByTypeMetric
DEBUG: martian: skipping round trip
DEBUG: martian: sent response: /api/Report/TasksByTypeMetric
DEBUG: martian: waiting for request: [::1]:53792
```

**Comment by pytlesk4** [comment]
@JacksonRudd could you email me your spec? My email is tom@stoplight.io

Thanks!

**Comment by JacksonRudd** [comment]
Yep, just sent it.

**Comment by pytlesk4** [comment]
Thanks that was super helpful, going to release a fix very soon.

**Comment by pytlesk4** [comment]
Released, let us know if you are still seeing the issue.

**Comment by JacksonRudd** [comment]
Works perfectly! Thanks :)
