### ISSUE TITLE
Prism v3.0.0 Alpha

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/prism#266]
Prism v3.0.0 Alpha will be out shortly, so this is a place for interested folks to keep an eye on things instead of having the conversation spread throughout the various feature issues in the repo. 

Subscribe for updates!

**Comment by philsturgeon** [comment]
Alright folks, it's underway. alpha1 and alpha2 already released. 

So far the are two known issues: 

1. if you use `.yml` as an extension it will fail, so please use `.yaml`or `.json` for now 😅 
2. on startup prism doesn't give you much information, and that will be taken care of with #293

RE 2, regardless of id you use OpenAPI v2 or v3, ignore the basePath entirely. That is merged into the host URL, and Prism is giving you a new host URL, so whatever you have in `paths` is where you start.

**Comment by ww-daniel-mora** [comment]
@philsturgeon subscribed!

**Comment by philsturgeon** [comment]
@ww-daniel-mora damn sorry meant to reach out. Glad you spotted this.

**Comment by danksim** [comment]
@philsturgeon nice! Is there a docker image for 3.0?

**Comment by XVincentX** [comment]
@danksim We do not have it just yet, but it shouldn't be a problem to create one, as we offer stand alone binaries and Prism is a NodeJS App:

```Dockerfile
FROM node:10

RUN yarn global add @stoplight/prism-cli

ENTRYPOINT ["prism"]
```

**Comment by danksim** [comment]
@XVincentX thanks! Was just about to write one.

**Comment by danksim** [comment]
Not sure if it's just me but I got `Error: Cannot find module 'json-schema-faker'` while running the `mock` cmd so I ended up installing that package in the Dockerfile.

**Comment by XVincentX** [comment]
@danksim That happens if you're using NPM and you're not exactly using the latest version.

`npm i -g npm` or simply use yarn to install the Prism alpha will fix the issue. We know where the problem is, we just need to fix it.

**Comment by philsturgeon** [comment]
The .yml issue is fixed in alpha4, so use .yml or .yaml doesnt matter. Another great fixz from @XVincentX.

**Comment by distinctgrey** [comment]
Any updates? :-)
Do you have a date in mind for a stable release?

Same question for integration of prism v3 into Stoplight.
For us, being able to execute a Stoplight mock scenario from Prism, instead of just an OAS file, is a huge advantage, as we have quite a lot of custom scenario steps in our mocking setup.

**Comment by pytlesk4** [comment]
@distinctgrey Prism V3 is a lot different. We ended up ditching the scenario approach in the context of mocking.

Could you share/describe your scenarios in your mocking custom scenario mocking setup?

**Comment by distinctgrey** [comment]
As most of our APIs adhere to the [JSON:API](https://jsonapi.org/) specification, we added some intermediate helper steps in order to make mocking response more realistic.
These include:
- HATEOAS linking url replacement
- pagination (https://jsonapi.org/format/#fetching-pagination)
- replacement of path parameters (e.g. IDs) in response bodies
- ...

Are you implying that the scenario approach will no longer be used in a future version of Stoplight?
And will there be a suitable replacement?

**Comment by philsturgeon** [comment]
@distinctgrey Prism v3.0 as a downloadable utility will have a focus as a CLI mock server, and whilst contract testing will be involved, scenarios wont be. 

Things like HATEOAS rewriting will be supported as a first class feature so we can chat about that over on #238.

The path parameters sounds interesting. Fancy starting up an issue where we can chat about that?

**Comment by ntiss** [comment]
Hello everyone.
Any plans to support the "conduct"' command ?
Thx.

**Comment by philsturgeon** [comment]
@ntiss the conduct command runs scenarios, so that falls outside of the initial "CLI mocking" use case. 

As I mentioned, scenarios and some other functionality is being re-imagined. We're getting the mocking use-case covered as well as possible before moving onto other verticals. You can continue using Prism v2 for anything you need that is not in v3.

**Comment by ntiss** [comment]
Hi @philsturgeon
Thx for the reply. I can't wait to test the next features. Special case for me, we are running onPremise. Maybe a long time before seeing something.
(btw, nice bike trip!)

**Comment by wintercounter** [comment]
- Without CLI with just importing it and running an instance manually.
- Ability to intercept response (onRequest callback or something).

**Comment by philsturgeon** [comment]
Alright, thanks for all your feedback so far, the alpha series has flushed out a bunch of bugs, and missing bits. After several [alpha releases](https://github.com/stoplightio/prism/releases) I think v3.0.0-alpha15 will probably be the last. 

We'll be tagging up a beta pretty soon, and then we continue the hardening. 

Prism now has response example picking:

```
$ http GET http://127.0.0.1:4010/pets/123\?__example\=dog
HTTP/1.1 200 OK
Connection: keep-alive
Date: Fri, 14 Jun 2019 15:02:57 GMT
content-length: 126
content-type: application/json; charset=utf-8

{
    "category": {
        "id": 2,
        "name": "Canis"
    },
    "id": 1,
    "name": "Sharik",
    "photoUrls": [],
    "status": "available",
    "tags": [
        {
            "id": 2,
            "name": "dog"
        }
    ]
}


$ http GET http://127.0.0.1:4010/pets/123\?__example\=cat
HTTP/1.1 200 OK
Connection: keep-alive
Date: Fri, 14 Jun 2019 15:03:00 GMT
content-length: 126
content-type: application/json; charset=utf-8

{
    "category": {
        "id": 1,
        "name": "Felis"
    },
    "id": 2,
    "name": "Fluffy",
    "photoUrls": [],
    "status": "available",
    "tags": [
        {
            "id": 1,
            "name": "pet"
        }
    ]
}
```

If no example is found and it has to generate an example from the schema, it will now be static by default, and use properties `example`, `examples`, `default`, `enum`, etc to produce the most useful looking example possible. Thanks to our friends over at ReDoc (whats up @RomanHotsiy!) for the [openapi-sampler](https://github.com/Redocly/openapi-sampler) package. 

You can now enable "dynamic mode", which will bring back the previous default behavior of creating random fake data for your properties.

```
$ http GET http://127.0.0.1:4010/pets/123\?__dynamic\=true
HTTP/1.1 200 OK
Connection: keep-alive
Date: Fri, 14 Jun 2019 15:06:58 GMT
content-length: 393
content-type: application/json; charset=utf-8

{
    "category": {
        "id": 37070591,
        "name": "non labore ea"
    },
    "id": 43025162,
    "name": "Duis",
    "photoUrls": [
        "eiusmod et",
        "minim cillum mollit",
        "laborum irure",
        "e"
    ],
    "status": "available",
    "tags": [
        {
            "id": -59360298,
            "name": "aute Duis quis est labore"
        },
        {
            "id": -12782588,
            "name": "qui"
        },
        {
            "id": -8002483,
            "name": "exercitation dolor ut"
        },
        {
            "id": 78411236,
            "name": "ex non"
        },
        {
            "id": 24195857,
            "name": "Lorem deserunt irure laboris"
        }
    ]
}
```

Content negotation now works nicely, with Accept and Content-Type being taken into account, and loads more awesome stuff. 

Seems like it's time to close this general alpha thread. If you wouldn't mind posting issues as you find them, and PRs if you can, then we can keep on trucking with the progress through the betas.
