### ISSUE TITLE
Docker Conduct Error: Path to Scenario Spec Required

### ISSUE THREAD

**Issue by krismeister** [stoplightio/prism#268]
The example docker command does not work for prism.
```
docker run --rm -v $(pwd):/tmp stoplight/prism:v2.0.20 conduct --spec /tmp/petstore.json
# output:
Error: Path to Scenario Spec Required.
```

I'll attach a PR with the broken example.
Feel free to disregard the pr.

**Comment by XVincentX** [comment]
Hey @krismeister,

The command you posted is lacking the (required) scenario file. The correct command should be something like:
`prism conduct ./scenario.yml --spec /tmp/petstore.json`

Can you point out where you found this command? If it's on our side, we'll make sure to fix it!
