### ISSUE TITLE
Unknown media type 'application/vnd.api+json'

### ISSUE THREAD

**Issue by ahx** [stoplightio/prism#287]
When using `prism mock` the mock server resonds with:

```
HTTP/1.1 500 Internal Server Error
content-type: application/problem+json
content-length: 133
Date: Fri, 10 May 2019 08:33:41 GMT
Connection: keep-alive

{"type":"https://stoplight.io/prism/errors#UNKNOWN","title":"Unknown media type 'application/vnd.api+json'","status":500,"detail":""}
```

Should prism respond with a reponse as specified in the API description when using any "*.json" media type by default or do you think this should be handled by case by case by the user

**Comment by philsturgeon** [comment]
Hey @ahx, when you say "support the JSON:API media type by default" what is it exactly that you mean? I definitely want to make sure nothing in prism stops people from using whatever media type they want, but if you mean that errors should be returned in JSON:API error format by default, I would rather not. 

There are two popular error standards for HTTP APIs:

1. RFC 7807 
2. JSON:API

If you are using JSON:API, then use JSON:API errors, but Prism is a generic HTTP tool so it uses the generic RFC. :D 

If that's not what you meant, let me know.

**Comment by ahx** [comment]
Sorry for being too vague here @philsturgeon. I was not thinking about the error responses made by the mock server.
I was just wondering if `prism mock` could/should be changed so that it does not respond with an error here, but "just works " meaning: Respond with a respons as specified in the API description. Currently it just works with "application/json", but does not with "application/vnd.api+json".

**Comment by philsturgeon** [comment]
Ahh, I'm starting to understand. Where are you putting this `application/vnd.api+json` ? Are you using it in an Accept header? A Content-Type? 

If I have some specifics I can write up a feature request. :)

**Comment by ahx** [comment]
I am specifying it as a content type for responses. Here's an example spec:
```yaml
openapi: 3.0.2
info:
  title: "Example API"
  version: "1.0.0"
  contact:
    url: https://www.example.com/
paths:
  /example:
    get:
      parameters:
        - name: start_date
          in: query
          description: Start date of the timeframe to fetch data
          required: true
          schema:
            type: string
            format: date
      responses:
        default:
          description: "an error occured"
          content:
            application/vnd.api+json:
              schema:
                type: object
                required: [errors]
```

Current response body:
```
{"type":"https://stoplight.io/prism/errors#UNKNOWN","title":"Unknown media type 'application/vnd.api+json'","status":500,"detail":""}
```

Expected response bod  (It just works with content-type `application/json`):
```json
{"errors":"dolor ad fugiat sint ex"}
```

**Comment by philsturgeon** [comment]
Great, got you. 

So, does #288 look like it'll take care of things? This feature was scheduled for beta to be done over the next week or two, and those beta stories are not in GitHub here. I'll move some more of them over.

**Comment by ahx** [comment]
Yes, given that "Accept */*" is handled as well. 👍 
Thank you.
