### ISSUE TITLE
Startup Information

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/prism#293]
**User Story**

As a brand new user who has never tried prism or even mocking, I need the mock command to guide me to making requests by showing me available URLs

**Current behavior**

```
$ prism mock examples/petstore.oas3.json
http://127.0.0.1:4010
```

This does not do much to help people figure out what endpoints are available. If we output a list of all HTTP operations, method and path template, we should be onto a winner.

```
$ prism mock examples/petstore.oas3.json
Starting web server: http://127.0.0.1:4010

Discovered Operations
------------------------
GET         /pets
POST        /pets
GET         /pets/{id}
DELETE      /pets/{id}
```

Formatting is up for grabs, but this is a suggestion. Gatsby has beautiful output maybe check that.

**Acceptance Criteria**

- If no operations are found, the console.error saying that and exit
- If operations are found, they should be listed so people can interact with them

**Comment by philsturgeon** [comment]
Here is what gatsby develop looks like, to save you spinning it up. 

<img width="545" alt="Screen Shot 2019-05-11 at 09 32 33" src="https://user-images.githubusercontent.com/67381/57566642-c6aa8800-73cf-11e9-934a-e308c2516f34.png">

**Comment by XVincentX** [comment]
This is done in #296
