### ISSUE TITLE
Add Prism as an NPM module

### ISSUE THREAD

**Issue by GFoley83** [stoplightio/prism#3]
I've been using this snippet to get it working with Node on Windows:

`prism.js`
```js
var exec = require('child_process').exec;

// Get the swagger json/yaml file passed in as an arg
var swaggerEndPoint = process.argv[2];

if(!swaggerEndPoint){
    console.error("No swagger endpoint given");
    return;
}

var prism = exec('prism_windows_386.exe run --mock --list --spec ' + swaggerEndPoint);  

prism.stdout.on('data', function(data) {
    console.log(data); 
});
```
and they use it with node like: `C:\>node prism http://petstore.swagger.io/v2/swagger.json`

Which works fine but I obviously need `prism_windows_386.exe` checked into source control. It would make this infinitely more usable if prism could just be installed via `npm` and used like a regular module.

**Comment by pytlesk4** [comment]
Hmm, interesting!  Do you actually want to use Prism in a project, or do you want to just install it easier on windows? If you want to use it in projects, what for?

**Comment by GFoley83** [comment]
I'd like to be able to use it in project, specifically for mocking a not-yet-ready endpoint and for day-to-day development and testing. 

E.g. a Swagger spec is created by the back-end team asap; with an actual, usable API endpoint based on said spec to come at a later date. 
The front-end team takes the swagger spec and builds the various models and services they need and use Prism to run a mock server for dev work and running integration/e2e tests against.

Having Prism as an installable `npm` module would make this process easier for the front-end guys, as `node` and `npm` are the foundation for everything front-end related these days e.g. dev dependences, package management, build etc.

**Comment by GFoley83** [comment]
@pytlesk4 great stuff. Look forward to seeing what you guys come up with.

**Comment by philsturgeon** [comment]
Hey, sorry this hasn't been updated for so long! The Prism v3 JavaScript (TypeScript) rewrite has been underway for a good amount of time now, and is approaching an alpha release. 

<img width="404" alt="Screen Shot 2019-04-29 at 14 13 59" src="https://user-images.githubusercontent.com/67381/56896016-f0d47f80-6a8a-11e9-9cb5-d4fa2ecba3ae.png">

Click this for updates!

**Comment by GFoley83** [comment]
So assuming that means installing via npm will also be included?

**Comment by philsturgeon** [comment]
Yup!
