### ISSUE TITLE
Add options to control terminal output when running scenarios

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/prism#30]
- [ ] Print list of failed tests at the end so you can do a quick find in the terminal.
- [ ] Filter Results

**Comment by pytlesk4** [comment]
- talk about this when we go over the prism cli

**Comment by amalsgit** [comment]
Is there any update on this? I have been evaluating Stoplight and prism cli for our API automation. But it looks like there are no options to view a proper test report after running a collection from prism. Is there any cli commands to output a proper test result report from prism and then generate an HTML report out of it? We are currently using postman(newman cli) for these and I am evaluating stoplight against postman. Any help is appreciated. Thanks @pytlesk4

**Comment by philsturgeon** [comment]
Hey there, sorry for the lack of reply for so long! Right now there is not a huge amount of work being done on Prism v2 as a huge amount of effort has been going into the v3 rewrite in TypeScript. It won't be coming out with scenario support immediately, but when tests do come along we will make sure they have common formats like xUnit for sure.

Will update back here with any testing related progress.

**Comment by philsturgeon** [comment]
So prism v3 is out and for the mean time it will be focusing on being the best CLI OpenAPI v2/v3 based mocking solution possible. We'll be bringing in other functionality over time and fielding feedback from the community best we can, but when testing does come back it will mostly be contract testing and that will definitely have lots of options for outputting results. #51
