### ISSUE TITLE
Not mocking response headers

### ISSUE THREAD

**Issue by LesterTheTester** [stoplightio/prism#311]
Hi - 

I'm updating to openAPI 3.0, and prism doesn't seem to be sending response header examples.  My JSON looks like this:

```"responses": {
          "200": {
            "headers": {
              "X-Entitlements": {
                "schema": {
                  "type": "string",
                  "example": "lesterlesterlester"
                }
              }
            },
            "content": {
              "application/json": {
                "description": "A successful request",
                "schema": {
                  "type": "object",
                  "properties": {
```

I get the response, but the headers are mising. Am I doing something wrong or is this not supported yet?

```HTTP/1.1 200 OK
content-type: application/json
content-length: 1227
Date: Mon, 20 May 2019 18:15:27 GMT
Connection: keep-alive

{"userSession":{"user":```

**Comment by philsturgeon** [comment]
Which version of Prism are you using? Prism v2.x does not support OpenAPI v3.x.

**Comment by LesterTheTester** [comment]
3.0.0-alpha.6

**Comment by philsturgeon** [comment]
You're absolutely right! I'll get this looked at, and it will be fixed for beta. Thank you for reporting this!

**Comment by XVincentX** [comment]
@LesterTheTester This is now a thing in prism 3.0 alpha 11!
