### ISSUE TITLE
Error 422, Missing Authorization header param

### ISSUE THREAD

**Issue by GuilhermeRizzottoLis** [stoplightio/prism#324]
When my requisition is with a header, the response is a 422, saying Missing Authorization Header param, but i put in the requisition -H "Authorization: bearer blabla". Is that an issue? When i use the Authorization as query, it works

**Comment by lag-of-death** [comment]
hi @GuilhermeRizzottoLis, so basically, security validation is not yet supported and it should not matter if you send the token as a header or as a part of the query. Please see https://github.com/stoplightio/prism/issues/267#issue-440752688 for more on this.

I'm guessing that you have a specification that has something like:
```json
"parameters": [
  {
    "name": "Authorization Header",
    "in": "query",
    "required": true,
    "type": "string"
  }
]
```
(or `schema` instead of `type` if it is OAS v3)

If the above is true, then everything is OK (unless my assumption is wrong of course). It is OK because you're sending the required parameter. In the case, when you do not send it, you get `422` and it is, in fact, the desired behavior.

Does this clarify the things? If not, please attach the spec and the requests (the one with the header and the one when you have `Authorization Header` in the query?

**Comment by GuilhermeRizzottoLis** [comment]
`"parameters": [
  {
    "name": "Authorization",
    "in": "header",
    "required": true,
    "type": "string"
  }
]`

in my case is in: header, when i put in: query it works

**Comment by GuilhermeRizzottoLis** [comment]
the problem is not about the security, it could be another parameter passed by header, and it doesent works

**Comment by GuilhermeRizzottoLis** [comment]
`curl -X GET -s -D "/dev/stderr" -H "Authorization = dasds" http://127.0.0.1:4010/templates | json_pp
`

**Comment by lag-of-death** [comment]
Hi @GuilhermeRizzottoLis, thanks for the feedback. I've just checked it and indeed when we provide a required header param in a request, we end up with `Missing <<HEADER_NAME>> header param` in the response. Thanks for reporting this!
@philsturgeon, https://github.com/stoplightio/prism/pull/325 is not related to the bug reported by @GuilhermeRizzottoLis.

**Comment by GuilhermeRizzottoLis** [comment]
Dou you guys pretend to fix quickly? Thanks for the support.

**Comment by XVincentX** [comment]
Hey @GuilhermeRizzottoLis ,

thanks a lot for reporting this!

I've tried to reproduce the issue with a very minimal document; according to the conversation I inferred you're using an OpenAPI 2.0 document — so I did the same:

```json
{
  "swagger": "2.0",
  "info": {
    "title": "Test"
  },
  "paths": {
    "/test": {
      "get": {
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "object",
              "properties": {}
            }
          }
        },
        "parameters": [
          {
            "in": "header",
            "name": "api_key",
            "type": "string",
            "required": true,
          }
        ]
      }
    }
  }
}
```

and then tried to make a CURL request:

```bash
HTTP/1.1 500 Internal Server Error
content-type: application/problem+json
content-length: 169
Date: Tue, 28 May 2019 13:14:11 GMT
Connection: keep-alive

{
   "detail" : "",
   "type" : "https://stoplight.io/prism/errors#UNKNOWN",
   "title" : "AJV validation error: \"Error: schema is invalid: data.required should be array\"",
   "status" : 500
}
```

The problem I'm getting here is not about required header missing — but a completely different error saying `ajv` is (correctly) not able to compile the schema.

Are you receiving the same error message? If so — then yes, this is an internal bug which we'll likely fix very soon.

If it's not, can you please help me reproduce it pasting the offending document?

Thanks!

**Comment by GuilhermeRizzottoLis** [comment]
Yeah, i had the same Error, `schema is invalid`. But my problem with the header is still happening, and im using .yaml file. Let me try to explain my issue again: I have my .yaml file with a header, im trying to make a request passing the header and another parameters as query.  When i send the request, I always regardless the way i do it, the response is always `Missing <<header name>> header param`. When i delete the header in .yaml and pass only the query, the curl works. So it seems not to be recognizing the sent header.

**Comment by XVincentX** [comment]
Hey @GuilhermeRizzottoLis 

Generally speaking, Yaml or Json does not really make any difference; but I need your help to reproduce the issue correctly, as apparently you're experiencing yet another behaviour

1. Are you using OpenAPI 2.0 or OpenAPI 3.0?
2. Is there any way you can send a minimal document to reproduce the issue?

**Comment by GuilhermeRizzottoLis** [comment]
`---
swagger: '2.0'
info:
  title: test
  version: 1.0.0
tags:
- name: test
schemes:
- http
paths:
  "/test":
    get:
      tags:
      - test
      description: 'bla'
      produces:
      - application/json
      parameters:
      - name: query
        in: query
        description: by query
        required: true
        type: string
        default: " "
      - name: Authorization
        in: header
        description: by header
        required: true
        type: string
      responses:
        '200':
          description: test
          schema:
            type: array
            items:
              $ref: '#/definitions/Test'
definitions:
  Test:
    type: object
    properties:
      test:
        type: string
        description: test

`

**Comment by GuilhermeRizzottoLis** [comment]
```
swagger: '2.0'
info:
  title: test
  version: 1.0.0
tags:
- name: test
schemes:
- http
paths:
  "/test":
    get:
      tags:
      - test
      description: 'bla'
      produces:
      - application/json
      parameters:
      - name: query
        in: query
        description: by query
        required: true
        type: string
        default: " "
      - name: Authorization
        in: header
        description: by header
        required: true
        type: string
      responses:
        '200':
          description: test
          schema:
            type: array
            items:
              $ref: '#/definitions/Test'
definitions:
  Test:
    type: object
    properties:
      test:
        type: string
        description: test

```

**Comment by GuilhermeRizzottoLis** [comment]
curl -X GET "http://localhost:3030/test?query=dsads" -H "accept: application/json" -H "Authorization: gtdd" | json_pp. Just change the port and try this curl.

**Comment by GuilhermeRizzottoLis** [comment]
`curl -X GET "http://localhost:3030/test?query=dsads" -H "accept: application/json" -H "Authorization: gtdd" | json_pp
`
Just change the port and then, try this curl

**Comment by GuilhermeRizzottoLis** [comment]
> Hey @GuilhermeRizzottoLis ,
> 
> thanks a lot for reporting this!
> 
> I've tried to reproduce the issue with a very minimal document; according to the conversation I inferred you're using an OpenAPI 2.0 document — so I did the same:
> 
> ```json
> {
>   "swagger": "2.0",
>   "info": {
>     "title": "Test"
>   },
>   "paths": {
>     "/test": {
>       "get": {
>         "responses": {
>           "200": {
>             "description": "",
>             "schema": {
>               "type": "object",
>               "properties": {}
>             }
>           }
>         },
>         "parameters": [
>           {
>             "in": "header",
>             "name": "api_key",
>             "type": "string",
>             "required": true,
>           }
>         ]
>       }
>     }
>   }
> }
> ```
> 
> and then tried to make a CURL request:
> 
> ```shell
> HTTP/1.1 500 Internal Server Error
> content-type: application/problem+json
> content-length: 169
> Date: Tue, 28 May 2019 13:14:11 GMT
> Connection: keep-alive
> 
> {
>    "detail" : "",
>    "type" : "https://stoplight.io/prism/errors#UNKNOWN",
>    "title" : "AJV validation error: \"Error: schema is invalid: data.required should be array\"",
>    "status" : 500
> }
> ```
> 
> The problem I'm getting here is not about required header missing — but a completely different error saying `ajv` is (correctly) not able to compile the schema.
> 
> Are you receiving the same error message? If so — then yes, this is an internal bug which we'll likely fix very soon. Basically we're feeding Ajv with an OAS2 specific schema which is not compatible with JSON Schema, confusing the library which is throwing an exception.
> 
> If it's not, can you please help me reproduce it pasting the offending document?
> 
> Thanks!


**Did you get another error? 
Now i have this issue here.**

**Comment by XVincentX** [comment]
@GuilhermeRizzottoLis Yes — that is what I described in the comment above:

https://github.com/stoplightio/prism/issues/324#issuecomment-496511639

This is going to require a fix on the way we feed Ajv.

**Comment by GuilhermeRizzottoLis** [comment]
Ok, thanks so much!!

**Comment by XVincentX** [comment]
We'll try to prioritise this though, it's pretty important. :+1: stay tuned!

**Comment by GuilhermeRizzottoLis** [comment]
Yeah!

**Comment by XVincentX** [comment]
@GuilhermeRizzottoLis This is now done in alpha 14

**Comment by GuilhermeRizzottoLis** [comment]
@XVincentX Thanks so much, appreciate!!! :)
