### ISSUE TITLE
Prism failing with custom Content-Type header

### ISSUE THREAD

**Issue by guilleiguaran** [stoplightio/prism#341]
**Describe the bug**
I'm getting an `Unsupported Media Type: application/vnd.api+json` error from Prism mock server.

**To Reproduce**

Using this example specification:
https://gist.github.com/guilleiguaran/3cb198f59f804acae754124c57304ef6

1. When I run this command: 
`prism mock openapi.yml`

2. Then make the following HTTP request: 
```
curl -X POST -H 'Content-Type: application/vnd.api+json' -H 'Accept: application/vnd.api+json' -i http://localhost:4010/users --data '{
  "data": {
    "type": "user",
    "attributes": {
      "email": "phil@fakemail.com",
      "password": "mypassword1$",
      "first_name": "Phil",
      "last_name": "Sturgeon",
      "terms_accepted": true
    }
  }
}'
```

3. Then I got this response:

```
{
  "statusCode": 415,
  "code": "FST_ERR_CTP_INVALID_MEDIA_TYPE",
  "error": "Unsupported Media Type",
  "message": "FST_ERR_CTP_INVALID_MEDIA_TYPE: Unsupported Media Type: application/vnd.api+json"
}
```

**Expected behavior**
I expect one response like the one displayed by redoc-cli for same endpoint:
```
{
  "data": {
    "type": "user",
    "attributes": {
      "email": "angelica.acosta@fakemail.com",
      "password": "nulla eu est",
      "first_name": "Angelica",
      "last_name": "Acosta",
      "registration_state": "onboarding_completed"
    },
    "id": "1"
  }
}
```

**Desktop (please complete the following information):**

- OS: macOS 10.14.4
- Prism Version: 3.0.0-alpha.12.
- Install method: yarn

**Comment by guilleiguaran** [comment]
This seems to be similar to https://github.com/stoplightio/prism/issues/332 but using a custom `Content-Type` instead of `Accept`

**Comment by XVincentX** [comment]
@guilleiguaran Yeah this is because we haven't configured Fastify, which handles by default only `text/plain` and `application/json`

**Comment by XVincentX** [comment]
@guilleiguaran Merged and released.
