### ISSUE TITLE
bug: DELETE returns wrong status code

### ISSUE THREAD

**Issue by javigomez** [stoplightio/prism#348]
**Describe the bug**
Prism DELETE operations returns wrong status code. It adds a 200 at the end of the expected code.

**To Reproduce**

do:
`docker run --name prism -d -p 4010:4010 stoplight/prism mock -s https://petstore.swagger.io/v2/swagger.json`

... then, execute: `curl -X DELETE -I http://localhost:4010/pet/1`

Note that for the example I am using https://petstore.swagger.io/#/pet/deletePet example swagger definition, but this happens with any DELETE operation on any of my definitions

**Actual behavior**
you get:

```
HTTP/1.1 401 200 OK
...
```

Note that the HTTP status code is invalid, the 200 should not be there

**Expected behavior**

```
HTTP/1.1 401 OK
```

``` yaml
openapi: 2.0
# ...
```
https://petstore.swagger.io/#/pet/deletePet

**Desktop (please complete the following information):**

- OS: [e.g. macOS 10.14.4]
- Prism Version [e.g. v3.0.0]
- Install method: docker

**Comment by XVincentX** [comment]
Ah — this is interesting. I'll look into this and see if we can quickly fix it!

**Comment by XVincentX** [comment]
@javigomez 

I'm not able to reproduce the error.

With the server running:
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/1416224/59422350-8aa08380-8dd0-11e9-9510-cac8aa75d2b1.png">

I'm correctly receiving a 500 message (because there's no 200 response defined)

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/1416224/59422411-a015ad80-8dd0-11e9-85e9-df8639a3d4d2.png">

**Comment by philsturgeon** [comment]
Expected behavior

HTTP/1.1 401 OK

Did you mean 401 OK?

--
Phil Sturgeon
@philsturgeon

**Comment by javigomez** [comment]
@XVincentX try it with the Docker Prism container, I have been able to reproduce the error in 2 MacOS and one Linux machine


<img width="1002" alt="issue" src="https://user-images.githubusercontent.com/1375475/59454071-982a2d80-8e11-11e9-8054-966a72eb0e25.png">


But anyway, you are right 

> I'm correctly receiving a 500 message (because there's no 200 response defined)

I am closing this issue and reopening it if I am able to provide a valid example

**Comment by XVincentX** [comment]
@javigomez Ah here's the problem! The docker image you're using is Prism 2.x — the old version written in Go :)
