### ISSUE TITLE
Build that runs on Alpine Linux?

### ISSUE THREAD

**Issue by davidham** [stoplightio/prism#35]
We have a Rails app with prism as part of its test suite. The alphas run fine on images based on `ruby:2.4-slim`, but when I tried running one on an image based on `alpine:3.6`, I got `No such file or directory` errors. When I run `ldd` on the binary, I get this:

```
bash-4.3# ldd /usr/bin/prism
    /lib64/ld-linux-x86-64.so.2 (0x5588243ac000)
    libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x5588243ac000)
    libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x5588243ac000)
    libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x5588243ac000)
Error relocating /usr/bin/prism: __isnan: symbol not found
Error relocating /usr/bin/prism: __finite: symbol not found
```

In this page from the [Docker alpine docs](http://gliderlabs.viewdocs.io/docker-alpine/caveats/#user-content-incompatible-binaries), it says that because Alpine uses musl libc instead of glibc, the binary would need to be compiled natively for musl in order to work. Is this something you could do? Or is there any other way we could run it in our alpine containers?

**Comment by marbemac** [comment]
Hi @davidham - which version of Prism are you running? We have v2 running in alpine already actually, and plan to publish+maintain official docker images with the v2 release.

**Comment by davidham** [comment]
I tried Prism 2.0.0-alpha-7 on an image based on `alpine:3.6` but it gave me the behavior above. I tried [adding glibc](https://github.com/sgerrand/alpine-pkg-glibc) just now and it worked, which is fine for now, but if you have a binary that runs without glibc that would be fantastic.
