### ISSUE TITLE
feature: Add static examples from OpenAPI specification as it was in 2.x versions

### ISSUE THREAD

**Issue by usmanovbf** [stoplightio/prism#363]
**Is your feature request related to a problem? Please describe.**
Add the possibility to return static examples into responses that listed in OpenAPI specification

**Describe the solution you'd like**
I liked this feature in 2.x versions

**Comment by XVincentX** [comment]
@usmanovbf Static Examples are now supported in Prism; are you referring to something in particular?

**Comment by philsturgeon** [comment]
Which version are you running? We only released it in a recent alpha so maybe upgrade.

**Comment by usmanovbf** [comment]
@philsturgeon yeah, thanks! Suddenly it appeared
