### ISSUE TITLE
Feature: Improve log message structure

### ISSUE THREAD

**Issue by marbemac** [stoplightio/prism#379]
The new logging is already a huge improvement over Prism v2, bravo 👏!

There might be a couple small wins we could consider to improve the readability and usefulness of the logs even more.

Here is the current behavior:

<img width="1337" alt="Screen Shot 2019-06-22 at 1 54 50 PM" src="https://user-images.githubusercontent.com/847542/59967931-3182cf00-94f7-11e9-8acd-7b4bed678156.png">

What if we:

1. Use indentation to visually group related logs together. In the above screenshot the 4 highlighted lines are basically children of the line above them.
2. Use the first ID in the message (in screen above, `[MOCKER]` and `[HTTP SERVER]` is what i'm talking about) to more precisely indicate the stage of the process that is generating the log. Disclaimer: I have not gone deep on the logging implementation so I don't know how easy or not easy this would be.

The example pictured above might look more like this:

```bash
[HTTP SERVER]    ℹ  info     'GET /todos' request received.
    [ROUTER]     ✔  success  Found HTTP operation.
    [VALIDATOR]  ✔  success  The request passed the validation rules.
    [NEGOTIATOR] ✔  success  Found compatible response for 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3'.
    [MOCKER]     ✔  success  Responding with status code 200.
```

IMHO these changes would make the logs easier to understand when there is more than one request in the log stream.

**Comment by XVincentX** [comment]
A possible implementation for this could be:

1. Replace child logger labels with numbers
2. Replace the numbers with labels in the CLI
3. Indent `N` times based on the value passed in the child logger
5. Profit

**Comment by XVincentX** [comment]
@marbemac What do you think of this?

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/1416224/60170651-2c7c9300-9809-11e9-91db-0a05b493910b.png">

**Comment by pytlesk4** [comment]
> @marbemac What do you think of this?
> 
> <img alt="image" width="1550" src="https://user-images.githubusercontent.com/1416224/60170651-2c7c9300-9809-11e9-91db-0a05b493910b.png">
> 
> <img alt="image" width="991" src="https://user-images.githubusercontent.com/1416224/60184289-13cfa580-9828-11e9-87fa-a7802d5988cb.png">
> 
> Help me out with the colours people, I agree they're horrible.

😍

**Comment by marbemac** [comment]
Better!

- @pytlesk4's colors are an improvement.
- I don't think that we need to indent the HTTP SERVER under CLI
- I'd suggest 4 spaces/tabs/whatever rather than 2
- Method + URL should be outputted on the "request received" line
- Do we have to duplicate the Method + URL in the child messages?

IMHO this is the cleanest output structure that I can think of:

```
[HTTP SERVER]    ℹ  info     'GET /todos' request received.
    [ROUTER]     ✔  success  Found HTTP operation.
    [VALIDATOR]  ✔  success  The request passed the validation rules.
    [NEGOTIATOR] ✔  success  Found compatible response for 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3'.
    [MOCKER]     ✔  success  Responding with status code 200.
[HTTP SERVER]    ℹ  info     'POST /todos' request received.
    [ROUTER]     ✔  success  Found HTTP operation.
    [VALIDATOR]  ✔  success  The request passed the validation rules.
    [NEGOTIATOR] ✔  success  Found compatible response for 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3'.
    [MOCKER]     ✔  success  Responding with status code 201.
```

**Comment by XVincentX** [comment]
I do not see any colors from @pytlesk4 — 🤔

**Comment by pytlesk4** [comment]
> I do not see any colors from @pytlesk4 — 🤔

It's right there!

**Comment by XVincentX** [comment]
Yeah ok but give me a reference, a color code, RGB value, something otherwise how am I supposed to find them?

**Comment by XVincentX** [comment]
> I don't think that we need to indent the HTTP SERVER under CLI

Removed

> I'd suggest 4 spaces/tabs/whatever rather than 2 

Done

> Method + URL should be outputted on the "request received" line

Added

> Do we have to duplicate the Method + URL in the child messages?

Removed

---

@pytlesk4 Can you provide more details on the colors?

@marbemac Unfortunately I'm struggling to get the padding you're requesting (Actually it was something I tried already in the past). Apparently chalk does not play very well with padded values and signale does not have automatic padding capabilities at the moment, although there's an open pull request for it. I'll see if I can find a workaround in meantime, but I'd say let's not spend too much time, we have bigger fishes to fry right now

**Comment by philsturgeon** [comment]
🚢 🚢 🚢

**Comment by pytlesk4** [comment]
Honestly, I like the colors you have already.

**Comment by pytlesk4** [comment]
I suggest we ship this right now so that we can move forward to hit our release target. This is 1000000000 times better than Prism v2. We can always revisit.

**Comment by marbemac** [comment]
Looks great! ONE last comment, I promise :).

In the last screenshot above, it looks like the request resulted in an error, is that correct? I suggest that everything related to a request be nested underneath it, including the final error there. As it stands, it's not clear that that error is the final result of the request above it. Does that make sense?

**Comment by XVincentX** [comment]
Done in #382
