### ISSUE TITLE
Prism does not allow requests that are not application/json

### ISSUE THREAD

**Issue by LesterTheTester** [stoplightio/prism#380]
The OpenAPI spec allows us to define request bodies in different formats, such as application/x-www-form-urlencoded.  However, this line causes prism to return a 415 for any request that is sending data in anything other than application/json:

https://github.com/stoplightio/prism/blob/62c3f45c2ff9a30fcb0a12d70e7017fcf590d033/packages/http-server/src/server.ts#L39

Honestly, I don't care if prism validates my request, but in this case, it should at least return my example response instead of always 415'ing

For reference, here is a spec of my endpoint:
```
 /api/v1/validate-pin:
   post:
     description: Validate a challenge code from user's phone
    requestBody:
       required: true
      content:
        application/x-www-form-urlencoded:
             schema:
               type: object
              properties:
                challengeCode:
                   type: string
                   example: 1234
     responses:
       '200':
        headers:
          X-Authorization:
             $ref: '#/components/schemas/authorization'
          X-Entitlements:
            $ref: '#/components/schemas/entitlements'
        content:
           application/json:
             description: A successful request
             schema:
               type: object
               properties:
                userSession:
                   $ref: '#/components/schemas/userSession'
```

**Comment by XVincentX** [comment]
Hey, @LesterTheTester 

Thanks for the issue.

You're indeed correct, in this case Prism should effectively return the response you've requested. The reason why it's responding in such way it's because fundamentally right now Prism is not able to de-serialise anything that's not JSON. We definitely have plans at least for XML and www-url-formencoded though.
