### ISSUE TITLE
CORS / Same Origin Policy

### ISSUE THREAD

**Issue by vanhoofmaarten** [stoplightio/prism#392]
**Is your feature request related to a problem? Please describe.**
The usage of the mocking server in a local application is blocked by *Same Origin Policy*.

Eg. SPA running on `http://localhost:3000`, Prism running on `http://localhost:3001`. SPA tries to fetch a mocked resource from Prism but is blocked by the Same Origin Policy.

**Describe the solution you'd like**
An option to disable the *Same Origin Policy* by adding the `Access-Control-Allow-Origin, "*"` header to the used http-server.

Eg. `prism mock --same-origin=false`

**Describe alternatives you've considered**
Describe and run the mocking server programatically.

**package.json**
```json
{
  "main": "index.js",
  "scripts": {
    "start": "npm run mock",
    "watch": "npm run mock:watch",
    "mock": "node index.js --port=3001 --schema='../schemas/petstore.yml'",
    "mock:watch": "nodemon --exec npm run mock -w ../schemas/petstore.openapi.yml -w index.js",
  },
  "dependencies": {
    "@stoplight/prism-core": "^3.0.0-beta.2",
    "@stoplight/prism-http-server": "^3.0.0-beta.2",
    "minimist": "^1.2.0"
  },
  "devDependencies": {
    "nodemon": "^1.19.1"
  }
}
```

**index.js**
```js
const { createServer } = require("@stoplight/prism-http-server");
const { createLogger } = require("@stoplight/prism-core");
const minimist = require("minimist");

const { port = 3001, schema: path } = minimist(process.argv);

const server = createServer(
  { path },
  {
    config: { mock: { dynamic: true } },
    components: {
      logger: createLogger()
    }
  }
);

server.fastify.addHook("onSend", (request, reply, payload, next) => {
  reply.header("Access-Control-Allow-Origin", "*");
  next();
});

server.listen(port).then(() => {
  console.log(`🤖 Mocking server enabled on port ${port}`);
});
```

**Comment by philsturgeon** [comment]
@vanhoofmaarten thanks for the issue, it's cool to see a potential implementation and a workaround all in the same feature request. 

CORS is definitely on our radar, and was going to be tackled before v3.0 but is now bumped back to 3.0.x or 3.1 due to time constraints. Gotta get existing features stable before making new ones right? :D

I've added it to the v3.1 milestone so expect to hear more on this in a week or two.

**Comment by dinfyru** [comment]
Is there any promotion?

**Comment by philsturgeon** [comment]
Im closing this one in favour of #412.
