### ISSUE TITLE
bug: file type incorrectly detected from URL with query params

### ISSUE THREAD

**Issue by czebe** [stoplightio/prism#397]
**Describe the bug**
When loading a `spec` from an URL that has query params, the graph parser fails.

**To Reproduce**
Supply an URL with a query param (eg. token for a private repo):

```
prism mock https://raw.githubusercontent.com/{private-repo}/master/docs/api.yaml?token=XXX
```

Here: https://github.com/stoplightio/prism/blob/c62f37732a476e9b12602f87c58a29eec7492bcd/packages/core/src/utils/graphFacade.ts#L67

it evaluates to `language: 'yaml?token=XXX'` instead of `language: 'yaml'`

**Comment by philsturgeon** [comment]
Good find! We'll get this sorted out.
