### ISSUE TITLE
Request for a docker version

### ISSUE THREAD

**Issue by jacktan1991** [stoplightio/prism#4]
Other than installing in mac or windows, I want to have the same experiencing under linux platform. And docker is the best option.

**Comment by pytlesk4** [comment]
Are you having issues with installing it in Linux? I will put this in our backlog and try to get to this next week.

**Comment by jacktan1991** [comment]
no, just because I want use it when I am in Windows or Mac

**Comment by thomas-barthelemy** [comment]
@jacktan1991 Feel free to have a look at https://hub.docker.com/r/webridge/stoplight-prism/ (I'm not part of webridge anymore but I still maintain those git/docker hub repos)
@pytlesk4  feel free to fork / salvage https://github.com/thomas-barthelemy/docker-stoplight-prism

**Comment by pytlesk4** [comment]
Awesome!!!
