### ISSUE TITLE
Prism Webinar

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#404]
**Chore summary**
Prism Webinar

**Tasks**
- [ ] develop script for webinar
- [ ] someone from engineering to review (maybe @XVincentX ?)

**Additional context**
Add any other context about the chore here.

**Comment by XVincentX** [comment]
Pinged Justin to settle down on a date

**Comment by tbarn** [comment]
Posting this as a new issue to pin (like we did for Spectral) and closing this one since the plan for it has been worked out.
