### ISSUE TITLE
Prism Blog Post 

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#406]
**Chore summary**
Prism Blog Post 
**Tasks**
- [ ] Need to do this
- [ ] And do that

**Additional context**
Add any other context about the chore here.

**Comment by XVincentX** [comment]
I gave it another round and changed some small things, but I think the text is almost completed.

**Comment by philsturgeon** [comment]
How's this one coming along? I saw a draft that looks great, can we schedule the post and close the issue?

**Comment by XVincentX** [comment]
I'm good with the text; unless Taylor wants to suggest some other changes, I consider this done.

**Comment by tbarn** [comment]
This wasn't something assigned to me, but I'm happy to take a look if someone sends it to me.

**Comment by philsturgeon** [comment]
Taylor this was a duplicate from our Jira to ZenHub/GitHub migration. You had the equivalent Jira story assigned and this was just floating about afterwards. :)

--
Phil Sturgeon
@philsturgeon

**Comment by tbarn** [comment]
Uhhh, not seeing that in Jira. Only Vincenzo, also in the release plan. Maybe you got it confused with Spectral?

**Comment by philsturgeon** [comment]
I do do that, sorry. Ok. All on Vincenzo!

--
Phil Sturgeon
@philsturgeon
