### ISSUE TITLE
Public JS API Improvements

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#407]
Prism currently depends on Graphite, which is public only because it has to be. We'd like to make that private again, and free Prism from its Graphite reliance. 

**Background**

There was interest in removing the loader, but now that we are about to release v3.0 we cannot just rip it out. Let’s add an other way to do things, which supports passing in an array of http-spec objects, and keep the loader in place as a convenience method. 

We can deprecate it later and remove, but we do not need to make decisions about that now.

This is a great chance for us to make a new and improved `createInstance` function in the core factory. Our instance has a whole lot of options, and if anyone has ideas on how to make it a little nicer for actual end users, now would be the time. Maybe we can seek inspiration from other mocking tools, or other popular TypeScript pacakges.

**Details**

1. prism reads the target openapi file itself
2. prism calls `@stoplight/json` or `@stoplight/yaml` parse to parse file contents
3. prism passes parsed content into `@stoplight/json-ref-resolver` to create a resolved version
4. prism passes that resolved version into `@stoplight/http-spec` transformOperations func to get a list of IHttpOperation objects

**Comment by XVincentX** [comment]
Note: as part of the improvement, make sure to display a nice error message in case the target file or URL fails the fetching operation.

**Comment by chris-miaskowski** [comment]
Comment on the implementation details @XVincentX . If we're removing the whole loading logic from Graphite we should wrap it up nicely in a lib so that UI utils like Request Maker don't have to repeat the same code.

**Comment by philsturgeon** [comment]
Removing Graphite was only one aspect of this, we were going to improve the JS API in general, not _just_ remove Graphite.

**Comment by XVincentX** [comment]
Ok, but in that case the issue is lacking the details.

**Comment by philsturgeon** [comment]
I'll start a new issue with specific implementation ideas. Leaving it open ended didn't work out.
