### ISSUE TITLE
Test Harness: OAS2/3 Body Param Validation

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#408]
**User Story**

As a developer I want to have confidence that Prism's validates request payload (body).

**ACs**
- add test cases to test harness
- add at least the cases described in the examples section- 
- if any of the test fails then mark that it is an invalid result (e.g. mark as skipped) and report a Jira bug
- link that bug to this card 
- Make sure to add the actual tests to TestRails

**Additional resources**

https://stoplightio.atlassian.net/wiki/spaces/EN/pages/52887637/Prism#Prism-MockServerFeatures (please find relevant row)

**Stuff to test oas2/oas3**
- [x] required x-www-form-urlencoded param
- [x] required x-www-form-urlencoded body
- [x] required application/json body
- [x] invalid form-data type 
- [x] invalid `enum`
- [x] form-data array (csv, pipes, multi)
- [x] form-data formats (e.g. byte)
- [x] allowEmptyValue

**oas3 related**
- [x] form-data + schema
- [ ] encoding/contentType
- [ ] encoding/headers
- [ ] encoding/allowReserved
- [ ] encoding/style
- [ ] encoding/explode

**Not in scope**

multipart/form-data

**Example tests**

Given there is an operation, that can consume requests of Content-Type CTAnd it is required that the payload has X fieldWhen I send a POST request (with Content-Type of CT) to this operationAnd the request doesn't have his X required field in the payloadThen I should get back a 400 response back

Given there is an operation, that can consume requests of Content-Type CTAnd it is required that the payload provides X fieldWhen I send a POST request (with Content-Type of CT) to this operationAnd the request does have this X required fieldThen I should get back a 2xx response back

Given there is an operation, that can consume requests of Content-Type CTAnd the operation has no required field for the payloadWhen I send a POST request (with Content-Type of CT) to this operationThen I should get back a 2xx response back

When I send a POST request (with Content-Type of CT) to an operationAnd this operation does not consume requests of Content-Type CTThen I should get back a 415 response back

**Example Specs**

**Open API 2**

Consider this rather minimal oas2 spec. It has

- POST /path operation
    - that operation takes a body
    - that body is application/json (see consumes)
    - that body requires 'x' param of string type
- PUT /path operation
   - that operation takes body
   - that body is of formData type
   - it has a required X field that can take only one of the values "one" or "two"

This is just an example.
```
swagger: '2.0'
info:
  title: Open API 2 Sink
  version: '1.0'
host: 'localhost:3000'
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /path:
    post:
      summary: create path
      tags: []
      responses: {}
      parameters:
        - in: body
          schema:
            type: object
            properties:
              x:
                type: string
            required:
              - x
    put:
      summary: update
      tags: []
      responses: {}
      parameters:
        - in: formData
          type: string
          name: x
          required: true
          description: ''
          enum:
            - one
            - two
definitions: {}
```
**Open API 3 **

Similarly to the previous example here is OAS3 (note the difference in formData)
```
openapi: 3.0.0
info:
  title: Open API 3 Sink
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /path:
    post:
      summary: create
      tags: []
      responses: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                x:
                  type: string
              required:
                - x
    put:
      summary: update
      tags: []
      responses: {}
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object,
              properties:
                  name:
                    description: Updated name of the pet
                    type: string
                  status:
                    description: Updated status of the pet,
                    type: string
              required:
                - status
components:
  schemas: {}
```

**Comment by chris-miaskowski** [comment]
@philsturgeon I updated the ACs following up my read up on OAS3

**Comment by philsturgeon** [comment]
OpenAPI not Open API :p

**Comment by philsturgeon** [comment]
This can progress without full support of encoding btw, I went years without even knowing that thing exists and I've never seen it in the wild. We seem to have issues created for each bit that Prism doesn't already support, so let's crack on with this PR and add coverage to what we do have.
