### ISSUE TITLE
Test Harness: Default Responses

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#413]
**User Story**

As a developer I want to get back a default response when no other response codes can be returned.

**ACs**
- add test cases to test harness
- add at least the cases described in the examples section
- if any of the test fails then mark that it is an invalid result (e.g. mark as skipped) and report a Jira bug
- link that bug to this card 
- Make sure to add the actual tests to TestRails

**Additional resources**

https://stoplightio.atlassian.net/wiki/spaces/EN/pages/52887637/Prism#Prism-MockServerFeatures (please find relevant row)

**Example tests**

When I send a request to an operation
And this operation is defined
And this operation has only a default response defined
Then I should get back the default response

When I send a request to an operation
And I force the response by adding __code to the path (ie http://localhost:4010/pets/123?__code=200)
And this operation has no response with such code defined
And this operation has a default response defined
Then I should get back the default response

When I send a request to an operation
And I force the response by adding __code to the path (ie http://localhost:4010/pets/123?__code=200)
And this operation has no response with such code defined
And this operation does not have default response defined
Then I should get back a response with 500 status code
And the response's payload should describe the error

When I send a request to an operation
And this operation has no response with a matching status code
And this operation does not have default response defined
Then I should get back a response with 500 status code
And the response's payload should describe the error

When I send a request to an operation
And in the path I specify ?_code=some-code (ie ?_code=200)
And the operation has such status code response defined
Then I get back a response with a status code of 200

When I send a request to an operation
And that operation has any 2xx defined
And the request was valid
Then I get back the lowest 2xx response (e.g. if 204 and 210 are defined, return 204)

When I send a request to an operation
And in the path I specify ?_code=404
And the operation has no 404 status code response defined
And the operation has 400 status code defined, but no schema or example defined in the response
Then I get back a response with a blank body with Content-Type of text/plain

When I send a request to an operation
And in the path I specify ?_code=404
And the operation has 404 status code response defined
And in this operation there is no schema or example defined in the response
Then I get back a response with Content-Type of application/json

**Comment by XVincentX** [comment]
Blocked on product decision.

**Comment by philsturgeon** [comment]
@XVincentX could you add context to what decion is blocking so folks know what’s up when they read this? I don’t remember myself. If this is the lowest 400 thing then could you mention that?

**Comment by XVincentX** [comment]
@philsturgeon Comment updated.

**Comment by philsturgeon** [comment]
Cool thanks! 

It should not look for the lowest 4xx in the series. There’s some rules around “a client should treat an unknown 4xx as a 400” in the spec but there’s no presidency for fishing out the lowest 407 or 401 because somebody requested a 418 and it wasn’t there. If our code currently does that please kill it off. Thanks for giving me some time to think about this one.

**Comment by XVincentX** [comment]
@philsturgeon So are you ok with getting an error saying "such response is not defined"? (look the last two examples)

**Comment by philsturgeon** [comment]
2nd to last can be deleted and the last one would be almost exactly the same as requesting a non existent  example

**Comment by XVincentX** [comment]
@philsturgeon I'm not completely sure I understand. Shall I remove all the test files for this?

**Comment by philsturgeon** [comment]
Sorry that was my fault for using confusing English: I meant specifically 

When I send a request to an operation
And in the path I specify ?_code=404
And the operation has no 404 status code response defined
And the operation has 400 status code defined, but no schema or example defined in the response
Then I get back a response with a blank body with Content-Type of text/plain

“2nd to last” should have been “second from the bottom”

**Comment by XVincentX** [comment]
Got it — agree and removed. We're good!
