### ISSUE TITLE
Minimal GET request fails with 406

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#418]
**Branch**

https://github.com/stoplightio/prism/tree/bug/so-265/inconsistent-content-negotiation

**How to reproduce**

Given the following spec file
```
{
  "openapi": "3.0.0",
  "paths": {
    "/pet": {
      "get": {
        "responses": {
          "200": {}
        }
      }
    }
  }
}
```
When

`curl -X GET localhost:4010/pet `

I expect to get 200 response with an empty body

**Actual**

{"type":"https://stoplight.io/prism/errors#NOT_ACCEPTABLE","title":"The server cannot produce a representation for your accept header","status":406,"detail":"Could not find any content that satisfies /"}

**Notes**

Reproduced locally running `yarn cli mock ...` in the `cli` package.

Integration test passes though... https://github.com/stoplightio/prism/blob/57fd3c559df93cd8fc3664ea566ab5f79997b204/packages/http-server/src/__tests__/server.oas.spec.ts#L32

**Workaround**

This schema works
```
{
  "openapi": "3.0.0",
  "paths": {
    "/pet": {
      "get": {
        "responses": {
          "200": {
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
```
Debugging results

when called from the CLI

the 'contents' array of the resource returned by Graphite is empty and therefore this line of code fails to match a content

the media type is `*/*` (`curl` adds accept header!)

given the explicit media type we FAIL if we can't find it 

when called from the integration test

the media type is 'undefined'

when media type is undefined we try to negotiate default content, but if contents are empty we return empty response (https://github.com/stoplightio/prism/blob/fa52a389e837a3837559ad6f0ff4b61f1f1c4f98/packages/http/src/mocker/negotiator/NegotiatorHelpers.ts#L144)

**Conclusions**

Prism's behaviour varies depending on whether we provide Accept header or not.If we do, then we fail if such content can't be found (I think this is correct and expected)If we don't (provide Accept header) we either return default content (default media type) OR if no content is found we return empty message (which I think is fine too...)

All in all this can actually be a feature depending how one looks at it... The problem is that curl adds */* Accept header by default.

**Comment by brianmrock** [comment]
Jira Comments 


Vincenzo Chianese
June 13, 2019, 6:58 AM

Very nice report Chris Miaskowski! Thanks for the investigation.

 

We can fix this in two ways:

Graphite should generate a */* default content, so that we can always respond correctly. Prism would not need any modification.

Prism shall consider a */* requested media type as a case where return an empty response in case there are no responses defined.

 

My gut says we should go with the latter — I guess for documentation and other purposes where Graphite is employed you do not really want to show a fake content that does not really exists, right?

 

Marc MacLeod Phil Sturgeon 

 


Phil Sturgeon
June 13, 2019, 7:48 AM

Im getting a bit confused when I read the report because it keeps saying “the media type is” but there are loads of media types in question. Is it the media type mentioned in Accept or Content-Type, is it a media type defined in a spec or somewhere else, is it one we’re hunting for to try and provide a default or something else.

We are dealing with very confusion scenarios here so being specific with our wording will hopefully make it easier to follow problems.   


Vincenzo Chianese
June 13, 2019, 7:53 AM

Media Type defined in the Accept header

The response does not have any content type defined

 


Phil Sturgeon
June 13, 2019, 7:59 AM

Ok and it looks like somebody is suggesting curl is adding 

 

Accept: */*
I don’t think thats possible, and it certainly should not work. If somebody is asking for a literal star/star they should get a 406 error yes.

It’s more likely our code is triggering this failure in its attempts to find a 406 response to show. Remember that star/star is just an OpenAPI thing, similar to the HTTP status “default” 


Vincenzo Chianese
June 13, 2019, 8:14 AM


Phil Sturgeon What do you mean it’s not possible? I just tried with curl and it’s effectively adding such header by default.


Phil Sturgeon
June 13, 2019, 8:23 AM

Vincenzo Chianese oh absolutely yeah, if you literally instruct curl to send MONKIES it will send MONKIES but that0’s not what I mean. It’s impossible for a wild Accept: star / star to appear out of nowhere, like the stories says. 

The problem is that curl adds */* Accept header by default.

Curl does not do that. It is probably coming from us somewhere in code.


Vincenzo Chianese
June 13, 2019, 8:27 AM

Phil Sturgeon Ehm no. Are we talking about the same thing?

 

You can see from the image above the sent headers — it added Accept:*/* on his own.

 

https://stackoverflow.com/questions/18183467/send-a-curl-request-with-no-accept-header


Phil Sturgeon
June 13, 2019, 8:47 AM

AGGGH WTF. That is so weird. Sorry Chris you were right. I had no idea curl CLI does this, and did not even know that was allowed, but the HTTP RFC does confirm:

     Accept = #( media-range [ accept-params ] )

     media-range    = ( "*/*"
                      / ( type "/" "*" )
                      / ( type "/" subtype )
                      ) *( OWS ";" OWS parameter )
     accept-params  = weight *( accept-ext )
     accept-ext = OWS ";" OWS token [ "=" ( token / quoted-string ) ]
So stars could appear in place or the type, and or the subtype.

I guess we just have to look out for stars and make sure our content negotiation is working accordingly. 

So if they request a star / star they get literally the first content type defined for whatever status we decide they’re getting. 

If they ask for application/* then they get the first one that matches that, from whatever status we’ve decided they’re getting. 

 

 


Phil Sturgeon
June 13, 2019, 8:48 AM

Can everyone double check the content negotiation chunk of that RFC and make sure im not missing anything else? 


Marc MacLeod
June 13, 2019, 2:00 PM

Weirdly enough, we might be able to use a simple glob matcher to handle the matching? Yes globs have many more features than the RFC, but I think? it’s a superset of features, so might cover the prism use cases. Have not dug into it deeply though - alternative we could look for a more purpose built solution or build our own.

Btw, I understand the “purity” of requiring the consumer to supply an accept header if there is no default response defined, but I’m not sure it’s the best DX? I suggest we default to */* so that the user is not forced to set accept header for the basic case. Thoughts?


Phil Sturgeon
June 14, 2019, 9:36 AM

Marc MacLeod hey! Fear not we do not require the Accept header. 

If no accept header is sent we look for */* and if there is no sign of that we default to application/json because the HTTP spec says we are allowed to pìck a default and that's what most people are using anyway.

Could you elaborate on the glob matcher idea? I don’t follow.

**Comment by XVincentX** [comment]
I was incorrect, this issue has been fixed.

![image.png](https://images.zenhubusercontent.com/5d204af0f96854554f62e173/806f1087-ee19-49a1-8553-793e85b3d65f)
