### ISSUE TITLE
Prism does not take the "required" property into account when validating body param

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#419]
Prerequisites
```
{
  "swagger": "2.0",
  "paths": {
    "/pet": {
      "get": {
        "produces": ["application/json"],
        "consumes": ["application/json"],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": false,
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer",
                  "format": "int64"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}
```
**Steps to reproduce**

1. Start prism with the provided endpoint2. `curl -X POST http://127.0.0.1:4010/pet`3. Observe output

**Expected**

Should return 200 and a lorem ipsum response

**Actual**

Returns an error

`{"type":"https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY","title":"Invalid request body payload","status":422,"detail":"Your request body is not valid: [{\"path\":[\"body\"],\"code\":\"type\",\"message\":\"should be object\",\"severity\":0}]"}`

**Context**

We currently don't check the required field when validating body. The proposed solutions is that `HttpBodyValidator ` should extend `HttpParamsValidator` class.

**Comment by XVincentX** [comment]
Confirmed. This is happening because the `body` schema in content is not a regular JSON Schema and needs to be transformed as well.
