### ISSUE TITLE
Test Harness: Security Scheme Validation

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#422]
**User Story**

As a Prism CLI user, I want to secure my endpoints, so that I know the API is only used by authorized users.

**ACs**

add test cases to test harness

add at least the cases described in the examples section

if any of the test fails then mark that it is an invalid result (e.g. mark as skipped) and report a Jira bug

link that bug to this card 

Make sure to add the actual tests to TestRails

**Additional resources**

https://stoplightio.atlassian.net/wiki/spaces/EN/pages/52887637/Prism#Prism-MockServerFeatures (please find relevant row)

When operations have security schemes, how do they respond when no authentication information is being sent?

 

Try and write tests for every single authentication scheme in OpenAPI 2/3, and write tests for every different location those schemes security information can be in. 

API Key in header

API key in query

API key in cookie (ugh why)

HTTP in Header

HTTP in query…

etc

Try all OpenAPI v2 specs against Prism v2 to get a general idea for how it is meant to work, then try that stuff in Prism v3. 

**Acceptance Criteria and Scope**

Prism should throw errors if security criteria are not matched

If Prism does not respond the way it should (based on v2 or common sense) create a story for investigation and move on

### Example tests

Given a spec has no global security scheme
And an operation has no security requirements defined
When I send a request to this operation
Then I get a response with 200 status code

Given a spec has a global security scheme
And an operation has no security requirements defined
When I send a request to this operation
And I don't include any credentials in the request
Then I get back a response with 401 status code
And the response should have WWW-Authenticate header

Given a spec has multiple global security schemes
And an operation has no security requirements defined
When I send a request to this operation
And I don't include any credentials in the request
Then I get back a response with 401 status code
And the response should have WWW-Authenticate header

Given a spec has multiple global security schemes
And an operation has no security requirements defined
When I send a request to this operation
And I include valid credentials for one of the global security schemes
Then I get back a response with 200 status code

Given a spec has multiple global security schemes
And an operation has no security requirements defined
When I send a request to this operation
And I include invalid credentials for one of the global security schemes
Then I get back a response with 403 status code

Given a spec has one or multiple global security schemes
And an operation defines its security requirements by specifying one of the security schemes
And I send a request to this operation
And I include invalid credentials for this operation security requirements
Then I get back a response with 403 status code

Given a spec has one or multiple global security schemes
And an operation overrides the global security scheme by overwriting them (making the operation not secured, having its security requirements as [])
And I send a request to this operation
And I don't include any credentials in the request
Then I get back a response with 200 status code

**Comment by XVincentX** [comment]
@lag-of-death keep in mind Prism does not have these capabilities *at all* right now, so all these tests will fail.

**Comment by philsturgeon** [comment]
Probably best to copy these into the actual story for security validation like I did with CORS so it can be done as part of the implementation. That way we don’t need two tickets for one feature. :)

**Comment by philsturgeon** [comment]
This work is being done in #484.
