### ISSUE TITLE
Record Mode

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#423]
There are [a few tools and methods](https://apisyouwonthate.com/blog/creating-api-specifications-from-bullst) out there which help users generate API description documents from actual traffic/json running through a system. This is not an ideal workflow, but a handy crutch for getting old systems caught up with the new systems which are design-first. 

### Approach A: CLI only

Prism CLI now got a proxy server in v3.2, and this gives us a chance to snoop on traffic. By adding a new `--record` switch, we can enable a special RecordService which will convert any requests and responses, along with all headers, status codes, etc. into [http-spec operations](https://github.com/stoplightio/http-spec/blob/master/src/oas3/operation.ts).

All learning should be an upsert of whatever is there when the server is started, instead of just replacing them. For example, a request with `"foo": "bar"` and then `"foo": 123` should be writing oneOf's to support both those types, and not just replacing with whichever came in second. 

When the server is closed, show various chunks of a potential diff we'd like to apply, and ask y/n for each chunk of diff to see if it is ok. 

Pros:
- Doing it all in Prism means fewer moving parts, and only one team on the task
- Updates the exact file being worked on by that dev, and they can then commit it, no confusion about switching to a web app

Cons:
- Adds a fair bit of complexity to Prism, which is going to need to know how to merge and write back changes to the file. If we are applying a diff we need to know how to create that diff, and if we do anything else we have to make sure we arent messing up any formatting or making unintended changes to their file

### Approach B: Record Requests via Stoplight.io

Prism CLI could have a `--report-traffic` switch which defaults to sending proxy traffic back to stoplight. Assuming you have an account set up (we'll need to figure out `prism login` like v2 had) it can report traffic back to us, and we save them as general "requests". Adding "prism-cli" as one more source of traffic to a more generic requests database means we can do quite a lot of things. 

**Contract Testing** 

We noticed a discrepancy in your descriptions vs reality, would you like to panic? Where should we send these alerts? 

**Improvements in Studio**

Studio offers improvement suggestions for various nodes and models: "Add this to xyz api" which would turn it into an openapi 2/3 operation object and add it to the file. or "add this to xyz requests file" which would basically add it to the equivalent of a postman file. This starts to get the original "learning" feature we have in classic.

Pros:
- a larger general intelligence system will make for more robust learning, which can be useful for studio and explorer users, and everyone who is sending traffic via Try it Now, etc as well as prism users
- Will work with OpenAPI v2, v3, if we add RAML, etc.

Cons: 
- Requires a stoplight account instead of being CLI only
- Experience is a little odd due to larger feedback loop: do a thing in CLI, go to web view, etc.

**Comment by transitive-bullshit** [comment]
https://github.com/opticdev/shape-hash could be useful here.

I'm interested in using this for [Saasify](https://github.com/saasify-sh/saasify) btw.

Keep up the great work! 😄

**Comment by philsturgeon** [comment]
This is happening but this isn't where we plan it. Moving a lot of the logic higher up into http-spec and other parts of the ecosystem, which will mean this can be done far easier in Prism.
