### ISSUE TITLE
Prism : Run test harness on macOS

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#427]
While we were working on the feature matrix it was useful to know how v2 and v3 differed, but ongoing it will be rather confusing running v3 tests against v2, as we are going to add new functionality which v2 didn’t do, and tryig to figure out which tests should run against which versions is going to be confusing.

Let’s focus on hardening Prism v3 with this great new e2e test suite, and get it running on macOS, not just linux. (Windows will be another job, circleci does not support it.

**Comment by brianmrock** [comment]
Vincenzo Chianese
June 19, 2019, 5:12 AM

Brian Rock for your information:

CircleCI does not support Windows, we are going to need Azure Pipelines

CircleCI supports MacOS only on paid plans.


Phil Sturgeon
June 21, 2019, 9:17 AM

Vincenzo Chianese we are hardly using our OS X plan at the moment so it should be fine. 


 


Vincenzo Chianese
June 21, 2019, 9:22 AM

Hmm then there’s something wrong with Prism’s CircleCI configuration; probably it has been put as a OSS project so it can’t benefit from the paid features?


Vincenzo Chianese
June 28, 2019, 8:29 AM

Collin Bachi Brian Rock Can I check if Prism is on the free plan and if so, move it to the paid plan so we can use MacOS? It’s probably going to cost some money or keep a container busy, so I want to triple check.

 


Collin Bachi
June 28, 2019, 9:18 AM

Can you configure it so only the needed job runs on OSX? That 500 minutes will run out fast--the only reason it’s so low is because we haven’t been building Studio on there.

 


Vincenzo Chianese
June 28, 2019, 9:22 AM

Collin Bachi …or I could offload this to Azure DevOps, they support MacOs and it’d be free?


Collin Bachi
June 28, 2019, 10:11 AM

Sounds good

**Comment by XVincentX** [comment]
Closed in #442
