### ISSUE TITLE
Contract Validation

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#429]
**User Story**

As a user of the Prism HTTP Client (#511) I have been building an entire end-to-end testing system  which uses Prism as a HTTP client, and I would love to enable contract testing against a provided API description document. 

**Details**

Contract violations for Prism would be a case of getting a HTTP response, and checking several things:

_Requests_

1. Are provided parameters (headers, query, path, etc) valid? Error
1. Is the response mime type defined in the document? Error
1. Is the body valid to the contents of `schema`

_Responses_

1. Is response status code specified in the document? This could be a warning if 300-599, but an error if 200-299.
1. Is the response mime type defined in the document? This could be an error
1. Is the body valid to the contents of `schema`

All of these things could trigger a `DiagnosticSeverity`, just like request validation, because this is exactly the same concept as request validation. Some of the logic from validation could be refactored into a new `contract-violations` folder, and we just make some "request validation" code which turns contract violations into HTTP problems.

**Why?**

Various aspects of our system care about knowing if the client matches against a real OpenAPI description document: 

- Prism HTTP Server
- Prism CLI
- Request Maker (Violation/Warning Component)
- Future Governance / Compliance Reports

All of this functionality will originate in Prism as a HTTP client. Contract violations can bubbled up to logs in Prism CLI, and request maker can store Violations in a "Store" for the Violations component to read from.

**Acceptance Criteria**
- Unit testing of new functionality at 85%
- Prism HTTP Client reports violations for real HTTP requests and responses when description doc is provided
- Prism HTTP Client reports violations for mock server requests
- Prism CLI logs warnings for any contract violation (and tested in test harness)
- Prism HTTP mock server continues to convert violations to HTTP Problems
- ~Integration testing showing warnings are being logged~

**Additional Context**

Blocked by #511

**Comment by philsturgeon** [comment]
@nhuray hey, great question. For now I recommend avoiding things like Dredd, that's more for checking the documentation you wrote is correct, than for checking your code matches your description document. To do that, here's an article: https://apisyouwonthate.com/blog/writing-documentation-via-contract-testing
