### ISSUE TITLE
Multipart Data and Files

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#432]
**User Story**

As a Prism mock server user trying to integrate another teams API into my client application, I would like to make sure I am uploading files and sending multipart data properly, because it is very confusing stuff. Prism should tell me if I am sending things correctly, [according to the spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#considerations-for-file-uploads).

**Acceptance Criteria**

- Uploading files according to the OpenAPI specification, and according to the API description document works

- Uploading files with the wrong name will fail like any other request validation

- multipart/formdata works a lot like application/x-www-form-encoded

**Comment by HenriqueMedina** [comment]
Hello There, 
I know you're not prioritizing support for `multipart/form-data` and `application/octet-stream`. 
But, I'd like to know if you have any plans to deliver that story?
@XVincentX

**Comment by philsturgeon** [comment]
Yeah we've got some ideas around multipart and the new contentEncoding and contentMediaType too, but we're going to move the planning for it over to our internal feature roadmap thingy for now.

**Comment by simoami** [comment]
@philsturgeon For some of us, just remember that we have recommended stoplight and prism for some clients and they came back asking how to mock requests with file uploads. Saying "you can't" is tough because we recommended the tool for mocking. This forces us to look for alternatives because finding solutions is what we do.

**Comment by philsturgeon** [comment]
@simoami I do understand that, but no open source software does 100% of what everyone wants. It only does what is popularly requested, or what has been sent in as a pull request by users with specific requirements. 

This is not popularly requested, so are you going to be the user who does the work to solve your specific requirements?

**Comment by simoami** [comment]
@philsturgeon Thanks for the opinion and I do appreciate building a great solution for the open api specs. I'm just sharing my outsider's experience in the hope that it can make a difference in your prioritization. Keep up the good work.
