### ISSUE TITLE
Custom Mocking with Middlewares

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#435]
Leveraging Fastify middleware, Prism users should be able to register middlewares via some form of configuration / CLI option, which allows them to programatically alter responses based on various inputs and their own logic.

**Comment by okv** [comment]
Hello there.
Any updates on this?
That would be very useful to have ability to modify responses (for filtering, etc).

**Comment by philsturgeon** [comment]
@okv thanks for checking in. Now that we use GitHub as our issue tracker for open source projects, you'll see any updates that happen on here. If a PR is started, it'll show up. If comments on how the implementation is gonna start to look happen, it'll show up. 

Now that you've commented you should get any of those updates via email. For anyone else looking at this, click that subscribe button and you'll get em too. 

If interested in timeframe, this is not going to be worked on for v3.1, which is focusing on paying down tech debt and stabilizing the JS API so we can remove the "experimental" flag and get it under SemVer like the rest of Prism.

v3.1 is slated for end of August, and hopefully this feature will make it into v3.1 which will probably be a month or two after that. 

If anyone wants to take this on (maybe you work for a company who needs mocking and want customizable functionality) raise your hand and we can figure out how you can get it done OSS style! :D

**Comment by okv** [comment]
ok, thanks for the detailed explanation.
I'm writing a lot of node.js code (commercial and opensouce) and interested in custom mocking. So if you provide some ideas and implementation points in project source code, I can take a look at that =)

**Comment by yingan-rival** [comment]
I am not sure if this would help with my use case, but feels very related.

Here is an example of my use case. I need to make 2 separate API requests (Request_A and Request_B) in one transaction, and I am expecting one field (x) in the response A will have the same value as the field (y) in the response B. 

I can't find a way to use Prism to achieve that, I am expecting the custom mocking would help.

**Comment by vanhoofmaarten** [comment]
It's already possible to leverage Fastify's [hooks](https://github.com/fastify/fastify/blob/master/docs/Hooks.md) when using Prism programmatically.

Below an example I use in one of my projects which has some custom use cases.

#### Tree-structure

```sh
.
├── data
│   ├── article.html
│   ├── man-getting-bit-by-alligator.mp3
│   └── photo.jpeg
│
├── hooks
│   ├── articles.js
│   ├── files.js
│   └── index.js
│
└── server.js
```


<details>
<summary>server.js</summary>
<p>

```js
const getHttpOperations = require("@stoplight/prism-cli/dist/util/getHttpOperations").default;
const path = require("path");
const { createServer } = require("@stoplight/prism-http-server");
const { createLogger } = require("@stoplight/prism-core");
const minimist = require("minimist");

const hooks = require("./hooks");

const { host = "localhost", port = 3001, schemaPath } = minimist(process.argv);
const config = { cors: true, mock: { dynamic: true } };
const components = {
  logger: createLogger("MOCK SERVER")
};

module.exports = async () => {
  const operations = await getHttpOperations(
    path.resolve(__dirname, "..", schemaPath)
  );

  const instance = createServer(operations, { config, components });

  Object.values(hooks).forEach(async ({ type, handler }) =>
    instance.fastify.addHook(type, (request, reply, payload) =>
      handler(request, reply, payload)
    )
  );

  instance.listen(port, host).then(() => {
    console.log(`🤖 - OpenAPI mocking server enabled on port ${port}`);
  });
};
```
</p>
</details>

<details>
<summary>/hooks/index.js</summary>
<p>

```js
const article = require("./articles");
const files = require("./files");

const hooks = { article, files };

module.exports = Object.keys(hooks).reduce((acc, key) => {
  const { type, path, handler } = hooks[key];

  return {
    ...acc,
    [key]: {
      type,
      path,
      handler: async (request, reply, payload) => {
        if (!path.test(request.params["*"])) return;
        return typeof payload === "string"
          ? handler(request, reply, payload)
          : handler(request, reply);
      }
    }
  };
}, {});
```
</p>
</details>


<details>
<summary>/hooks/articles.js</summary>
<p>

```js
const fs = require("fs");
const path = require("path");
const { minify: htmlMinifier } = require("html-minifier");

module.exports = {
  type: "onSend",
  path: /\/articles\/\d/,
  handler: async (request, reply, payload) => {
    const oldPayload = payload ? JSON.parse(payload) : {};
    const newPayload = { ...oldPayload };
    const htmlPath = path.resolve(
      __dirname,
      "../data/article.html"
    );
    const html = fs.readFileSync(htmlPath, "utf8");
    newPayload.content = htmlMinifier(html, {
      collapseWhitespace: true,
      preserveLineBreaks: false
    });
    return JSON.stringify(newPayload);
  }
};
```
</p>
</details>

<details>
<summary>/hooks/files.js</summary>
<p>

```js
const fs = require("fs");
const path = require("path");

const getStream = urlPath => {
  switch (true) {
    case /\/audio/.test(urlPath):
      return {
        type: "audio/mpeg",
        stream: fs.createReadStream(
          path.resolve(__dirname, "../data/man-getting-bit-by-alligator.mp3")
        )
      };
    case /\/image/.test(urlPath):
      return {
        type: "image/jpg",
        stream: fs.createReadStream(
          path.resolve(__dirname, "../data/photo.jpeg")
        )
      };
    default:
      return { type: "plain/txt", stream: "This is a plain text file" };
  }
};

module.exports = {
  type: "onRequest",
  path: /\/files\/.+/,
  handler: async (request, reply) =>
    new Promise(resolve => {
      const urlPath = request.params["*"];
      const { type, stream } = getStream(urlPath);
      reply.type(type);
      reply.send(stream);
      reply.res.once("finish", () => resolve());
    })
};
```
</p>
</details>

<br/>

```sh
# Run in CLI with:
node server.js
```

Does this answer your question?

---

The **downside** of this approach is that there's no definition of this custom mocking approach present in the OpenAPI scheme. This could create opaqueness between project teams, eg. the back end and the front end team.

That's one of the reasons why I opened #394, so that custom extensions and formats are defined in the project's OpenAPI definition.

**Comment by yingan-rival** [comment]
Thanks @vanhoofmaarten, that's very helpful, and I think it could help with my use case. Another downside is that we need to write custom node js code for that, which is not as convenient as configuration in the OpenAPI schema or some type of Prism configuration being described in this open issue. I am looking forward to the release of #394

**Comment by rich-rival** [comment]
@philsturgeon is this issue likely to make it into a sprint any time soon?

**Comment by philsturgeon** [comment]
Thanks for all the feedback everyone. This is something I really want to see happen, but I also think we can continue to solve much of the use-cases that people would leverage customization to solve, by providing first class features that solve the problem properly instead. 

The first would be object persistence, starting off by using values from the request for the response, and then adding datastore support for something like SQLite to persist between requests. 

If you'd like that, please [vote on the roadmap](https://roadmap.stoplight.io/c/50-persisted-mock-data) for this feature, and we can then devote resources based on how the votes turn out. 

Seeing as this is an open-source project, if anyone wants to take a swing at this and send a PR, I am always happy to discuss it with them! Our team is cranking away hard on all sorts of features, and if you need it sooner then I'd really appreciate the help in making that happen, and I'm happy to offer [tree donations](https://ecologi.com/philsturgeon) as a bribe to any contributors. 🌱 🙌
