### ISSUE TITLE
Implement Troll Mode in Prism

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#437]
**Chore summary**
Prism's logging system is too polite. If the user makes a wrong request, we have to punish them somehow.

Ask Vincenzo or Tom for inspiration on the messages to output. They've got a lot of material

**Tasks**
- [ ] Need to do this
- [ ] And do that

**Additional context**
Add any other context about the chore here.

**Comment by philsturgeon** [comment]
:trollface:
