### ISSUE TITLE
Create a chart for all of the config flow cases

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#439]
Request comes in, user asks for 200, does 200 exist? Yes -> this happens, no -> this happens. Etc.

Generate a diagram (for public consumption) of the data flow of requests coming into the mock (prism) server.  Flow chart like with the various paths.

**Comment by XVincentX** [comment]
I think we have this already @philsturgeon @chris-miaskowski , right?

**Comment by XVincentX** [comment]
https://github.com/stoplightio/prism/blob/master/packages/http/docs/images/mock-server-dfd.png

**Comment by judgej** [comment]
Cool, very useful :-)

Next question: is the source for this diagram available? I'm hoping there is a Graph Markup Language (graphml) or similar source that I can use.

**Comment by XVincentX** [comment]
@judgej I _think_ @chris-miaskowski has the sources somewhere

**Comment by philsturgeon** [comment]
It’s lucid chart not makeup based. Those are great for prototyping and “sketching” but for this sort of diagram you usually end up needing to use a more visual tool for something pretty enough to put in front of users. 

--
Phil Sturgeon
@philsturgeon
