### ISSUE TITLE
XML Keyword Support

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/prism#456]
**User story.**
As a OpenAPI v3.0 user I can use the `xml` keyword in all its glory, to support wrapped arrays, namespaces, prefixes, and everything else outlined in [Representing XML](https://swagger.io/docs/specification/data-models/representing-xml/).

**Is your feature request related to a problem?**
Prism is currently very JSON-centric and we should widen support for folks who use OpenAPI to describe XML APIs. 

**Describe the solution you'd like**

See if OpenAPI Sampler can handle [the `xml`openapi object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#xmlObject), and if not, look into adding support to it.

**Comment by chohmann** [comment]
@philsturgeon going through to try to get a handle on open Prism issues. Is this one still valid?

**Comment by philsturgeon** [comment]
Technically yes but nobody seems to be interested in it. It's not been mentioned since I wrote it, and it's not got any thumbs here, so let's close it. 

If anyone wants this feature or any other features, please make a feature request over here: https://roadmap.stoplight.io/tabs/7-under-consideration/submit-idea

**Comment by XVincentX** [comment]
Yeah I agree. It seems like XML is really not a thing anymore.
