### ISSUE TITLE
Refine the release process 

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/prism#464]
**Chore summary**

A bunch of work has been done on Spectral to mean that we only need an annotated tag pushed to create a release to NPM, Docker, GitHub, etc. Let's bring that over to Prism.

**Tasks**
- [ ] Update Lerna to use the `from-git` option
- [ ] Ask for a salary raise

**Comment by XVincentX** [comment]
This is done already. Prism is using the `from-git` option already and there's nothing more we can do for it currently.

The mono-repo thing unfortunately limits a bit what we can do to automate, but Lerna will catch up and it's not that terrible currently.
