### ISSUE TITLE
Proxy Server

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/prism#473]
**User story.**

As a client developer integrating with an API which has moved from the mock stage to a prototype or staging instance, I can run Prism in proxy mode, send all that API's traffic through this proxy, which will throw big loud errors if there is an issue with my request, or the response I'm getting back.

As a QA tester managing an e2e suite testing flows between a bunch of APIs, I can funnel all traffic through the Prism proxy, to make sure all the requests and responses coming through the proxy line up with what their API descriptions are advertising, in order to catch contract mismatches quicker, and without relying on those API teams to self report issues.

**Is your feature request related to a problem?**

This is a feature that Prism v1 and v2 had in various forms, and we sadly had to take it out of v3 due to time constraints, and slightly unclear specifications. The two use cases above should help shape thew return of this feature in v3.2 or later. 

**Describe the solution you'd like**

When #429 is done, we should have the means to listen for contract mismatches. Using this mechanism we can have the proxy server listen to requests and using the Prism HTTP Client JS interface, it can make those requests to the real server.

The proxy server should have two modes:

```js
prism proxy {upstream} openapi.yaml --log
prism proxy {upstream} openapi.yaml --error
```

Not sure which should be default right now, but the two modes would work like this:

1. Log would just report mismatches to logs stdout/stderr
2. Error would respond with Prism JSON errors explaining the mismatch

the goal of logs would be to have it running in staging or maybe even production (agh this will need lots of load testing), and error would be more useful for local development and testing environments.

**Additional context**

Blocked by #429 

/cc @ww-daniel-mora for input.

**Comment by philsturgeon** [comment]
> a client makes a request to Prism and Prism forwards that request to an upstream

correct.

**Comment by philsturgeon** [comment]
Btw the reason we are not interested in `curl http://some_upstream.com --proxy http://localhost:4010` is because http://localhost:4010 is the proxy yes, and the proxy is started with an upstream, so we don't need to place that extra burden on the client. The client can just request http://localhost:4010 and it's already going to the upstream.

This is still a proxy 👍

**Comment by lag-of-death** [comment]
@philsturgeon, I understand. I was trying to clarify what type of proxy Prism is to be, which you did, so thank you for that. And also, this is the only way I believe to be able to peek into request/responses. With Prism creating a TCP tunnel (for https over http) between a client and an upstream, it would be impossible to do so.

**Comment by philsturgeon** [comment]
For implementation, we want to write as little of the proxy code as possible. There are existing middlewares around which may be able to help us. 

Possibly this: https://github.com/fastify/fastify-http-proxy 

If we ever switch to express: https://www.npmjs.com/package/express-http-proxy

The fastify thing looks handy as it has http2 support built in, and that's something we should keep in mind for pretty much all of our tooling. HTTP/3 is coming.

**Comment by philsturgeon** [comment]
Question from @pytlesk4:

> @philsturgeon is proxy only going to proxy requests? It would be cool if we could proxy/mock requests for a particular spec. It was something we did in the first version of Prism, you could turn mocking on for particular operations. Thought was you could start out mocking your API, and slowly over time turn mocking off for operations and start recieving real data from your API. It was possible in Prism V2, but not as easy as v1. Here is how it was done in classic: https://help.stoplight.io/prism/getting-started/swagger

Yep! So the proxy at this stage offers one thing: validation. It will soon allow for contract testing, and eventually offer traffic inspection, recording (#423) and a bunch of other stuff, but we want to get that going without confusing proxy and mock for now. 

In the past its been rather difficult to tell what Prism is actually for, because we had a lot of commands that all did a lot of really similar things, and we're trying to keep things very separate based on the use case for now. The Prism v3 rewrite for a while would let you proxy in mock and mock in proxy and it was generally super confusing. One thing at a time. :)

**Comment by XVincentX** [comment]
@pytlesk4 That is an interesting feature; although I'd be interested to see some usage (is this a feature people was enjoying/using?)

@philsturgeon I've got some questions to clarify the direction of which we want the proxy feature of Prism to go:

1. When Prism is in proxy mode, shall it verify the requested path is valid against the paths declared in the document? If so and it's not valid, shall it return a 404 code or *still* proxy the request to the upstream server? This will affect the implementation significantly.

```yml
paths:
  /pet:
```

`prism proxy test.server.com openapi.yml && curl http://localhost:4010/aosdasoid` error or not?

2. When Prism is in proxy mode, shall it verify that the upstream server is listed in the `servers` section of the document?

```yml
servers:
  - https://test.server.com
```

`prism proxy https://prod.server.com openapi.yml` — this would trigger an error

3. Is it possible to run Prism as a pure proxy (which would just proxy the request, no input or output validation *at all*?); is it possible to run Prism with only one validation enabled? (only input or only output)

**Comment by XVincentX** [comment]
//cc @lag-of-death

**Comment by lag-of-death** [comment]
@XVincentX, these are all cool questions. Personally I would just deliver it gradually. So, for me, for the first version:

ad1. No verification.
ad2. No verification.
ad3. No mechanism for switching off validations. Validate requests and responses. That's what Prism is for in the end. For "just a proxy", people can look elsewhere for now.

We could add the mechanisms later if they turn out to be needed by users (?).

**Comment by philsturgeon** [comment]
@XVincentX seeing as you are currently working on #429 it is not possible for this PR to enable full contract testing (reporting mismatches in the response object).

It can perform input validation much like the existing mock server though, certainly. That validation logic should be in some sort of form which can be easily shared. If validation became a middleware that'd make that really easy to do. :)

**Comment by lag-of-death** [comment]
so, @XVincentX, would you like me to add to https://github.com/stoplightio/prism/pull/633 so that Prism as proxy can "perform input validation much like the existing mock server"? @philsturgeon, do you mean `middleware` as in `fastify middleware` or do you have something else in mind?

**Comment by XVincentX** [comment]
@philsturgeon Correct, I know we can't get all of this right, but it will help me to give some directions for the code so @lag-of-death can be autonomous and work on this. 

Can you re-check the questions again and let me know whether (now or in the future) this is something it should do?

**Comment by philsturgeon** [comment]
Sorry @XVincentX absolutely, I missed one there.

> 1. When Prism is in proxy mode, shall it verify the requested path is valid against the paths declared in the document? If so and it's not valid, shall it return a 404 code or still proxy the request to the upstream server? This will affect the implementation significantly.

You got it, that is what these options are intended for:

```
prism proxy {upstream} openapi.yaml --log
prism proxy {upstream} openapi.yaml --error
```

It could also be:

1. `--mode=log` or `--mode=error`
2. logs by default and `--error`
3. errors by default and `--silent`

Maybe 2?

Some people will want to use it as a "validation proxy", where it blows up if an incoming request is no good, just like using it for [server-side validation](https://www.apisyouwonthate.com/blog/server-side-validation-with-api-descriptions/), for giving hard errors (JSON Problems) on request and response. (The response part might have to wait until #429 is done. When I wrote these issues there was a specific order in mind, but things did not work out that way.)

Other people will enable it just so they can check the logs, so there are reports of issues but it does not error. This would be useful in production for inspecting traffic. 

There will be a lot more functionality and use cases added on top of this, but initially this is what the proxy is going to be about. 

> 2. When Prism is in proxy mode, shall it verify that the upstream server is listed in the servers section of the document?

"server validation" and "security validation" and all the other various forms of "input validation" should be on the same big switch for now.  

> 3. Is it possible to run Prism as a pure proxy (which would just proxy the request, no input or output validation at all?); is it possible to run Prism with only one validation enabled? (only input or only output)

Yes so the "silent" mode or "logging mode" whatever switch we pick will be a pure proxy. Then we enable validation. And no combined mode of proxy/mock either, as mentioned above.

**Comment by lag-of-death** [comment]
@XVincentX, so probably the place where `forwarder` was invoked would be best?

**Comment by XVincentX** [comment]
That is correct :)

**Comment by lag-of-death** [comment]
@philsturgeon, @XVincentX, is there an agreement on the approach?

**Comment by XVincentX** [comment]
Kind of; we're going to need to do some refactor of stuff and break down some concept of Prism to make the proxy story property; I'll take care of this and try to come up with a design document hopefully soon.
