### ISSUE TITLE
OAS2 invalid form data not validated correctly

### ISSUE THREAD

**Issue by chris-miaskowski** [stoplightio/prism#483]
**Describe the bug**

Prism fails to handle an invalid OAS2 form data parameters.

**To Reproduce**

(see https://github.com/stoplightio/prism/pull/482)

```
====test====
Given form data expected in request body then return 422 when that body is invalid.
====spec====
swagger: '2.0'
paths:
  /path:
    post:
      consumes:
        - application/x-www-form-urlencoded
      responses:
        200:
          schema:
            type: string
      parameters:
        - in: formData
          type: integer
          name: id
          required: true
        - in: formData
          type: string
          name: status
          required: true
          enum:
            - open
            - close
====server====
mock -p 4010
====command====
curl -i -X POST http://localhost:4010/path -H "Content-Type: application/x-www-form-urlencoded" --data-urlencode "status=ooopsie!"
====expect====
HTTP/1.1 422 Unprocessable Entity
content-type: application/problem+json
Connection: keep-alive

{"type":"https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY","title":"Invalid request body payload","status":422,"detail":"Your request body is not valid and no HTTP validation response was found in the spec, so Prism is generating this error for you.","validation":[{"code":"required","message":"should have required property 'id'","severity":"Error"},{"code":"enum","location":["body","status"],"message":"should be equal to one of the allowed values","severity":"Error"}]}
```

**Actual**

```
 "{\"type\":\"https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY\",\"title\":\"Invalid request body payload\",\"status\":422,\"detail\":\"Your request body is not valid and no HTTP validation response was found in the spec, so Prism is generating this error for you.\",\"validation\":[{\"location\":[\"body\"],\"severity\":\"Error\",\"code\":\"type\",\"message\":\"should be integer\"}]}"
```

**Environment (remove any that are not applicable):**
 - Library version: [e.g. 3.0.1]

**Additional context**

Most likely the issues must be fixed in Graphite

Failing integration tests:

```
oas2 with form data param
      required parameter not in body
        ✕ returns 422 (21ms)
      parameter does not match enum criteria
        ✕ returns 422 & proper validation message (17ms)
      valid parameter provided
        ✕ returns 200 (13ms)
```

PR: https://github.com/stoplightio/http-spec/pull/9

**Comment by philsturgeon** [comment]
I think there’s two problems here, It’s like it’s failing on the first problem (integer is a string) then not getting to the second problem (the status is invalid). 

I think we need to think about why we get “should be an integer” instead of “is missing” that might be a sign of a bigger problem. 

--
Phil Sturgeon
@philsturgeon

**Comment by chris-miaskowski** [comment]
@philsturgeon it is a sign of a bigger problem. I already debugger it and the problem lays in Graphite (or http-spec package). We interpter oas2 `formData` icorrectly. I've been investigating it with short pauses for the last day and I came across other issues:
- multipart data does not work at all (but will be covered by https://github.com/stoplightio/prism/issues/432 afaik)
- formData in oas2 seems to be totally different than in oas3. I can tell now that we don't do best job validating oas2 request body.
- graphite tries to munge the oas2 and oas3 together in a single universal "content" thingy... but not sure we can do it (haven't figure it out yet).
- I'm now writing more tests to be able to see how much we're missing

**Comment by philsturgeon** [comment]
@chris-miaskowski good work so far, keep on sleuthing! Create a github issue for any distinct bugs or units of work required that do not fall under this issue, and updating this one accordingly. :)
