### ISSUE TITLE
Validate response examples when a response has no schema

### ISSUE THREAD

**Issue by lag-of-death** [stoplightio/prism#495]
**User story.**
As a prism user, I can validate my schema-free response examples, so that I know they are correct.

**Is your feature request related to a problem?**
Prism allowing something to be looked at as X (like of content-type `application/xml`) and then not validating if that something truly is of type X (so of `application/xml` in this example) might be confusing (?).

**Describe the solution you'd like**
If an example is given for a response of some `content-type` and we have no schema for that response, then the example should be validated against its `content-type`. So, for example, we could check if:
`application/xml: 123` is an XML or not.

**Comment by philsturgeon** [comment]
I might be misunderstanding the suggestion, but it seems like this is a job for Spectral? 

Spectral looks at examples in the description doc and makes sure they are valid, which you know as you're working on it :D 

This seems like the same feature but for request/response examples too. 

Am I misunderstanding? 

We are assuming the Prism doc is validated and useful through an existing validator, so maybe this feature should be: run Spectral against the document before passing it to Prism, which... maybe we could do.

**Comment by lag-of-death** [comment]
@philsturgeon, yeah, so either: run spectral inside prism (and do the validation in spectral) or validate an example in prism :+1: I reported it here because https://github.com/stoplightio/prism/issues/424 is Prism issue. This issue is about validating `when a response has no schema`, so it's a bit different than https://github.com/stoplightio/spectral/pull/472

**Comment by philsturgeon** [comment]
We are going to avoid crossing prism and spectral for now. At some point validation of the description docs being passed in certainly seems like useful functionality, but this specific use case is not appropriate for prism at this time.
