### ISSUE TITLE
allowEmptyValue is not respected

### ISSUE THREAD

**Issue by chris-miaskowski** [stoplightio/prism#499]
**Describe the bug**

allowEmptyValue is not allowing empty values currently.

> Hint, search in project by `TO BE FIXED BY: https://github.com/stoplightio/prism/issues/499` to find related tests.

**To Reproduce**

```
====test====
Set allowEmptyValue to true, send request with only a key
and expect to get 200
====spec====
swagger: '2.0'
paths:
  /path:
    post:
      consumes:
        - application/x-www-form-urlencoded
      responses:
        200:
          schema:
            type: string
      parameters:
        - in: formData
          type: string
          name: id
          allowEmptyValue: true
====server====
mock -p 4010
====command====
curl -i -X POST http://localhost:4010/path -H "Content-Type: application/x-www-form-urlencoded" --data "id"
====expect====
HTTP/1.1 200 OK
```

```
====test====
Set allowEmptyValue to false and try to send an empty key, should fail.
====spec====
swagger: '2.0'
paths:
  /path:
    post:
      consumes:
        - application/x-www-form-urlencoded
      responses:
        200:
          schema:
            type: string
      parameters:
        - in: formData
          type: string
          name: id
          allowEmptyValue: false
====server====
mock -p 4010
====command====
curl -i -X POST http://localhost:4010/path -H "Content-Type: application/x-www-form-urlencoded" --data "id"
====expect====
HTTP/1.1 422 Unprocessable Entity
content-type: application/problem+json
Connection: keep-alive

{ "tobe": "done" }
```
**Expected behavior**

**Screenshots**

**Environment (remove any that are not applicable):**
 - Library version: [e.g. 3.0.0]
 - OS: [e.g. Windows 7]
 - Browser: [e.g. Chrome 61]

**Additional context**

This bit of code in http-spec is probably backwards:

```
if ('allowEmptyValue' in param && param.allowEmptyValue) {
    schema.minLength = 1;
}
```

**Comment by philsturgeon** [comment]
@marbemac @XVincentX I really cant remember why we had:

```
if ('allowEmptyValue' in param && param.allowEmptyValue) {
    schema.minLength = 1;
}
```

Can we separate the de-serialization logic and have it report errors in its own way, and have schema validation be something which happens on the result of whatever gets serialized? I think confusing the two things is leading to this sort of oddity. 

Yes we could switch this to: 


```
if ('allowEmptyValue' in param && param.allowEmptyValue === false) {
    schema.minLength = 1;
}
```

Maybe we do this with a test and throw a note into a greater issue that solves all of the concerns with validation which @XVincentX has been eluding to recently? Up to you Vincenzo.

**Comment by XVincentX** [comment]
I'm on this now.

**Comment by XVincentX** [comment]
> I really cant remember why we had:

I am _pretty_ sure it was just me being dumb and writing incorrect code.

> Maybe we do this with a test and throw a note into a greater issue that solves all of the concerns with validation

I with it would be so easy. I still didn't find the time to look up seriously in the validation process — making it right will probably require too much time. I'll fix the bug on the http-spec package and then we'll talk about doing validation right in another occasion
