### ISSUE TITLE
Excessive memory usage on Ubuntu16

### ISSUE THREAD

**Issue by simarpreets** [stoplightio/prism#5]
Hi, I am using prism on Amazon Ec2 instance with following OS : 
`Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
`

After few requests, as i checked its memory usage went upto 2GB's.

**Comment by pytlesk4** [comment]
Can you send me your spec file and your config file, and the curl command of the requests you sent. I will look into this asap for you.

**Comment by simarpreets** [comment]
It works fine on other ports than PORT 80, I tried that on my local Os X as well.
It falls into some kind of recursive call loop. I am attaching Prism's dump for your reference.
I was using this command to run `sudo prism run -p 80 -d --mock --list --spec my_swagger_spec.json`
[dump.txt](https://github.com/stoplightio/prism/files/677698/dump.txt)

**Comment by pytlesk4** [comment]
Sweet, I was able to replicate this, will let you know when I update prism and fix this.

**Comment by pytlesk4** [comment]
Please download the latest prism binary, let me know if it is working properly and I will close this issue.

**Comment by simarpreets** [comment]
Now its working fine for a local curl request but still going in a loop for a remote curl request (when I am making a curl request to ec2 instance or try to access it through browser)

**Comment by pytlesk4** [comment]
Dang it, that is an easy fix, I will get that out shortly.

**Comment by pytlesk4** [comment]
Updated binaries, download the latest and let me know if your issue is resolved.

**Comment by simarpreets** [comment]
No Luck! But let me tell you the exact setup I am using so that you can reciprocate the issue.

I am running nginx server on port 80 which redirects everything to 443. Here's what my nginx config looks like.

    server { 

    listen 80 default_server;
    listen [::]:80 default_server;

    server_name gst-gsp-demo.com www.gst-gsp-demo.com;
    return 301 https://$server_name$request_uri;
    }

    server {

    # SSL configuration

    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;
    include snippets/ssl-gst-gsp-demo.com.conf;
    include snippets/ssl-params.conf;

       # For mock server. Passing to Prism 
       location /mock/ {
        
        proxy_pass http://localhost:4010;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        #auth_basic "Private Property";
        #auth_basic_user_file /etc/nginx/.htpasswd;
    }

As obvious, on 4010, prism is running, and URI's like '/mock/' are redirected to it. But It falls into infinite loop.

I am using this command to run prism `prism  run  -d --mock --list --spec swagger.json` and using `Prism version 0.4.9`

**Comment by pytlesk4** [comment]
Happy New Year! Should be good to go now! Talk to you next year.

**Comment by simarpreets** [comment]
Happy New Year Thomas!
Sorry to bother you during holidays but problem still persists. Attaching the logs snapshot
<img width="1280" alt="screen shot 2017-01-01 at 1 17 02 pm" src="https://cloud.githubusercontent.com/assets/17894229/21580539/9c6618b2-d024-11e6-8413-1d8cc55fab26.png">
 for your reference:-

**Comment by simarpreets** [comment]
Hi Thomas, 
I was able to fix this by commenting out the explicit setting of Headers in my nginx config.  :)

For your reference, here's how my nginx location block looks like now.
   # For mock server. Passing to Prism 
    location /mock/ {
    
    proxy_pass http://localhost:4010;
    #proxy_set_header Host $host;
    #proxy_set_header X-Real-IP $remote_addr;
    #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #proxy_set_header X-Forwarded-Proto $scheme;
    #auth_basic "Private Property";
    #auth_basic_user_file /etc/nginx/.htpasswd;
    }

Thanks a lot, for your active responses during holidays, really appreciate this.

**Comment by pytlesk4** [comment]
Awesome! Going to close this out now!
