### ISSUE TITLE
Standardized error results

### ISSUE THREAD

**Issue by marbemac** [stoplightio/prism#51]
- [x] Design result errors structure.
- [x] Implement result errors structure.
- [x] Decide and implement how we want to output this in the run from terminal output
- [ ] The UI will need to display these errors prominently to the user. [marc]

Some example errors we might want to track:
- [x] invalid request body json #39 
- [x] couldn't deref error
- [x] js runtime error (script failed, instead of logging, add a formal error)
- [x] variables are used but not defined ($$.env, $$.ctx, $.ctx, etc)
- [x] capturing failed because property isn't there, warning
- [x] extra slashes warning
- [x] empty base path warning
- [x] ... anything else?

**Comment by pytlesk4** [comment]
- js runtime errors, should those be an error, or just logging.

**Comment by pytlesk4** [comment]
- errors
  - couldn't deref error

- warnings
  - capturing failed because property isn't there.

**Comment by pytlesk4** [comment]
- extra slashes warning
- empty base path warning(error?)
