### ISSUE TITLE
Can't run Prism throw jsonErr;

### ISSUE THREAD

**Issue by wal0x** [stoplightio/prism#519]
**Describe the bug**
Can't run prism. Getting error after first launch.

**To Reproduce**

1. Install prism globally "npm install -g @stoplight/prism-cli"
2. Run this CLI command 'prism'
3. See error

**Expected behavior**
Display prism command options

**Error :**

> C:\Users\user\AppData\Roaming\npm\node_modules\@stoplight\prism-cli\node_modules\parse-json\index.js:31
>                 throw jsonErr;
>                 ^
>     "@...' in ..\package.jsonxpected token < in JSON at position 557 while parsing near '...evDependencies": {
>     at module.exports (C:\Users\user\AppData\Roaming\npm\node_modules\@stoplight\prism-cli\node_modules\parse-json\index.js:26:19)
>     at parse (C:\Users\user\AppData\Roaming\npm\node_modules\@stoplight\prism-cli\node_modules\load-json-file\index.js:8:29)
>     at Function.module.exports.sync (C:\Users\user\AppData\Roaming\npm\node_modules\@stoplight\prism-cli\node_modules\load-json-file\index.js:11:29)
>     at Function.sync (C:\Users\user\AppData\Roaming\npm\node_modules\@stoplight\prism-cli\node_modules\pkg-conf\index.js:52:27)
>     at Signale.get packageConfiguration [as packageConfiguration] (C:\Users\user\AppData\Roaming\npm\node_modules\@stoplight\prism-cli\node_modules\signale\signale.js:81:20)
>     at new Signale (C:\Users\user\AppData\Roaming\npm\node_modules\@stoplight\prism-cli\node_modules\signale\signale.js:20:39)
>     at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\@stoplight\prism-cli\node_modules\signale\index.js:4:32)
>     at Module._compile (internal/modules/cjs/loader.js:776:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
>     at Module.load (internal/modules/cjs/loader.js:643:32) {
>   name: 'JSONError',
>   fileName: '..\\package.json'
> }

**Environment (remove any that are not applicable):**
 - Library version: 3.0.3
 - OS:  Windows 10
 - Node:  v12.6.0

**Comment by philsturgeon** [comment]
Very strange, I just ran this and didn't get the issue. I think, maybe, some HTML crept into a file download on your end somewhere. Maybe a corporate proxy, or some other middleman: 

> "@...' in ..\package.jsonxpected token < in JSON at position 557 while parsing near '...evDependencies": {

This could have been a one-off, did you try again? 

If it happens again, is it the same file, or a different one? 

Can you phone tether or get on a different network? 

Anything you can do to help debug this would be handy. 

If problems are still happening can you try [another installation method](https://stoplight.io/p/docs/gh/stoplightio/prism/docs/getting-started/installation.md)?

**Comment by wal0x** [comment]
I am using Git-bash to run it, in fact I could run prism normally when I opened the bash from my desktop, when I run it directly from the folder where my .yaml is I get the same error.

**Comment by philsturgeon** [comment]
So you have git bash, and it fails there. 

Running normal bash, you can install just fine? 

Then... something else causes an error? Could you elaborate on that part?

**Comment by wal0x** [comment]
Same issue with PowerShell

**Comment by wal0x** [comment]
I found something interesting, I got the issue when am inside a folder where there is a node_modules folder on it hierarchy.

**Comment by philsturgeon** [comment]
Did you get any further on this? Do you have the same problem installing other global NPM packages in those same folders, like maybe `npm i -g gatsby-cli` or something? 

If you discover the solution please report back and close the issue. I get the sense that it's not us.

**Comment by wal0x** [comment]
Yes I could call the global NPM pachakges such as vue eslint and angular cli...
But A simple restart solved the issue :|
