### ISSUE TITLE
Support Path Params in Scenarios spec

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/prism#54]
[ ] Path Parameters
[ ] Query String Parameters

- https://help.stoplight.io/scenarios/http/input
  - support 'params' object, where the key is the name of the path parameter in the url and it's corresponding value. Example: 
```
{
  ...
  url: http://todos.stoplight.io/todos/{todoId},
  params: {
    todoId: 123
  }
  ...
}
```

URL will resolve to http://todos.stoplight.io/todos/123

**Comment by marbemac** [comment]
Note: let brad@kindrid.com know when this is live.

**Comment by marbemac** [comment]
In addition, value can be something like:

```
{
  ...
  url: http://todos.stoplight.io/todos/{todoId},
  params: {
    todoId: "{$.ctx.todoId}"
  }
  ...
}
```

Which would be equivalent to what you can already do, which is this:

```
{
  ...
  url: http://todos.stoplight.io/todos/{$.ctx.todoId}
  ...
}
```

Really this feature is an added convenience thing to be able to keep path params the same notation as OAS, and to clear up any confusion over wether params can be stored in the spec itself or not.
