### ISSUE TITLE
Add a dependencies property to Prism Instances and Collections spec 

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/prism#56]
```
// type can one of: oas, collection
{
  [type]: {
    [id]: {
      $ref: "relative filepath or url" 
    } 
  }
}
```

**Comment by pytlesk4** [comment]
- running from cli no longer requires --spec for contract testing, can still be used to add specs, or over write existing dependencies.
 --spec 'foo=location' // will over write foo

**Comment by pytlesk4** [comment]
- Is Data a dependency @marbemac ?

**Comment by rossmcdonald** [comment]
Example:

```json
{
  "scenarios": {
    "foo": {
      "$ref": "#/dependencies/users/data"
    },
    [...],
  },
  "dependencies": {
    "users": {
      "type": "oas2",
      "data": {
        "$ref": "foo.com/users.json"
      }
    },
    "posts": {
      "type": "oas2",
      "data": {
        "$ref": "foo.com/posts.json"
      }
    }
  }
}
```

**Comment by pytlesk4** [comment]
Just to make sure I am on the same page as everyone, the foo.$ref is going to resolve to swagger spec, not a scenario. For a scenario it should be a type: 'collection'.

**Comment by marbemac** [comment]
correct

**Comment by pytlesk4** [comment]
OAS dependencies are done

**Comment by marbemac** [comment]
Awesome, I'm about to do the frontend - the latest format described above is accurate right?

**Comment by pytlesk4** [comment]
This was changed to settings, and is done.
