### ISSUE TITLE
[BUG] Prism should support */* by default for DELETE

### ISSUE THREAD

**Issue by lfmunoz** [stoplightio/prism#562]
I have a simple DELETE endpoint and want to return empty with a 204

Documentation  says

"Some responses, such as 204 No Content, have no body. To indicate the response body is empty, do not specify a content for the response"

https://swagger.io/docs/specification/describing-responses/

```
 /api/calls/{id}:
    delete: # DELETE
      tags:
        - Calls
      description: Delete a call history item
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        204:
          description: OK
        400:
          description: NOK
        500:
          description: ERROR
components:
    id:
      in: path
      name: id
      description: id for the item
      required: true
      schema:
        type: integer
        format: int64

```

```
curl -X DELETE "http://127.0.0.1:4010/api/calls/1" -H "accept: */*"
or
curl -X DELETE "http://127.0.0.1:4010/api/calls/1"  
```

```                                                                                                                
{
detail: "Unable to find content for application/json, text/plain, */*"
status: 406
title: "The server cannot produce a representation for your accept header"
type: "https://stoplight.io/prism/errors#NOT_ACCEPTABLE"        
}   
```

The following is a workaround but it seems like it is pollution in my spec file 
```
  /api/calls/{id}:
    delete: # DELETE
      tags:
        - Calls
      description: Delete a call history item
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        204:
          description: OK
          content:
            '*/*':
              schema:
                type: string
        400:
          description: NOK
        500:
          description: ERROR
```

**Comment by equalspeterd** [comment]
I have encountered the same issue with `PUT` as well. The preferred solution is to handle `204` responses with no body at all (and thus, no content type), which openAPI v3.x supports.

Per RFC7231:
```
A 204 response is terminated by the first empty line after the header
fields because it cannot contain a message body.
```
for the time being, I have been using the `nullable` parameter:

```
responses:

    204_resp:
      description: The updates were successfully applied to the resource. An ETag in the response header indicates
        the latest ETag for the resource.
      headers:
        ETag:
          $ref: '#/components/headers/ETag'
      content:
        application/json:
          schema:
            nullable: true
```

**Comment by XVincentX** [comment]
@lfmunoz Can you try again with Prism 3.1.1? Although we haven't looked at this specific issue I am almost sure that we've been ironed out some stuff that will make this…disappear.

Thanks!

**Comment by XVincentX** [comment]
//cc @equalspeterd

**Comment by XVincentX** [comment]
I've tried both examples and they work correctly in 3.1.1; please reopen if it is not the case.

**Comment by lfmunoz** [comment]
@XVincentX yes fixed / works as expected, thank you

**Comment by equalspeterd** [comment]
> //cc @equalspeterd

confirmed fixed. thanks!

**Comment by smitha99** [comment]
I still see this issue while using version 3.1.1.

When I do with a global install it seems like its fixed. But, I have not globally installed the @stoplight/prism-cli npm package. I want to trigger it in my application source code.

**Comment by XVincentX** [comment]
@smitha99 You might want to provide more details, otherwise it's not easy to help you.

**Comment by smitha99** [comment]
I have a Delete endpoint in my openapi spec as below - 

```
'/books/{book_id}':
    delete:
      summary: Delete a book
    
      parameters:
        - id: book_id
          in: path
          description: Id of Book
          required: true
          schema:
            $ref: '#/components/schemas/BookId'
     responses:
        204:
          description: Book deleted successfully
```

When I have prism-cli installed globally -

Step 1 :`npm install -g @stoplight/prism-cli`

and run 
Step 2 :`prism mock books.yaml --dynamic`

- prism cli gives the below mock endpoint and expected response (204)

```
[CLI] ●  note      DELETE     http://127.0.0.1:4010/books/{book_id}
```

But when I have `prism-cli` installed locally in my app as 

`npm install --save-dev @stoplight/prism-cli` and trigger Step 2 through a script on package.json, the same mock endpoint is created

```
[CLI] ●  note      DELETE     http://127.0.0.1:4010/books/{book_id}
```

But while deleting a book, I get the following error - 

```
{"type":"https://stoplight.io/prism/errors#NOT_ACCEPTABLE","title":"The server cannot produce a representation for your accept header","status":406,"detail":"Unable to find content for application/json, text/plain, */*"}
```
@XVincentX,
You were mentioning with version 3.1.1, this issue should be fixed. But I am still seeing the issue.

My version in package.json is `"@stoplight/prism-cli": "^3.1.1"`. Any help regarding this issue is appreciated.

**Comment by lfmunoz** [comment]
In your package.json add a script to check the version and confirm it is running 3.1.1

prism --version
3.1.1

**Comment by smitha99** [comment]
I did that, and it gives the version as 3.1.1 😅 
```
> prism --version
3.1.1
```

**Comment by Rawnly** [comment]
`Cannot find serializer for */*"`

Running `prism mock -p 4010 http://localhost:8080/v2/api-docs -m`

I'm using `spring-fox` on my Spring server, I can't figure out how set default response to `application/json` so I'm using `*/*` but with `prism v3.2.2` nothing has changed so far.

Any solution?

**Comment by XVincentX** [comment]
@Rawnly Can you share your OpenAPI document?

**Comment by Rawnly** [comment]
> @Rawnly Can you share your OpenAPI document?

Sure! [Here it is](https://stockpapers.s3.amazonaws.com/files/swagger.yaml)

**Comment by XVincentX** [comment]
@Rawnly What operation shall I test? Can you paste a CURL command to reproduce?

**Comment by Rawnly** [comment]
Here the CURL

```
❯ curl http://localhost:8080/api/events | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   169  100   169    0     0  16900      0 --:--:-- --:--:-- --:--:-- 16900
{
   "detail" : "",
   "status" : 500,
   "title" : "Your schema contains $ref. You must provide specification in the third parameter.",
   "type" : "https://stoplight.io/prism/errors#UNKNOWN"
}
```

**Comment by XVincentX** [comment]
This is a different error that the one you described. This is likely related to #643

**Comment by Rawnly** [comment]
> This is a different error that the one you described. This is likely related to #643

Oh sorry wrong issue 😂, wait a sec and I'll post the right response

**Comment by Rawnly** [comment]
### CURL
`❯ curl http://localhost:4010/api/locations -H 'Content-Type: application/json' | json_pp`
  
### Response
```json
{
   "detail" : "Cannot serialise complex objects as text",
   "status" : 500,
   "title" : "Cannot serialise complex objects as text",
   "type" : "https://stoplight.io/prism/errors#NO_COMPLEX_OBJECT_TEXT"
}
```

**Comment by XVincentX** [comment]
Ma non è che per caso eri a RomaJS questo Novembre? No giusto per capire :trollface:

**Comment by Rawnly** [comment]
hahah no c'era un mio collega 😅 dovevo venire pure io ma non son riuscito... comunque non ricordo esattamente l'endpoint che mi dava problemi ieri.. stiamo cercando di tirar su un mock il più velocemente possibile per eseguire dei test, `prism` ci sembrava carino, ma ci sta dando problemi con il file OpenAPI generato da `swagger` :(

**Comment by XVincentX** [comment]
Il problema è nei generatori automatici che solitamente puzzano de merda — provo a dare un occhio al tuo documento e vedere di chi è la colpa :)

**Comment by XVincentX** [comment]
@Rawnly 

<img width="899" alt="image" src="https://user-images.githubusercontent.com/1416224/72077762-168f7500-32f8-11ea-8bc5-cdfe47903560.png">


A me restituisce correttamente una risposta.

**Comment by Rawnly** [comment]
@XVincentX 

Ti posso chiedere che versione hai?

**Comment by XVincentX** [comment]
3.2.3 con dall'immagine docker.

`docker run --init -P stoplight/prism:3 mock https://stockpapers.s3.amazonaws.com/files/swagger.yaml -h 0.0.0.0`
