### ISSUE TITLE
$$.stop, $.stop and stop

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/prism#57]
- [x] $$.stop - stops current collection run.
- [x] $.stop - stops current scenario.
- [x] stop - stop step currently running.

**Comment by pytlesk4** [comment]
needed-by #71

**Comment by marbemac** [comment]
We need to discuss exact runtime syntax.

**Comment by pytlesk4** [comment]
@marbemac did you have any thoughts?

**Comment by marbemac** [comment]
Looks pretty good, minus the data ones. What is the difference between $.stop and $.skip?

$.stop could stop the scenario, $.skip could skip the current scenario iteration?

**Comment by pytlesk4** [comment]
I remember what we decided on.

$$.stop // stops collection
$.stop // stops current scenario iteration
stop // stops/skips current step

We decided we didn't need the skip function on a scenario level because it doesn't really make sense.

**Comment by pytlesk4** [comment]
Starting this now, so last call.

**Comment by marbemac** [comment]
It does make sense now - see my comment above.

$.stop stops scenario
$.skip skips current scenario iteration

**Comment by pytlesk4** [comment]
so $.stops all the iterations for a scenario?

**Comment by marbemac** [comment]
Yessah

**Comment by pytlesk4** [comment]
We don't have data driven tests yet, so I haven't supported all. I will make a note the data driven issue about this.

**Comment by pytlesk4** [comment]
Just need to do $$.stop

**Comment by pytlesk4** [comment]
stop() throws an error when called, if a user uses a try catch, and calls stop() the step will continue running. Need to do something similar as $.stop().

**Comment by marbemac** [comment]
Perhaps just do this in fast prism if take too long in slow.

**Comment by russmilburn** [comment]
Hey is there any news on $$.stop() for stopping a collection in prism?

**Comment by pytlesk4** [comment]
Got a release going out tonight, then I am going to add support for this. I will let you know when it is done.

**Comment by russmilburn** [comment]
Hey Guys

Could you let us know what version will the $$.stop() feature which stops and entire collection be complete for prism.

Thanks

Russ

**Comment by pytlesk4** [comment]
@russmilburn We will be releasing it latter this week, so in the next version of prism which is 2.0.0-beta.7, we just need to finish testing all the changes. Should be happening in the next day or two.

**Comment by pytlesk4** [comment]
released in 2.0.0-beta.7
