### ISSUE TITLE
Look up prism instances with API

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/prism#58]
- https://docs.gitlab.com/ee/api/repository_files.html#get-raw-file-from-repository

- {projectId}-{gitRef}.stoplight-proxy.io
  * git ref is the branch to use, defaults to master if it isn't there.
  * need to support yaml and json files

**Comment by pytlesk4** [comment]
- Need to figure out how environments are going to work in prism instances.

**Comment by marbemac** [comment]
New plan:

sri = object with several properties. for example, if the url was the internal one described above:
  org: 'stoplight'
  project: 'todos-demo'
  ref: 'master'
  file: 'specs/oas.json'

Example of full SRI (all the above joined with ":"): "stoplight:todos-demo:master:specs/oas.json"

OR shorter, with just project id

"123:master:specs/oas.json"

Every prism config file in a user's project will display a prism-server url like:
"NTptYXN0ZXI6c3BlY3Mvb2FzLmpzb24.stoplight-proxy.io"

The subdomain is base64 encoded SRI. Prism needs to decode it, extract the parts, and put together the correct API request to fetch the prism config file.

NOTE: https://stackoverflow.com/questions/6916805/why-does-a-base64-encoded-string-have-an-sign-at-the-end

We will strip the = off the end of the base64, need to add it back (if necessary) before decoding.
