### ISSUE TITLE
Negotiator incorrectly returns a 406 for 204's with no defined response

### ISSUE THREAD

**Issue by labsvisual** [stoplightio/prism#584]
**Describe the bug**
When Prism is mocking an OA3 specification containing a 204 response, it incorrectly returns an error since it can not find a valid response layout and specification for the same. 

As per [RFC 7231](https://tools.ietf.org/html/rfc7231), [Section 6.3.5](https://tools.ietf.org/html/rfc7231#section-6.3.5):

> The 204 (No Content) status code indicates that the server has successfully fulfilled the request and that there is no additional content to send in the response payload body.

The bug can be traced back to `@stoplight/prism-http/src/mocker/negotiator/NegotiatorHelper.ts` on [Line 154](https://github.com/stoplightio/prism/blob/master/packages/http/src/mocker/negotiator/NegotiatorHelpers.ts#L154). 

**To Reproduce**

1. Given this OpenAPI document:

```yaml
openapi: 3.0.0
info:
  title: Test
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /auth/logout:
    get:
      summary: Deletes the current session
      tags: []
      responses:
        '204':
          description: No Content
        '404':
          description: No session with the provided session ID was found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        statusCode:
                          type: string
                        description:
                          type: string
                      required:
                        - code
                        - statusCode
                        - description
                required:
                  - errors
              examples:
                '404':
                  errors:
                    - code: SESSION_NFOUND
                      statusCode: '404'
                      message: No session with the provided ID was found.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sessionId:
                  type: string
                  format: uuid
              required:
                - sessionId
```

2. Run this CLI command: `prism mock ./openapi.yaml`
3. Make a `curl` GET request: `curl -XGET http://127.0.0.1:4010/auth/logout`
4. See error:
```json
{
    "type": "https://stoplight.io/prism/errors#NOT_ACCEPTABLE",
    "title": "The server cannot produce a representation for your accept header",
    "status": 406,
    "detail": "Unable to find content for */*"
}
```

**Expected behavior**
Prism should just return 204 with no body or content unless explicitly added to the response definition.

**Screenshots**
<img width="835" alt="Screen Shot 2019-09-05 at 12 17 24 PM" src="https://user-images.githubusercontent.com/13390457/64318208-26f4b380-cfd7-11e9-8e37-d37513b24737.png">

**Environment (remove any that are not applicable):**
 - Prism version: v3.1.0
 - OS: macOS 10.14.6

**Possible Fix**
The simplest fix is to add an explicit check for status code 204 in the negotiator and let the application continue from there instead of falling back on the negotiatingByMediaType which inevitably gives the standardized `ProblemJson` response.

I have a working PR for this and would love to submit it. 😄

**Comment by XVincentX** [comment]
Yeah, we've been receiving this kind of issue multiple times (you can see similar duplicates for `DELETE` verbs for example). In general we've been skipping this use case completely so far.

There's a workaround (tweak the API Description Document to return something, even if empty, anyway) but yeah this is something we should fix.

I'd he happy to have a look at your pull request, but keep in mind it's not only about `204`, there are other use cases.

**Comment by labsvisual** [comment]
A couple of other corner cases I can think of are `DELETE`, `2XX` with no response body. Ideally, however, if a body is defined for `204`, we should return the response but emit a warning in the console. 

Similar is the case with `DELETE` and `GET`.
