### ISSUE TITLE
chore: auto-deploy docs

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/prism#585]
**Chore summary**
Auto deploy documentation so we don't have to remember. Seeing as this repo is not git flow it will need to be done as part of release and not on master merge. 

**Additional context**
Use the same approach as spectral
https://github.com/stoplightio/spectral/issues/530

**Comment by XVincentX** [comment]
@StefanDywersant The idea would be to use the Stoplight Analyzer CLI to upload the docs when something gets released; I think @lottamus can give you some directions since he's been working on an ORB for CircleCI that could really be helpful.

**Comment by lottamus** [comment]
@XVincentX @StefanDywersant here's the orb. It's pretty easy to set up: https://github.com/stoplightio/circleci-orbs#stoplightcli-
