### ISSUE TITLE
Bump http-spec to use version with strictMode disabled for JSON Schema conversion

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/prism#588]
**Describe the bug**
Prism has a fatal error and doesn't start.

**To Reproduce**

1. Given this OpenAPI document'

```yaml
openapi: 3.0.0
info:
  title: Example API
  version: '1.0'
  contact:
    name: Bear
    url: 'https://bear.dojo'
    email: pooh@bear.dojo
  termsOfService: 'https://bear.dojo/terms'
  description: The Bear Dojo API
paths:
  /honey:
    get:
      summary: Get Raw Honey
      responses:
        '200':
          description: 'Success, found the bears can have some honey.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  honey:
                    type: 
                      - object
                      - string
                    properties: 
                       name:
                         type: string
                       location:
                         type: string
                       species:
                         type: string
                         example: killer bees
                required:
                  - ok
                  - honey
      description: Get some raw honey.
      operationId: getRawHoney
```

2. Run this CLI command

`prism mock https://gist.githubusercontent.com/pytlesk4/e0f60de87783af0cb7b3077bd5ca5b9e/raw/24690903c7448c233cc03e1839483db0d10a793e/bear.dojo.v2.yaml`

3. See error

![](https://user-images.githubusercontent.com/2294309/64367389-7b9b2d00-cfdd-11e9-8dc1-e1bb724e433f.png)

**Expected behavior**

Prism to mock my API, or provide information on how to fix the error.

**Environment (remove any that are not applicable):**
 - Library version: 3.1.0
 - OS: OSX

**Additional context**

I know there is a fix coming, but wanted to create an issue so that we add this to the test harness.

**Comment by XVincentX** [comment]
Note to self: this is not a valid OAS file but still want to make sure Prism spins up.

**Comment by philsturgeon** [comment]
Do we actually want Prism to run if its invalid? I don't think it should? How can we mock an OpenAPI document if its not an OpenAPI document?

**Comment by pytlesk4** [comment]
I feel like [this](https://github.com/stoplightio/http-spec/pull/12) conversation has happened like 10 times now. 

Yes, we should run. In the example spec above, we should def run, it especially because of how we let users create json schema files and reference them in an OAS spec.

At the very least, if we aren't going to, then I want to be able to actually fix an error. 

![](https://user-images.githubusercontent.com/2294309/64367389-7b9b2d00-cfdd-11e9-8dc1-e1bb724e433f.png)

That was not helpful at all.

**Comment by marbemac** [comment]
> Do we actually want Prism to run if its invalid? I don't think it should? How can we mock an OpenAPI document if its not an OpenAPI document?

Best effort, depending on degree of "incorrectness". If a document is totally invalid then we can't do anything, but where we can it's nice to be fault tolerant (in this case the invalid bit is using an array for types).

This is the same issue from http-spec, and this one re types in particular will be fixed when https://github.com/stoplightio/http-spec/pull/23 is resolved.

---

@pytlesk4 the issue title and description could be better - we won't be able to handle most invalid spec issues. If the user has a $schema property in some referenced model, or used a types array in some referenced model, we'll be able to handle it. This issue seems to be able types: array[] leading to an error, and wether or not we want to handle this case.

**Comment by XVincentX** [comment]
> Do we actually want Prism to run if its invalid? I don't think it should? How can we mock an OpenAPI document if its not an OpenAPI document?

Frankly this is starting to be a really big source of confusion to be. It's probably the 4th or 5th time one of these situations happen and I still hear two voices — but we never agree on something.

Side A: if the spec is wrong, we're going to tell you how a bad person you are and refuse to run our software

Side B: if your spec is wrong and you vomit on us, we're still going to thank you and try to run and fallback the stuff as much as I can.

Now I understand that we want a tradeoff, but I'm really struggling to draw the line between "this is not ok but we'll pretend it's ok" and "this is not ok and we're going to stop you"

I do not have an answer/solution for that, but I just wanted to point it out. Maybe we should at least keep track of the "non standard things we're going to fix for you" somewhere in a GitHub issue.

**Comment by philsturgeon** [comment]
@XVincentX I think we can summarize it like this:

> If your document is valid enough that whatever comes out of the json-schema-to-openapi-schema object is valid OpenAPI, then this is fine. Anything else and we error.

So we want valid OpenAPI documents, but we make an exception and allow certain bits of JSON Schema through as they'll be converted anyway.

Does that make sense?

**Comment by XVincentX** [comment]
Ok that makes sense. @philsturgeon maybe we should create a document in Prism documentation where we clearly outline the tradeoffs we're doing on the Schema object?

**Comment by philsturgeon** [comment]
Yeah! We should call it “JSON Schema Compatibility” or something. 

--
Phil Sturgeon
@philsturgeon
