### ISSUE TITLE
Mocked dynamic response content type not defined in OAS spec

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/prism#589]
**Describe the bug**
Prism mocks dynamic XML responses from the browser. XML is not defined in my spec.

**To Reproduce**

1. Given this OpenAPI document'

```yaml
openapi: 3.0.0
info:
  title: Example API
  version: '1.0'
  contact:
    name: Bear
    url: 'https://bear.dojo'
    email: pooh@bear.dojo
  termsOfService: 'https://bear.dojo/terms'
  description: The Bear Dojo API
paths:
  /honey:
    get:
      summary: Get Raw Honey
      responses:
        '200':
          description: 'Success, found the bears can have some honey.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  honey:
                    type: object
                    properties: 
                       name:
                         type: string
                       location:
                         type: string
                       species:
                         type: string
                         example: killer bees
                required:
                  - ok
                  - honey
      description: Get some raw honey.
      operationId: getRawHoney
```

2. Run this CLI command

`prism mock https://gist.githubusercontent.com/pytlesk4/ddbd7c6f791e68b2b34b0cbd6b11f250/raw/5170c01992bc43c8f8f335ec64ae5ca73257e6e8/bear.dojo.v1.yaml`

3. Open any browser and go to `http://localhost:4010/honey`.

![xml-response](https://user-images.githubusercontent.com/2294309/64368026-0c263d00-cfdf-11e9-8529-269769634449.gif)

**Expected behavior**

Dynamic JSON response.

**Environment (remove any that are not applicable):**
 - Library version: 3.1.0
 - OS: OSX
 - Browser: Firefox

**Comment by XVincentX** [comment]
Note to self: the serialized is not correctly checking that the Accept header and the reproducible format are in sync
