### ISSUE TITLE
When request doesn't contain proper security scheme, return the user-defined 401 first

### ISSUE THREAD

**Issue by LesterTheTester** [stoplightio/prism#591]
When a request to an endpoint does not meet the security scheme (i.e, lacking bearer token), Prism currently looks for a 422 definition, followed by a 400 definition, followed by 401.  This seems odd, if we have our own 401 defined, it should be the first one tried by Prism.

**To Reproduce**

1. Given an endpoint defined like so:

```
/users:
    get:
      summary: "Retrieves the authenticated user"
      description: "Returns the `user` object associated with the bearer token in the Authorization header."
      responses:
        200:
          $ref: '#/components/responses/SuccessfulUserResponse'
        400:
          description: "The provided user data was malformed, or attempted to modify a read-only field (such as `balance`)."
        401:
          $ref: '#/components/responses/InvalidAuthorizationTokenResponse'
```

2. Curl the endpoint without an "Authorization: Bearer" token
3. Prism log:

```
    [VALIDATOR] ⚠  warning   Request did not pass the validation rules
    [NEGOTIATOR] ●  note      Unable to find a 422 response definition
    [NEGOTIATOR] ✔  success   Found response 400. I'll try with it.
    [NEGOTIATOR] ●  note      Unable to find a content with an example defined for the response 400
    [NEGOTIATOR] ✔  success   The response 400 has a schema. I'll keep going with this one
    [NEGOTIATOR] ✔  success   Responding with the requested status code 400
```

**Expected behavior**
That the 401 we defined would be used first, before trying 422/400 since this is explicitly an authorization failure.

**Comment by philsturgeon** [comment]
Ahh yes for sure. I think this is another hint that it's time to refactor our validation logic. All headers/param/etc checking is "validation" and all validation uses 422/400, but "security validation" should not be triggering the same responses as that generic validation. It should look for 401 not 422/400. 

We'll get this ironed out.

**Comment by LesterTheTester** [comment]
Y'all the best! Thank you!
