### ISSUE TITLE
Conduct - No error when scenario/collection file doesn't exist or is invalid

### ISSUE THREAD

**Issue by mccataldo** [stoplightio/prism#6]
When running `prism conduct scenario.json` where `scenario.json` doesn't exist yields no output by prism. I would expect some error indicating that the file doesn't exist.

Likewise where `scenario.json` exists but is not valid, there's no output and I would expect an error indicating a problem with the file.

**Comment by marbemac** [comment]
Agreed on both fronts. @pytlesk4 we just talked about providing feedback when our api is down and the SRN fetch fails, but these are two more good cases. could you kind of audit and try to think of all the ways the various commands might fail for people, and basically add helpful feedback *everywhere*? :)

**Comment by pytlesk4** [comment]
Done, making some builds and pushing out.

**Comment by pytlesk4** [comment]
Fixed in Prism 0.6.5, just run prism update @mccataldo
