### ISSUE TITLE
Output validator is not checking the returned status code

### ISSUE THREAD

**Issue by XVincentX** [stoplightio/prism#647]
The Prism output validator is not checking out that the returned status code is in line with what specified in the contract/open api file;

We need this for the contract validation story; the returned status code should be within the defined responses for the current operation.

Question for @philsturgeon — if there's a default response, does it mean that *any* status code is ok? Maybe we mark is as a warning?

**Comment by philsturgeon** [comment]
Default can mean any that’s ok. No need for a warning. 

--
Phil Sturgeon
@philsturgeon
