### ISSUE TITLE
Reload Mock Server on Change

### ISSUE THREAD

**Issue by smizell** [stoplightio/prism#673]
**User story.**
As a developer, I can use my most up-to-date document for mocking without restarting the server, so that I can get quick feedback on my changes and work through changes iteratively.

**Is your feature request related to a problem?**
When working with developers new to Prism or API mocking in general, I've found they expect the server to automatically use their changes. However, they have to restart the server. Loading new changes automatically is something they expect.

It also comes up later when someone makes a change and forgets to restart.

**Describe the solution you'd like**
I'd like to see the mock server reloaded automatically. I'd like for the terminal to show it's been reloaded. We can use something like `nodemon` to handle this, but that's not what people are expecting.

**Comment by XVincentX** [comment]
@lag-of-death 

This stuff shall be implemented entirely in the CLI. We can use [chokidar](https://github.com/paulmillr/chokidar) to detect the file changes; when these are happening we should shutdown the current server and create a new one with the new operations array. Also, make sure to save the current options (such the running port) somewhere and reuse them.

Let men now if you need further help on this.

**Comment by kiranbpatil** [comment]
@XVincentX : I have started the prism server with a file in git repo. On change of the file in git, I don't see the prism server restarting. When tested with local file change, prism server reloads
Is this an expected behavior? Does the prism server track the file changes in git?

I am on the latest version of prism..

**Comment by philsturgeon** [comment]
@kiranbpatil When you change the local file, it works: good. When you change it in git, if the file is not local, it will not work. Prism has no concept of the file changing on a remote repository somewhere, it only reloads when the local file changes. For example, if in one terminal tab you had it running, and in another you did a git pull, then you'd see it reload. It will not reload without a pull.
