### ISSUE TITLE
Validate static examples with the provided response schema

### ISSUE THREAD

**Issue by chris-miaskowski** [stoplightio/prism#688]
**User story.**
As a User, I can ask Prism to validate that my static example meets the schema, so that I can assure my examples are correct.

**Is your feature request related to a problem?**

My Prism endpoint may have a response schema defined and additionally have some static examples defined. Currently when the static example doesn't match the schema Prism will say nothing and I may be using examples that aren't particularly useful.

**Describe the solution you'd like**

I would like to have an option to ask Prism to validate the static example it is returning against the schema the response defines. I'm not sure whether Prism should do it by default or whether it should be a parameter passed to Prism.

**Additional context**

Consider the following example

```
openapi: 3.0.0
paths:
  /path
    get:
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                example-1:
                  value: 123
              schema:
                  type: object
```

Instead of returning "123" I would like Prism to either return an error or warning telling that 123 does not match the defined schema.

**Comment by XVincentX** [comment]
@chris-miaskowski This issue has been solved already, it just hasn't been published yet. See the image

<img width="973" alt="image" src="https://user-images.githubusercontent.com/1416224/66388222-ecab7700-e9c5-11e9-8514-a06a813b0564.png">

**Comment by chris-miaskowski** [comment]
Oh, that's good enough! Looking forward to te feature being published.
