### ISSUE TITLE
The other query parameter is not validated

### ISSUE THREAD

**Issue by chris-miaskowski** [stoplightio/prism#692]
**To Reproduce**

1. create oas3 spec
2. add path
3. add two query params
4. make the "second" have some validations
5. run prism & make invalid request

```yaml
openapi: 3.0.0
servers:
  - url: 'http://localhost:3000'
paths:
  /path:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              examples: {}
      parameters:
        - schema:
            type: string
            maxLength: 3
            minLength: 1
          in: query
          name: a
          required: true
        - schema:
            type: string
            maxLength: 3
            minLength: 1
          in: query
          name: b
```

`curl 127.0.0.1:4010/path?a=2&b=633333`

**Expected behavior**

Should fail

**Actual**

200 OK

**Environment (remove any that are not applicable):**
 - Library version: 3.1.1

**Comment by XVincentX** [comment]
The posted command is incorrect; you need to quote the URL otherwise the sent query string won't  be the intended one.

`curl "http://127.0.0.1:4010/path?a=2&b=633333"`
