### ISSUE TITLE
prism does not find api spec if the scenario has variable in the request

### ISSUE THREAD

**Issue by goodwillguy** [stoplightio/prism#7]
In prism, while running scenarios with following example 
{$.ctx.host}/users/{$.ctx.user}/profile, it does not find the api specification /users/{id}/profile.

If substituted with a actual data like {$.ctx.host}/users/1/profile it will pick up the api specification

**Comment by pytlesk4** [comment]
Can you please provide an example scenario that demonstrates the issue, the command used for Prism, and Prism's version?

**Comment by pytlesk4** [comment]
Please provide a spec too.

**Comment by pytlesk4** [comment]
@goodwillguy 

{$.ctx.host}/users/{$.ctx.user}/profile is $.ctx.host set, should it be $.env.host?
