### ISSUE TITLE
Prism server always returns empty body response when "addtionalProperties" is false

### ISSUE THREAD

**Issue by henggai** [stoplightio/prism#715]
**Describe the bug**
When additionalProperties is false, Prism server always returns empty body response.

**To Reproduce**

1. OpenAPI specification:

```
openapi: 3.0.0
info:
  title: Sample API
  version: v1
paths:
  '/services/resources/{resource_id}':
    get:
      summary: Get a resource info.
      description: returns a single resource.
      operationId: getResource
      responses:
        '200':
          description: A resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
        '404':
          description: Not found.
components:
  schemas:
    Resource:
      type: object
      properties:
        name: 
          type: string
        tags:
          type: string
        createTime:
          type: string
          format: date-time
      additionalProperties: false
```

2. Start prism mock server and run curl http://localhost:4010/services/resources/5

**Current behavior**
 {}

**Expected behavior**
{
    "name": "aliquip",
    "tags": "",
    "createTime": "1985-06-04T11:15:57.166Z"
}

**Environment:**

Library version: 3.1.1
OS: MacOS Darwin Kernel Version 18.7.0

**Additional context**
The additionalProperties false means the properties not in the properties listed are not allowed in the request.  (Block the Invalid request). But the mock server should behave the same as addtionalProperties is true.

**Comment by XVincentX** [comment]
Verified. Apparently this is a bug in the underlying library we're using (json-schema-faker).

Although we're telling to generate optional values, for some reason it is ignoring the option value. I'll investigate and try to understand what is the problem (the library or the way we use it); in meantime you can workaround the problem by putting the properties you need in the schema's required array.

**Comment by XVincentX** [comment]
Yes confirmed, this is a bug in json-schema-faker.

**Comment by henggai** [comment]
Thank you!  Do you know when will be a new version released?

**Comment by XVincentX** [comment]
I think we're going to wait for #669 and #702 to get merged; then we will release 3.2.

**Comment by henggai** [comment]
Thank you!~~~

**Comment by XVincentX** [comment]
We have just released 3.2.0-beta.5 that fixes this issue. You can try it out installing Prism from npm with its beta tag

`npm i @stoplight/prism-cli@beta`

**Comment by henggai** [comment]
Hello,
Just asking again when will the next version be released?

Thanks
Henggai

**Comment by XVincentX** [comment]
We're in the process of verifying all the bits we've put in this version. We hope to make it happen within this week //cc @philsturgeon

**Comment by XVincentX** [comment]
Prism 3.2.0's been released!
