### ISSUE TITLE
Cannot find serializer for text/html

### ISSUE THREAD

**Issue by codeasashu** [stoplightio/prism#795]
**Describe the bug**
Unable to render `text/html` responses containing objects (per OAS 3.x, I can have objects within `text/html` block). Getting error:

```json
{
    "detail": "",
    "status": 500,
    "title": "Cannot find serializer for text/html",
    "type": "https://stoplight.io/prism/errors#UNKNOWN"
}
```
When making a valid request to schema path, having valid response within `text/html` content type, the response does not get parsed and error is returned.
 
**To Reproduce**
====spec====
```yaml
openapi: "3.0.1"
paths:
  "/path":
      get:
        responses:
          '200':
            content:
              text/text:
                schema:
                  properties:
                      status:
                        type: string
                      required:
                        - status
                  type: object
```

**Expected behavior**
I should be able to see the response in with the header type `text/html` in string if it have a valid response

**Environment (remove any that are not applicable):**
 - Library version: 3.0.0
 - OS: MacOS

**Comment by XVincentX** [comment]
@philsturgeon We're currently let text/plain pass through — maybe what we could do is to let pass through all the `text/*`?

**Comment by philsturgeon** [comment]
Yes that was the original plan but it didn’t get implemented that way I suppose. All text should be treated as text so text/* is great!

**Comment by XVincentX** [comment]
Sweet. @StefanDywersant ^ this is for you.
