### ISSUE TITLE
prism does not find the api specification if the host name in scenarios different from swagger host

### ISSUE THREAD

**Issue by goodwillguy** [stoplightio/prism#8]
The swagger files contains the host as "www.abc.com", when running prism test with command "prism conduct scenario.json -s swagger.json  --env host="localhost". 

The api specification is not found.

**Comment by pytlesk4** [comment]
Can you please provide an example scenario that demonstrates the issue, the command used for Prism, and Prism's version?

**Comment by pytlesk4** [comment]
Please provide a spec too.

**Comment by pytlesk4** [comment]
This is fixed, and I will be releasing a new binary sometime today for it.

**Comment by pytlesk4** [comment]
fixed with release https://github.com/stoplightio/prism/releases/tag/v0.6.13
