### ISSUE TITLE
DNS lookup fails when running prism

### ISSUE THREAD

**Issue by meahow** [stoplightio/prism#80]
When running tutorial command
`prism run --mock --list --spec http://petstore.swagger.io/v2/swagger.json`
i get 
`Error Loading from swagger spec: Get http://petstore.swagger.io/v2/swagger.json: dial tcp: lookup petstore.swagger.io: no such host`
and no endpoints are being created nor processed.

Prism version is 0.6.21

I run Ubuntu 16.10, it runs ok on ubuntu xenial docker image.

**Comment by pytlesk4** [comment]
@meahow are you still running into this issue? Or can it be closed now?

**Comment by meahow** [comment]
@pytlesk4  I don't see why this would be fixed (since there was no 0.6.x release since then), but when I just tried to run it in the same environment, it was complaining on different issues, relevant to the remote side (connection reset).
Let's close it, then.

**Comment by pytlesk4** [comment]
@meahow it looks like something is wrong with the url: http://petstore.swagger.io/v2/swagger.json

When I open it up in my browser, I get a 503. If I keep refreshing eventually I can load the spec, took me about 3/4 times. We will update the link on the prism page.
