### ISSUE TITLE
Proxy/Violations Feedback

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/prism#805]
1. Getting `{"location":["response"],"severity":"Error","message":"The received media type does not match the one specified in the document"}` is not very descriptive. I can see which media type is in the response, sure, but in logs it is even less descriptive. 

<img width="715" alt="image" src="https://user-images.githubusercontent.com/67381/68857962-ed79ac00-06db-11ea-8d09-57b705a7da3b.png">

Telling the user which media type was the problem would help for logs and for scraping sl-violations. 

2. I would not expect to see "The received media type does not match **the one** specified in the document" in a document where I have multiple media type objects defined. I had application/json and application/xml and it still said "the one". It could say "The received media type has not been defined"

3. Requesting invalid route returns error by default

```
$ http GET http://127.0.0.1:4010/nonsense
HTTP/1.1 404 Not Found
Connection: keep-alive
Date: Thu, 14 Nov 2019 12:45:45 GMT
access-control-allow-origin: *
content-length: 200
content-type: application/problem+json

{
    "detail": "The route /nonsense hasn't been found in the specification file",
    "status": 404,
    "title": "Route not resolved, no path matched",
    "type": "https://stoplight.io/prism/errors#NO_PATH_MATCHED_ERROR"
}
```

When running in log mode, prism proxy should be trucking along and making requests to the upstream server regardless of what happens, and reporting issues to logs and sl-violations. Requesting a totally invalid URL blows up with a problem+json. 

4. Proxy logs could tell me what upstream request is being made

I see this:

```
[HTTP SERVER] get /pet/123 ℹ  info      Request received
    [VALIDATOR] ✖  error     Violation: response The received media type does not match the one specified in the document
    [VALIDATOR] ✖  error     Violation: request Invalid security scheme used
```

It's rather tricky for me to now debug this, as I have to figure out the actual URL being made from copying and pasting various strings: `https://petstore.swagger.io/` from the command I wrote and `/pet/123` from the HTTP server. logging the full URL would make debugging easier.

```
[HTTP SERVER] get /pet/123 ℹ  info      Request received
    [PROXY] Making request to upstream server: https://petstore.swagger.io/pet/123
    [VALIDATOR] ✖  error     Violation: response The received media type does not match the one specified in the document
    [VALIDATOR] ✖  error     Violation: request Invalid security scheme used
```

5. violations when logged are joining arrays of bits of JSON Paths with commas: `error     Violation: response,body,photoUrls[0] should match format "url"`

6. enums are logged with incomplete information: `error     Violation: response,body,status should be equal to one of the allowed values`

7. enums in JSON are incomplete too:

```json
        {
            "code": "enum",
            "location": [
                "response",
                "body",
                "status"
            ],
            "message": "should be equal to one of the allowed values",
            "severity": "Error"
        },
```

8. "Unable to match the returned status code with those defined in spec" again could we mention the status code, and could we not say "spec" as we talk about documents to be short, or "description documents"  

9. Indentation is looking a little funny here:

<img width="523" alt="image" src="https://user-images.githubusercontent.com/67381/68859227-b789f700-06de-11ea-8be5-331c4d49fddc.png">

**Comment by XVincentX** [comment]
Points 1 and 2 are not true anymore, you were probably using an old version of the source code. The new message is:

`The received media type "${mediaType}" does not match the one(s) specified in the current response: ${contents.map(c => c.mediaType).join(', ')}`

//cc @philsturgeon

**Comment by StefanDywersant** [comment]
There is still something wrong though:
`curl -v -H'Accept: application/karol' http://127.0.0.1:4011/no_auth/pets/891`

Proxy console:
```
[2:31:56 PM] › [HTTP SERVER] get /no_auth/pets/891 ℹ  info      Request received
[2:31:56 PM] ›     [VALIDATOR] ✖  error     Violation: response,body,id should match format "int64"
[2:31:56 PM] ›     [VALIDATOR] ✖  error     Violation: response,body,category,id should match format "int64"
[2:31:56 PM] ›     [VALIDATOR] ✖  error     Violation: response,body,tags[0],id should match format "int64"
[2:31:56 PM] › [HTTP SERVER] ⚠  warning   Reply already sent
```

1. what is `Reply already sent?`
2. I need to verify those data violations, it shouldn't occur
3. I did sent a request with weird header, I see no complaints

**Comment by StefanDywersant** [comment]
> There is still something wrong though:

Sorry for not being descriptive enough.

In order to replicate, you shall start two instances of Prism (`master` branch):
1. `yarn cli mock -p 4010 ../../examples/petstore.oas3.json`
2. ` yarn cli proxy -p 4011 ../../examples/petstore.oas3.json http://localhost:4010`

Then call:
`curl -v -H'Accept: application/karol' http://127.0.0.1:4011/no_auth/pets/891`

Then watch it exploding!

**Comment by XVincentX** [comment]
1. The data violations are effectively correct. When using static examples, OpenAPI3 sampler is ignoring the `format` parameter (in our test document is 404, and so the generated examples are effectively not compliant by definition. I've opened an issue about this: https://github.com/Redocly/openapi-sampler/issues/62

2. In proxy mode effectively we're skipping the negotiation process which checks the `Accept` header. I'll see if we can add a dedicated check for it.

**Comment by XVincentX** [comment]
@philsturgeon Can you grab the latest master branch and try it out? I haven't finished the verification yet but I am quite sure we've addressed all the points.

**Comment by philsturgeon** [comment]
This is great. I haven't tested every single possible error but you seem to have fixed the concerns I raised in this issue.
