### ISSUE TITLE
Add Chalk to dependencies list

### ISSUE THREAD

**Issue by Arual90** [stoplightio/prism#853]
Hello,
I have installed the version **3.2.0** of **@stoplight/prism-cli**

Executing the command `prism mock ./swagger.yml -p 8086` i receive the following error:
```
/Users/me/Documents/app/node_modules/@stoplight/prism-cli/dist/const/options.js:5
    CLI: { index: 0, color: chalk_1.default.bgWhiteBright },
                                            ^

TypeError: Cannot read property 'bgWhiteBright' of undefined
    at Object.<anonymous> (/Users/me/Documents/app/node_modules/@stoplight/prism-cli/dist/const/options.js:5:45)
```

My app uses **chalk** version **3.0.0** and i noticed that **prism-cli** have no **chalk** dependency defined in the `package.json` even if it uses it, this way it resolves using the globally installed version 3 which is not the version it needs.

I think adding the line `"chalk": "2.4.2"` to prism-cli package.json would resolve this little dependency problem

**Comment by XVincentX** [comment]
Minchia — questa non me la aspettavo @Arual90 

Yeah, I think for some reason the dependency has been removed by mistake. I'll open a PR to close this.

**Comment by XVincentX** [comment]
@Arual90 Che versione di node e npm stai usando?

**Comment by Arual90** [comment]
Sto usando Node 10, probabilmente gestisce la cosa diversamente
Grazie per il fix ;)
