### ISSUE TITLE
Path param validation fails with kebab-case param

### ISSUE THREAD

**Issue by pgoshulak** [stoplightio/prism#858]
**Describe the bug**
Prism fails to validate path parameters when given as kebab-case, instead returning Error 422 Invalid Request Body Payload

**To Reproduce**
1. Given this OpenAPI document:
https://gist.github.com/pgoshulak/76f582cb34673e60be4b5ecdd059b9d9
2. Run this CLI command
```
prism mock <file.yaml>
```
Send request:
```
curl http://127.0.0.1:4010/organizations/42
```
3. See error: Prism returns error 422: `https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY: Invalid request body payload`
4. Change lines 5, 14 in example `.yaml` file from `organization-id` to `organizationId`
5. Rerun `prism mock` and `curl` commands
6. Data is return correctly

**Expected behavior**
Path parameter given in kebab-case is allowed; request with kebab-case parameter returns `200`.

**Environment (remove any that are not applicable):**
 - Library version: 3.2.0
 - OS: Ubuntu 18
 - Browser: N/A

**Comment by XVincentX** [comment]
Hey,

effectively I've noticed that the underlying library we're using to extract the parameters is failing when a parameter has a dash; I've tried another library as well having the same issue.

What's funny though, the spec seems to make clear that the dash is a supported char. I'll look a little bit more into that.

https://github.com/litejs/uri-template-lite/issues/1

**Comment by pgoshulak** [comment]
Further on the spec, we use [swagger-cli](https://www.npmjs.com/package/swagger-cli) to bundle and validate our `.yaml` files, and [openapi-generator-cli](https://www.npmjs.com/package/@openapitools/openapi-generator-cli) to generate client packages - both of them seem to be ok with dashes in the params

Thanks for looking into this so quickly :)

**Comment by pgoshulak** [comment]
for anyone encountering this issue, my hacky workaround is to replace all kebab-case params with camelCase directly in the `.yaml` file. We only use path params so renaming these params seems to be ok. 

In our particular use case, it's always `user-id` or `organization-id`, always `*-id`, so we can run `sed -i s/-id/Id/g api-spec.yaml` to replace all `-id` with `Id`. Use with caution of course

**Comment by XVincentX** [comment]
@pgoshulak Apparently `-` is not allowed.

varspec is defined in [section 2.3](https://tools.ietf.org/html/rfc6570#section-2.3)

```
variable-list =  varspec *( "," varspec )
varspec       =  varname [ modifier-level4 ]
varname       =  varchar *( ["."] varchar )
varchar       =  ALPHA / DIGIT / "_" / pct-encoded
```
