### ISSUE TITLE
npm install fails at CI

### ISSUE THREAD

**Issue by luckylooke** [stoplightio/prism#859]
First of all, thank you for great library, works well! :)
It only fails to install in my pipeline 🤷‍♂ 

**Describe the bug**
For some reason npm install of your package does not install on my Gitlab CI pipeline.

**To Reproduce**

1. have prism-cli in package.json dependencies
2. push it to gitlab repo with CI
3. See error:
```
npm ci
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/stoplightio/openapi-schema-to-json-schema.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```
It seems like it cannot install some dependency without presence of git... but why it is git dependant? There are planty other packages, none of them have problem with missing git.

**Expected behavior**
pass pipeline without need of git installation

Thanks

**Comment by luckylooke** [comment]
For now, I have put `@stoplight/prism-cli` as optionalDependency and installing in CI with "no optional" flag `npm ci --no-optional` because I dont need the package for any CI task.. I use it just locally in development. 🙂

**Comment by luckylooke** [comment]
Ok, I have found out that git dependencies are supported as feature of npm but git is not included in node apline image because it is too big, and they choose to keep it small rather then support all building features of npm (https://github.com/nodejs/docker-node/pull/367), so I have two options here.. keep it as peerDependency  or use some docker image with git included just to be able to install package I dont need for build 🤔 Anyway, closing this because it is not issue of prism package.

**Comment by XVincentX** [comment]
@luckylooke Or use Docker Multi Stage build feature (we use it in Prism's docker image as well)
