### ISSUE TITLE
Change $$.ctx to $$.data (or figure out what to do here)

### ISSUE THREAD

**Issue by marbemac** [stoplightio/prism#86]

**Comment by bradobro** [comment]
I'd like to see `$$.ctx`, `$.env`, and `$.data` with these distinct purposes:

 - `$$.ctx` - data isolated to a scenario (very powerful--BDD folks can treat it like the per-feature test world most Cucumber implementations use). This is crucial for parallel test runs.
- `$.env` - key config and settings, common to the whole collection--the sort of things that change across environments, like host names and ports. Changing `$.env` during a run should usually be considered a smell.
- `$.data` - fixture data, shared across the whole collection, but not persisted or shared like `$.env` is when Stoplight is restarted. Typical use will be to fill it during some *Before* script and request steps. (I suppose some people will want to write to it during steps, but then you'd need a write mutex for parallel runs...maybe? Sounds like a good recipe for making order-dependent scenarios.)
