### ISSUE TITLE
Export createClientFromResource from prism-http

### ISSUE THREAD

**Issue by adrianosmond** [stoplightio/prism#877]
[The docs](https://stoplight.io/p/docs/gh/stoplightio/prism/docs/guides/client.md) talk about `createClientFromResource`, but that isn't exported from. `@stoplight/prism-http`. 

It should be, right? Or have I misunderstood?

I could get it by going into `dist/client` like:
`const {createClientFromResource} = require('@stoplight/prism-http/dist/client');`
but I don't think that's the intended way to access it, is it?

**Comment by XVincentX** [comment]
It is the intended way, although there's a failure in the documentation. HTTP is a generic package with (probably) too much stuff inside.

**Comment by adrianosmond** [comment]
Yeah the docs could really use some love! Thanks for a quick response.
