### ISSUE TITLE
Docker Image Compatibility with Jenkins Kuberenetes Plugin: Be Able to use Docker Image Interactively OOB

### ISSUE THREAD

**Issue by julianwilkinson** [stoplightio/prism#878]
**User story.**
I would like to be able to run Prism in Jenkins as a container 

**Is your feature request related to a problem?**
Out of the Box you can't use the default Prism image in Jenkins using the Jenkins Kubernetes Plugin)

**Describe the solution you'd like**
Maybe there could be an interactive variant of the docker image, or just let the prism command be executable from the shell?

**Comment by XVincentX** [comment]
Hey,

I am not really familiar with Jenkins system as a container and the Prism command is effectively excitable from the shell if you use the `exec` command in docker instead of the regular run. Would it be possible to get more details?

Feel free to reopen or respond once you have more data for me!

Thanks!

**Comment by julianwilkinson** [comment]
Hey thanks for responding so quickly,


Basically Jenkins in Kubernetes is run by the overarching Jenkins master orchestrating at least one new Jenkins "agent" (sometimes referred to as a slave) as a Kubernetes Pod. In these pods you specify containers with tools you want to use and then inside your pipeline you can use the shell in those containers to execute commands. The Jenkins workspace is mounted to each container so the idea for Prism would be to have Prism run, have tests performed, and then have Prism output the proper artifact for the Prism Jenkins plugin.

Correct me if I'm wrong but when running prism using the docket command it will exit?


Thanks,
Julian

**Comment by XVincentX** [comment]
I am a little bit unprepared here — to help you I would need to check out what is going on or you'd need to paste here some evidences (logs, screenshots).

> Correct me if I'm wrong but when running prism using the docket command it will exit?

This seems to be incorrect to me. Prism is a long running server and won't stop as long you do not send a signal it won't stop. You can verify this by yourself by running the docker image:

`docker run --init stoplight/prism:3 mock https://raw.githack.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore-expanded.yaml`

Here's the result:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1416224/70278457-9e8fd580-17b4-11ea-8d45-23cb29dba49a.png">


You can see that the server is not exiting but waiting for the connection. Is this what you were referring to?
