### ISSUE TITLE
v2.0.0-beta.0 | exist tests are detected as NOT to exist

### ISSUE THREAD

**Issue by krismeister** [stoplightio/prism#88]
The newest prism, breaks the EXISTs tests from the Stoplight Scenarios tools.
It looks like its changing `exist` into `NOT to exist`

This bug was not present in previous versions.

previous output from `v2.0.0-alpha.7`:
```
POST http://localhost:4000/v1/login (0.206s)
         ✓  output.status (eq) 200
         ✓  output.body.status.code (eq) 200
         ✓  output.body.data.token (exists) <nil>
         ✓  output.body (validate.contract) against JSON Schema
```

output from `v2.0.0-beta.0`:
```
      , POST http://localhost:4000/v1/login (0.202s)
         ✗  Expected output.body.data.token NOT to exist - actual is 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1OWRkMTcwMmZjMzRiMDdkMWJlZTM4OWQiLCJpYXQiOjE1MDc4NDM5Mjl9.AAt-2xn56Aq3pQURPaqNy_9QZMkrmrkn3fAXdIQorTQ'
         ✓  output.status (eq) 200
         ✓  output.body.status.code (eq) 200
         ✓  output.body (validate.contract) against JSON Schema
```

**Comment by pytlesk4** [comment]
Good catch, got a fix for you, will be releasing it in a couple days. In the meantime, can you update the exist assertion. If you add "expected": true, it will work.

**Comment by krismeister** [comment]
"expected" isn't an option in the assertions area in the scenarios tool (v3.4.1) We're fine to remove these asssertions for now.
