### ISSUE TITLE
Uncaught Validation Exception

### ISSUE THREAD

**Issue by AndrewBell** [stoplightio/prism#894]
**Describe the bug**

When validating a response, AJV can throw (an uncaught) exception, causing Prism to hang. We've been using `examples` and we're seeing an unhandled promise rejection from the AJV `validate` used [here](https://github.com/stoplightio/prism/blob/3cdc07f4bfc8ddf4945b3f925b95e4b7eb66b332/packages/http/src/validator/validators/utils.ts#L39)

~We've also noticed the error appears slightly differently depending on if I run Prism from an npm global package:~

<Error from 3.2.1 Redacted, 3.2.2 gives the same error message shown below>

~But, if we build from source, we get an error in a different spot. But we were able to at least see that it was a validation error.~

Here's the exception we're seeing:

```
(node:53106) UnhandledPromiseRejectionWarning: TypeError: Cannot assign to read only property 'areaCode' of object '#<Object>'
    at validate (eval at localCompile (/Users/andrew.bell/workspace/prism/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:29309)
    at pipeable_1.pipe.O.mapNullable.validate (/Users/andrew.bell/workspace/prism/packages/http/src/validator/validators/utils.ts:39:7)
    at /Users/andrew.bell/workspace/prism/node_modules/fp-ts/lib/Option.js:356:77
    at Object.pipe (/Users/andrew.bell/workspace/prism/node_modules/fp-ts/lib/pipeable.js:13:26)
    at Object.exports.validateAgainstSchema (/Users/andrew.bell/workspace/prism/packages/http/src/validator/validators/utils.ts:36:3)
    at pipeable_1.pipe.O.fold (/Users/andrew.bell/workspace/prism/packages/http/src/validator/validators/body.ts:111:19)
    at /Users/andrew.bell/workspace/prism/node_modules/fp-ts/lib/Option.js:87:49
    at Object.pipe (/Users/andrew.bell/workspace/prism/node_modules/fp-ts/lib/pipeable.js:13:23)
    at pipeable_1.pipe.O.fold (/Users/andrew.bell/workspace/prism/packages/http/src/validator/validators/body.ts:105:11)
    at /Users/andrew.bell/workspace/prism/node_modules/fp-ts/lib/Option.js:87:60
```

In both situations, an HTTP response is not returned, and the server hangs.

**To Reproduce**

~Unfortunately, I have not been able to reproduce this externally. I'm unsure what is different about our spec that would cause this behavior.~ See below for example spec

**Expected behavior**

Exception to be caught and added to the list of validation errors.

**Environment (remove any that are not applicable):**
 - Library version: 3.2.2
 - OS: OSX Mojave 10.14.6

**Additional context**

I took a very amateur shot at fixing by wrapping the `validate` call with an `O.tryCatch`. This prevented Prism from hanging, but (understandably) doesn't add the validation error. [Added here](https://github.com/stoplightio/prism/blob/3cdc07f4bfc8ddf4945b3f925b95e4b7eb66b332/packages/http/src/validator/validators/utils.ts#L39)

Thank you for taking a look! If you have any suggestions for implementation, I can take a shot at a fix.

**Comment by XVincentX** [comment]
@AndrewBell Would it be possible to share with us the offending document?

**Comment by AndrewBell** [comment]
Unfortunately it's very large and full of IP. I've been trying to re-create a 'petstore' example, but haven't had any luck. I'll try to see if I can't recreate, if not maybe someone else runs into this too.

**Comment by AndrewBell** [comment]
Thanks for your patience, I was able to extract a failing example. You'll see at the end `areaCode`. The int is rightly invalid (schema defines as a string), but when I try to get a mocked response for this endpoint, Prism hangs. If I correct it to a String, it works fine. 

Still seeing the same error as above, although I'll note that once I upgraded my npm version of prism, it no longer gave me the `target.split` error, and instead returns the same `Cannot assign to read only property 'areaCode' of object '#<Object>'` as I see when building and running from source.

```
openapi: 3.0.2
info:
  contact:
    email: "andrew@recursivechaos.com"
  title: "Example API"
  version: 1.0.0
paths:
  /v1/addresses:
    get:
      description: 'A description'
      operationId: v1.getAddresses
      responses:
        200:
          $ref: '#/components/responses/GetAddressesOk'
components:
  responses:
    GetAddressesOk:
      content:
        application/json:
          examples:
            Phone:
              description: Stubbed response containing only Phone type Addresses
              value:
                results:
                - $ref: '#/components/examples/Phone'
          schema:
            properties:
              results:
                items:
                  discriminator:
                    propertyName: addressType
                  oneOf:
                  - $ref: '#/components/schemas/PhoneNumber'
                type: array
            required:
            - results
            type: object
      description: Successful operation
  schemas:
    AddressType:
      description: 'Address Type'
      enum:
      - PHONE_NUMBER
      - EMAIL_ADDRESS
      - POSTAL_ADDRESS
      type: string
    Address:
      description: A set of information used to locate someone or something
      properties:
        addressType:
          allOf:
          - $ref: '#/components/schemas/AddressType'
          description: The type of address
        id:
          description: 'The unique identifier of the address.'
          format: uuid
          readOnly: true
          type: string  
    PhoneNumber:
      allOf:
      - $ref: '#/components/schemas/Address'
      - properties:
          areaCode:
            type: string
          phoneNumber:
            type: string
        required:
        - phoneNumber
        type: object
      description: The sequence of digits used to connect to a specific telephone     
  examples:
    Phone:
      id: 3face8ee-0000-0000-0000-d4d75640cefc
      addressType: PHONE_NUMBER
      phoneType: MOBILE
      # Comment/Uncomment below to trigger exception
      areaCode: 206 # Invalid property - causes Prism to hang
      # areaCode: "206" # Valid property - Prism behaves as expected
      phoneNumber: "2064147850"
```

**Comment by XVincentX** [comment]
Ok I think I've been able to identify the problem; ajv is trying to overwrite the source object with something. Most likely it's trying to coerce the `206` from number to string because of the schema definition. We should handle this gracefully.

**Comment by XVincentX** [comment]
@AndrewBell #905 should fix it. Can you pull the branch down and try it out?

**Comment by AndrewBell** [comment]
That did the trick, I confirmed with both the shared example and the problem spec. I can see the errors coming through on the header as well. Thanks for the quick turnaround, and let me know if there's anything else I can do to help!

**Comment by XVincentX** [comment]
Keep using Prism :trollface:
