### ISSUE TITLE
How to run api and prism on differnet ports

### ISSUE THREAD

**Issue by irfanyusanif1** [stoplightio/prism#919]
**Installation**
I installed prism using command 
`npm install -g @stoplight/prism-cli`

**Run mock server**
I used following command to run mock server and start mocking:
`prism mock -p 7000 C:\Users\other-folders\authorizationapi.v1.yaml`

It starts listing at `http://127.0.0.1:7000`.  Here is the screenshot
![image](https://user-images.githubusercontent.com/59409772/71640284-13b5d400-2ca9-11ea-9f28-a91a534b92e7.png)
But then nothing happens because api is also hosted on 7000. 

How can I run api and mock server on different ports?

**Update:**
If I host the api on port 8000, then api will work on url `http://127.0.0.1:8000/api/login` but when I run prism on port 7000 then prism will hit the url `http://127.0.0.1:7000/api/login` but api is now on 8000. 

How can I run prism server on port 7000 and it should hit api on port 8000.

**Comment by XVincentX** [comment]
I am afraid I do not understand the question. From the informations you provided it seems like you need to use the `proxy` command, not the `mock` one.

Feel free to reopen in case you need any more help.
