### ISSUE TITLE
Validate server response if compliant according to openapi spec

### ISSUE THREAD

**Issue by dario-frongillo** [stoplightio/prism#920]
**User story.**
I have a suite of test i need a tool ( a jar for ex or a javascript module) that validate a server response.. for example in my script i invoke an api that return a json... i want to validate if that response is compliant according to my openapi yaml. for example if the json refer user model that have username required .. if the response not contains username response i want that the tool raise an error.
Prism or stoplight other tools support this feature ?

**Comment by XVincentX** [comment]
Hey Dario,

Prism effettivamente supporta questa funzionalità usando il comando `proxy` invece del comando `mock`

https://github.com/stoplightio/prism/blob/master/docs/guides/cli.md#proxy

Da qui poi potrai selezionare il modo di reporting degli errori in fase di validazione della risposta:

`prism proxy examples/petstore.oas2.yaml https://petstore.swagger.io/v2 --errors`

Saluti da Austin, TX!

V.
