### ISSUE TITLE
Use range defined in data type

### ISSUE THREAD

**Issue by nicodh** [stoplightio/prism#928]
In OpenAPI v3 it is possible to define a minimum and a maximum for type number like that:
type: number
minimum: 0
exclusiveMinimum: true
maximum: 50

It would be great if the mocked data would reflect these boundaries to produce a more realistic data set. For example if I have a property holding a temperature I get values like -32532.345234 at the moment instead of random numbers in a realistic range

**Comment by XVincentX** [comment]
This is indeed supported in Prism and it works correctly with a sample document I just created:

```yml
openapi: 3.0.0
paths:
  '/pet/{petId}':
    get:
      summary: Find pet by ID
      description: Returns a single pet
      operationId: getPetById
      parameters:
        - name: petId
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  age:
                    type: integer
                    minimum: 1
                    maximum: 50
                required:
                  - age
```

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/1416224/72713276-118abb00-3b6d-11ea-9293-1cfc39bc7313.png">


Can you verify and provide the offending document?

**Comment by joh-klein** [comment]
I had the same issue. The problem was, that it wasn't clear to me, that you can either define `format` OR `minimum/maximum`,  but not both. So

```yaml
type: integer
format: int32
```
OR

```yaml
type: integer
minimum: 1
maximum: 50
```

But not both:
```yaml
type: integer
format: int32
minimum: 1
maximum: 50
```
