### ISSUE TITLE
Prism v2 how to run - there is no RUN command

### ISSUE THREAD

**Issue by FastNinja** [stoplightio/prism#93]
Hi there,
trying to use Prism 2 (alpha) but struggling to start it - there is no `run` command similar to Prism 0.6.x?
Tried to search for source code - but failed to do so..
Thank you!

**Comment by krismeister** [comment]
This is how we run it in our CI:

```
prism conduct "./collections/definition.json" --spec "./specs/api.json" --env "./variables.json"
```

The paths are relative to where the command is being run.

**Comment by pytlesk4** [comment]
@FastNinja prism 0.6.x to 2 is a complete rewrite, so the prism run command is removed. As I type this we are preparing for a big release tomorrow, and prism will have a serve command( `prism serve` ), which will run a prism server instance. Will release some much needed docs as well.
