### ISSUE TITLE
Can't create Prism Client 

### ISSUE THREAD

**Issue by AwesomeRei** [stoplightio/prism#934]
Hi, I've used prism to build a server stub from OpenApi 3 Specs. 
I've installed prism and successful on creating the server. Now I want to create client, but I find it difficult to understand where do I have to put this code, and how do I run it. I've tried using node but it won't work it says 
UnhandledPromiseRejectionWarning: ReferenceError: createClientFromResource is not defined

I think prism works great. just need a little bit more tweaking on the documentation

**Comment by XVincentX** [comment]
We do have some documentation about using the client, did you check it out?

https://github.com/stoplightio/prism/blob/master/docs/guides/client.md#create-from-a-filename-or-http-resource

```ts
const client = require('@stoplight/prism-http/dist/client')
…
…
```
