### ISSUE TITLE
Mock returns example value as number while type: string was defined

### ISSUE THREAD

**Issue by RonaldvdH** [stoplightio/prism#935]
**Describe the bug**
After updating @stoplight/prism-cli from 3.2.1 to 3.2.3 a property defined as type: string was returned as number. The example value was not encapsulated with quotes (") and only contained numbers

**To Reproduce**

1. Given this OpenAPI document
```
openapi: 3.0.0
info:
  title: example
  version: 0.0.1
paths:
  /path/:
    get:
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'

components:
  schemas:
    Response:
      type: object
      properties:
        stringTypeString:
          type: string
          example: string
        numberTypeString:
          type: string
          example: 10001
```

2. Run this CLI command 'prism mock api.aos3.yaml' (create file with contents of step 1)
3. See error -> When calling the endpoint path the property 'numberTypeString' will be returned as number

**Expected behavior**
I expect the response to be a string as type string is defined in the OpenAPI document

**Environment**
 - Library version: 3.2.1
 - OS: windows 10
 - Browser: Edge 81

**Additional context**
Encapsulating the type string example value with quotes (") fixed the issue for me but it is weird that the type is defined but not taken into account.

**Comment by XVincentX** [comment]
Hey @RonaldvdH ,

I've just tried with Prism 3.2.1 and it is behaving in the same way of Prism 3.2.3 (which is right, we didn't touch that part at all during these two releases)

The example property shall return a complete example with the correct encoding out of the box (this is the spec), thus you should effectively quote the value in the document.

If you can reproduce with another document (I used the one you pasted here) feel free to reopen or add more details.

Thanks!
