### ISSUE TITLE
Q: run prism mock along an angular app on ngix docker

### ISSUE THREAD

**Issue by skorunka** [stoplightio/prism#937]
I have a docker linux image with ngix which hosts the angular app. It is possible to run the prism mock server in the same docker image?

In other words, I would like to have ngix to host an Angular app and run the `prism-cli mock api.yaml -- port 4500` at the same time. Api requests would be proxied to the internal 4500 port.

If the above is not possible, I could actually create a new container to run the `prism-cli`... but I don't know how to build the image. The following doesn't work for me:

```
FROM stoplight/prism:3
EXPOSE 4010
COPY api.yaml .
ENTRYPOINT ["prism-cli" "mock", "api.yaml", "--port", "4010"]
```

after `docker run` I get 

```
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'micri'
Require stack:
- /usr/src/prism/packages/http-server/dist/server.js
- /usr/src/prism/packages/http-server/dist/index.js
- /usr/src/prism/packages/cli/dist/util/createServer.js
- /usr/src/prism/packages/cli/dist/commands/mock.js
- /usr/src/prism/packages/cli/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/prism/packages/http-server/dist/server.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/prism/packages/http-server/dist/server.js',
    '/usr/src/prism/packages/http-server/dist/index.js',
    '/usr/src/prism/packages/cli/dist/util/createServer.js',
    '/usr/src/prism/packages/cli/dist/commands/mock.js',
    '/usr/src/prism/packages/cli/dist/index.js'
  ]
}
```

Thank you.

**Comment by XVincentX** [comment]
You're using the docker image incorrectly — the entry point you put is wrong and won't work. 

This is way better:

`docker run -P --init stoplight/prism:3 mock -h 0.0.0.0 file.yml`

…but if you really want to use it in your way, this is the Dockerfile you should be using

```dockerfile
FROM stoplight/prism:3
EXPOSE 4010
ENTRYPOINT ["node", "./dist/index.js", "mock", "https://raw.githack.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore-expanded.yaml", "--port", "4010","-h","0.0.0.0"]
```

**Comment by mottolini** [comment]
Another possibility that I found it works, especially if you have a complex definition that you would deploy easily in a kubernetes cluster, is to create your own Dockerfile:

    FROM stoplight/prism:3
    RUN mkdir /usr/src/prism/packages/cli/api
    COPY ./openapi /usr/src/prism/packages/cli/api/
    CMD ["mock", "./api/openapi.v1.yaml", "-h", "0.0.0.0"]
    EXPOSE 4010
