### ISSUE TITLE
Add a signal or a way to notify users that prism is up and running

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/prism#95]
- Right now sendgrid has to put in a 20 second delay to wait for Prism to startup and create a server. It is really gross.

**Comment by philsturgeon** [comment]
@pytlesk4 did you come up with an idea for how this could be done? We should either close it, or make a plan for v3.

**Comment by pytlesk4** [comment]
@philsturgeon SendGrid wanted this for prism v1, and told them I would try to get it in for v2. Right now in their unit tests for their SDKs, they run prism v1 in docker, and set a timeout to wait for prism to spin up a mock server. They just want a way to know when prism is up and running so they can start running their tests. 

Example -> https://github.com/sendgrid/sendgrid-go/blob/master/sendgrid_test.go#L106

**Comment by XVincentX** [comment]
This is not a Prism specific issue — every software that needs to be spun up will have this kind of issue. 

In general, you do not spin up a process from another process.

I suggest to use [dockerize](https://github.com/jwilder/dockerize) to check out when the software is running.

`dockerize -wait tcp://localhost:4010 -timeout 10s` or also `dockerize -wait http://localhost:80`

If you *really* need to do that, the most reliable way is to attach to the new process's stdout and wait for some string, such as `Prism is listening`

**Comment by philsturgeon** [comment]
Yeah I think this is a pretty common problem for anything. Kuber has tcpSocket for this sort of reason, and @XVincentX has demo'ed the docker approach. Let's close this down to make space for Prism v3.0 work.
