### ISSUE TITLE
Support for AWS API Gateway

### ISSUE THREAD

**Issue by johanntang** [stoplightio/prism#951]
**User story.**
As a user of AWS API Gateway I can use JSON schema draft 4, so that I can run a prism mock server.

**Is your feature request related to a problem?**
Get a fatal error "There's been an error while trying to resolve external references in your document"  

**Describe the solution you'd like**
Prism to be able to read a .yml that uses the aws api gateway spec to start a mock server

**Additional context**

**Comment by XVincentX** [comment]
@johanntang We're going to need more details in order to help you out with this. Can you provide an example document we can look at?

**Comment by XVincentX** [comment]
Closing until more details are provided.
