### ISSUE TITLE
Make sure matchBaseUrl does not throw

### ISSUE THREAD

**Issue by XVincentX** [stoplightio/prism#960]
In Prism we try to never throw exceptions, since the Error is part of its domain model.

We still have few places where this is happening, and we want to fix that.

https://github.com/stoplightio/prism/blob/master/packages/http/src/router/matchBaseUrl.ts

It would be great to come up with a way to not throw an exception anymore and return an `Either` structure — and then propagate it back to the user with the relative `.chain` method.

**Comment by marcelltoth** [comment]
If we are going to return an Either from that function, would `MatchType.NOMATCH` still exist as a possible Right value, or would it be considered an Error?

**Comment by XVincentX** [comment]
That’s up for a different discussion, for now let’s assume it’s a Either.right — we can reason about making it an Option.none in the future
