### ISSUE TITLE
Add ability to generate responses based on a pre-defined regex pattern 

### ISSUE THREAD

**Issue by sevendiko** [stoplightio/prism#964]
**As a user, I can generate dynamic response objects, which fields are matching the defined regexp pattern (if present).**

We only started to use Prism for API mocking, and we tried to use the dynamic mock generation feature, but unfortunately we are unable to generate relevant mocks. For example we have a /configurations endpoint in one of our microservices. We are developing a mobile application for both platforms (Android, iOS) and this configurations endpoint is the first that the mobile calls right after the application starts. The response contains the feature configurations in a simple format like this: **{ "feature1": "2.5.0.b1" }** **which means the feature1 available from the 2.5.0.b1 version of the Android/iOS application.** **We have a regex pattern in the swagger definition (for the version number), which is completely ignored by Prism during dynamic mock generation, therefore we will have some random strings instead of a correct version number.**
This is a serious issue for us, because the mobile client strongly depends on this configuration, features looks turned off in the app, if we can't pass a version number in the defined format. 

**Prism could generate responses based on the pre-defined regex pattern if it's present, which would solve the problem we are facing.**

**Comment by XVincentX** [comment]
@sevendiko Can you share the OpenAPI Document? Prism should be able to generate examples based on the provided format.

**Comment by philsturgeon** [comment]
This would be part of #435, let's add this as a use case over there and consolidate the conversation.

**Comment by XVincentX** [comment]
@philsturgeon Pretty sure the use case is _already_ supported by Prism though

**Comment by sevendiko** [comment]
Yeah, for sure.

```
'/v1/configurations':
    get:
      produces:
        - application/json
      description: Get the latest aggregated configurations
      tags:
        - Content Management
      operationId: getAggregatedConfigurations
      responses:
        '200':
          description: Aggregated Configuration values response
          schema:
            $ref: '#/definitions/ConfigurationVersions'
        '404':
          description: Object Not Found
          schema:
            $ref: '#/definitions/Error'
ConfigurationVersions:
    type: object
    description: Response containing config versions.
    properties:
      tenants:
        type: object
        additionalProperties:
          $ref: '#/definitions/TenantConfig'
TenantConfig:
    type: object
    properties:
      callCenterPhoneNumber:
        type: string
        description: bank's call center phone number
      loanDepartmentCenterPhoneNumber:
        type: string
        description: bank's loan department center phone number
      consents:
        type: object
        additionalProperties:
          $ref: '#/definitions/Consent'
      featureToggleiOS:
        type: object
        additionalProperties:
          type: string
          **pattern: '^[\d]+\.[\d]+\.[\d]+\.b[\d]+$'**
      featureToggleAndroid:
        type: object
        additionalProperties:
          type: string
          **pattern: '^[\d]+\.[\d]+\.[\d]+\.b[\d]+$'**
      scaWorkflows:
        $ref: '#/definitions/StrongCustomerAuthenticationWorkflows'
      overdraftInfo:
        type: object
        properties:
          rate:
            type: number
          validityDate:
            type: string
            format: date
    required:
      - callCenterPhoneNumber
      - loanDepartmentCenterPhoneNumber
      - consents
      - featureToggleiOS
      - featureToggleAndroid
      - scaWorkflows
```

We are running prism with this command: prism mock -h 0.0.0.0 -d api.yml

**Comment by XVincentX** [comment]
@sevendiko The document is invalid, I guess you just pasted the path with some definitions, but other are not there. I'll try to craft something from this but it'd be beneficial if you could provide a ready to use file.

**Comment by XVincentX** [comment]
@sevendiko The document is invalid, I guess you just pasted the path with some definitions, but other are not there. 
Also, the **pattern** is not valid, you need to remove the stars.



I have just tried with a document I crafted manually starting from your example and the dynamic example returned is indeed a value that's taken out of the pattern property. 

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/1416224/73843233-883ae000-481e-11ea-8983-7ce008741e32.png">

Please reopen with more details.

**Comment by sevendiko** [comment]
Yes, it is not the full .yaml, because that is 7000 lines long :D I just pasted the relevant parts but here you can find a valid example. 
```
swagger: '2.0'
info:
  version: 1.1.0
  title: Mobile API
  description: API which used by our mobile development team
schemes:
  - https
  - http
paths:
  '/configurations':
      get:
        produces:
          - application/json
        description: Get the latest aggregated configurations
        tags:
          - Content Management
        operationId: getAggregatedConfigurations
        responses:
          '200':
            description: Aggregated Configuration values response
            schema:
              $ref: '#/definitions/ConfigurationVersions'
          '404':
            description: Object Not Found
            schema:
              $ref: '#/definitions/Error'
definitions:
  ConfigurationVersions:
    type: object
    description: Response containing config versions.
    properties:
      tenants:
        type: object
        additionalProperties:
          $ref: '#/definitions/TenantConfig'
  TenantConfig:
      type: object
      properties:
        featureToggleiOS:
          type: object
          additionalProperties:
            type: string
            pattern: '^[\d]+\.[\d]+\.[\d]+\.b[\d]+$'
        featureToggleAndroid:
          type: object
          additionalProperties:
            type: string
            pattern: '^[\d]+\.[\d]+\.[\d]+\.b[\d]+$'
        overdraftInfo:
          type: object
          properties:
            rate:
              type: number
            validityDate:
              type: string
              format: date
      required:
        - featureToggleiOS
        - featureToggleAndroid
  Error:
    type: object
    properties:
      errorCode:
        type: string
        description: Optional error code for reporting purposes.
      errorId:
        type: string
        description: Unique UUID for audit purposes.
      errorDescription:
        type: string
        description: The description of the error.
```

**Comment by sevendiko** [comment]
Oh, It's really working for you. Then what am I do wrong ? :D

**Comment by XVincentX** [comment]
I do not know. Same with your document: 

<img width="962" alt="image" src="https://user-images.githubusercontent.com/1416224/73844406-cd601180-4820-11ea-9d9d-bd135228a52b.png">

**Comment by sevendiko** [comment]
Ah, yeah, sorry guys, it was our mistake. Works as expected :) thanks for your help :)
