### ISSUE TITLE
Support the Prefer header

### ISSUE THREAD

**Issue by XVincentX** [stoplightio/prism#966]
We currently support the selection of a specific response with the `__code` query parameter and a specific example with `__example` query parameter.

However, instead of polluting the query string with such thing we should probably be using the [Prefer header](https://tools.ietf.org/html/rfc7240)

We could do something like
`Prefer: code=201, example=named_example, dynamic=true`

I would also suggest, once this feature is merged to declare the query parameters thing deprecated.

**Comment by philsturgeon** [comment]
Yep, support both for the lifetime of v3.x, deprecated the query string stuff, and we can maybe drop it in v4. Gives us time to change documentation a bunch and get people used to the new way.

**Comment by marcelltoth** [comment]
Have you thought about maybe using a custom header instead? What are the arguments for / against? One I can think of:

Prefer:
- It's a standard header

Custom:
- Will not collide if the API we're mocking also uses a Prefer header. (I haven't seen a lot of APIs use it but still it's nice to be prepared for it.)

**Comment by XVincentX** [comment]
At this point I really do not think people will put constraints on the preference header and moreover it’s only used in the requests, not in the responses. I’m inclined to leave it as it is.
