### ISSUE TITLE
Prism returning different status codes and data types than expected

### ISSUE THREAD

**Issue by elimerrell** [stoplightio/prism#968]
**Describe the bug**
My development team uses Prism to test our API contracts during the build process for our React app. During our most recent build, several API contract tests failed due to Prism returning different status codes as well as data types that differ from the OpenAPI spec. Our tests were passing locally, but we were able to recreate the issue by removing the node modules and doing a fresh npm install.

These are the errors we are experiencing:

* Prism returning an object instead of an array (as specified in OpenAPI spec)

* Expected: 204 Received: 200

* Request failed with status code 422

**To Reproduce**

**Prism is returning the response for the first call under a path (responses are being interchanged)**

Using the following example: 
```
paths:
  /api/users:
    post:
      summary: "Create a user"
      operationId: "dal.users.create_and_get"
      requestBody:
        description: "Parameters to define a new user."
        content:
          application/json:
            schema:
              x-body-name: "user"
              $ref: "#/components/schemas/UserCreateEntity"
            example:
              name: "test_user"
      responses:
        200:
          description: "User created successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserCreateResponseEntity"
              example:
                id: "e274bf3ebe3841a88ade1630515624c6"
                name: "test_user"
        409:
          description: "Duplicate user name"
    get:
      summary: "List all users"
      operationId: "dal.users.get_all"
      responses:
        200:
          description: "Get a list of all Users."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserCollectionEntity"
```

If I make a `get` call to `/api/users`, I am expecting to receive an array of users. Prism is actually returning the response for the `post` call, and is responding with a `UserCreateResponseEntity` instead of a `UserCollectionEntity`.

We have observed that if there are multiple CRUD operations under a path, Prism responds with the first operation by default. We have observed this across multiple OpenAPI Spec files and tests. 

**Expected behavior**
1. Prism should return the correct data type based on OpenAPI Spec
2. Prism should not be returning 422 because there is no request body for that call
3. Prism should return the status code as defined in the OpenAPI Spec

**Screenshots**

**Environment (remove any that are not applicable):**
 - Library version: `@stoplight/prism-cli": "^3.2.5`,
 - OS: MacOS Mojave 
 - Browser: Chrome 79.0.3945.130

**Additional context**

**We feel that this issue is linked to a dependency in Prism. We pinned Prism's dependency versions (removed ^), and were able to resolve the issue.**

**Comment by VenkatRamReddyK** [comment]
With 3.2.8 version seems like only 1 issue is fixed. 

**Fixed issue:** 
1. **Prism is returning the response for the first call under a path (responses are being interchanged)**

**Un-resolved Issue:** 
1. Request failed with status code 422

**Expected result:** 
api should respond with the data as per the data contract


When I access `/api/users/locations` or `/api/users/23` 
I see 422 with the following error. 

 

```
{"type":"https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY","title":"Invalid request body payload","status":422,"detail":"Your request is not valid and no HTTP validation response was found in the spec, so Prism is generating this error for you.","validation":[{"location":["path","user_id"],"severity":"Error","code":"format","message":"should match format \"uuid\""}]}
```
Here is the yaml code for simulating 422 issue
```
/api/users/{user_id}:
  get:
    summary: "Get details of a user by id"
    operationId: "dal.user.get"
    parameters:
      -
        name: "user_id"
        in: "path"
        description: "Id of User"
        required: true
        schema:
          $ref: "#/components/schemas/UserId"
    responses:
      200:
        description: "User retrieved successfully"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserEntity"
      
/api/users/locations:
  get: 
    summary: "Get location info for the users. It returns a list of existing custom name."
    operationId: "dal.users.get_locations"
    responses: 
      200: 
        description: "Retrieve location info successfully"
        content: 
          application/json: 
            schema: 
              $ref: "#/components/schemas/UserLocationsEntity"
```

**Comment by VenkatRamReddyK** [comment]
@XVincentX, 

Digging it further we figured out if we had **Endpoint1** followed by **Endpoint2** it throws 422, 
if it is vice-versa it works fine. 
So, we think that it is assuming locations is a uuid and not a seperate route.
 
**Endpoint1**. `/api/users/:uuid`
**Endpoint2**. `/api/users/locations`

**Comment by VenkatRamReddyK** [comment]
@XVincentX Created #981 to track the 422 issue. 
FYI: @elimerrell
