### ISSUE TITLE
PRISM returns 422 for routes with same parent route

### ISSUE THREAD

**Issue by VenkatRamReddyK** [stoplightio/prism#981]
**Describe the bug**
We use **Prism Mock Server** for development and mock server for running API contracts tests for our React application. With the recent update 3.2.8 we figured out some of the tests are failing. 
As a practice, we removed node modules, did `npm cache clean --force` and restarted prism and ran tests.

**To Reproduce**

**Here is the yaml code for simulating 422 issue**

```
/api/users/{user_id}:
  get:
    summary: "Get details of a user by id"
    operationId: "dal.user.get"
    parameters:
      -
        name: "user_id"
        in: "path"
        description: "Id of User"
        required: true
        schema:
          $ref: "#/components/schemas/UserId"
    responses:
      200:
        description: "User retrieved successfully"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserEntity"
      
/api/users/locations:
  get: 
    summary: "Get location info for the users. It returns a list of existing custom name."
    operationId: "dal.users.get_locations"
    responses: 
      200: 
        description: "Retrieve location info successfully"
        content: 
          application/json: 
            schema: 
              $ref: "#/components/schemas/UserLocationsEntity"
```
**These are the errors we are experiencing:**
if we had 2 endpoints with same parent routes (`/api/users/`) with route 1 accept  uuid as query-params (i.e `/api/users/:uuid`), while other route has sub-route (`/api/users/locations`) Prism returns 422 for the sub-route.
Route 1. /api/users/:uuid
Route 2. /api/users/locations

In our yaml file if add Route2 followed by Route1 it works fine.

So, we think that it is assuming locations is a uuid and not a separate route and so it throws the following error

```
{"type":"https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY",
"title":"Invalid request body payload",
"status":422,"detail":"Your request is not valid and no HTTP validation response 
was found in the spec, so Prism is generating this error for you.",
"validation":[{"location":["path","user_id"],"severity":"Error","code":"format",
"message":"should match format \"uuid\""}]}
```

**Expected behavior**
PRISM should handle nested routes and routes that accept parameters correctly.

**Environment**

Library version: @stoplight/prism-cli": "3.2.8",
OS: MacOS Mojave
Browser: Chrome 78
**Additional context**
We think that it is assuming locations is a uuid and not a separate route and so it throws the following error

**Comment by XVincentX** [comment]
That is correct, I believe the router at the moment stops at the first match before checking out if there are more precise ones or something like that. We'll try to look into that.

**Comment by VenkatRamReddyK** [comment]
@XVincentX , 
Thanks for fixing this. 
Can you please tell us the release of next version to liverage this fix ?

**Comment by XVincentX** [comment]
Most likely we'll cut a minor release once #984 is done
