### ISSUE TITLE
Support redirect only endpoints out of the box

### ISSUE THREAD

**Issue by joe42** [stoplightio/prism#982]
**User story.**
As a developer, 
I can add a mocked endpoint with a redirection response,
so that I can call the endpoint without additional metadata, and be redirected.

**Is your feature request related to a problem?**
Currently the only way to get around this limitation is to add metadata to the actual request. We do this using the `__code` query parameter. The problem is twofold:
1. This limitation, and the workaround are not obvious
2. We need to modify the code instead of just rerouting the request to the mock server.

**Describe the solution you'd like**
It would be great if this works out of the box: If there is only one response defined for an endpoint in the OpenAPI interface, like for instance a 303 redirect, just use this response, and the associated example.
An alternative solution could be to use OpenAPI to mark a specific response as a default response that the mock server picks (if that is possible). As I understand, it currently defaults to the 200 response.

**Additional context**
Currently, when I request an endpoint that only has a 303 redirect defined this happens in the log:
>>get /redirect_endpoint error     Request terminated with error: Error: No 2** response defined, cannot mock

**Comment by XVincentX** [comment]
Yeah, effectively maybe we should by default look also to any 3XX status code before giving up, what do you think @philsturgeon ?

**Comment by philsturgeon** [comment]
Could I see an example of the API description here to get my head around it better? Just the relevant bits is fine.

**Comment by XVincentX** [comment]
Closing, @joe42 feel free to reopen when you'll provide more information
