### ISSUE TITLE
Proper report need to be generated by Prism Mock server after handling requests from client

### ISSUE THREAD

**Issue by ksudheernathreddy** [stoplightio/prism#991]
Hi,

Currently I am evaluating Prism for mock CI integration in our workflow, it really fits in. But I want to archive the summary of tests has been done, its detailed status for each jenkins build run over the period of time (client requests to prsim mock http server) and I want to make visualizations for developer for ease, I was checking this plugin (https://plugins.jenkins.io/stoplightio-report/), they are expecting report to be in JSON or stdout (I would prefer JSON, so that I can archive), currently I don't see an option while running prism mock server to generate report.

**Comment by XVincentX** [comment]
Hey,

that file was generated by Prism using the scenario file you'd provide, effectively informing Prism of all the tests you were about to run.

In our case, Prism is currently not offering any scenario capability but just mocking/validation proxy capabilities, making the production of such file, at least at the moment, not possible.

I've marked this issue as a enhancement and assigned it to the relevant product people — they'll take it from here.

**Comment by philsturgeon** [comment]
@ksudheernathreddy could you explain your needs a little more? What is the use case you are working with? It seems like you want a mock server, but then you talk about reports? 

As a general comment, and to build on what @XVincentX said: older versions of Prism had "Scenarios" which was running a test suite, and you got a report from the test suite. Now there is the mock server and the validation server, no test suite. If I knew exactly what you were trying to do, we could consider the appropriate next step.

**Comment by chohmann** [comment]
Going to close this issue as we haven't gotten a response from the user.
